### ISSUE TITLE
Discover the `GeneratedDllImport` via the semantic model rather than syntactic

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/runtimelab#1002]
Update to use the latest Roslyn Source Generator API - @chsienki has details on what new options exist for us.

> Use `GetSymbolInfo` to bind an `AttributeSyntax`, grab the type and compare the FQN of that type to the name you’re looking for. This means the generator will work for any attribute that has the right FQN.

The above approach will ensure that C# type aliasing can be used with our triggering attribute.

/cc @jkoritzinsky @elinor-fung

**Comment by jkoritzinsky** [comment]
The semantic model visitor API was introduced in https://github.com/dotnet/roslyn/pull/50419. I don't know if there's any docs for it, but we can use the implementation PR as a reference.

**Comment by jkoritzinsky** [comment]
Fixed by #1116
