### ISSUE TITLE
[NativeAOT] singlemethodname do not work in non system module

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtimelab#1011]
I was trying to use that option to limit generation only to method which use marshallers, but unfortunately I cannot do that. `singlemethodname` used only system module for it's work. Is it possible to have it work for at least entry point assembly?

**Comment by jkotas** [comment]
Try: `--singlemethodtypename "MyType,MyAssembly"`

**Comment by jkotas** [comment]
It uses the custom attribute type name syntax that is defined in ECMA-335 (look for `SerString`).

**Comment by kant2002** [comment]
Will try tomorrow, when I will be around Windows, but I doubt it will works:

https://github.com/dotnet/runtimelab/blob/9f3f548d4fa69215f871d383c1ad5ce228e3003e/src/coreclr/tools/aot/ILCompiler/Program.cs#L864

where 

https://github.com/dotnet/runtimelab/blob/9f3f548d4fa69215f871d383c1ad5ce228e3003e/src/coreclr/tools/aot/ILCompiler/Program.cs#L841-L854

where explicitly SystemModule is used.

And SingleMethod resolved at stage of parsing arguments before even assemblies list collected.

**Comment by jkotas** [comment]
I am pretty sure that it works. I have used it many times. To double check, I have just tried `--singlemethodtypename "HelloWorld.Program,HelloWorld" --singlemethodname Main` with the samples/HelloWorld, and it worked as expected.

> where explicitly SystemModule is used.

SystemModule is the default if the name does not specify any assembly.

> SingleMethod resolved at stage of parsing arguments before even assemblies list collected.

That's not correct.

**Comment by kant2002** [comment]
Ok. I will check that. Thanks.

**Comment by kant2002** [comment]
Indeed, when I specify assembly it works. Thanks.
