### ISSUE TITLE
There is any way to check whether reflection is disabled?

### ISSUE THREAD

**Issue by josephmoresena** [dotnet/runtimelab#1017]
I'm trying to switch from Enum.GetValues to an AOT-friendly alternative but I would like to use Enum.GetValues whatever is possible. I don't wanna wait for Enum.GetValues exception occours but I would like to initialize a flag to go always for the right way.
It is possible?

**Comment by MichalStrehovsky** [comment]
@davidfowl asked me the same question and I didn't have anything at that time.

I don't think there's a good way by default, but if you enable the [DoNotThrowForNames shim](https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/docs/using-nativeaot/reflection-free-mode.md#shimming), you could do `bool reflectionDisabled = typeof(Program).Name != nameof(Program)`.

**Comment by josephmoresena** [comment]
> @davidfowl asked me the same question and I didn't have anything at that time.
> 
> I don't think there's a good way by default, but if you enable the [DoNotThrowForNames shim](https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/docs/using-nativeaot/reflection-free-mode.md#shimming), you could do `bool reflectionDisabled = typeof(Program).Name != nameof(Program)`.

If I use typeof(Program).Contains(nameof(Program)) may wouln't requiried DoNotThrowForNames, would it?

**Comment by MichalStrehovsky** [comment]
> If I use typeof(Program).Contains(nameof(Program)) may wouln't requiried DoNotThrowForNames, would it?

Yes, that should work. I don't think we throw for `ToString` and if we do, we shouldn't.

**Comment by jkotas** [comment]
As @MichalStrehovsky pointed out in the other issue, the reflection-only mode is way too experiemental to be useful. I do not think it makes sense to be changing any shipping libraries to make it work well with it. I would just use `#define` to build the libraries you case about in a mode that's compatible with reflection-only mode.

**Comment by josephmoresena** [comment]
> > If I use typeof(Program).Contains(nameof(Program)) may wouln't requiried DoNotThrowForNames, would it?
> 
> Yes, that should work. I don't think we throw for `ToString` and if we do, we shouldn't.

Today, typeof (T) .ToString () is totally legal, without reflection the result is EETypeRva: 0xhexCod.

> As @MichalStrehovsky pointed out in the other issue, the reflection-only mode is way too experiemental to be useful. I do not think it makes sense to be changing any shipping libraries to make it work well with it. I would just use `#define` to build the libraries you case about in a mode that's compatible with reflection-only mode.

You're right but even its experimental state a great majority of static code works without any problems, and strip out all code for reflection has a big real impact over final size of binary.
The #define only work if my source code will be compilated but no if I distribute the assembly. It would be the right way if I create two versions of the same assembly but as you are pointed out it may isn't convenient.

**Comment by hez2010** [comment]
I think you can create an enum (or use any existing enum):
```csharp
enum ReflectionFree { Test }
```

Then you can validate it without needs of worrying about exceptions:
```csharp
public static bool IsInReflectionFreeMode = ReflectionFree.Test.ToString() != nameof(ReflectionFree.Test);
```

Because in reflection-free mode, all enums lose their names and use the underlaying number instead, and this approach doesn't require `DoNotThrowForNames`.
