### ISSUE TITLE
NativeAOT: MarshalAPI tests

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtimelab#1020]
Since I feel that I'm close to RCW completition, I decide that I should unlock other test and run them locally (to improve quality of my submission).

So I add to `src\tests\Common\dirs.proj` to be used during Smoke testing
```
<AllProjects Include="$(TestRoot)interop\COM\ComWrappers\**\*.csproj" Exclude="@(DisabledProjects)" />
<AllProjects Include="$(TestRoot)interop\MarshalAPI\IUnknown\**\*.csproj" Exclude="@(DisabledProjects)" />
```

Also I implement `Marshal.GetIUnknownForObject(o)`.
```
public static IntPtr GetIUnknownForObject(object o)
{
    return ComWrappers.ComInterfaceForObject(o);
}
```

But tests falling because they are need global marshalling registered. 
My understanding that `interop\MarshalAPI\IUnknown` is tests shared with runtime repository, so I decide do not touch that. What's option how can I validate my implementation on the broader set of cases?

**Comment by jkotas** [comment]
The tests under `interop\MarshalAPI\IUnknown` are focused on testing built-in interop. I think you should only worry about the tests under `interop\COM\ComWrappers`, for now at least.

**Comment by kant2002** [comment]
Overall, modification in the `src\tests\Common\dirs.proj` is the only way how I can augment dev loop with test? Just trying to familiarize myself with build environment.

**Comment by MichalStrehovsky** [comment]
> Overall, modification in the src\tests\Common\dirs.proj is the only way how I can augment dev loop with test? Just trying to familiarize myself with build environment.

Yes, if you want to build additional tests as part of a full SmokeTestsOnly dev run, you have to modify that file.

You can also dotnet build individual tests: https://github.com/dotnet/runtime/blob/main/docs/workflow/testing/coreclr/testing.md#build-individual-test. I thing you also need to pass `/p:TestBuildMode=nativeaot`. I don't really use that workflow. I tend to paste the test code into the repro project in the Visual Studio solution and leave running the tests to the CI.

**Comment by kant2002** [comment]
I like that option. Biggest problem with quality of my latest contribution was that I have long feedback loop. Your workflow seems suited much better for me.

**Comment by kant2002** [comment]
I have strange error in ComWrappers tests, where some tests do not run because of missing `CoreShim.dll`.
 
```
Copying 'artifacts\tests\coreclr\windows.x64.Debug\Tests\Core_Root\CoreShim.dll'...
The system cannot find the file specified.
native\GlobalInstanceMarshallingTests
Expected: 100
Actual: 14001
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=d:\runtimelab\artifacts\tests\coreclr\windows.x64.Debug\Tests\Core_Root
> d:\runtimelab\artifacts\tests\coreclr\windows.x64.Debug\interop\COM\ComWrappers\GlobalInstance\GlobalInstanceMarshallingTests\GlobalInstanceMarshallingTests.cmd
```

Any advice what this is means?

**Comment by MichalStrehovsky** [comment]
CoreShim is this: https://github.com/dotnet/runtime/tree/01b7e73cd378145264a7cb7a09365b41ed42b240/src/coreclr/hosts/coreshim

It's a dll that exports DllGetClassObject and DllCanUnloadNow that allows one to get at COM components written in managed code. It's a CLR host for COM basically. I would probably ignore those tests.
