### ISSUE TITLE
NativeAOT Question about singlemethodname behaviour

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtimelab#1049]
I try to apply `singlemethodname` on `[PInvoke]PInvokeTests.Program.TestString()` method. Unfortunately it fails with 
```
Unhandled exception. ILCompiler.CodeGenerationFailedException: Code generation failed for method '[PInvoke]PInvokeTests.Program.TestString()'
 ---> System.NotImplementedException: The method or operation is not implemented.
   at ILCompiler.DependencyAnalysis.ExternSymbolsImportedNodeProvider.ImportedMethodDictionaryNode(NodeFactory factory, MethodDesc method)
   at ILCompiler.DependencyAnalysis.NodeFactory.<CreateNodeCaches>b__39_39(MethodDesc method)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at ILCompiler.DependencyAnalysis.NodeFactory.NodeCache`2.GetOrAdd(TKey key)
   at ILCompiler.DependencyAnalysis.NodeFactory.MethodGenericDictionary(MethodDesc method)
   at Internal.JitInterface.CorInfoImpl.getCallInfo(CORINFO_RESOLVED_TOKEN& pResolvedToken, CORINFO_RESOLVED_TOKEN* pConstrainedResolvedToken, CORINFO_METHOD_STRUCT_* callerHandle, CORINFO_CALLINFO_FLAGS flags, CORINFO_CALL_INFO* pResult)
   at Internal.JitInterface.CorInfoImpl._getCallInfo(IntPtr thisHandle, IntPtr* ppException, CORINFO_RESOLVED_TOKEN* pResolvedToken, CORINFO_RESOLVED_TOKEN* pConstrainedResolvedToken, CORINFO_METHOD_STRUCT_* callerHandle, CORINFO_CALLINFO_FLAGS flags, CORINFO_CALL_INFO* pResult)
   --- End of inner exception stack trace ---
   at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(IMethodNode methodCodeNodeNeedingCode, MethodIL methodIL)
```

It fails at call to `ThrowIfNotEquals` method. Does that means that this mode require all symbols/methods to be declared, in order to produce something?

**Comment by MichalStrehovsky** [comment]
We probably need to change this line:

https://github.com/dotnet/runtimelab/blob/fd45d6f8499eccb6004fefcbe12a9150e44c5705/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/SingleMethodCompilationModuleGroup.cs#L39

to:

```csharp
return true;
```

This is currently going into a codepath that expects the dictionary to be in a different dll/so/dylib file (inherited from .NET Native, but not currently used).

If it fixes the issue you're seeing, could you please make a pull request?

**Comment by kant2002** [comment]
Now it fails with `LLVM ERROR: Cannot represent a difference across sections` and no stack trace.

Actual crash produced by ObjWriter

https://github.com/dotnet/runtimelab/blob/fd45d6f8499eccb6004fefcbe12a9150e44c5705/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/ObjectWriter.cs#L889

ILdump option does not print any IL.

**Comment by MichalStrehovsky** [comment]
> Now it fails with `LLVM ERROR: Cannot represent a difference across sections` and no stack trace.

I haven't seen that one. The way to troubleshoot that would be to build objwriter as well (`build.cmd nativeaot.objwriter`) and debug with that. But maybe it's not worth too much effort.

The single method mode is not very tested. It's meant for compiler development only and issues get fixed only when someone really wants to.

**Comment by kant2002** [comment]
It seems I hit some can of worms. After I apply suggested change.
- On Gentoo I have `LLVM ERROR`
- On Windows do not and application exits cleanly.

On both systems when I `--ildump` hoping to have some IL there, I have only empty file created. Is this expected?
Will try to build ObjWriter when would be around my Gentoo.

**Comment by MichalStrehovsky** [comment]
Frankly, I don't know whether this will work for compiler-generated methods. The method being compiled might be different from the one specified on the command line. It might be easier to do this with Test.CoreLib (don't use single method; just compile everything - there won't be much extra stuff to distract you anyway).

**Comment by kant2002** [comment]
Yeah. I have no problem with this sometimes broken and working not as I expect. I just try to report hoping that maybe this is something simple, and can be fixed. Hope this does not looks like I abuse the system.

Will try to use Test.CoreLib as playground.

**Comment by MichalStrehovsky** [comment]
> Hope this does not looks like I abuse the system.

Not at all. I thought it's a simple fix, but looks like there's more to this.

**Comment by kant2002** [comment]
Have and issue during build on Gentoo after running `./build.sh nativeaot.objwriter`
```
  ~/d/github/runtimelab/eng/native/gen-buildsys.sh: line 110: /cmake_cmd_line.txt: Permission denied
  ~/d/github/runtimelab/artifacts/llvm/build/x64 ~/d/github/runtimelab/artifacts/llvm
```

Seems to be this is related to fact, that `__CMakeBinDir` is not set.
But this is not affect actual build. Just think that something maybe broken.
