### ISSUE TITLE
Allow non-concrete classes when marshalling SafeHandle by-value 

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/runtimelab#1052]
The source generator currently requires a non-abstract subclass of `SafeHandle` - even for by-value parameters. We require a concrete subclass to instantiate when handling `out` / `ref`,  but shouldn't need it for by-value.

Declaring a P/Invoke using an abstract base class or `SafeHandle` itself is a common use case in runtime libraries - e.g:
[Interop.Read.cs](https://github.com/dotnet/runtime/blob/94221f30cce9783f39d30eebbd9994f9711472e7/src/libraries/Common/src/Interop/Unix/System.Native/Interop.Read.cs#L20-L21)
```C#
[DllImport(Libraries.SystemNative, EntryPoint = "SystemNative_Read", SetLastError = true)]
internal static extern unsafe int Read(SafeHandle fd, byte* buffer, int count);
```
[Interop.Properties.cs](https://github.com/dotnet/runtime/blob/94221f30cce9783f39d30eebbd9994f9711472e7/src/libraries/Common/src/Interop/Windows/NCrypt/Interop.Properties.cs#L16-L17)
```C#
[DllImport(Interop.Libraries.NCrypt, CharSet = CharSet.Unicode)]
internal static extern unsafe ErrorCode NCryptGetProperty(SafeNCryptHandle hObject, string pszProperty, [Out] void* pbOutput, int cbOutput, out int pcbResult, CngPropertyOptions dwFlags);
```

cc @AaronRobinsonMSFT @jkoritzinsky

**Comment by jkoritzinsky** [comment]
Fixed by #1066
