### ISSUE TITLE
NativeAOT-LLVM :  There is no application host available for the specified RuntimeIdentifier 'browser-wasm'

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#1056]
Hi,

I'm trying to merge NativeAOT into NativeAOT-LLVM.  This merge includes the `global.json` sdk change
```
  "sdk": {
-    "version": "5.0.100",
+    "version": "6.0.100-preview.2.21155.3",
```
which may or may not be relevant.  The windows build and smoke tests are fine, but for the browser wasm build
```
build nativeaot+libs+nativeaot.packages -rc Debug -lc Release -a wasm -os Browser -runtimeFlavor CoreCLR -v normal -bl
```
I've got this error:
```
    1>Project "C:\Users\ScottWaye\.nuget\packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21222.1\tools\Build.proj" (1) is building "E:\GitHub\runtimelab2\Build.proj" (3) on node 1 (Restore target(s)).

     3>Restore:

         Determining projects to restore...

     3>E:\GitHub\runtimelab2\.dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(99,5): error NETSDK1084: There is no application host available for the specified RuntimeIdentifier 'browser-wasm'. [E:\GitHub\runtimelab2\Build.proj]

     3>E:\GitHub\runtimelab2\.dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(99,5): error NETSDK1084: There is no application host available for the specified RuntimeIdentifier 'browser-wasm'. [E:\GitHub\runtimelab2\Build.proj]

     3>E:\GitHub\runtimelab2\.dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(99,5): error NETSDK1084: There is no application host available for the specified RuntimeIdentifier 'browser-wasm'. [E:\GitHub\runtimelab2\Build.proj]

     3>E:\GitHub\runtimelab2\.dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(99,5): error NETSDK1084: There is no application host available for the specified RuntimeIdentifier 'browser-wasm'. [E:\GitHub\runtimelab2\Build.proj]
```
Does that ring any bells with anyone?  Maybe I've just messed something up with the conflict resolution, but thought I'd ask just in case someone recognizes it.

Complete log attached
[1.txt](https://github.com/dotnet/runtimelab/files/6411751/1.txt)

**Comment by hez2010** [comment]
I think it's an issue of .NET 6.
As for workaround you need to add a line to your wasm project `PropertyGroup`:
```xml
<PlatformTarget>AnyCPU</PlatformTarget>
```

**Comment by jkoritzinsky** [comment]
@yowl can you share a binlog for the failure? I'll try to take a look next week and find what issue you're hitting in the sdk (and hopefully how to work around it)

**Comment by yowl** [comment]
Thanks, here it is, zipped for github's sake, although I think it is already a zip .

[Build.zip](https://github.com/dotnet/runtimelab/files/6565228/Build.zip)
.

**Comment by jkoritzinsky** [comment]
So it looks like a failure during Restore, which since we use static graph mode will be in a different binlog. Do you have another binlog at `artifacts\log\Debug\Restore-Build.proj.binlog`?

**Comment by jkoritzinsky** [comment]
Also if you can point me to a commit hash/branch on either this repo or your fork that I can mess around with to help fix this, that could also be helpful.

**Comment by yowl** [comment]
No, I don't have that file there.  Maybe the scripts aren't passing through the -bl to the right place .  I tried a search for the file name and that came up blank also.
![image](https://user-images.githubusercontent.com/2720041/120193091-9bc34480-c1e1-11eb-8cd8-894282c5d7a0.png)

Is there anything in the log which would help add the right flags to get this binlog?

For the repo, https://github.com/yowl/runtimelab/tree/merge-0521 is where I'm at.  To complete the build you'd need to install LLVM and emscripten as per "Building for Web Assembly" at  https://github.com/dotnet/runtimelab/blob/feature/NativeAOT-LLVM/docs/workflow/building/coreclr/nativeaot.md but as this problem occurs before any LLVM work then you probably don't want to bother with that.

**Comment by jkoritzinsky** [comment]
I'm not sure. I'll try to build locally and I'll mess around with stuff to get the binlog.

**Comment by jkoritzinsky** [comment]
Ok I found the issue and it's what I was expecting.

The build is trying to build the ILCompiler.csproj project to target browser-wasm. You need to make some changes to determine a "host" architecture that `ilc` is supposed to actually run on and use that RID for `ILCompiler.csproj` when building for wasm is specified.

You had some preliminary work set up to do this, but it didn't kick in correctly. Here's a patch for your branch that gets it through restore and to build:

[diff.patch.txt](https://github.com/dotnet/runtimelab/files/6571808/diff.patch.txt)

Hopefully that will unblock you.

**Comment by yowl** [comment]
@jkoritzinsky Thanks a lot for taking the time to look at this.  Indeed that has fixed this error.
