### ISSUE TITLE
Native AOT: Exception during compilation of method.

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtimelab#1069]
I see compilation failure in WinForms application

```
Invalid IL or CLR metadata in 'Void Accessibility.CAccPropServicesClass.SetHmenuProp(Accessibility._RemotableHandle ByRef, UInt32, System.Guid, System.Object)''
```

Exception is raised here https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs#L255

This method declared here https://github.com/dotnet/winforms/blob/d46ad2e8dc76248739d9ae22b28b399a6a6b299e/src/Accessibility/src/Accessibility.il#L375

Is this exception related to `internalcall` IL attribute?

**Comment by jkotas** [comment]
Yes, this is COM interop.

This is an example of COM interop use that has to be rewritten. It is not possible to fix it up using ComWrappers from the outside.

**Comment by kant2002** [comment]
Thanks. Hopefully simple app just works
