### ISSUE TITLE
NativeAOT: Linker error

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtimelab#1071]
Honestly not sure if this is issue at all. I have Preview 4 installed and compile WinForms app. 

Now I receive link time errors.

```
Runtime.lib(UniversalTransition.asm.obj) : error LNK2001: unresolved external symbol RhpPublishObject
```

I was having setup issues, so manually modify response files to point to locally built version of files. 
I have to upgrade to Preview 4, since ILC expect CoreLib to have `ClearLastError` (IIRC).

Is this something which rings the bell?

**Comment by jkotas** [comment]
You have mismatched runtime and compiler bits again. I have deleted `RhpPublishObject` in one of my recent PRs.

**Comment by jkotas** [comment]
When you run into issues like this, you may want to try cleaning up your git enlistment (`git clean -x -d -f .`) and also deleting your nuget cache (`rmdir /s /q %userprofile%\.nuget`).
