### ISSUE TITLE
Structs with explicit field offsets crash ilc.exe

### ISSUE THREAD

**Issue by wjk** [dotnet/runtimelab#1092]
What the title says, really. I have a dependency that contains such a type, and even though I do not use it in my app, its existence breaks my build. (The type is [`CRYPTUI_WIZ_IMPORT_SRC_INFO_UNION`](https://github.com/dahall/Vanara/blob/7ea275cc7a982211d919b408ba621cc232d8e202/PInvoke/Cryptography/CryptUI/Wincrypt.cs#L1887).)

**Comment by jkotas** [comment]
This type has invalid layout. It will fail to load even with regular .NET runtime:
```
C:\repro>type Program.cs
using System;

Console.WriteLine(typeof( Vanara.PInvoke.CryptUI.CRYPTUI_WIZ_IMPORT_SRC_INFO.CRYPTUI_WIZ_IMPORT_SRC_INFO_UNION));

C:\repro>dotnet run
Unhandled exception. System.TypeLoadException: Could not load type 'CRYPTUI_WIZ_IMPORT_SRC_INFO_UNION' from assembly 'Vanara.PInvoke.Cryptography, Version=3.3.9.0, Culture=neutral, PublicKeyToken=c37e4080322237fa' because it contains an object field at offset 0 that is incorrectly aligned or overlapped by a non-object field.
   at <Program>$.<Main>$(String[] args)
```
What is the crash that you are seeing?

**Comment by wjk** [comment]
@jkotas I am getting that exact error. I’ll file a bug report at the Vanara repo. Thanks!
