### ISSUE TITLE
NativeAOT question: Marshalling using wrappers?

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtimelab#1095]
I notice that in .NET 6.0 Preview 3 was introduced some new classes (`System.Runtime.InteropServices.XxxWrapper`) like this one https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.bstrwrapper

Does that means that they support for them should be done separately, or some magic will happens and they suddenly starts working?

**Comment by MichalStrehovsky** [comment]
Is that class new? The docs say it dates back to .NET 2.0. From a quick search in the repo it seems like it does something for the built-in interop (might be related to IDispatch?).

**Comment by kant2002** [comment]
You was right. I again somehow was confused when glancing over docs :cry: .  From docs seems to be this is related to Variant. This is not implemented, at least I cannot find code in the Marshaller.cs and Marshaller.Aot.cs, but MarshallerKind.Variant is present.

**Comment by jkotas** [comment]
Variant marshaling is part of the built-in COM interop support. It is in a similar category as COM coclass types. I do not think we should implement it for NativeAOT, and instead recommend to remove the dependency from the calling code.

Have you run into any real piece of code that needs it?

**Comment by kant2002** [comment]
No, this was just a question from me.
