### ISSUE TITLE
[DllImportGenerator] Reserved keywords support

### ISSUE THREAD

**Issue by SupinePandora43** [dotnet/runtimelab#1096]
```cs
[GeneratedDllImport("Example")]
internal static partial void MyFunc([MarshalAs(UnmanagedType.LPUTF8Str)] string @event);
```

# Actual Result

CS8795: `Partial method 'MyFunc(string)' must have an implementation part because it has accessibility modifiers` in source file
CS0759: `No defining declaration found for implementing declaration of partial method 'MyFunc(string, event)'` in `DllImportGenerator.g.cs`

## Generated code

`internal static partial void MyFunc(string event)`

# Expected Result

## Generated code

`internal static partial void MyFunc(string @event)`

**Comment by jkoritzinsky** [comment]
Fixed by #1105
