### ISSUE TITLE
WPF marshalling issue for SafeHandle

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtimelab#1108]
Exception during marshalling WPF

`{[System.Security.Cryptography.Pkcs]Interop+Crypt32.CertCreateCertificateContext(MsgEncodingType,void*,int32)}` failed to generate PInvoke
because `{[System.Security.Cryptography.Pkcs]Microsoft.Win32.SafeHandles.SafeCertContextHandle}` has no parameterless constructor.

**Comment by kant2002** [comment]
I general I notice that a lot of SafeHandles like to sit in the fields of some structures which is currently not implemented.

**Comment by MichalStrehovsky** [comment]
https://github.com/dotnet/runtime/issues/43016 - this is dead code. We compile it because the default policy is not to trim non-framework code and WPF is not considered framework.
