### ISSUE TITLE
WPF require IDispatch

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtimelab#1109]
Line here require IDispatch marshalling 

https://github.com/dotnet/wpf/blob/89d172db0b7a192de720c6cfba5e28a1e7d46123/src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/Controls/ActiveXHelper.cs#L147

This maybe obscure and not needed. Just report that so all that issues can be tracked if needed.

**Comment by jkotas** [comment]
This looks like a dead code in WPF. I do not see any uses of it.

**Comment by kant2002** [comment]
thanks.

**Comment by jkotas** [comment]
It may be nice to submit PR to WPF repo to delete it.
