### ISSUE TITLE
Allow marshalling blittable structs without `BlittableType` if they are in the same assembly as the GeneratedDllImport method

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/runtimelab#1125]
A lot of the blittable structs marshalled in the runtime are internal structs in the same assembly. In these cases, the source generator could be able determine that the struct should be considered blittable rather than requiring the additional metadata of the `BlittableType` attribute.

cc @AaronRobinsonMSFT @jkoritzinsky

**Comment by jkoritzinsky** [comment]
I'd prefer to only do this for internal types so as to not to end up in a scenario where a type can be considered blittable in one assembly but not another.

**Comment by elinor-fung** [comment]
Agreed - internal structs.

**Comment by jkoritzinsky** [comment]
Fixed by #1126
