### ISSUE TITLE
Why BStr tests disabled

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtimelab#1144]
I notice that in #1133 tests for BSTR was disabled again. https://github.com/dotnet/runtimelab/pull/1133/files#diff-72d87bb5dc27f15b0bfbc2423cff89c3085f4109dc8cd5d83e1724d828ebbde0R1156

I testing that locally and it seems to work. I test only in Debug configuration, so maybe that the reason. Do I miss something?

**Comment by MichalStrehovsky** [comment]
They were failing when I kicked off the test pass in #1074. The reason looked like the "invalid marshalling directive compatibility" (we're throwing different exception when the directive is bogus).

**Comment by kant2002** [comment]
Is this related to multifile module or Release mode in your opinion? I maybe can play with that if was able to reproduce locally?

I run locally following tests `artifacts\tests\coreclr\windows.x64.Debug\Interop\StringMarshalling\BSTR\BSTRTest>BSTRTest.cmd`  and Debug works ok.

**Comment by MichalStrehovsky** [comment]
Submit a pull request removing it. We can re-run it.

Maybe I ran the test pass between #1057 that enabled the test and #1077 that would actually have a chance to make the test work.
