### ISSUE TITLE
Unsupported PreserveSig = false combination prevent working with images in WinForms.

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtimelab#1183]
Any image related code crashed with following exception
```
System.Exception: Method '[System.Windows.Forms.Primitives]Interop+Ole32.OleCreatePictureIndirect(PICTDESC*,Guid&,BOOL)' requires marshalling that is not yet supported by this compiler.
   at Interop.Ole32.OleCreatePictureIndirect(Interop.Ole32.PICTDESC*, Guid&, Interop.BOOL) + 0x45
```

Lines which crash compiler:

https://github.com/dotnet/winforms/blob/d46ad2e8dc76248739d9ae22b28b399a6a6b299e/src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.OleCreatePictureIndirect.cs#L12-L14

**Comment by kant2002** [comment]
I see two cases left
1. Return results is some is int-mappable value. Enum or probably any struct of size 4 bytes falls into this category.
For example:
```
public static extern HRESULT GetErrorInfo(uint dwReserved, ref IErrorInfo pperrinfo);
```
2. Return value is object or any custom struct.
For example:
```
object OleCreatePictureIndirect(PICTDESC* pictdesc, ref Guid refiid, BOOL fOwn)
```

For case 1 I probably should extend condition here somehow.
https://github.com/dotnet/runtimelab/blob/5a44950f44500c3817e841bbcf7ced771d232daf/src/coreclr/tools/Common/TypeSystem/IL/Stubs/PInvokeILEmitter.cs#L234-L235
And that would be it in general.

With case 2 I'm have one idea, but not sure that this is what you want to have as part of code.
My understanding that call 
```
object OleCreatePictureIndirect(PICTDESC* pictdesc, ref Guid refiid, BOOL fOwn)
```
should be translated to 
```
int OleCreatePictureIndirect(PICTDESC* pictdesc, ref Guid refiid, BOOL fOwn, out object retval);
```
This increase count of marshallers by 1 then all other cases and I do not sure where modifications should be.
I can increate count of marshallers in the `InitializeMarshallers` method.
https://github.com/dotnet/runtimelab/blob/5a44950f44500c3817e841bbcf7ced771d232daf/src/coreclr/tools/Common/TypeSystem/IL/Stubs/PInvokeILEmitter.cs#L54
Maybe some other kind of MethodThunk should be created for this case, and then I can use that as switch here
https://github.com/dotnet/runtimelab/blob/5a44950f44500c3817e841bbcf7ced771d232daf/src/coreclr/tools/Common/TypeSystem/IL/Stubs/PInvokeILEmitter.cs#L58

So I would like to have some advice on case 2

**Comment by jkotas** [comment]
> [DllImport(Libraries.Oleaut32, ExactSpelling = true, PreserveSig = false)]
> public static extern HRESULT GetErrorInfo(uint dwReserved, ref IErrorInfo pperrinfo);

This is wrong PInvoke definition. `PreserveSig = false`  should be deleted here. It works by a pure luck, and I am not sure whether it is even the case. It is used on error handling path, and it is possible that this eror handling path is never actually used and nobody noticed that it is broken. Would you like to send PR to WinForms to fix it up?

> This increase count of marshallers by 1

I do not think increasing count of marshallers would work well. I think you want to keep the count of the marshallers same, and instead handle the HRESULT swapping by adding special cases as necessary. It is how CoreCLR does it - look for `SF_IsHRESULTSwapping` in https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/dllimport.cpp.

**Comment by kant2002** [comment]
> It works by a pure luck, and I am not sure whether it is even the case.

I tried with 
```
[DllImport("dwmapi.dll", EntryPoint = "DwmIsCompositionEnabled", PreserveSig = false)]
public static extern HRESULT DwmIsCompositionEnabled(IntPtr x);

DwmIsCompositionEnabled(IntPtr.Zero);
```
And this code throws ArgumentException on CoreCLR. So I assume that even this is wierd it should be supported. Isn't it?

> Would you like to send PR to WinForms to fix it up?

Will do. No error handling there at all, I assume they want `PreserveSig = false` and change result to `void`

**Comment by kant2002** [comment]
I send changes to WinForms, that was only one strange place. Also I inspect WPF too and found 2 more locations
https://github.com/dotnet/wpf/blob/d26eaaca20aa2f5de768e4053593f50a30776380/src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/Win32/UnsafeNativeMethodsPenimc.cs#L634
https://github.com/dotnet/wpf/blob/d26eaaca20aa2f5de768e4053593f50a30776380/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Standard/NativeMethods.cs#L3331-L3333

I probably send PR again, but my last PR is still pending and do not know how to ping people.

**Comment by jkotas** [comment]
> And this code throws ArgumentException on CoreCLR. So I assume that even this is wierd it should be supported. Isn't it?

It should be transformed into `int DwmIsCompositionEnabled(IntPtr x, out HRESULT x);` just like the case 2. The behavior at runtime may be unpredictable just like for any other mismatched PInvoke signature.
