### ISSUE TITLE
ILC crash on DataGridView

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtimelab#1187]
After adding `DataGridView` to simple WinForms application

```
Unhandled exception. System.InvalidOperationException : Internal linker error : processing of call from System.Windows.Forms.DataGridView.BeginEditInternal(Boolean) to System.Type.GetInterface(String) returned value which is not correctly annotated with the expected dynamic member access kinds. [c:\CoreRTWinFormsTestBed\samples\SampleWindowsForms\SampleWindowsForms.csproj]
     at ILCompiler.Dataflow.ReflectionMethodBodyScanner.HandleCall(MethodIL callingMethodBody, MethodDesc calledMethod, ILOpcode operation, Int32 offset, ValueNodeList methodParams, ValueNode& methodReturnValue)
     at ILCompiler.Dataflow.MethodBodyScanner.HandleCall(MethodIL callingMethodBody, ILOpcode opcode, Int32 offset, MethodDesc calledMethod, Stack`1 currentStack, Int32 curBasicBlock)
     at ILCompiler.Dataflow.MethodBodyScanner.Scan(MethodIL methodBody)
     at ILCompiler.Dataflow.ReflectionMethodBodyScanner.ScanAndProcessReturnValue(NodeFactory factory, FlowAnnotations flowAnnotations, Logger logger, MethodIL methodBody)
     at ILCompiler.DependencyAnalysis.DataflowAnalyzedMethodNode.GetStaticDependencies(NodeFactory factory)
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependenciesImpl(DependencyNodeCore`1 node)
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependencies(DependencyNodeCore`1 node)
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ProcessMarkStack()
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ComputeMarkedNodes()
     at ILCompiler.RyuJitCompilation.CompileInternal(String outputFile, ObjectDumper dumper)
     at ILCompiler.Compilation.ILCompiler.ICompilation.Compile(String outputFile, ObjectDumper dumper)
     at ILCompiler.Program.Run(String[] args)
     at ILCompiler.Program.Main(String[] args)
```

methodReturnValue variable has type `ILCompiler.Dataflow.MergePointValue`

File https://raw.githubusercontent.com/dotnet/winforms/d46ad2e8dc76248739d9ae22b28b399a6a6b299e/src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs

Piece of code which trigger issue.
```csharp
if (editControlType is null)
{
    // Current cell does not have an editing control. Does it implement IDataGridViewEditingCell?
    Type editingCellInterface = dataGridViewCell.GetType().GetInterface("System.Windows.Forms.IDataGridViewEditingCell");
    if (editingCellInterface is null)
    {
        return false;
    }
}
```

**Comment by jkotas** [comment]
The annotations on GetInterface method have changed recently. This is the kind of error you would get when your ILCompiler and CoreLib are out of sync. Could you please double-check that it is not the case? 

A small repro of this pattern works fine for me. It would be useful to have full repro steps.

**Comment by kant2002** [comment]
Here what I have on my system when I reproduce bug with DataGridView.
ILC `6.0.0-preview.6.21280.1`
Dotnet SDK `6.0.100-preview.6.21278.6`
Microsoft.AspNetCore.App `6.0.0-preview.6.21277.6`
Microsoft.NETCore.App `6.0.0-preview.6.21276.13`
Microsoft.WindowsDesktop.App `6.0.0-preview.6.21278.1`

I'm trying to create something similar with `repro` project, but right now no luck.
I try replace in created RSP file shipped with Nuget package paths to `runtimelab\artifacts\bin\coreclr\windows.x64.Debug\aotsdk`
No lock.
Then in addition to aotsdk replace `framework\*.dll` with `runtimelab\artifacts\bin\pkg\net6.0\runtime\windows-Release-x64\`
Same exception.

So only paths from .NET SDK was `microsoft.windowsdesktop.app.runtime.win-x64` but I cannot understand how it can be related to `Type.GetInterfaces()`. So seems to be I do all what is needed to run same ILCompiler and CoreLib. Am I right?

**Comment by jkotas** [comment]
> all what is needed to run same ILCompiler and CoreLib. Am I right?

Right.

**Comment by kant2002** [comment]
This is as minimal as I can produce.

```
using System;
using System.Globalization;

var dummy = "";

var dataGridViewCell = new DataGridViewCell();
var editType = dataGridViewCell.GetType();
if (dummy == "")
{
    editType = typeof(object);
    Type editingCtrlInterface = editType.GetInterface("System.Windows.Forms.IDataGridViewEditingControl");
    var xx = editType.IsSubclassOf(Type.GetType("System.Windows.Forms.Control"));
}

public class DataGridViewCell
{
    public Type GetEditType()
    {
        return typeof(Math);
    }
}
```

**Comment by jkotas** [comment]
Thank you for the repro. I have copied your repro to `samples\HelloWorld\Program.cs`, updated `samples\HelloWorld\HelloWorld.csproj` as below, and run `dotnet publish -c Debug -r win-x64`.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.DotNet.ILCompiler" Version="6.0.0-*" />
  </ItemGroup>

</Project>
```

@MichalStrehovsky Does it ring any bells?

**Comment by kant2002** [comment]
The warning in my sample produced 
```
Trim analysis warning IL2075: <Program>$.<Main>$(String[]): 'this' argument does not satisfy
'DynamicallyAccessedMemberTypes.Interfaces' in call to 'System.Type.GetInterface(String)'. 
The return value of method 'System.Object.GetType()' does not have matching annotations. 
The source value must declare at least the same requirements as those declared on the target location it is assigned to.
```

**Comment by kant2002** [comment]
Okay. I maybe finally get what's going on.
Code which I post has 2 control flow blocks.
In each of them I use local variable editType.

In first variant it is `ReturnType(None)` from `object.GetType()` method. In second this is `SystemTypeValue(object)`.

Since we have 2 usages from two blocks, when call `Type.GetInterface(typeName)` happens from stack taken value of type `MergePoint()` which contain both of possible types(?) .
And here where bug happens. Last step of `HandleCall` is 
https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Dataflow/ReflectionMethodBodyScanner.cs#L2224-L2241
Where this option does not called.

So I believe that here should be added additional case for MergePoint where I should check that requirements are met for all variants of data.

Also if talk about DataGridView, I probably should annotate `Type GetEditType()` with `[return: DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.Interfaces)]` and this probably unblock me in that area.
