### ISSUE TITLE
NativeAOT: ILC can produce object file that crashes clang 11 (ld) on macOS 10.14 Mojave

### ISSUE THREAD

**Issue by christianscheuer** [dotnet/runtimelab#1190]
When running NativeAOT on our build machine, which runs macOS 10.14 (Mojave), it appears that the clang 11 linker doesn't like the ILC-produced object file and it causes the linking to crash here:

```
Thread 1 Crashed:
0   ld                            	0x0000000100ec5be1 mach_o::relocatable::Parser<x86_64>::parse(mach_o::relocatable::ParserOptions const&) + 1375
1   ld                            	0x0000000100ebcb1e mach_o::relocatable::Parser<x86_64>::parse(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, mach_o::relocatable::ParserOptions const&) + 232
2   ld                            	0x0000000100f0f550 ld::tool::InputFiles::makeFile(Options::FileInfo const&, bool) + 780
3   ld                            	0x0000000100f11ee2 ld::tool::InputFiles::parseWorkerThread() + 550
4   libsystem_pthread.dylib       	0x00007fff654fd2eb _pthread_body + 126
5   libsystem_pthread.dylib       	0x00007fff65500249 _pthread_start + 66
6   libsystem_pthread.dylib       	0x00007fff654fc40d thread_start + 13
```

Running the same build on our development computer which runs 10.15 Catalina, there's no such crash.

On both machines, we see quite a few linker warnings like these:
```
ld: warning: could not create compact unwind for _Internal_CompilerGenerated__Module___InvokeRetO<SixLabors_ImageSharp_SixLabors_ImageSharp_Formats_Jpeg_Components_Encoder_RgbToYCbCrTables>: stack subq instruction is too different from dwarf stack size
```

While we see those warnings on both machines, the crash only occurs with clang Apple-11 on Mojave. I have no idea if they could be related or not.

I tried running the linker through lldb, but it doesn't reveal any usable backtrace (or I'm doing it wrong).

Any ideas as to what may cause this and/or how I could troubleshoot? We'd like to keep our build machine on Mojave for the time being.

**Comment by MichalStrehovsky** [comment]
I looked into the warnings briefly and filed #956. The linker has a command line option not to generate the compact unwinding info (I tried it and it broke exception handling - but later I found out there's also an option to "keep dwarf unwinding" - I didn't have patience to retry with "disable compact" and "keep dwarf" both enabled, which might fix things).

I'm not clear why the thing we generate is not representable with the compact unwind format though. It's also possible that there's something wrong with the unwinding info the compiler generates.

Not sure if it's related to the crash though.

**Comment by christianscheuer** [comment]
Thank you so much for taking a look at this, Michal.

> My theory based on seeing lld64 source code was that we're generating DWARF that is too new (Apple is typically a decade in the past when it comes to computer standards and seem to only support DWARF 3)

This sounds very plausible to my ears (purely based on the fact that this doesn't break clang 12 in Catalina but breaks clang 11 in Mojave).
I can see why there wouldn't be much point in trying to make this backwards compatible with Mojave, so maybe we'll just shelve out the money for a new build machine :)

**Comment by filipnavara** [comment]
Should be fixed in .NET 8.
