### ISSUE TITLE
How to install coreRT after Build. 

### ISSUE THREAD

**Issue by sangramsalunkhe97** [dotnet/runtimelab#1207]
Hi , I am done with building of source code by command `"./build.sh -s clr -c release "` on ubuntu 18.04 for that see the following screenshot. Now i wanna install coreRT for same but not get any idea how to do that. 
![error2](https://user-images.githubusercontent.com/81962828/121020855-678dec00-c7be-11eb-8ad8-e1265e38ade1.png)

**Comment by jkotas** [comment]
The build produces nuget packages. You can reference the locally built nuget packages via a path in your nuget.config file as described in https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/docs/workflow/building/coreclr/nativeaot.md#building

There is no install step.
