### ISSUE TITLE
Marshal.SizeOf and Marshal.OffsetOf

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtimelab#1234]
I learn from https://github.com/dotnet/corert/issues/5374#issuecomment-455706335 that 
`Marshal.SizeOf(typeof(TStruct))` should be replaced with `Marshal.TypeOf<TStruct>()`. Does similar possibility exists for `Marshal.OffsetOf` ?

**Comment by kant2002** [comment]
I try compile desktop application written in [Eto](https://github.com/picoe/Eto) using NativeAOT, but discover issue with [GtkSharp](https://github.com/GtkSharp/GtkSharp/pull/261) where they use a lot of `Marshal.SizeOf` and `Marshal.OffsetOf`

**Comment by jkotas** [comment]
> Does similar possibility exists for Marshal.OffsetOf ?

Yes, look for `Marshal.OffsetOf<T>(string fieldName)`.

For performance, it is even better to avoid calling the `Marshal.SizeOf/Offset/StructureToPtr/PtrToStructure` methods and use blittable types instead. See https://docs.microsoft.com/en-us/dotnet/standard/native-interop/ . It is not always easy to refactor old code to avoid these `Marshal` methods.

**Comment by kant2002** [comment]
Thanks!
