### ISSUE TITLE
Question: IR - how to get the arg position from GenTreeLclVar or LclVarDsc

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#1235]
Given this IR:
```
------------ BB01 [000..00B) (return), preds={} succs={}
               [000010] ------------                 IL_OFFSET void   IL offset: 0x0
N001 (  1,  1) [000000] ------------                 NO_OP     void
N004 (  3,  2) [000003] ------------         t3 =    LCL_VAR   int    V00 arg0
```
In `arg0` on the last line, presumably `0` refers to the argument position, but how can I get that number from either a `GenTreeLclVar` or a `LclVarDsc`?

Thanks

**Comment by jkotas** [comment]
`tree->GetLclNum()` ?

The first N lcl nums corresponds to the first N arguments (including hidden arguments). For example, if the method has hidden return buffer argument, lcl num 0 is the hidden return buffer and lcl num 1 is the first real argument.
