### ISSUE TITLE
Marshal.ReleaseComObject in NativeAOT

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtimelab#1254]
I would like to understand how https://github.com/dotnet/runtime/issues/54317 will affect NativeAOT.
 I understand decision behind answer, but slitly disappointed that WPF, and other libraries out of reach even with COM support in NativeAOT. Maybe I miss some idea?

**Comment by jkotas** [comment]
Discussed in https://github.com/dotnet/runtime/issues/54317
