### ISSUE TITLE
Selective reflection metadata generation

### ISSUE THREAD

**Issue by hez2010** [dotnet/runtimelab#1273]
Hello, 
I only need reflection for some specific types, setting `IlcDisableReflection` to `false` for the whole app would cause a major size regression.  

Is there any way to emit reflection metadata selectively so that metadata are only generated for types I specified?

**Comment by MichalStrehovsky** [comment]
Try adding `<IlcArg Include="--reflectedonly">` to an ItemGroup in your project. In this mode, only following thing get metadata:

* Types that were allocated or were target of `typeof` (without any of their members)
* Things that the dataflow analysis computed as necessary (e.g. you do `typeof(Foo).GetMethod("Bar")` - we will need metadata for Bar.
* Things that are referenced from RD.XML or as command line roots
* Things that are referenced through DynamicDependencyAttribute

You can expect around 15% savings compared to without this switch.
