### ISSUE TITLE
OS dev with this?

### ISSUE THREAD

**Issue by Shadowblitz16** [dotnet/runtimelab#1278]
Is it possible to compile a .net 5 application to bare metal x86-64 hardware with this?

**Comment by kant2002** [comment]
In short if you willing to put some effort into this, this is possible 

https://github.com/MichalStrehovsky/zerosharp
https://github.com/JoshuaWierenga/EfiSharp
https://github.com/MichalStrehovsky/SeeSharpSnake/pull/16
https://github.com/Michael-Kelley/RoseOS
https://github.com/dpeter99/CsharpLinkingTest

Some of these projects was written in CoreRT time, so you may need a bit of update. But in general that doable, maybe not so easy 😄
