### ISSUE TITLE
Can `typeof(T).Module` be supported in reflection-free mode?

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtimelab#1326]
It looks similar to `typeof(T).Assembly` and I think some limited form of object can be constructed.
Example of usage 

https://github.com/dotnet/winforms/blob/f3c6d29f74c23eb773cfaa7efebfa1eee5635b98/src/System.Windows.Forms/src/System/Windows/Forms/Application.cs#L827-L828

**Comment by MichalStrehovsky** [comment]
Yes, the way forward is dotnet/runtime#67193. This should work then.
