### ISSUE TITLE
NativeAOT-LLVM: Question: Should ints < 32 bits be used as parameter types?

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#1333]
In the IL-> LLVM code a function that returns a bool like https://github.com/dotnet/runtimelab/blob/482b83e1272e8225410c2056d846bd3919557d4e/src/coreclr/nativeaot/System.Private.CoreLib/src/Internal/Runtime/Augments/EnumInfo.cs#L63

will have an LLVM return type of `i1`.  For the RyuJIT->LLVM module this is a bit of a problem as ints are 32 bits so the above method gets compilled to 
```
define i1 @S_P_CoreLib_Internal_Runtime_Augments_EnumInfo__get_HasFlagsAttribute(i8* %0) {
Prolog:
  br label %1

1:                                                ; preds = %Prolog
  %2 = bitcast i8* %0 to i8**
  %3 = load i8*, i8** %2, align 4
  %4 = getelementptr i8, i8* %3, i32 20
  %CastPtrToPtr = bitcast i8* %4 to i32*
  %5 = load i32, i32* %CastPtrToPtr, align 4
  ret i32 %5
}
```
Which does not compile as `ret i32` does not match the `define i1`  .  Would it be more inline with RyuJIT IR to use `i32` for all parameter and return types of `i8`, `i16`, `i32`?

**Comment by jkotas** [comment]
We usually try to closely match the native calling conventions in RyuJIT. It helps with interop with unmanaged code. We have to be able to handle native calling convention for interop, and so it is easiest to use the same calling convention for regular managed code too.

Now, I am not sure how well this rule translates to the custom wasm calling convention that we have been using.

cc @AndyAyersMS

**Comment by yowl** [comment]
Thanks, Aside from changing i1 (bool) to i8 (byte) which is already done, I'll leave the others as is unless there is evidence changing it makes any difference.  I don't think LLVM can target any <32 bit systems so that may indicate that small ints are expanded anyway.
