### ISSUE TITLE
Failure to compile MsQuicApi class

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtimelab#1336]
I hit that in WinForms app, where is no networking, so I assume this is `PictureBox` being impolite.
```
D:\d\kant\GitHub\dotnet\runtimelab\src\coreclr\jit\importer.cpp:20927
D:\d\kant\GitHub\dotnet\runtimelab\src\coreclr\jit\importer.cpp:20927
Assertion failed '((size_t)exactContext & CORINFO_CONTEXTFLAGS_MASK) == CORINFO_CONTEXTFLAGS_CLASS' in 'System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi:.cctor()' during 'Importation' (IL size 259)

Assertion failed '((size_t)exactContext & CORINFO_CONTEXTFLAGS_MASK) == CORINFO_CONTEXTFLAGS_CLASS' in 'System.Net.Quic.Implementations.MsQuic.Internal.SafeMsQuicConfigurationHandle:.cctor()' during 'Importation' (IL size 55)
```

**Comment by jkotas** [comment]
Could you please share repro steps?

**Comment by kant2002** [comment]
https://github.com/kant2002/RibbonWinForms/tree/nativeaot/src/RibbonDemo1

Publish this project. Do I need something simpler?

**Comment by jkotas** [comment]
It does not repro for me. Here is what I have done:
```
build.cmd -s nativeaot+libs+nativeaot.packages -rc checked -c release

git clone https://github.com/kant2002/RibbonWinForms/
git checkout nativeaot

rem fix build breaks with .NET 6 preview.6
del /s assemblyinfo.cs

edit nuget.config to point to my local build above

cd src\RibbonDemo1
dotnet publish -c Release -r win-x64 RibbonDemo1Core.csproj --packages pkg
```

**Comment by kant2002** [comment]
Let's assume that I again do not recompile NativeAOT when switch branches. That's highly likely given my track record of doing that. So I will close that, as not an issue. Still I hit that when I receive `SEHException` during `FinishObjWriter` in a manner similar to #1316 that's why I even start running local ILC. But I hit `SEHException` with Nuget version of ILC, so that's a bit strange. I assume issue is on me, but would be good to find a way to slap error on my face in more friendly manner somehow.
