### ISSUE TITLE
Question: NativeAOT-LLVM: Emit Dwarf from clrjit

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#1364]
In order to get DWARF instructions written to the LLVM module from the clrjit dll is it `get/setBoundaries` that I should be looking at?  I think targets like x64 write the dwarf out separately at `PublishCode` in `CorInfoImpl` but I think I need to set the locations as I build the LLVM.

**Comment by MichalStrehovsky** [comment]
RyuJIT uses `setBoundaries` to tell us the mapping from native offsets to IL offsets. The compiler uses that to map native offsets to line numbers and passes the info to the object writer.

I don't know if it's convenient to hook into that mechanism.

The other option would be to add an API to the JitInterface that tells RyuJIT the IL to source mapping and pipe that through to LLVM. The debug information is available in `_debugInfo` on the CorInfoImpl.cs side.

**Comment by yowl** [comment]
Thanks, I'm just a bit reluctant to jump straight to extending the API in case I've missed something, but here it looks like the way to go.
