### ISSUE TITLE
GetMethod and MakeGenericMethod reflection 

### ISSUE THREAD

**Issue by anaanook** [dotnet/runtimelab#1366]
I've spent some time messing about with rd.xml and no luck, is something like this even possible with AOT or am I wasting my time?

```
            var readComponentMethod = typeof(Engine).GetMethod(methodName, BindingFlags.NonPublic | BindingFlags.Instance);
            var genericReadComponentMethod = readComponentMethod.MakeGenericMethod(type);
            genericReadComponentMethod.Invoke(this, parameters);
```

It warns me with messages like : 

```
Calling 'System.Reflection.MethodInfo.MakeGenericMethod(Type[])' which has `RequiresDynamicCodeAttribute` can break functionality when compiled fully ahead of time. The native code for this instantiation might not be available at runtime. 
```
I was hoping that there's some way to get this functionality with rd.xml, but the documentation for it is sparse and I'm a bit dense.  Probably slightly outside my depth here but I'd like to get it working.

Thanks for taking a look.

**Comment by Suchiman** [comment]
It is possible, see the last one here with `GenericArgument` https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/docs/using-nativeaot/rd-xml-format.md#types-directives

For that thing you provided, it would need to look something like
```xml
<Directives xmlns="http://schemas.microsoft.com/netfx/2013/01/metadata">
  <Application>
    <Assembly Name="MyCoolApp">
      <Type Name="MyCoolApp.Engine">
        <Method Name="methodName">
          <GenericArgument Name="type" />
        </Method>
        <Method Name="methodName">
          <GenericArgument Name="System.Double, System.Private.CoreLib" />
        </Method>
      </Type>
    </Assembly>
  </Application>
</Directives>
```

**Comment by anaanook** [comment]
Okay, so I seem to have gotten it working, although it's going to be extremely painstaking to build this file out for a complete project.  My naive approach is this:
```
<Directives xmlns="http://schemas.microsoft.com/netfx/2013/01/metadata">
  <Library>
    <Assembly Name="EncompassECS.Framework">
        <Type Name="Encompass.UberEngine">
            <Method Name="CallAllMessageMethods">
                <GenericArgument Name="Helloworld.TestMessage, Helloworld_Proj" />
            </Method>
            <Method Name="CallAllComponentMethods">
                <GenericArgument Name="Helloworld.TestComponent, Helloworld_Proj" />
            </Method>
        </Type>
    </Assembly>
    <Assembly Name="Helloworld_Proj">
        <Type Name="Helloworld.TestEngine" />
    </Assembly>
  </Library>
</Directives>
```

My question now, is on a full project I have hundreds of different components and messages, will I need to have them all represented ( could be achieved via script) , or is there a better approach

I gotta say, it is exciting just to see it working at all after hitting a wall for a while.

**Comment by Suchiman** [comment]
Any particular reason why you ***have to*** use reflection?
An alternative to using `rd.xml` is to use the type at least once in source, like (needs to be called like `IncludeGenerics(true)` from somewhere on the startup path)
```csharp
[MethodImpl(MethodImplOptions.NoInlining)]
public void IncludeGenerics(bool dontExecute)
{
    if (dontExecute)
        return;

    Encompass.UberEngine.CallAllMessageMethods<TestMessage>();
    Encompass.UberEngine.CallAllComponentMethods<TestComponent>();
    ...
}
```
although you only need to specify the generic arguments of structs, reference types use all the same native code. For the reference type version, you only need to ensure it's reflection preserved IIRC.

**Comment by anaanook** [comment]
Ahh, that method is doing the trick.  As far as reflection goes, I really like the cleanliness of this framework, and removing reflection from it is likely require work outside the scope of what I want to do.  

I really appreciate all the help, thank you so much!
