### ISSUE TITLE
Question: Building NativeAOT on limited devices

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtimelab#1382]
I build ILC on Raspberry PI to test ARM32 arch. Unfortunately I hit https://github.com/NuGet/Home/issues/10968 where not enough memory  on device and it start swap a lot.
Location where this is happens is `build.sh libs -rc Debug -lc Release`.
I strictly speaking do not neeed libs probably for limited testing, but `nativeaot.packages` do not want to compile until I have libs built at least once.
Any ideas how I can unblock building?

**Comment by MichalStrehovsky** [comment]
You might be better off crossbuilding. Crossbuilding works with CoreCLR, there are Ubuntu docker images available that should have everything needed to crossbuild (https://github.com/dotnet/runtime/blob/main/docs/workflow/building/coreclr/linux-instructions.md). Crossbuilding is how the official .NET ARM32/64 packages are created too. Never tried it though. NativeAOT might just work with that, or be a couple fixes away (modulo objwriter that doesn't hook into the build the usual way).

That said, the managed part of libs should be buildable by just specifying `-os` and `-arch` to build.sh (or even build.cmd), so you could build those on a more powerful machine and then copy all artifacts over. The native part requires a crossbuild toolchain of course, but that can be skipped. But that's a hack of course.

**Comment by alpencolt** [comment]
Don't know about current NativeAOT workflow but crossbuilding worked well on CoreRT https://github.com/dotnet/corert/blob/master/Documentation/cross-building.md

**Comment by kant2002** [comment]
After I wrote issue, I realise that I'm lazy bum and can look at the `eng/Subsets.props` to find appropriate targets.
I try `./build.sh libs.ref -rc Debug -lc Release` and I receive refs which was needed for building Nuget package. 
So now I was able to build NativeAOT on Raspberry with following commands
```
./build.sh nativeaot.objwriter -rc Debug -lc Release
./build.sh nativeaot -rc Debug -lc Release
./build.sh libs.ref -rc Debug -lc Release
./build.sh nativeaot.packages -rc Debug -lc Release
```

I avoid cross-building at all costs, since that's put huge toll on my main laptop where I working. I'm relatively active with development on different stacks, and each tools take couple Gb here and there. So I cannot afford installing WSL at the moment unfortunately. I understand that this is like participating in NASCAR on Lada Samara.

Anyway, all that's suggestions really helpful, since it allow me understand build process better and I do not have something against cross-building. I think my problem is solved.

**Comment by kant2002** [comment]
Not without further problems. Some additional steps needed.

Modify `eng/Subsets.props` to include lines in the `nativeaot.libs` subset.
```patch
+    <ProjectToBuild Include="$(LibrariesProjectRoot)System.Private.DeveloperExperience.Console\src\System.Private.DeveloperExperience.Console.csproj" Category="clr" />
+    <ProjectToBuild Include="$(LibrariesProjectRoot)System.Console\src\System.Console.csproj" Category="clr" />
+    <ProjectToBuild Include="$(LibrariesProjectRoot)System.Runtime\src\System.Runtime.csproj" Category="clr" />
+    <ProjectToBuild Include="$(LibrariesProjectRoot)System.Runtime.InteropServices\src\System.Runtime.InteropServices.csproj" Category="clr" />
+    <ProjectToBuild Include="$(LibrariesProjectRoot)System.Private.Uri\src\System.Private.Uri.csproj" Category="clr" />
```

Once this is done, run these command to build missing assemblies from libs set and create Nuget again.
```
./build.sh nativeaot.libs -rc Debug -lc Release
./build.sh nativeaot.packages -rc Debug -lc Release
``` 
Without that ILC crashed on missing assembly. Again, this is needed only for cases where you cannot do cross-compilation.

Also you need run 
```
echo "LANG=en_US.UTF-8" | sudo tee /etc/locale.conf > /dev/null
sudo locale-gen en_US.UTF-8
```
