### ISSUE TITLE
Question: NativeAOT-LLVM: For WebAssembly imports, DllImport Value misuse?

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#1390]
When importing functions from other modules in WebAssembly using the proposed WebAssembly canonical ABI, https://github.com/bytecodealliance/witx-bindgen, , the final Wasm/Wat looks like 
```
  (import "hellowasi" "reverse" (func $reverse (type 4)))
```
This imports the `reverse` function from the `hellowasi` module.  In order to generate this from LLVM, the LLVM has to look like:
```
declare void @reverse(i8*, i32, i8*) #2
...
attributes #2 = { "wasm-import-module"="hellowasi" "wasm-import-name"="reverse" }
```
For information, the C equivalent for emscripte/wasm-ld would be
```
__attribute__((import_module("hellowasi"), import_name("reverse"))) void reverse();
```

In c# this starts with currently
```
        [DllImport("*")]
        private static extern void reverse(byte* utf8Bytes, int len, IntPtr returnArea);
```

Not all `DllImports` are going to be Wasm imports, some like e.g. printf are supplied by the Emscripten runtime.  A rule could be created:

`DllImportAttribute.Value == "*"`  - treat as now.
`DllImportAttribute.Value != "*"`- assume its a Wasm import from another module and add the LLVM attributes - the Value property goes to the `wasm-import-module` attribute.

So this example would be
```
 [DllImport("hellowasi")]
```

Would that be acceptable or a misuse of DllImport and "The name of the DLL file that contains the entry point" https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.dllimportattribute.value?view=net-5.0

**Comment by jkotas** [comment]
>  A rule could be created:

I think we may want this rule to be configurable, similar to how the direct PInvoke calls are configurable today: https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/docs/using-nativeaot/interop.md#direct-pinvoke-calls

Otherwise, it looks reasonable to me.

**Comment by jkotas** [comment]
@lewing Is there any thinking about how the support for WebAssembly canonical ABI is going to look like in Mono?

**Comment by yowl** [comment]
Looking at the PInvoke config, how about
```
<WasmImport Import="wasi_snapshot_preview1!random_get" />
```

Then when 
```
[DllImport("*")]
private static extern int random_get(byte* utf8Bytes, int len);
```
Ilc would match `random_get` to the `WasmImport` and generate the correct LLVM import?

**Comment by yowl** [comment]
or
```
<WasmImport Module="wasi_snapshot_preview1" Function="random_get"/> 
```
To avoid ! parsing

(Edit, no maybe that's a bad idea as in Ilc these options appear as strings and also allowing a file containing a list would be more consistent)

**Comment by yowl** [comment]
I've gone ahead and put in a PR, sorry if I'm jumping the gun on feedback, something to actually review is often better though.

**Comment by zwcloud** [comment]
Is it possible to import emscripten functions via `[DllImport("*")]`, for example functions declared in `emsdk\upstream\emscripten\system\include\emscripten.h` and other builtin libs?

Usage of ``[DllImport("*")]`` seems not documented anywhere?

**Comment by zwcloud** [comment]
> Not all DllImports are going to be Wasm imports, some like e.g. printf are supplied by the Emscripten runtime. A rule could be created:
> 
> DllImportAttribute.Value == "*" - treat as now.

OK. Just read that and understood. I'm trying.
