### ISSUE TITLE
Build on ARM device broken (?)

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtimelab#1394]
After clean checkout on Raspberry, installing prerequisites and running first `./build.sh nativeaot -rc Debug -lc Release` I hit following error
```
......
  [100%] Built target nativeaot
  ~/runtimelab/src/coreclr
  Repo successfully built.
  Product binaries are available at /home/pi/runtimelab/artifacts/bin/coreclr/Linux.arm.Debug
  System.Private.CoreLib.Generators -> /home/pi/runtimelab/artifacts/bin/System.Private.CoreLib.Generators/netstandard2.0-Debug/System.Private.CoreLib.Generators.dll
/home/pi/.nuget/packages/microsoft.net.compilers.toolset/4.0.0-3.21376.12/tasks/netcoreapp3.1/Microsoft.CSharp.Core.targets(75,5): error MSB6006: "csc.dll" exited with code 137. [/home/pi/runtimelab/src/coreclr/nativeaot/System.Private.CoreLib/src/System.Private.CoreLib.csproj]

Build FAILED.
```

Second time I run this command issue is gone and I have error about missing `libobjwriter` which is obviously expected.
Any ideas what can go wrong?

**Comment by jkotas** [comment]
137 is out of memory. I guess that there are fewer things running in parallel when you rerun the build, and it is what allows it to pass.

**Comment by kant2002** [comment]
then for my case thats expected. thanks.
