### ISSUE TITLE
NativeAOT: No debug info emitted for osx-x64

### ISSUE THREAD

**Issue by TheSpydog** [dotnet/runtimelab#1414]
When I compile a Hello World app on my Mac via `dotnet publish -r osx-x64 -c Debug`, the following warning is generated from the compiler:
```
  ld: warning: can't parse dwarf compilation unit info in obj/Debug/net5.0/osx-x64/native/HelloWorld.o
```

The compiled executable runs fine, but I am unable to set breakpoints via lldb because none of the managed function names are recognized. Generating a dSYM folder manually by running `dsymutil HelloWorld` does not provide the required symbols either.

**Comment by filipnavara** [comment]
This is fixed with https://github.com/dotnet/llvm-project/pull/269.
