### ISSUE TITLE
[NativeAOT] System.BadImageException

### ISSUE THREAD

**Issue by fahrettinenes** [dotnet/runtimelab#1421]
Hello, I get System.BadImageFormatException error from my C# NativeAOT dll file,  when I want use assembly.load. How do I solve this?

**Comment by MichalStrehovsky** [comment]
Are you trying to `Assembly.Load` a DLL that was compiled with NativeAOT, or are you trying to use `Assembly.Load` within a NativeAOT-compiled app?

A stack with the failure would help.
