### ISSUE TITLE
ARM Linker issues

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtimelab#1424]
After I fix scanner issues, I have following error from linker
```
/usr/bin/ld: sdk/libRuntime.a(EHHelpers.cpp.o):(.data+0x1c): undefined reference to `RhpInterfaceDispatchAVLocation1'
/usr/bin/ld: sdk/libRuntime.a(EHHelpers.cpp.o):(.data+0x20): undefined reference to `RhpInterfaceDispatchAVLocation2'
/usr/bin/ld: sdk/libRuntime.a(EHHelpers.cpp.o):(.data+0x24): undefined reference to `RhpInterfaceDispatchAVLocation4'
/usr/bin/ld: sdk/libRuntime.a(EHHelpers.cpp.o):(.data+0x28): undefined reference to `RhpInterfaceDispatchAVLocation8'
/usr/bin/ld: sdk/libRuntime.a(EHHelpers.cpp.o):(.data+0x2c): undefined reference to `RhpInterfaceDispatchAVLocation16'
/usr/bin/ld: sdk/libRuntime.a(EHHelpers.cpp.o):(.data+0x30): undefined reference to `RhpInterfaceDispatchAVLocation32'
/usr/bin/ld: sdk/libRuntime.a(EHHelpers.cpp.o):(.data+0x34): undefined reference to `RhpInterfaceDispatchAVLocation64'
```

I assume that I should provide

**Comment by kant2002** [comment]
I take a look and seems that I need add `ALTERNATE_ENTRY RhpInterfaceDispatchAVLocation\entries` somewhere here
https://github.com/dotnet/runtimelab/blob/d648860b17173467e6f76116f8906596172e8ddc/src/coreclr/nativeaot/Runtime/arm/StubDispatch.S#L15-L21

I look how that's done on ARM64 and I see lot less ceremony with saving registers. That maybe due to fact that this is newer code, or because this is 64-bit arch. For example

https://github.com/dotnet/runtimelab/blob/d648860b17173467e6f76116f8906596172e8ddc/src/coreclr/nativeaot/Runtime/arm64/StubDispatch.S#L32-L39

Also on ARM64 this entry is `NESTED_ENTRY` whereas ARM uses `LEAF_ENTRY`. I need some education on that parts or what direction should I take.

**Comment by jkotas** [comment]
> I look how that's done on ARM64 and I see lot less ceremony with saving registers.

That's because ARM64 has enough scratch registers. 

> ARM64 this entry is NESTED_ENTRY whereas ARM uses LEAF_ENTRY

`NESTED_ENTRY` should be used when the function is pushing/popping registers. It will cause the right unwind info to be generated that is necessary for seeing good stacktrace during debugging.

`LEAF_ENTRY` can be used for functions that do not push/pop registers and that do not need the unwind info for other reasons.

**Comment by kant2002** [comment]
> That's because ARM64 has enough scratch registers.

Thanks

Does `NESTED_ENTRY` make push/pop automatically, or that's still on developer? I assume that this is developer responsibility.

`LEAF_ENTRY RhpInterfaceDispatch` seems to be incorrect usage because it is pushing registers as first command. Does this correct?

Can I add `ALTERNATE ENTRY RhpInterfaceDispatchAVLocation\entries` immediately below `RhpInterfaceDispatch\entries` and above `PROLOG_PUSH`. Like this.
```asm
LEAF_ENTRY RhpInterfaceDispatch\entries, _TEXT
       ALTERNATE_ENTRY RhpInterfaceDispatchAVLocation\entries
        // r12 currently contains the indirection cell address. But we need more scratch registers and
        // we may A/V on a null this. Both of these suggest we need a real prolog and epilog.
        PROLOG_PUSH {r1-r2}

        // r12 currently holds the indirection cell address. We need to get the cache structure instead.
        ldr         r2, [r12, #OFFSETOF__InterfaceDispatchCell__m_pCache]

        // Load the EEType from the object instance in r0.
        ldr         r1, [r0]
```

Based on other implementation proper place is right above `ldr r1, [r0]`, like this
```asm
LEAF_ENTRY RhpInterfaceDispatch\entries, _TEXT
        // r12 currently contains the indirection cell address. But we need more scratch registers and
        // we may A/V on a null this. Both of these suggest we need a real prolog and epilog.
        PROLOG_PUSH {r1-r2}

        // r12 currently holds the indirection cell address. We need to get the cache structure instead.
        ldr         r2, [r12, #OFFSETOF__InterfaceDispatchCell__m_pCache]

        // Load the EEType from the object instance in r0.
       ALTERNATE_ENTRY RhpInterfaceDispatchAVLocation\entries
        ldr         r1, [r0]
```

But I cannot find a way how I can skip popping of the saved registers. Or, or, or I think I get it. This location is just for pointing to location in the code where fault happens, and I should not care about popping of registers and simply can use variant 2.

**Comment by jkotas** [comment]
>  I assume that this is developer responsibility.

Correct.

> `LEAF_ENTRY RhpInterfaceDispatch` seems to be incorrect usage because it is pushing registers as first command. Does this correct?

Agree.

> This location is just for pointing to location in the code where fault happens, and I should not care about popping of registers and simply can use variant 2.

Popping of the registers when the fault happens is done in `UnwindSimpleHelperToCaller`
