### ISSUE TITLE
Publishing fails - exited with code 1181

### ISSUE THREAD

**Issue by MrSimsure** [dotnet/runtimelab#1449]
Hello, i was experimenting a bit with AoT for .NET and found this repo. Following the instruction i got the HelloWorld Sample project and tried to publish it, but an error appear at the end.
I will attach the last part of the output console, don't know if this part contains anything useful to discover what's causing the error, tell me if i need to post all the output text.

my setup is:
- **WINDOWS 10**
- **VISUAL STUDIO 2019**
- **PUBLISH SETTINGS** : release - Any CPU- net5.0 - self-contained - win-x64

```
_2>Target "Compile" skipped. Previously built successfully.
2>Target "SetupProperties" skipped. Previously built successfully.
2>Target "SetupProperties" skipped. Previously built successfully.
2>Target "SetupProperties" skipped. Previously built successfully.
2>Using "Exec" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
2>where /Q cl && where /Q link
2>Task "Message" skipped, due to false condition; ('$(_WhereCppTools)' != '0') was evaluated as ('0' != '0').
2>Task "Exec" skipped, due to false condition; ('$(_WhereCppTools)' != '0') was evaluated as ('0' != '0').
2>Task "Error" skipped, due to false condition; ('$(_WhereCppTools)' != '0' AND '$(_VCVarsAllFound)' == '1') was evaluated as ('0' != '0' AND '' == '1').
2>Target "_ComputeUserRuntimeAssemblies" skipped. Previously built successfully.
2>Using "ComputeManagedAssemblies" task from assembly "C:\Program Files\dotnet\sdk\5.0.400\Sdks\Microsoft.NET.ILLink.Tasks\Sdk\../tools/net472/ILLink.Tasks.dll".
2>Task "NETSdkError" skipped, due to false condition; ('$(SelfContained)' != 'true') was evaluated as ('true' != 'true').
2>Skipping target "IlcCompile" because all output files are up-to-date with respect to the input files.
2>Input files: obj\Release\net5.0\win-x64\HelloWorld.dll
2>Output files: obj\Release\net5.0\win-x64\native\HelloWorld.obj
2>Skipping target "GenerateResFile" because all output files are up-to-date with respect to the input files.
2>Input files: obj\Release\net5.0\win-x64\HelloWorld.dll
2>Output files: obj\Release\net5.0\win-x64\native\HelloWorld.res
2>Building target "LinkNative" completely.
2>Output file "bin\Release\net5.0\win-x64\native\HelloWorld.exe" does not exist.
2>Task "Exec" skipped, due to false condition; ('$(TargetOS)' != 'windows' and '$(NativeLib)' != 'Static') was evaluated as ('windows' != 'windows' and '' != 'Static').
2>Task "Exec" skipped, due to false condition; ('$(TargetOS)' != 'windows' and '$(NativeLib)' == 'Static') was evaluated as ('windows' != 'windows' and '' == 'Static').
2>link  @"obj\Release\net5.0\win-x64\native\link.rsp"
2>cannot open input file 'advapi32.lib'
2>The command "link  @"obj\Release\net5.0\win-x64\native\link.rsp"" exited with code 1181._
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========
```

This appens also with any other solution i try to create from zero.

**Comment by jkotas** [comment]
advapi32.lib is part of Windows SDK. It looks like there is a problem with your Windows SDK installation on your machine. Native AOT depends on Windows SDK to be installed.

Could you please share output of `dir "c:\Program Files (x86)\Windows Kits\10\Lib"` and `dir /s "c:\Program Files (x86)\Windows Kits\10\Lib\advapi32.lib"` from your machine?

**Comment by MrSimsure** [comment]
I should have installed the windows SdK through the .NET Desktop workload.
This is the  Windows Kit folder
![IMG_20210823_204858](https://user-images.githubusercontent.com/44972930/130504372-f9c55601-ad0b-4081-aec3-62a842f733da.jpg)

And this is the Lib subfolder
![IMG_20210823_210346](https://user-images.githubusercontent.com/44972930/130504433-b2659770-e0f4-40e7-a22d-b8476782a22d.jpg)
![Screenshot_20210823-204948](https://user-images.githubusercontent.com/44972930/130504451-03f28fa0-0795-46db-affe-4724680ad02a.jpg)

 in the x64 folder the advapi.lib is present, bit even if is the x64 folder it's named advapi32.lib

**Comment by MrSimsure** [comment]
I should have installed the windows SDK with the . NET desktop workload. 
This is the Windows Kit Folder
![IMG_20210823_204858](https://user-images.githubusercontent.com/44972930/130509540-809d52ad-1ef1-44d3-8924-00e0312e778d.jpg)

And this is the Lib subfolder
![IMG_20210823_210346](https://user-images.githubusercontent.com/44972930/130509578-90b4dc96-02c4-4d7a-8777-c6da6733b63a.jpg)


The advapi.lib is actually but in a subfolder of Lib present

**Comment by hez2010** [comment]
Can you try publishing with command line: `dotnet publish -c Release -r win-x64`?

**Comment by MrSimsure** [comment]
> Can you try publishing with command line: `dotnet publish -c Release -r win-x64`?

This produce a more precise output.

`  HelloWorld -> F:\Dev\cs\helloWorld\bin\Release\net5.0\win-x64\HelloWorld.dll
     Creating library bin\Release\net5.0\win-x64\native\HelloWorld.lib and object bin\Release\net5.0\win-x64\native\HelloWorld.exp
LINK : error LNK2001: unresolved external symbol wmainCRTStartup [F:\Dev\cs\helloWorld\HelloWorld.csproj]
HelloWorld.obj : error LNK2001: unresolved external symbol GetCPInfoExW [F:\Dev\cs\helloWorld\HelloWorld.csproj]
HelloWorld.obj : error LNK2001: unresolved external symbol SetLastError [F:\Dev\cs\helloWorld\HelloWorld.csproj]
HelloWorld.obj : error LNK2001: unresolved external symbol FormatMessageW [F:\Dev\cs\helloWorld\HelloWorld.csproj]`

It goes on with a long list of red _"unresolved external symbol"_, then starts with a list of yellow _"library machine type 'x86' conflicts with target machine type 'x64'"_

`C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x86\advapi32.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64' [F:\Dev\cs\helloWorld\HelloWorld.csproj]
C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x86\bcrypt.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64' [F:\Dev\cs\helloWorld\HelloWorld.csproj]`

And it ends with
`bin\Release\net5.0\win-x64\native\HelloWorld.exe : fatal error LNK1120: 207 unresolved externals [F:\Dev\cs\helloWorld\HelloWorld.csproj]
C:\Users\myname\.nuget\packages\microsoft.dotnet.ilcompiler\6.0.0-preview.7.21366.3\build\Microsoft.NETCore.Native.targets(353,5): error MSB3073: uscita dal comando "link  @"obj\Release\net5.0\win-x64\native\link.rsp"" with code 1120. [F:\Dev\cs\helloWorld\HelloWorld.csproj]`

**Comment by jkotas** [comment]
This error likely means that you have the `LIB` or `LIBPATH` environment variables pointing to 32-bit (x86) libraries. These environment variables should either not exist so that the Native AOT compiler will use the default paths for the libraries, or they should point to 64-bit (x64) libraries.

How did these environment variables got set on your machine?

You can try opening `x64 Native Tools Command Prompt for VS 2019` and try to run `dotnet publish -c Release -r win-x64` from there to see whether it works.
`dotnet publish -c Release -r win-x64`

**Comment by MrSimsure** [comment]
I have no LIB or LIBPATH env var set.
Even tried uninstalling and reinstalling all visual studio and workloads.
But i get the exact same output as before.
Setting LIB or LIBPATH to point to the x64 libs doesn't work either
Next i tried with _x64 Native Tools Command Prompt for VS 2019_, but i get this red error message

`error MSB4126: The specified solution configuration "Release | x64" is invalid. Specify a valid solution configuration using the Configuration and Platform properties (for example, MSBuild.exe Solution.sln / p: Configuration = Debug / p: Platform = "Any CPU") or do not specify any values for those properties in order to use the default solution configuration. [F: \ Dev \ cs \ HelloWorld \ HelloWorld.sln]`

**Comment by MrSimsure** [comment]
> This error likely means that you have the `LIB` or `LIBPATH` environment variables pointing to 32-bit (x86) libraries. These environment variables should either not exist so that the Native AOT compiler will use the default paths for the libraries, or they should point to 64-bit (x64) libraries.
> 
> How did these environment variables got set on your machine?
> 
> You can try opening `x64 Native Tools Command Prompt for VS 2019` and try to run `dotnet publish -c Release -r win-x64` from there to see whether it works.
> `dotnet publish -c Release -r win-x64`

I have no LIB or LIBPATH env var set.
Even tried uninstalling and reinstalling all visual studio and workloads.
But i get the exact same output as before.
Setting LIB or LIBPATH to point to the x64 libs doesn't work either
Next i tried with _x64 Native Tools Command Prompt for VS 2019_, but i get this red error message

`error MSB4126: The specified solution configuration "Release | x64" is invalid. Specify a valid solution configuration using the Configuration and Platform properties (for example, MSBuild.exe Solution.sln / p: Configuration = Debug / p: Platform = "Any CPU") or do not specify any values for those properties in order to use the default solution configuration. [F: \ Dev \ cs \ HelloWorld \ HelloWorld.sln]`

**Comment by jkotas** [comment]
> error MSB4126: The specified solution configuration "Release | x64" is invalid.

Does it work if you delete  HelloWorld.sln and run `dotnet publish -c Release -r win-x64 HelloWorld.csproj` so that it builds the hello world project directly?

**Comment by kant2002** [comment]
Hi @MrSimsure do you able to build your application? I usually compile form regular Powershell (PS Core to be precise) and build works now without a need to use Dev Command line for Visual Studio.
