### ISSUE TITLE
After latest update of NativeAOT cannot publish samples

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtimelab#1451]
After these steps
```
cs samples/HelloWorld
../../.dotnet/dotnet publish -c Release -r linux-arm --packages pkg /p:DisableUnsupportedError=true
```

Publish fails with this message.
```
/home/pi/runtimelab/samples/HelloWorld/HelloWorld.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Runtime.linux-arm with version (= 6.0.0-rc.1.21411.2)
/home/pi/runtimelab/samples/HelloWorld/HelloWorld.csproj : error NU1102:   - Found 57 version(s) in dotnet-public [ Nearest version: 6.0.0-preview.7.21377.19 ]
/home/pi/runtimelab/samples/HelloWorld/HelloWorld.csproj : error NU1102:   - Found 0 version(s) in dotnet-experimental
/home/pi/runtimelab/samples/HelloWorld/HelloWorld.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.App.Runtime.linux-arm with version (= 6.0.0-rc.1.21411.7)
/home/pi/runtimelab/samples/HelloWorld/HelloWorld.csproj : error NU1102:   - Found 59 version(s) in dotnet-public [ Nearest version: 6.0.0-preview.7.21378.6 ]
/home/pi/runtimelab/samples/HelloWorld/HelloWorld.csproj : error NU1102:   - Found 0 version(s) in dotnet-experimental
```

**Comment by jkotas** [comment]
This is side-effect of https://github.com/dotnet/runtime/pull/57143 that updated SDK to unsigned build. You either need to copy the samples out so that they do not pick up repo global.json; or install the unsigned SDK from the nightly feed globally.

**Comment by kant2002** [comment]
I'm a bit lazy, so I comment out `<clear />` in the Nuget.config
Also I receive warning `warning NETSDK1179: One of '--self-contained' or
'--no-self-contained' options are required when '--runtime' is used.`. I
assume that I should use `../../.dotnet/dotnet publish --self-contained -c
Release -r linux-arm --packages pkg /p:DisableUnsupportedError=true` . Is
this correct?

**Comment by jkotas** [comment]
> I comment out `<clear />` in the Nuget.config

Yep, that works too.

> `--self-contained` or `--no-self-contained` options are required when '--runtime' is used.

Yes, specifying `--self-contained` will silence this warning with the latest SDK.
