### ISSUE TITLE
[NativeAOT] Bug on enumeration (Dispose)

### ISSUE THREAD

**Issue by dellamonica** [dotnet/runtimelab#1455]
Here's a minimal repro:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.DotNet.ILCompiler" Version="7.0.0-*" />
  </ItemGroup>

</Project>
```

```csharp
using System.Collections.Immutable;

var list = ImmutableList<string>.Empty.Add("Hello,").Add( "World!");
foreach (var s in list) 
{
    Console.Write(s);
}
```

Output:
```
Hello,World!Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Immutable.ImmutableList`1.Enumerator.Dispose() + 0x3f
   at <Program>$.<Main>$(String[]) + 0x121
   at tmp!<BaseAddress>+0x1df6ba
```

---

In my actual code this reproduced problem goes away when avoiding the Dispose call (which is done by the foreach lowering), however, soon after it hits what is possibly another different bug:

```
Process terminated. Generic virtual method pointer lookup failure.

Declaring type handle: MethodTable:0x00007FF74C7567B8
Target type handle: MethodTable:0x00007FF74C77A4E0
Method name: System.Linq.IOrderedEnumerable<TElement>.CreateOrderedEnumerable
Instantiation:
  Argument 00000000: MethodTable:0x00007FF74C760670
```

**Comment by MichalStrehovsky** [comment]
Thanks for the good repro steps! This is a regression introduced in #1430. The fix is in #1456.

The "Generic virtual method pointer lookup failure." may or may not be the same bug.

**Comment by dellamonica** [comment]
@MichalStrehovsky, thanks! I'll try the next package update (with the fix) and will post here whether the pointer lookup failure still happens.

**Comment by MichalStrehovsky** [comment]
Please open a new issue if the `Generic virtual method pointer lookup failure.` part still reproes. Thank you!

**Comment by dellamonica** [comment]
It does. Let me try to figure out a minimal repro and I will then open a
separate issue.


Thanks for the fix.
