### ISSUE TITLE
System.Text.Json using source generators produces "Method not found"

### ISSUE THREAD

**Issue by jimmylearns** [dotnet/runtimelab#1498]
```csharp
using System.Text.Json;
using System.Text.Json.Serialization;
using NAOTJsonMissingMethod;

Sample sample = new();
JsonSerializer.Serialize(sample, SampleJsonContext.Default.Sample);

namespace NAOTJsonMissingMethod
{
    internal class Sample
    {
        public string Property { get; set; }
    }

    [JsonSerializable(typeof(Sample))]
    internal partial class SampleJsonContext : JsonSerializerContext
    {
        
    }
}
```
dotnet 6.0.100-preview.7
NativeAOT 7.0.0-alpha.1.21431.2

due the compilation stage it pops warning about missing method and then after running the published binary it throws:

Unhandled Exception: System.MissingMethodException: Method not found: 'System.Text.Json.Serialization.Metadata.JsonTypeInfo`1<!!0> System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo(System.Text.Json.JsonSerializerOptions, System.Func`1<!!0>, System.Func`2<System.Text.Json.Serialization.JsonSerializerContext, System.Text.Json.Serialization.Metadata.JsonPropertyInfo[]>, System.Text.Json.Serialization.JsonNumberHandling, System.Action`2<System.Text.Json.Utf8JsonWriter, !!0>)'.
   at Internal.Runtime.TypeLoaderExceptionHelper.CreateMissingMethodException(ExceptionStringID, String) + 0x47
   at Internal.Runtime.CompilerHelpers.ThrowHelpers.ThrowMissingMethodException(ExceptionStringID, String) + 0x6
   at NAOTJsonMissingMethod.SampleJsonContext.get_Sample() + 0x12
   at <Program>$.<Main>$(String[]) + 0x2f
   at NAOTJsonMissingMethod!<BaseAddress>+0x200305

**Comment by MichalStrehovsky** [comment]
There were breaking changes in the source generator APIs and looks like things are not fully stable yet.

I'm following up on one of the similar issues in https://github.com/dotnet/runtime/pull/59042#issuecomment-928685839.

This should all stabilize as get close to .NET 6 RTM.

**Comment by jimmylearns** [comment]
same problem with release version

**Comment by jkotas** [comment]
This works fine for me with .NET 6.0 RTM and the latest ilc package (7.0.0-alpha.1.21559.1). 

It it does not work for you, please share the ilc package version that you are using and the build log.

Also, you may want to make sure to clean you obj and bin directories. The incremental builds do not always work correctly when .NET SDK version is updated.
