### ISSUE TITLE
NativeAOT: "Undefined instruction was hit" in StartupCodeHelpers.InitializeModules

### ISSUE THREAD

**Issue by TheSpydog** [dotnet/runtimelab#1499]
```
Unhandled exception at 0x0800D000 in Bootstrap.nspd_root
 0x00000000:  Undefined instruction was hit
```
This occurs on line 40 of StartupCodeHelpers.cs, called from my Bootstrap InitializeRuntime function.

I believe this is a very recent regression bug. I encounter this crash when running an application built with runtime.win-x64.Microsoft.DotNet.ILCompiler package version 7.0.0-alpha.1.21453.5, but if I revert back to the last package version (7.0.0-alpha.1.21431.2) then it works as expected.

Worth noting that I'm cross-compiling to linux-arm64, which might be a contributing factor.

**Comment by MichalStrehovsky** [comment]
It's probably https://github.com/dotnet/runtimelab/pull/1461. We're probably still not generating the right relocs for something.

Can you see what relocs are there in InitializeRuntime at the spot where it's crashing? https://github.com/dotnet/runtimelab/pull/1461#issuecomment-908246032 has the objdump command - the grep might be different.

I checked this statically and it looked alright but maybe I wasn't looking at the right spot. We have zero test coverage for ARM64 in the CI and I don't have ARM64 hardware.

(I need to get Android builds running so that I can at least use my phone...)

**Comment by TheSpydog** [comment]
> Can you see what relocs are there in InitializeRuntime at the spot where it's crashing? [#1461 (comment)](https://github.com/dotnet/runtimelab/pull/1461#issuecomment-908246032) has the objdump command - the grep might be different.

Sure, although because I'm very new to LLVM and the inner workings of ObjWriter I'm not entirely sure what I should be looking for. 😅 

Here are all the lines involving InitializeRuntime in the output from `llvm-objdump -r compiled-il.o`:
```
RELOCATION RECORDS FOR [.rodata]:
00000000000ffd20 R_AARCH64_PREL32 S_P_CoreLib_Internal_Runtime_CompilerHelpers_StartupCodeHelpers__InitializeModules

RELOCATION RECORDS FOR [.debug_info]:
0000000000116b3a R_AARCH64_ABS64 S_P_CoreLib_Internal_Runtime_CompilerHelpers_StartupCodeHelpers__InitializeModules
...
0000000000116b98 R_AARCH64_ABS64 S_P_CoreLib_Internal_Runtime_CompilerHelpers_StartupCodeHelpers__InitializeModules+0x34

RELOCATION RECORDS FOR [.debug_loc]:
00000000000a57fc R_AARCH64_ABS64 S_P_CoreLib_Internal_Runtime_CompilerHelpers_StartupCodeHelpers__InitializeModules
00000000000a5804 R_AARCH64_ABS64 S_P_CoreLib_Internal_Runtime_CompilerHelpers_StartupCodeHelpers__InitializeModules+0x2c
00000000000a580f R_AARCH64_ABS64 S_P_CoreLib_Internal_Runtime_CompilerHelpers_StartupCodeHelpers__InitializeModules+0x34
00000000000a5817 R_AARCH64_ABS64 S_P_CoreLib_Internal_Runtime_CompilerHelpers_StartupCodeHelpers__InitializeModules+0x1e8
00000000000a5834 R_AARCH64_ABS64 S_P_CoreLib_Internal_Runtime_CompilerHelpers_StartupCodeHelpers__InitializeModules
00000000000a583c R_AARCH64_ABS64 S_P_CoreLib_Internal_Runtime_CompilerHelpers_StartupCodeHelpers__InitializeModules+0x2c
00000000000a5847 R_AARCH64_ABS64 S_P_CoreLib_Internal_Runtime_CompilerHelpers_StartupCodeHelpers__InitializeModules+0x34
00000000000a584f R_AARCH64_ABS64 S_P_CoreLib_Internal_Runtime_CompilerHelpers_StartupCodeHelpers__InitializeModules+0x1e8
00000000000a586c R_AARCH64_ABS64 S_P_CoreLib_Internal_Runtime_CompilerHelpers_StartupCodeHelpers__InitializeModules
00000000000a5874 R_AARCH64_ABS64 S_P_CoreLib_Internal_Runtime_CompilerHelpers_StartupCodeHelpers__InitializeModules+0x2c
00000000000a587f R_AARCH64_ABS64 S_P_CoreLib_Internal_Runtime_CompilerHelpers_StartupCodeHelpers__InitializeModules+0x34
00000000000a5887 R_AARCH64_ABS64 S_P_CoreLib_Internal_Runtime_CompilerHelpers_StartupCodeHelpers__InitializeModules+0x1e8
00000000000a58a4 R_AARCH64_ABS64 S_P_CoreLib_Internal_Runtime_CompilerHelpers_StartupCodeHelpers__InitializeModules
00000000000a58ac R_AARCH64_ABS64 S_P_CoreLib_Internal_Runtime_CompilerHelpers_StartupCodeHelpers__InitializeModules+0x2c
00000000000a58b7 R_AARCH64_ABS64 S_P_CoreLib_Internal_Runtime_CompilerHelpers_StartupCodeHelpers__InitializeModules+0x34
00000000000a58bf R_AARCH64_ABS64 S_P_CoreLib_Internal_Runtime_CompilerHelpers_StartupCodeHelpers__InitializeModules+0x1e8
00000000000a58dc R_AARCH64_ABS64 S_P_CoreLib_Internal_Runtime_CompilerHelpers_StartupCodeHelpers__InitializeModules
00000000000a58e4 R_AARCH64_ABS64 S_P_CoreLib_Internal_Runtime_CompilerHelpers_StartupCodeHelpers__InitializeModules+0x2c
00000000000a58ef R_AARCH64_ABS64 S_P_CoreLib_Internal_Runtime_CompilerHelpers_StartupCodeHelpers__InitializeModules+0x34
00000000000a58f7 R_AARCH64_ABS64 S_P_CoreLib_Internal_Runtime_CompilerHelpers_StartupCodeHelpers__InitializeModules+0x1e8

RELOCATION RECORDS FOR [.eh_frame]:
000000000003b8e5 R_AARCH64_PREL32 _lsda0S_P_CoreLib_Internal_Runtime_CompilerHelpers_StartupCodeHelpers__InitializeModules
```

I also searched for the function call that it crashed on (`RhpRegisterOsModule`) but there were no results. I'm guessing that's because it's a call to a native function implemented in the Runtime library, not a managed method.

Out of curiosity I ran `llvm-dwarfdump` on the .o file as well, and it spat out hundreds of `error: failed to compute relocation: R_AARCH64_PREL32, Invalid data was encountered while parsing the file` messages. I wonder if that might be related?

**Comment by MichalStrehovsky** [comment]
Yeah, this is because of relocs.

Unfortunately, we're emitting the correct type of relocs. The problem is that some of them point to wrong things, and some are absent completely (compared to when using older objwriter library). Still trying to make sense out of that...

**Comment by MichalStrehovsky** [comment]
> It's probably #1461

Okay, I broke this in #1488 instead. #1519 should hopefully fix this.

**Comment by TheSpydog** [comment]
Yes, that fixed it! Thank you!
