### ISSUE TITLE
Failed to made HttpClient work on Windows in reflection free mode

### ISSUE THREAD

**Issue by jimmylearns** [dotnet/runtimelab#1512]
The following code is working fine with flag `<IlcDisableReflection>true</IlcDisableReflection>` compiled on Linux
```csharp
await new HttpClient().GetStringAsync("https://github.com/dotnet");
```
I tried to do the same on the windows machine but it failed with the following exception 
```
Unhandled Exception: EETypeRva:0x0031B9E8: TypeInitialization_Type_NoTypeAvailable  
---> EETypeRva:0x0031B0D0: Reflection_Disabled
at HttpClientAot!<BaseAddress>+0xf2233
at HttpClientAot!<BaseAddress>+0x2c5c84
at HttpClientAot!<BaseAddress>+0x1bf46b
at HttpClientAot!<BaseAddress>+0x2c5b1c
at HttpClientAot!<BaseAddress>+0x1bf5dd
at HttpClientAot!<BaseAddress>+0x1b8379
at HttpClientAot!<BaseAddress>+0x1ba6a4
at HttpClientAot!<BaseAddress>+0x18948a
Exception_EndOfInnerExceptionStack 
```
To figure out what is using reflection and make this exception log more understandable i've tried to add flag `<IlcGenerateStackTraceData>true</IlcGenerateStackTraceData>` but this flag adds warning 
```
System.Private.StackTraceMetadata.dll : warning IL9702: Assembly 'System.Private.StackTraceMetadata produced AOT analysis warnings.
```
and then on the launch of the app output prints nothing at all... 

latest version of NativeAOT and .net 6.0 prev 7

How to make exception stacktraces full in the reflection free mode? (before adding the flag works fine)
What is preventing HttpClient from work on Windows?

**Comment by MichalStrehovsky** [comment]
Broken stack trace is #1248. I'm fixing it in #1518.

Unfortunately, HttpClient does use reflection on Windows.

The stack is:

```
   at System.Runtime.InteropServices.Marshal.PtrToStructure[T](IntPtr) + 0xa0
   at System.Net.NetworkInformation.HostInformationPal.GetFixedInfo() + 0x7b
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T&, Boolean&, Object&, Func`1) + 0xab
   at System.Threading.LazyInitializer.EnsureInitialized[T](T&, Boolean&, Object&, Func`1) + 0x59
   at System.Net.NetworkInformation.HostInformationPal.get_FixedInfo() + 0x98
   at System.Net.CookieContainer.CreateFqdnMyDomain() + 0x9
   at System.Net.CookieContainer..cctor() + 0x24
```

PtrToStructure calls Activator.CreateInstance.
