### ISSUE TITLE
Disambiguate CalliMarshallingMethodThunk based on modopts

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtimelab#153]
Name mangling doesn't take modopts into account so we end up with two different signatures having the same simple name.

We should probably drop all modopt except for the one specifying calling convention.

Might need to add code to respect the calling convention too.

Test: baseservices/callconvs/TestCallingConventions

**Comment by kant2002** [comment]
`CalliMarshallingMethodThunk.ClassCode` always return `1594107963` or `0x5F04283B`, If I understand correctly there need to provide different values based on different `modopts`? How original number was selected, and what bits can I use to produce variants, based on modopts?

**Comment by MichalStrehovsky** [comment]
ClassCode would stay the same. The fix would be somewhere within CompareToImpl - the signatures should not compare equal.

The fix probably needs to be all the way in MethodSignature.CompareTo - it hasn't been updated for the fact that calling conventions can be encoded outside the signature flags.

(ClassCode is chosen with a fair dice roll :))

**Comment by kant2002** [comment]
`MethodSignature` has only Flags which has calling convention. 
https://github.com/dotnet/runtime/blob/afacf6a99e1b98331af958caec638bd93dc46ffe/src/coreclr/tools/Common/TypeSystem/Common/MethodDesc.cs#L12-L25

Nothing what hints on the modopts in the `MethodSignature` itself. Properties of `CalliMarshallingMethodThunk` also the same between two instances, so I assume that issue somewhere in the different place.

**Comment by MichalStrehovsky** [comment]
The modopts are accessed this way:

https://github.com/dotnet/runtime/blob/55e2378d86841ec766ee21d5e504d7724c39b53b/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs#L782-L840

**Comment by kant2002** [comment]
Does that mean that I should properly construct `Signature` property here, but reading embedded data?
https://github.com/dotnet/runtime/blob/55e2378d86841ec766ee21d5e504d7724c39b53b/src/coreclr/tools/Common/TypeSystem/IL/Stubs/CalliMarshallingMethodThunk.cs#L68

Also I see differences between methods only in `[in]/[out]` attributes. for example one method has `[InAttribute]`, and second has `[InAttribute][OutAttribute]`

**Comment by MichalStrehovsky** [comment]
> Does that mean that I should properly construct Signature property here, but reading embedded data?
https://github.com/dotnet/runtime/blob/55e2378d86841ec766ee21d5e504d7724c39b53b/src/coreclr/tools/Common/TypeSystem/IL/Stubs/CalliMarshallingMethodThunk.cs#L68

That signature should be okay as-is - it's the managed signature without any calling convention (we explicitly don't copy the flags either).

> Also I see differences between methods only in [in]/[out] attributes. for example one method has [InAttribute], and second has [InAttribute][OutAttribute]

Those attributes cannot be placed on a calli signature so they don't matter.

**Comment by kant2002** [comment]
Repro case for asserts from #68278

```csharp
Vftbl d;
var g = new Guid();
unsafe
{
    d._RegisterInterfaceInGlobal = (void*)(IntPtr)5;
    d._RevokeInterfaceFromGlobal = (void*)(IntPtr)5;

    d.RegisterInterfaceInGlobal(ref g);
    d.RevokeInterfaceFromGlobal(in g);
}
public struct Vftbl
{
    public unsafe void* _RegisterInterfaceInGlobal;

    public unsafe void* _RevokeInterfaceFromGlobal;

    public unsafe delegate* unmanaged[Stdcall]<ref Guid, int> RegisterInterfaceInGlobal => (delegate* unmanaged[Stdcall]<ref Guid, int>)_RegisterInterfaceInGlobal;

    public unsafe delegate* unmanaged[Stdcall]<in Guid, int> RevokeInterfaceFromGlobal => (delegate* unmanaged[Stdcall]<in Guid, int>)_RevokeInterfaceFromGlobal;
}
```
