### ISSUE TITLE
Assembly.GetEntryAssembly crashes instead of returning null with shared library and CGO consumer

### ISSUE THREAD

**Issue by CarlosLanderas** [dotnet/runtimelab#1545]
Hello everyone.

I'm doing some labs and trying to compile a shared library with the AOT runtime and I have Microsoft.Azure.CosmosDb as a dependency.

There is a internal method inside DocumentClient called initialize that executes `if (Assembly.GetEntryAssembly() != null)` and it is not returning null but crashing. I'm consuming the linux so shared library with golang using cgo.

I understand I am executing the shared library from an unmanaged platform and it might not have the entry assembly information but how can I bypass the crash? Is there any stub available for GetEntryAssembly? Thanks

The stacktrace looks like this:

```csharp
Object reference not set to an instance of an object. -    at Internal.Runtime.CompilerHelpers.StartupCodeHelpers.GetEntryAssembly() + 0x14
   at Microsoft.Azure.Cosmos.DocumentClient.Initialize(Uri, ConnectionPolicy, Nullable`1, HttpMessageHandler, ISessionContainer, Nullable`1, IStoreClientFactory, TokenCredential) + 0x117
   at Microsoft.Azure.Cosmos.ClientContextCore.Create(CosmosClient, CosmosClientOptions) + 0x13e
   at Microsoft.Azure.Cosmos.CosmosClient..ctor(String, AuthorizationTokenProvider, CosmosClientOptions) + 0xbc
```

**Comment by jkotas** [comment]
It is a bug. #1546 has the fix. Thank you for reporting it!

**Comment by CarlosLanderas** [comment]
Thanks @jkotas!! When will this fix be released to test it?.

**Comment by jkotas** [comment]
The package with the fix should be available later today.
