### ISSUE TITLE
Implement ICustomMarshaler

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtimelab#160]
Related tests:

```
Interop/ICustomMarshaler/ConflictingNames/SameNameDifferentAssembly
Interop/ICustomMarshaler/Primitives/ICustomMarshaler_TargetWindows
Interop/PInvoke/CustomMarshalers/CustomMarshalersTest
```

**Comment by kant2002** [comment]
What's needed for these? I hit this when trying to use https://github.com/Ruslan-B/FFmpeg.AutoGen

**Comment by kant2002** [comment]
This library uses https://github.com/Ruslan-B/FFmpeg.AutoGen/blob/master/FFmpeg.AutoGen/ConstCharPtrMarshaler.cs custom marshaller class. Maybe it would be easier for me fix here, instead of trying to make it work for codegen solution

**Comment by MichalStrehovsky** [comment]
It would involve writing a new marshaller that uses the marshalling metadata from the assembly (we currently just ignore it):

https://github.com/dotnet/runtimelab/blob/30767ec88d693ba7696cdc34b0aebd778f42591e/src/coreclr/tools/Common/TypeSystem/Ecma/EcmaSignatureParser.cs#L607-L624

Calls `GetInstance` on the type specified in the marshaller, and uses it to marshal the values.

**Comment by kant2002** [comment]
For now I read "managed marshaler name", and pass that to `MarshalAsDescriptor`, which in turn drive `CustomTypeMarshaller` which is new marshaller class.
Within that class I have `TypeSystemContext`, but I did not see a way how I can resolve from existing type name. `TypeSystemContext` has access only to `SystemModule`, and I do not have access to assembly where this custom marshaller living. This is indication for me that some other changes needed. Would like to know, what's better place where I put "currently processing assembly"
