### ISSUE TITLE
HelloWorld doesn't work

### ISSUE THREAD

**Issue by ghost** [dotnet/runtimelab#1611]
Hi everyone,

I can't get the helloworld example to work with the current documentation.
All steps in the documentation can be performed until you have to add the compiler package with command:

dotnet add package Microsoft.DotNet.ILCompiler.LLVM -v 7.0.0-*

That package doesn't seems to exist in the repository for the LLVM compiler, only for the non LLVM compiler:
https://dev.azure.com/dnceng/public/_packaging?_a=feed&feed=dotnet-experimental

A version 6.0.0-* can be added but during publishing I get the following error that doesn't make much sense either:

dotnet publish -r win-x64 -c release

error : Native compilation can run on x64 and arm64 hosts only.

**Comment by jkotas** [comment]
The LLVM branch is focused on targeting Wasm currently. If you would like to target win-x64, use the regular RyuJIT based Microsoft.DotNet.ILCompiler package.

**Comment by ghost** [comment]
I see. That seems to work just fine.

But if that's case, which still seems weird to me, someone should modify the HelloWorld and NativeLibrary to WASM examples and alter the corresponding documentation. Currently it's clearly focused on console and native libraries, with attention for very specific OS related functionalities. No WASM at all.

Anyway, thanks for the fast response!

**Comment by jkotas** [comment]
@yowl Could you please fix the README in the LLVM branch?
