### ISSUE TITLE
[NativeAOT] __declspec(dllexport) even for lib

### ISSUE THREAD

**Issue by wegylexy** [dotnet/runtimelab#1617]
I use NativeAOT to build a static lib. Then wrap it in a single all-in-one DLL such that it is the only DLL required by third-party EXEs.

Currently, I have to include a `.def` file to export my `UnmanagedCallersOnly` entry points.

Is there an easy way to `__declspec(dllexport)` even when pushing a static lib?

**Comment by jkotas** [comment]
The toolchain will generate the .def file (on Windows) or linker exported_symbols_list (on non-Windows) if you set `ExportsFile` msbuild property.

**Comment by wegylexy** [comment]
I was trying to create a C++ wrapper for the NativeAOT output and bundle both into a single DLL. It turns out LIBs compiled for different C++ runtime libraries cannot be linked into the same DLL. At the end, I put `/MT`.
`ExportsFile` helps to build the intermediate DLL, but at the end I no longer need it.
It seems I'm getting close to building a light weight native client for SignalR.
