### ISSUE TITLE
Make AOT compiler work with VS 2022

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtimelab#1618]
I uninstalled VS 2019 and I get this error when trying to use native AOT with .NET 6:

```
C:\Users\david\.nuget\packages\microsoft.dotnet.ilcompiler\7.0.0-alpha.1.21503.2\build\Microsoft.NETCore.Native.Windows.props(113,5): error : Platform linker not found. To fix this problem, download and install Visual Studio 2019 from http://visualstudio.com. Make sure to install the Desktop Development for C++ workload. For ARM64 development also install C++ ARM64 build tools. [C:\Users\david\source\repos\WebApplication564\WebApplication564\WebApplication564.csproj]
```

Do I need to do anything special to make it work with VS 2022

**Comment by MichalStrehovsky** [comment]
If there as no C++ ABI change, we probably just need to bump the version here: https://github.com/dotnet/runtimelab/blob/5a67a65f6fe2d4a0e1cf06cce2545e8b8fd56c90/src/coreclr/nativeaot/BuildIntegration/findvcvarsall.bat#L18

Could you try updating the batch file in your NuGet cache? Should be next to the props file that is complaining.

**Comment by jkotas** [comment]
https://github.com/dotnet/runtimelab/pull/1624
