### ISSUE TITLE
[NativeAOT] SignalR MessagePackHubProtocol

### ISSUE THREAD

**Issue by wegylexy** [dotnet/runtimelab#1625]
Any idea how to solve this? https://github.com/dotnet/aspnetcore/issues/12102#issuecomment-933785686
Although their concern is Android/iOS or Unity using a different AOT, the root cause may be the same.

**Comment by jkotas** [comment]
https://github.com/neuecc/MessagePack-CSharp#aot-code-generation-support-for-unityxamarin ?

**Comment by wegylexy** [comment]
The thing that SignalR MessagePack worker `internal`ly uses at [dotnet/aspnetcore/.../DefaultMessagePackHubProtocolWorker.cs#L23](https://github.com/dotnet/aspnetcore/blob/0cff8a75a3b7692ff510d63a59d632f56029e092/src/SignalR/common/Protocols.MessagePack/src/Protocol/DefaultMessagePackHubProtocolWorker.cs#L23) rely on lambda expression compilation here [neuecc/MessagePack-CSharp/.../MessagePackSerializer.NonGeneric.cs#L249-L254](https://github.com/neuecc/MessagePack-CSharp/blob/b6761136762ac4215d9d5c077f7d11e733ec38b8/src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackSerializer.NonGeneric.cs#L249-L254)

**Comment by wegylexy** [comment]
It'd be great if NativeAOT can discover and pre-compile those expressions via static analysis or otherwise.

The problem currently is that the non-generic version doesn't know runtime types ahead of time. Nevertheless, SignalR JSON hub protocol works; that's `System.Text.Json`.

**Comment by jkotas** [comment]
Right, that does not work well with AOT. We have no plans to make it work well with AOT, it is not even possible.

If a library wants to be usable with AOT, it has to avoid patterns that are incompatible with AOT (e.g. by using source generators).

**Comment by wegylexy** [comment]
I learned that source generators can only insert codes, but not replace existing codes.

**Comment by jkotas** [comment]
Source generators are intentionally designed that way. The library itself typically requires updates to allow the source generated code to be plugged in. The source generators shipping in .NET 6 have some good examples on how it can be done.

**Comment by wegylexy** [comment]
In my use case, I can use C++ to do the dynamic part by passing a portion of the raw buffer. And, it's working now.
