### ISSUE TITLE
I am trying to compile a .net core app, seeing linking errors..

### ISSUE THREAD

**Issue by ssarin3194** [dotnet/runtimelab#1634]
The command "link  @"obj\Debug\netcoreapp3.1\win-x64\native\link.rsp"" exited with code 1.
C:\Users\ssarin\.nuget\packages\microsoft.dotnet.ilcompiler\1.0.0-alpha-29408-02\build\Microsoft.NETCore.Native.targets(331,5)
: error MSB3073: The command "link  @"obj\Debug\netcoreapp3.1\win-x64\native\link.rsp"" exited with code 1. [C:\Asm-AsmScannersU
tilities\src\WindowsAuditSetting\SetACLNative.csproj]

```
call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=amd64 -host_arch=amd64 -winsdk=10.0.16299.0
pushd "%~dp0"
msbuild /t:restore "%~dp0src\WindowsAuditSetting\SetACLNative.csproj"
msbuild "%~dp0src\WindowsAuditSetting\SetACLNative.csproj" 
msbuild /t:publish "%~dp0src\WindowsAuditSetting\SetACLNative.csproj" 
popd
exit /B %EX%
```

Here is my .csproj

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
	<runtimeidentifier>win-x64</runtimeidentifier>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.DotNet.ILCompiler" Version="1.0.0-alpha-29408-02" />
	<PackageReference Include="Microsoft.Win32.Registry" Version="4.4.0" />
  </ItemGroup>
	
</Project>
```

**Comment by MichalStrehovsky** [comment]
Could you try to rerun link.exe to see why it's failing?

You can do that by adding a `cd %~dp0` followed by `link @"obj\Debug\netcoreapp3.1\win-x64\native\link.rsp"` line right after the `msbuild /t:publish` line in your script.

**Comment by kant2002** [comment]
@ssarin3194 did you try method which Michal suggested?

**Comment by ssarin3194** [comment]
yes, this seems to have worked. thank you
