### ISSUE TITLE
Error MCG0004 while building UWP release package

### ISSUE THREAD

**Issue by iloxmn** [dotnet/runtimelab#1638]
This is the project I try to use in my app
https://github.com/smourier/DirectN
Only modified HRESULT.cs to avoid this issue
https://github.com/microsoft/dotnet/issues/807

It works fine in debug mode but in release mode it gets error 
Error		MCG0004:InternalAssert Assert Failed: Unexpected inline array element type. during [UNKNOWN]	
And some warnings
[MarshalAs(UnmanagedType.IDispatch)] is obsolete

I searched the whole internet and I can't find anything related. 
All nuget packages are up-to-date, downgrade packages also doesn't work. 

I managed to remove a lot of files which I didn't use, it complied but doesn't work properly, it gets wrong properties and "access violation ...... memory corrupted" error which I don't remember exactly.

**Comment by jkotas** [comment]
Hi @iloxmn, this repo is not a good place to report issue in .NET Native for UWP. Could you please report it via VS Developer Community Portal (https://developercommunity.visualstudio.com/home) instead ?
