### ISSUE TITLE
Roundtripping delegates through a native function pointer

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtimelab#164]
Interop/MarshalAPI/FunctionPointer/FunctionPtrTest

**Comment by filipnavara** [comment]
The test doesn't seem to exist anymore at this location. Would it make sense to remove the exclusions and close the issue?

**Comment by jkotas** [comment]
Yes

**Comment by MichalStrehovsky** [comment]
This is not resolved. The test was just converted to an `ActiveIssue` but still references this issue number.

**Comment by filipnavara** [comment]
Thanks for pointing that out. I was looking for the test since it exercises a broken code path on ARM.

For posterity, the new location:
https://github.com/dotnet/runtime/blob/25b1249e4edb3fef50be35df88fcb363d42f8574/src/tests/Interop/MarshalAPI/FunctionPointer/FunctionPointer.cs#L30-L68
