### ISSUE TITLE
NativeAOT-LLVM: Question: CT_HELPER calls and getMethodSig

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#1640]
Is there something about helper methods, e.g. `CORINFO_HELP_READYTORUN_STATIC_BASE` that means that I can't call 
```
_compiler->eeGetMethodSig(call->gtCallMethHnd, &sigInfo);
```
 for them?

I want to generate the function signature for LLVM.  Maybe I should just use the args on the `GenTreeCall`?

**Comment by yowl** [comment]
I tried and the `handle` is much lower than the `handleBase` for
```
        private Object HandleToObject(IntPtr handle)
        {
#if DEBUG
            handle = new IntPtr(~(long)s_handleHighBitSet & (long) handle);
#endif
            int index = ((int)handle - handleBase) / handleMultipler;
            return _handleToObject[index];
        }
```
In `CorInfoImpl.cs`

**Comment by jkotas** [comment]
JIT helpers have fake `METHOD_HANDLEs` inside the JIT. These fake method handles do not work when passed to JIT/EE interface.

**Comment by yowl** [comment]
Thanks
