### ISSUE TITLE
Idea: Tracking based Native AOT

### ISSUE THREAD

**Issue by hez2010** [dotnet/runtimelab#1642]
# Tracking based Native AOT
This is an idea proposal helping .NET Native AOT dependency analysis.

## Background
AOT compilation in .NET is hard: the most annoying problem is that the compiler cannot statically figure out all type instantiations and methods which are built by reflection, so we have to heavily rely on runtime directives, i.e. `rd.xml` to indicate compiler to generate extra code for those types and methods.

We already have composite crossgen2 to pre-AOT code as much as possible and use JIT as fallback if there's no code pre-generated, so similarly, I'm suggesting tracking JIT events of type instantiations and method calls for those don't have code pre-generated during runtime. This is somewhat similar to static PGO but for dependency analysis. 

## Design
I'm proposing two build properties.

### IlcCollectingJitTrackingData
`IlcCollectingJitTrackingData` can be set with a file name, and then the program built by ilc will contain a JIT for generating code during runtime which also responsible for collecting JIT codegen information, and write tracking data to the file specified.

```
dotnet publish -c Release -r win-x64 /p:IlcCollectingJitTrackingData=data.mibc
```

And users need to run the published program for tracking data collection.

Data collected by PerfView for below code:

```
var method = typeof(Array).GetMethod(nameof(Array.IndexOf), 1, BindingFlags.Public | BindingFlags.Static | BindingFlags.DeclaredOnly, null, CallingConventions.Any, new[] { Type.MakeGenericMethodParameter(0).MakeArrayType(), Type.MakeGenericMethodParameter(0) }, null)!.MakeGenericMethod(typeof(int));
var array = new int[] { 3, 2, 1, 0 };
Console.WriteLine(method.Invoke(null, new object?[] { array, 0 }));
```

```
Microsoft-Windows-DotNETRuntime/Method/JittingStarted
HasStack="True" ThreadID="8,524" ProcessorNumber="0" MethodID="140,717,073,463,624" ModuleID="140,717,070,893,056" MethodToken="100,663,749" MethodILSize="21" MethodNamespace="System.Array" MethodName="IndexOf" MethodSignature="generic int32  (!!0[],!!0)" ClrInstanceID="7" 
```

Then we know a method `System.Array.IndexOf<System.Int32>(System.Int32[], System.Int32)` is JITted during runtime.

An example of the tracking data `data.mibc`:
```json
{
    "Version": "1.0",
    "Assemblies":
    [
        {
            "Name": "System.Private.CoreLib",
            "Types":
            [
                {
                    "Name": "System.Array",
                    "Methods":
                    [
                        {
                            "Name": "IndexOf", 
                            "GenericArguments": [ { "Name": "System.Int32", "Assembly": "System.Private.CoreLib" } ], 
                            "Parameters": [ { "Name": "System.Int32[]", "Assembly": "System.Private.CoreLib" }, { "Name": "System.Int32", "Assembly": "System.Private.CoreLib" } ] 
                         }
                    ]
                }
            ]
        }
    ]
}
```

Also, we can have a tool similar to `dotnet-pgo` for merging tracking data, importing data from `rd.xml`, and exporting data to `rd.xml`. Alternatively, we can produce `rd.xml` directly instead of json data.

### IlcJitTrackingData

`IlcJitTrackingData` is used for consuming the tracking data for codegen:

```
dotnet publish -c Release -r win-x64 /p:IlcJitTrackingData=data.mibc
```

Then the compiler will know it needs to generate code for `System.Array.IndexOf<System.Int32>(System.Int32[], System.Int32)` without needs of `rd.xml`.

**Comment by jkotas** [comment]
Thank you for sharing the idea.

We have experimented with approaches like this in the past in .NET Native UWP project. They did not work well. They allow creating a working demo quickly; but they do not produce reliable applications. The problem is that it is impossible in practice to achieve 100% code coverage in the training run that would be required to capture all generic instantiations and reflection accesses that the application may do. We have decided to not invest into approaches like this, and instead invest into solutions that deliver predictable experience: static analysis supported by annotations and source generators. Look for "predictable experience" in https://github.com/dotnet/designs/blob/main/accepted/2020/form-factors.md for more details.

If you would like to build a solution like this yourself, the way to do that would be:
- Run the application on CoreCLR and capture all JIT events
- Convert the CoreCLR trace to rdxml that you will pass to the NativeAOT toolchain

**Comment by hez2010** [comment]
Thanks for your reply and advise.

This approach is not perfect but will reduce the effort of writing `rd.xml` manually while dealing with non-AOT-friendly libraries - it can get rid of the need of heavily performing the "run program - see exception - write runtime directive" loop. I'll try building an external tool for this. 

It's ok to close this issue as it's not suitable as a generic solution.

**Comment by hez2010** [comment]
I have a question: How can I get the corresponding assembly name using `ModuleId` in an ETW event?

```csharp
var source = new EventPipeEventSource(session.EventStream);
source.Clr.MethodJittingStarted += (data) =>
{
    var assemblyName = ? ; // I think I can get this with data.ModuleId but I don't know how to do it
};

```

**Comment by jkotas** [comment]
ModuleLoad events should give you mapping from ModuleIDs to names.
