### ISSUE TITLE
NativeAOT-LLVM: Question: Cast/InstanceOf helper implementation 

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#1644]
For these helpers, 
https://github.com/dotnet/runtimelab/blob/14e7c749e4f9e075e41b2655f3ddddd3a6598a5b/src/coreclr/jit/assertionprop.cpp#L4363-L4371

Should the implementation in clrjit be using the runtime export, e.g. `RhTypeCast_CheckCastClass` or should it be doing what the IL generation does and going straight to the `CheckCastClass` in `TypeCast` ?

**Comment by jkotas** [comment]
It would be nice if the LLVM backend can reuse the JIT helper mapping in `src\coreclr\tools\aot\ILCompiler.Compiler\Compiler\JitHelper.cs` so that it does not have to be duplicated. If it is hard to do, I think either of the two options you have mentioned would work.

**Comment by yowl** [comment]
I was looking at that (`GetCastingHelperNameForType`) but I have this code which gives me the same names I think:

```
        CorInfoHelpFunc helperNum = _compiler->eeGetHelperNum(call->gtCallMethHnd);
        void* addr = _compiler->compGetHelperFtn(helperNum, &pAddr);
        const char* symbolName = (*_getMangledSymbolName)(_thisPtr, addr);
```

**Comment by jkotas** [comment]
Yes, `_getMangledSymbolName` looks good.
