### ISSUE TITLE
NativeAOT-LLVM: Question: Determine from clrjit if a struct contains a GC pointer

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#1647]
I want to move this C# logic to the clrjit:
```
        if (type is DefType defType)
        {
            if (!defType.IsGCPointer && !defType.ContainsGCPointers)
            {
                return true;
            }
        }
```
Can I do this from a `CORINFO_CLASS_HANDLE`  assuming I know it represents a struct already?  Structs which don't contain GC pointers are passed on the LLVM stack, otherwise they go in the shadow stack.

**Comment by jkotas** [comment]
I think you should be able to call `getClassAttribs` and look for `CORINFO_FLG_CONTAINS_GC_PTR`

**Comment by SingleAccretion** [comment]
Another way would be to use `ClassLayout*`:
```cs
// Usually you would have access to ClassLayout* directly
// however, as it is stored in LclVarDsc's and GT_OBJ's.
ClassLayout* layout = compiler->typGetObjLayout(handle);

if (layout->HasGCPtr()) { ... }
```

**Comment by yowl** [comment]
Thanks.  If I may extend this question a bit more.  For structs that wrap a single primitive of an int32/int64/single/double, the struct is passed as the primitive type in LLVM.  For IL it decides this here:

https://github.com/dotnet/runtimelab/blob/d56d19272484f803b4c8739e0ca19482735ca15b/src/coreclr/tools/aot/ILCompiler.LLVM/CodeGen/ILToLLVMImporter.cs#L1438

I see there is a `ClassLayout::AreCompatible` which in name at least might do what I want, is this the right way to go?  To use it I'd need to be able to get the `ClassLayout` or `CORINFO_CLASS_HANDLE` for int32/64/single/double.  

Alternatively I can call back to Ilc I imagine and use `StructIsWrappedPrimitive`.

**Comment by SingleAccretion** [comment]
I don't think there is an existing facility that would provide exactly the same semantics (there is `LclVarDsc::CanBeReplacedWithItsField`, but that is a hack used for another purpose), so I think calling back into the VM would be the better choice in this case (for compatibility if nothing else).

However, I will ask: what is the reason for this unwrapping? Can we not do it? Every instance I've seen of it in the past was eventually understood to be flawed.

**Comment by yowl** [comment]
Pretty sure this predates my involvement, but there is this comment:

https://github.com/dotnet/runtimelab/blob/d56d19272484f803b4c8739e0ca19482735ca15b/src/coreclr/tools/aot/ILCompiler.LLVM/CodeGen/ILToLLVMImporter.cs#L1288-L1289

@morganbr it's a long time ago, but do you remember where this problem manifested itself?

**Comment by SingleAccretion** [comment]
Hmm, so an interop problem. Of course would be nice to see if it can be worked around some other way, and what is the root cause.

I think it is ok to continue to unwrap (after all, I suspect this is just the beginning of the swizzling we'll have to put up with to reconcile .NET's and LLVM's type systems), but it would be nice to not have to do this.

**Comment by morganbr** [comment]
@yowl it looks like that was you in https://github.com/dotnet/corert/commit/5b103fba8576f294f1ed2e6cb454950e0a4c5ec9 but I'm guessing it had to do with whether they turned into WASM method arguments or got pushed onto the (LLVM) stack

**Comment by yowl** [comment]
@morganbr  Shame on me for dragging you back when it me :-0  Thanks anyway for putting me in it!
