### ISSUE TITLE
NativeAOT-LLVM: Question: Replacing locals on the shadow stack with OBJ/IND

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#1652]
Its going to be beneficial to implement this suggestion for locals stored on the shadow stack

1.  Transform all locals that will live on the shadow stack into IND/OBJ(SHADOW_STACK_ADDRESS_LCL_VAR + OFFSET) (in a pre-SSA walk).
2.   Then perform a layout pass that sets lvStkOffs, which the codegen will then ultimately use.

From https://github.com/dotnet/runtimelab/pull/1649#discussion_r728334303

Currently we might have this IR
```
  /--*  t13    ref
 *  STORE_LCL_VAR ref    V16 
...
t44 =    LCL_VAR   ref    V16
```

If I understand the idea, this would become something like (hand drawn IR Frankenstein'ed from places)
```
      /--*  t13
txx = OBJ       struct<System.EETypePtr, 4>

/--*  txx    ref
*  STORE_LCL_VAR ref    V16 
...
t44 =    IND   ref   
         \ V16

```

I'm missing something (maybe a lot) about how the `OBJ` will work and "store" the local `t13`.  

cc @SingleAccretion

**Comment by SingleAccretion** [comment]
The idea is very simple: the loads and stores would be converted to their indirect form.

So, for the `STORE_LCL_VAR`:
```scala
     STORE_LCL_VAR(t1) ref V01

Becomes (VSS is the variable representing the base of the shadow stack):
t2 = LCL_VAR(VSS) + OFFSET_V01
     STOREIND(t2, t1)
```
```scala
     STORE_LCL_VAR(t3) struct V02

Becomes:
t4 = LCL_VAR(VSS) + OFFSET_V02
     STORE_OBJ(t4, t3)
```

`LCL_VAR`s are transformed into `IND`s (for scalar types) or `OBJ`s (for struct types)
```scala
t1 = LCL_VAR ref V01

Becomes:
t2 = LCL_VAR(VSS) + OFFSET_V01
t1 = IND(t2) ref
```
```scala
t3 = LCL_VAR struct V02

Becomes:
t4 = LCL_VAR(VSS) + OFFSET_V02
t3 = OBJ(t4)
```

> Then perform a layout pass that sets lvStkOffs, which the codegen will then ultimately use.

I think we should also do this before the above transform, but only for locals to live on the shadow stack. You can imagine some optimizations possible there,  e. g. giving locals that are more used (have higher weighted ref counts...) smaller offsets on the shadow stack.

**Comment by yowl** [comment]
Thanks, I'll do the first bit, "I think we should also do this before the above transform, but only for locals to live on the shadow stack" and check I'm on the right page.  As you say, the idea is simple enough, its just the implementation where I may go off the tracks.

**Comment by yowl** [comment]
I have this where I sort the applicable locals by their `lvRefCntWtd` descending
```
void Llvm::SetShadowStackLocalOffsets(Compiler* pCompiler)
{
    if (pCompiler->lvaCount == 0) return;

    auto cmpLambda = [](const LclVarDsc* lhs, const LclVarDsc* rhs) { return lhs->lvRefCntWtd() > rhs->lvRefCntWtd(); };
    std::vector<LclVarDsc*> locals;

    unsigned lclNum;
    LclVarDsc* varDsc;
    for (lclNum = 0, varDsc = pCompiler->lvaTable; lclNum < pCompiler->lvaCount; lclNum++, varDsc++)
    {
        if (!varDsc->lvIsParam && !canStoreLocalOnLlvmStack(varDsc))
        {
            locals.push_back(varDsc);
        }
    }

    if (locals.size() == 0) return;

    std::sort(locals.begin(), locals.end(), cmpLambda);

    unsigned int offset = 0;
    for (unsigned i = 0; i < locals.size(); i++)
    {
        LclVarDsc* varDsc = locals.at(i);
        CorInfoType corInfoType = toCorInfoType(varDsc->TypeGet());
        offset = padOffset(corInfoType, offset);
        varDsc->SetStackOffset(offset);
        offset = padNextOffset(corInfoType, offset);
    }
}
```
Nothing too controversial for this bit I hope?

**Comment by SingleAccretion** [comment]
Yep, the approach looks good. Note that the ref counts may be stale at this point and are only available when optimizing (and I think we should do it only when optimizing too). It is a bit unfortunate that we cannot share the refcounting pass with SSA, but it is how it is.

In general, there are many things to optimize here (say we have a "hot" struct with only one ref field that is not used a lot, we could "promote" structs and do other complex things (minimize alignment holes say), but it is good to get things working first 😄).

**Comment by yowl** [comment]
Thanks, `LCL_VAR(VSS) + OFFSET_V01` is this a `LCL_VAR_ADDR` ?

**Comment by SingleAccretion** [comment]
`LCL_VAR_ADDR` will represent "an address" on the LLVM stack in our model (they would in fact be converted into `LCL_VAR(VSS) + OFFSET_V01` in this walk for shadow stack vars). `VSS` will be our local variable representing the shadow stack (`&shadowStack[0]`) (it should be marked as ~~`lvArgument`~~ `lvIsParam` too, and I think eventually integrated into the method signature that is initted [at import time](https://github.com/dotnet/runtime/blob/abd6ea46b250bac1c0183a227e15d102ac5a30f3/src/coreclr/jit/lclvars.cpp#L92) with all the other parameters).

`LCL_VAR(VSS) + OFFSET_V01` is simply `GT_ADD(LVL_VAR VSS, GT_CNS_INT(offset on the shadow stack))`.

**Comment by yowl** [comment]
When I replace the `LCL_VAR`, I need to get it to replace the node, i.e. in 
```
t1 = IND(t2) ref
```
The `t1` needs to be the same node  as the `LCL_VAR`, replaced in other uses.  I can see a `gtReplaceTree` but that's for statements.  Do I just walk the blocks and nodes looking for uses of the `LCL_VAR`?

**Comment by SingleAccretion** [comment]
You can use `ChangeOper` to transform an existing node into a different one (this is known as "bashing"). There is also `LIR::TryGetUse`, which does the linear walk you mention, but it is unnecessary in this case.

**Comment by yowl** [comment]
Thanks.  
I have this code for GT_STORE_IND which as you see does a `RhpAssignRef`.  I don't want that for these replacements, but I'm not sure how to identify them easily.  Is there some flag or something I could set on the node to help ?
```
void importStoreInd(llvm::IRBuilder<>& builder, GenTreeStoreInd* storeIndOp)
{
    Value* address = getGenTreeValue(storeIndOp->Addr()).getValue(builder);
    Value* toStore = getGenTreeValue(storeIndOp->Data()).getValue(builder);
    if (toStore->getType()->isPointerTy())
    {
        // RhpAssignRef will never reverse PInvoke, so do not need to store the shadow stack here
        builder.CreateCall(getOrCreateRhpAssignRef(), ArrayRef<Value*>{address, castIfNecessary(builder, toStore, Type::getInt8PtrTy(_llvmContext))});
    }
    else
    {
        castingStore(builder, toStore, address, storeIndOp->gtType);
    }
}
```

**Comment by SingleAccretion** [comment]
There is such a flag, yes, `GTF_IND_TGT_NOT_HEAP` (all nodes have the `gtFlags` field which is used for these sort of miscellaneous purposes).

There is also a function that tells the kind of barrier one needs for a given indirect store: `gcIsWriteBarrierCandidate`. Not sure how well it'd work "as is" for us though (presumably it should work ok).

**Comment by SingleAccretion** [comment]
Related to this tangentially.

I presume the way our WASM GC reporting will work is that (all) calls will be labeled as safepoints, and then GC triggered only from explicit allocations (this is ok because we are single-threaded). This makes implementing the reporting require that the GC know all live references be put on the shadow stack at a safepoint. Locals are already always put on the shadow stack (but with this design we can explore optimizations similar to "EH-WriteThru", where we don't put them there always in safepoint-free regions...) (we'll need to use volatile writes to the shadow stack so that LLVM doesn't do funny things with them), but "tree temps" are not, i. e. if we have something like this:
```scala
t1 = BYREF
     CALL
t2 = t1 + 2;
... some code that uses t2 ...
```
`t1` is live across a safepoint, so we'll need to report it, aka implement "spilling" to the shadow stack for these refs.

**Comment by yowl** [comment]
You can run it multithreaded.  Its' not part of the main branch, but it "worked"  in some experiments I did.

**Comment by SingleAccretion** [comment]
Heh, well, it would also be really nice to have this work on non-WASM, where concurrency is a given :).

But it seems that will require a very different approach to precise reporting anyway (likely using the "statepoints GC" support in LLVM).

**Comment by yowl** [comment]
I think I need a `CodeGenInterface`, which is commented out, for gcIsWriteBarrierCandidate, so I'll try the `GTF_IND_TGT_NOT_HEAP ` flag on its own.

**Comment by yowl** [comment]
Going to close this now.  The tests are passing so think I'm on the home stretch.
