### ISSUE TITLE
NativeAOT: Cannot build from source.

### ISSUE THREAD

**Issue by Carcass-Project** [dotnet/runtimelab#1676]
Hi, I made an issue about NativeAOT a bit back, and I got a fix, but I have to compile from source.
Now, I'm trying to compile it from source but I get this error message:

![image](https://user-images.githubusercontent.com/91569324/138595809-73334329-df40-488c-a67a-7d88041dc9a6.png)

**Comment by Carcass-Project** [comment]
Also the files listed below don't seem to exist..

**Comment by jkotas** [comment]
> Also the files listed below don't seem to exist..

This is a problem inherited from dotnet/runtime . I have opened https://github.com/dotnet/runtime/issues/60809 on it.

You should be able to find the error earlier in the build console. If you are not able to, could you please share the build console output?

**Comment by Carcass-Project** [comment]
The console output
[log.txt](https://github.com/dotnet/runtimelab/files/7405845/log.txt)
:

**Comment by jkotas** [comment]
The problem is that the repo root path is too long. It is again a problem inherited from dotnet/runtime. I have opened https://github.com/dotnet/runtime/issues/60812

Could you please try cloning the repo into a shorted path?

**Comment by Carcass-Project** [comment]
Everything worked this time, thanks for the help!
