### ISSUE TITLE
[NativeAOT-LLVM] Identity FunctionPointerType in clrjit?

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#1703]
In Ilc, there is a type for the return value of
```
        public delegate*<MethodTable*, MethodTable*, ushort, IntPtr> DynamicTypeSlotDispatchResolve
        {
```
`FunctionPointerType`.  These types are placed on the shadow stack for the LLVM backend.  In clrjit, can I differentiate between these and other `CorInfoType::CORINFO_TYPE_PTR` ?

I see that there is a  `retTypeSigClass` on `CORINFO_SIG_INFO` and there is something in here `0x4000000000420010`  .  I can pass that back to `getClassAttribsInternal` in https://github.com/dotnet/runtimelab/blob/ffdb757581deab3fef9c1babe059bc590f583bea/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs#L1888 and the type looks right
![image](https://user-images.githubusercontent.com/2720041/140569623-9b9e7caf-52b2-4eef-ad71-2aeed830295e.png)

But its not picked up as `type.IsDelegate` so I dont get a useful flag back, only `CORINFO_FLG_FINAL`.  Why is that?

Thanks!

**Comment by jkotas** [comment]
`FunctionPointerType` is not a delegate. 

I do not think you can differentiate between a unmanaged pointer and a function pointer in the JIT. Both of them are  `CORINFO_TYPE_PTR`.

**Comment by yowl** [comment]
Thanks, so does a `FunctionPointerType` need to be GC tracked?   I'm thinking it would be better to change
```
        internal static bool CanStoreTypeOnStack(TypeDesc type)
        {
            if (type is DefType defType)
            {
                if (!defType.IsGCPointer && !defType.ContainsGCPointers)
                {
                    return true;
                }
            }
            else if (type is PointerType)
            {
                return true;
            }

            return false;
        }
```
In the existing IL->LLVM generation to
```
        internal static bool CanStoreTypeOnStack(TypeDesc type)
        {
            if (type is DefType defType)
            {
                if (!defType.IsGCPointer && !defType.ContainsGCPointers)
                {
                    return true;
                }
            }
            else if (type is PointerType || type is FunctionPointerType)
            {
                return true;
            }

            return false;
        }
```

**Comment by jkotas** [comment]
> Thanks, so does a FunctionPointerType need to be GC tracked? I

FunctionPointerType should not be GC tracked.

**Comment by yowl** [comment]
Thanks.
