### ISSUE TITLE
[NativeAOT] cannot preempt symbol: Program__Module__cctor

### ISSUE THREAD

**Issue by TheSpydog** [dotnet/runtimelab#1704]
I'm getting the following lld linker error when attempting to build any .NET assembly with module initializers for the Switch platform (linux-arm64):
`cannot preempt symbol: Program__Module____cctor`

These errors appear for both the main assembly and every referenced assembly that contains a module initializer. (`FNA__Module__cctor`, for example.) If I remove the module initializers, then the build has no errors.

The same project built correctly as of early September, so this seems to be either a regression or a side effect of the new module initializer logic implemented in NativeAOT.

I'm aware I'm in unsupported territory targeting an exotic platform, but it's possible this might be a bug on linux-arm64 in general. I don't have the infrastructure to test though, so I'm not certain. If this is something potentially specific to the toolchain I'm using, is there any clear way to start debugging this?

**Comment by jkotas** [comment]
Are you able to build the NativeAOT compiler locally? If yes, could you please try changing https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/ModuleInitializerListNode.cs#L33 to return `ObjectNodeSection.DataSection` and see whether it fixes the problem for you?

**Comment by TheSpydog** [comment]
Yes, I can confirm that fixes the issue for me.

**Comment by jkotas** [comment]
The package with the fix will be published in a few hours.

**Comment by TheSpydog** [comment]
Great, thank you!
