### ISSUE TITLE
Throw when LCID marshalling is needed

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtimelab#171]
We might want to at least fix the bad failure mode.

Interop/PInvoke/Attributes/LCID/LCIDTest

**Comment by MichalStrehovsky** [comment]
We should probably just copy these two lines from crossgen2:

https://github.com/dotnet/runtimelab/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/coreclr/src/tools/aot/ILCompiler.ReadyToRun/IL/Stubs/PInvokeILEmitter.cs#L84-L85

And place them around here:

https://github.com/dotnet/runtimelab/blob/beef8b0fad689f8d7a7f7b2ec0f72263698e658e/src/coreclr/src/tools/Common/TypeSystem/IL/Stubs/PInvokeILEmitter.cs#L229-L230

Then add a test in the [p/invoke smoke test] that ensures methods that need LCID marshalling throw an exception when invoked (add a p/invoke declaration with LCID in it, and add a method with a try/catch block that calls the p/invoke).

**Comment by rohithv1997** [comment]
Hi @MichalStrehovsky ,
I would like to take this up.
Thanks!

**Comment by MichalStrehovsky** [comment]
You got it. Thank you!

**Comment by MichalStrehovsky** [comment]
Fixed in https://github.com/dotnet/runtime/pull/63320.
