### ISSUE TITLE
NativeAOT treat runtime-dependent values as constants

### ISSUE THREAD

**Issue by SupinePandora43** [dotnet/runtimelab#1711]
* [`OperatingSystem.Is___`](https://github.com/dotnet/runtime/blob/14854e209868749262bd58a64407b3802177542f/src/libraries/System.Private.CoreLib/src/System/OperatingSystem.cs#L167)
* [`BitConverter.IsLittleEndian`](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Private.CoreLib/src/System/BitConverter.cs#L26)

**Comment by jkotas** [comment]
These values are treated as constants in release builds. Can you share more details on why you think it is not the case?
