### ISSUE TITLE
Can I use Native AOT to compile WPF now?

### ISSUE THREAD

**Issue by sogeisetsu** [dotnet/runtimelab#1717]
If not, I would like to know the reason and whether there are plans to support WPF. If Native AOT can compile wpf, is there anything I need to pay attention to?

I learned from other people’s blogs that the 6.0 version of Microsoft.DotNet.ILCompiler does not seem to support WPF. I see that the current version has reached Microsoft.DotNet.ILCompiler7.0.0-alpha.1.21560.2. Does this version support WPF now?

**Comment by jkotas** [comment]
> Does this version support WPF now?

It does not.

https://github.com/dotnet/runtimelab/issues/770 lists issues that have to be fixed in WPF before this can be considered.
