### ISSUE TITLE
Publishing static library should also publish other necessary static libs

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtimelab#1733]
We should either binplace the required static libraries (the appropriate Runtime.lib flavor, ClrCompression, etc.) to the publish output to make it easier to consume this or produce some artifact (RSP file fragment for example?) that has the paths.

**Comment by kkptm** [comment]
is there a plan for this work?

**Comment by cxcubehd** [comment]
This should become much higher priority since it is so painful to compile these libraries manually. I tried it and I was unsuccessful

**Comment by ceztko** [comment]
Maybe a valuable option to have would be to output a newline separated list of paths, which can be easily parsed for example with [cmake](https://cmake.org/cmake/help/latest/command/file.html#strings) and piped to linker options.

**Comment by MichalStrehovsky** [comment]
Tracked in https://github.com/dotnet/runtime/issues/70277.
