### ISSUE TITLE
Question: Difference between CORINFO_FLG_CONTAINS_GC_PTR and varDsc->HasGCPtr()

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#1740]
A while back there was some discussion on a means to decide if a struct should be GC tracked for the LLVM/Wasm backend.  
https://github.com/dotnet/runtimelab/issues/1647#issuecomment-939528154
and
https://github.com/dotnet/runtimelab/issues/1647#issuecomment-939538732

There's  a different between these 2 for `Span<char>` as one method includes `type.IsByReferenceOfT` and one doesn't.  Why is that and should `type.IsByReferenceOfT` be considered when passing `Span<char>` as an argument?

Currently the IL->LLVM backed passes `Span<char>` on the LLVM stack, so is that correct?

**Comment by jkotas** [comment]
`Span<char>` has to be GC tracked, so it means `varDsc->HasGCPtr()` is what you need.

There was a discussion about `CORINFO_FLG_CONTAINS_GC_PTR` back in the day when `Span<T>` was introduced, and we agreed that it should not be set for `Span`: https://github.com/dotnet/runtime/issues/6909#issuecomment-277065925
