### ISSUE TITLE
There is no nuget package called "Microsoft.DotNet.ILCompiler"

### ISSUE THREAD

**Issue by Symbai** [dotnet/runtimelab#1747]
Following this [instruction](https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/docs/using-nativeaot/compiling.md#add-ilcompiler-package-reference) there is no nuget package called "Microsoft.DotNet.ILCompiler". Only these two packages exist:
![image](https://user-images.githubusercontent.com/14368203/142992964-4add3064-e3e7-484e-9ac0-8e8fb4225344.png)

Also can [this](https://github.com/dotnet/runtimelab/tree/feature/NativeAOT/samples/NativeLibrary#building-shared-libraries) be done via editing csproj file, so we can publish through VS?

**Comment by antonheryanto** [comment]
please refer to the document. 
https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/docs/using-nativeaot/compiling.md 
you need to set `nuget.config` before using `Microsoft.DotNet.ILCompiler`

**Comment by Symbai** [comment]
I did but it doesn't appear in VS but adding it to the csproj directly worked, thats why I also closed the issue.
