### ISSUE TITLE
[NativeAOT-LLVM]: string.AsSpan() rewriting

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#1749]
For this c#
```cs
        public static string Join(string? separator, params object?[] values) =>
            JoinCore(separator.AsSpan(), values);
```
When it gets to IR the return value for `AsSpan` has been changed to an arg:
```
               [000002] S-C-G-------              *  CALL      void   System.MemoryExtensions.AsSpan
               [000004] ------------ arg0         +--*  ADDR      byref
               [000003] -------N----              |  \--*  LCL_VAR   struct<System.ReadOnlySpan`1[System.Char], 8> V03 tmp1
               [000001] ------------ arg1         \--*  LCL_VAR   ref    V00 arg0
```
And then when LIR
```
N003 (  3,  3) [000004] ------------         t4 =    LCL_VAR_ADDR int    V03 tmp1
N004 (  3,  2) [000001] ------------         t1 =    LCL_VAR   ref    V00 arg0
                                                  /--*  t4     int    arg0 in rcx
                                                  +--*  t1     ref    arg1 in rdx
N005 ( 20,  9) [000002] S-CXG-------              *  CALL      void   System.MemoryExtensions.AsSpan
```
This is a bit tricky for the IR->LLVM backend, at least for it to be compatible to the IL->LLVM backend, as in the latter the return value is seen still as a return value.  Not sure what to do here, I could just ignore these calls if I could identify them.  Any suggestions?

I can think of `CORINFO_SIG_INFO.retTypeClass != void && callNode->TypeGet() == void` as a temporary way to avoid attempting these calls.

cc @SingleAccretion

**Comment by jkotas** [comment]
You can detect it using `impMethodInfo_hasRetBuffArg` or `Compiler::getReturnTypeForStruct`.

What are the wasm rules for returning values via return buffer? It sounds like that these methods may need updating for wasm.

**Comment by SingleAccretion** [comment]
I agree, it seems the simplest solution is to always pass structs by value. This is controlled by what `getArgTypeForStruct` returns.

**Comment by yowl** [comment]
Thanks, yes, that looks like it's going to work out:
```
N002 (  3,  2) [000001] ------------         t1 =    LCL_VAR   ref    V00 arg0
                                                  /--*  t1     ref    arg0 in rcx
N003 ( 17,  5) [000002] --CXG-------         t2 = *  CALL      struct System.MemoryExtensions.AsSpan
                                                  /--*  t2     struct
N005 ( 21,  8) [000005] DA-XG-------              *  STORE_LCL_VAR struct<System.ReadOnlySpan`1[System.Char], 8> V03 tmp1
```
