### ISSUE TITLE
[NativeAOT]: generate native on build

### ISSUE THREAD

**Issue by EYHN** [dotnet/runtimelab#1756]
I want to know if I can generate native files on build instead of publish.

I tried adding a target to invoke `LinkNative` target.

```
<Target Name="BuildNativeLibrarys" AfterTargets="AfterBuild" DependsOnTargets="LinkNative" >
</Target>
```

When i run `dotnet build`, The native library is generated with a warning, and the method is always throw

`ILC : AOT analysis warning IL1005: NApi.ModuleExports_AutoGen.napi_register_module_v1(IntPtr,IntPtr): Method will always throw because: Failed to load assembly 'NApi' `

**Comment by jkotas** [comment]
We depend on the publish pipeline to compute the list the assemblies to compile. https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Publish.targets#L11-L24 talks about it.

You can try invoking the `Publish` target as part of the build (ie replace `LinkNative` in your fragment with `Publish`).

**Comment by EYHN** [comment]
Thank you for your reply, I tried to call `Publish` target after the `AfterBuild` target, but he reported an circular dependency error.

 But I find the following code to solve my problem.
 ```
<Target Name="BuildNativeLibrarys" AfterTargets="AfterBuild" >
  <MSBuild Projects="$(MSBuildProjectFullPath)" Targets="Publish" Properties="NoBuild=true"/>
</Target>
 ```
 
 Thank you again for your help.
