### ISSUE TITLE
How to automate nativeaot compiler targeted for x64 using 32bit vs command prompt

### ISSUE THREAD

**Issue by ssarin3194** [dotnet/runtimelab#1766]
https://github.com/dotnet/runtimelab/issues/1674

I am facing a similar problem while compiling my code . The code targets x64 but the developer command prompt is x86.
While setting the arch to amd64 helped, I do wish to automate this in my release process in our build pipeline.

Here is my bat file

```
rem Initialize the developer environment just like a developer box. Note that 'call' keyword that ensures that the script does not exit after 
rem calling the other batch file.
call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" 
 
call "cmd /k vsdevcmd -arch=amd64"

cl

rem Save working directory so that we can restore it back after building everything. This will make developers happy and then 
rem switch to the folder this script resides in. Don't assume absolute paths because on the build host and on the dev host the locations may be different.
pushd "%~dp0"


dotnet restore "%~dp0src\a\b.csproj"

dotnet build "%~dp0src\a\b.csproj"

dotnet publish "%~dp0src\a\b.csproj"
popd

rem Exit with explicit 0 code so that build does not fail.
exit /B %EX%

```

**Comment by jkotas** [comment]
What's wrong with using this batch file in your pipeline?

**Comment by TheLegendaryCopyCoder** [comment]
I just ran into this problem when following the Hello World sample setup instructions to a tee. 
I kept running into x86 errors, and so tried "cmd /k vsdevcmd -arch=amd64" in order to switch my Development Command Prompt to (I assume) exclusive 64bit mode which resolved my problem.

**Comment by jkotas** [comment]
We reset the build environment by default now: https://github.com/dotnet/runtime/pull/67525
