### ISSUE TITLE
[NativeAOT] Build in Linux-X64

### ISSUE THREAD

**Issue by sorainnosia** [dotnet/runtimelab#1784]
**Error**
/usr/bin/ld: cannot find -lz
/usr/bin/ld: cannot find -lgssapi_krb5

clang : error : linker command failed with exit code 1 (use -v to see invocation) [/mnt/c/splitjoin/SplitJoin.csproj]
/home/innosia/.nuget/packages/microsoft.dotnet.ilcompiler/7.0.0-alpha.1.21602.1/build/Microsoft.NETCore.Native.targets(356,5): error MSB3073: The command "clang "obj/Release/net6.0/linux-x64/native/SplitJoin.o" -o "bin/Release/net6.0/linux-x64/native/SplitJoin" /home/innosia/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.0-alpha.1.21608.2/sdk/libbootstrapper.a /home/innosia/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.0-alpha.1.21608.2/sdk/libRuntime.WorkstationGC.a /home/innosia/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.0-alpha.1.21608.2/framework/libSystem.Native.a /home/innosia/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.0-alpha.1.21608.2/framework/libSystem.Globalization.Native.a /home/innosia/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.0-alpha.1.21608.2/framework/libSystem.IO.Compression.Native.a /home/innosia/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.0-alpha.1.21608.2/framework/libSystem.Net.Security.Native.a /home/innosia/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.0-alpha.1.21608.2/framework/libSystem.Security.Cryptography.Native.OpenSsl.a -g -Wl,-rpath,'$ORIGIN' -Wl,--as-needed -pthread -lstdc++ -ldl -lm -lz -lgssapi_krb5 -lrt -pie -Wl,-z,relro -Wl,-z,now -Wl,--discard-all -Wl,--gc-sections" exited with code 1. [/mnt/c/splitjoin/SplitJoin.csproj]

**Tried**
I have tried installing openssl

**Comment by sorainnosia** [comment]
full comment that solve the problem
```
sudo apt install clang
sudo apt-get install libtool
sudo apt-get install libssl-dev
sudo apt-get install -y make gcc libc-dev libpq-dev zlib1g-dev
sudo -E apt-get install -y libpam-dev libedit-dev libselinux1-dev
sudo -E apt-get install -y libssl-dev libkrb5-dev
```

**Comment by Beau-Gosse-dev** [comment]
Thank you so much @sorainnosia !
