### ISSUE TITLE
[NativeAOT] ld does not support aarch64linux

### ISSUE THREAD

**Issue by sorainnosia** [dotnet/runtimelab#1785]
Generating native code
  /usr/bin/ld: unrecognised emulation mode: aarch64linux
  Supported emulations: elf_x86_64 elf32_x86_64 elf_i386 elf_iamcu elf_l1om elf_k1om i386pep i386pe
clang : error : linker command failed with exit code 1 (use -v to see invocation) [/mnt/c/splitjoin/SplitJoin.csproj]
/home/innosia/.nuget/packages/microsoft.dotnet.ilcompiler/7.0.0-alpha.1.21602.1/build/Microsoft.NETCore.Native.targets(356,5): error MSB3073: The command "clang "obj/Release/net6.0/linux-arm64/native/SplitJoin.o" -o "bin/Release/net6.0/linux-arm64/native/SplitJoin" /home/innosia/.nuget/packages/runtime.linux-arm64.microsoft.dotnet.ilcompiler/7.0.0-alpha.1.21608.2/sdk/libbootstrapper.a /home/innosia/.nuget/packages/runtime.linux-arm64.microsoft.dotnet.ilcompiler/7.0.0-alpha.1.21608.2/sdk/libRuntime.WorkstationGC.a /home/innosia/.nuget/packages/runtime.linux-arm64.microsoft.dotnet.ilcompiler/7.0.0-alpha.1.21608.2/framework/libSystem.Native.a /home/innosia/.nuget/packages/runtime.linux-arm64.microsoft.dotnet.ilcompiler/7.0.0-alpha.1.21608.2/framework/libSystem.Globalization.Native.a /home/innosia/.nuget/packages/runtime.linux-arm64.microsoft.dotnet.ilcompiler/7.0.0-alpha.1.21608.2/framework/libSystem.IO.Compression.Native.a /home/innosia/.nuget/packages/runtime.linux-arm64.microsoft.dotnet.ilcompiler/7.0.0-alpha.1.21608.2/framework/libSystem.Net.Security.Native.a /home/innosia/.nuget/packages/runtime.linux-arm64.microsoft.dotnet.ilcompiler/7.0.0-alpha.1.21608.2/framework/libSystem.Security.Cryptography.Native.OpenSsl.a --target=aarch64-linux-gnu -g -Wl,-rpath,'$ORIGIN' -Wl,--as-needed -pthread -lstdc++ -ldl -lm -lz -lgssapi_krb5 -lrt -pie -Wl,-z,relro -Wl,-z,now -Wl,--discard-all -Wl,--gc-sections" exited with code 1. [/mnt/c/splitjoin/SplitJoin.csproj]

**Comment by jkotas** [comment]
It looks like you are trying to cross-compile and you do not have your cross-compilation environment setup correctly.

**Comment by jkotas** [comment]
Can you please share details about setup of your cross-compilation environment?

**Comment by sorainnosia** [comment]
> 

I wsl install ubuntu

the ubuntu installation install below library including dotnet
```

wget https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
rm packages-microsoft-prod.deb

sudo apt-get update; \
sudo apt-get install -y apt-transport-https && \
sudo apt-get update && \
sudo apt-get install -y dotnet-sdk-6.0

sudo apt install clang
sudo apt-get install libtool
sudo apt-get install libssl-dev
sudo apt-get install -y make gcc libc-dev libpq-dev zlib1g-dev
sudo -E apt-get install -y libpam-dev libedit-dev libselinux1-dev postgresql-contrib
sudo -E apt-get install -y libssl-dev libkrb5-dev
```

then start command which fails, however linux-x64 built is successful
```
dotnet publish -r linux-arm64 -c Release -p:PublishTrimmed=true -p:EnableCompressionInSingleFile=true -p:TrimMode=Link --self-contained
```

error message
```
/usr/bin/ld: unrecognised emulation mode: aarch64linux
```

**Comment by jkotas** [comment]
Cross building needs rootfs for the target system https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/docs/using-nativeaot/compiling.md#cross-architecture-compilation . You may want to try the pre-created docker image with rootfs mentioned in the instructions.

**Comment by sorainnosia** [comment]
when i use
```
which ld
```
it shows
```
/usr/bin/ld
```
is this correct?

**Comment by jkotas** [comment]
The linker name for cross-compilation should be like `/usr/bin/aarch64-linux-gnu-ld` . You should be able to get this linker by installing `binutils-aarch64-linux-gnu` . The pre-created docker image from the link above has it installed already.
