### ISSUE TITLE
[NativeAOT] Problem importing NativeAOT static library (.lib) in C++ project

### ISSUE THREAD

**Issue by Pedrodudux** [dotnet/runtimelab#1794]
I'm trying to use NativeAOT to produce a .NET Static Library (.lib) to use in C++ project, however when I try to compile the C++ code I get the following errors:

![errors](https://user-images.githubusercontent.com/46046933/147017945-a8baae9e-ecbd-4324-866b-3c4d0520986b.png)

I found this [article about NativeLibrary](https://github.com/dotnet/runtimelab/blob/8e81d3a5bfd7639a197b51a1f65fcbba129d3b5f/samples/NativeLibrary/README.md), but it only explains how to implement using Shared Libraries (.dll).

---
### .NET side with NativeAOT:

NativeLibrary.csproj
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	  <OutputType>Library</OutputType>
	  <TargetFramework>net6.0</TargetFramework>
	  <Platforms>x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.DotNet.ILCompiler" Version="7.0.0-alpha.1.21612.2" />
  </ItemGroup>
</Project>
```

NativeLibrary.cs
```
using System.Runtime.InteropServices;
namespace NativeLibrary
{
    public class LibClass
    {
        [UnmanagedCallersOnly(EntryPoint = "add")]
        public static int Add(int a, int b)
        {
            return a + b;
        }
    }
}
```
---

### C++ side importing `NativeLibrary.lib`:

NativeLibrary.h
```
#pragma once
extern "C" int __stdcall add(int a, int b);
```

Main.cpp
```
#include <iostream>
#include "NativeLibrary.h"
int main()
{
    int result = add(1, 2);
    std::cout << "Sum from library: " << result << "\n";
    return 0;
}
```

**Comment by jkotas** [comment]
This is duplicate of https://github.com/dotnet/runtimelab/issues/974

You need to add a bunch of static libraries to the linker: https://github.com/dotnet/runtimelab/issues/974#issuecomment-822024128

We have https://github.com/dotnet/runtimelab/issues/1733 opened to make the static libraries scenario better.

**Comment by Pedrodudux** [comment]
@jkotas thanks for your comment, now linking some of these libraries i can compile my application, but when i call any library function the application crashes without any error.

---

Main.cpp
```
#include <iostream>
#include "NativeLibrary.h"

#pragma comment(lib, "NativeLibrary.lib")
#pragma comment(lib, "bcrypt.lib")
#pragma comment(lib, "Runtime.ServerGC.lib")

int main()
{
    std::cout << "Hello world.\n"; // print "hello world" normally
    int result = add(1, 2); // crash the application without errors
    std::cout << "Sum from library: " << result << "\n";
    return 0;
}
```
Output:
![output](https://user-images.githubusercontent.com/46046933/147051949-78622f59-6fac-4b03-a678-c55659c80f4b.png)

---


Another detail that I have doubts, the library  `Runtime.ServerGC.lib` was compiled using `MT_StaticRelease` which means I need to use a project with the same configuration, but I have projects that need the `MD_DynamicRelease` option. How could I get the `Runtime.ServerGC.lib` library compiled with `MD_DynamicRelease` RuntimeLibrary option?

**Comment by jkotas** [comment]
> call any library function the application crashes without any error.

It is likely caused by missing runtime initialization. You need to explicitly reference or call `CoreRT_StaticInitialization` method.

https://github.com/dotnet/runtimelab/issues/1787#issuecomment-993656416

> How could I get the Runtime.ServerGC.lib library compiled with MD_DynamicRelease RuntimeLibrary option?

We do not include this flavor today in the package. You would have to build it yourself: Add the required options to https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/src/coreclr/nativeaot/CMakeLists.txt and build the repo (use Release flavor, you can build just the nativeaot part by using `-s nativeaot` option for the build).

**Comment by Pedrodudux** [comment]
By calling `CoreRT_StaticInitialization` the application works fine, thanks.

---

NativeLibrary.h
```
#pragma once
extern "C" void* CoreRT_StaticInitialization();
extern "C" int __stdcall add(int a, int b);
```

Main.cpp
```
#include <iostream>
#include "NativeLibrary.h"

#pragma comment(lib, "NativeLibrary.lib")
#pragma comment(lib, "bcrypt.lib")
#pragma comment(lib, "Runtime.ServerGC.lib")
#pragma comment(lib, "bootstrapperdll.lib")

int main()
{
    CoreRT_StaticInitialization();
    std::cout << "Hello world.\n";
    int result = add(1, 2);
    std::cout << "Sum from library: " << result << "\n";
    return 0;
}
```
