### ISSUE TITLE
Tls callbacks

### ISSUE THREAD

**Issue by Fabi** [dotnet/runtimelab#1795]
I basically want to come back to my old own question from https://github.com/dotnet/corert/issues/7407

This is still an interesting topic for me and I tried to to achieve that through exporting functions, adding them to the linker etc. However I'm not successful currently.

Are there any plans to make this possible in any way?

**Comment by jkotas** [comment]
We have no plans to add support for this.

**Comment by Fabi** [comment]
Wouldn't it make sense to have have module initializers as tls callbacks? 🤔

**Comment by jkotas** [comment]
We try to avoid building NativeAOT-only APIs. If you think .NET runtime should support TLS callbacks, create a feature suggestion in dotnet/runtime. If this feature gets approved and implemented for dotnet/runtime, it will be in NativeAOT variant too.
