### ISSUE TITLE
Question: is it possible to disable reflection and keep reflection for assemblies in rd.xml file ? 

### ISSUE THREAD

**Issue by LLT21** [dotnet/runtimelab#1798]
I am trying to create a workflow with .NET Native AOT in order to have some code protection. I have tried based on the examples from Andrey Kurdyumov to create a simple example (repository https://github.com/LLT21/aottest) where the purpose is to protect (disable reflection) the aottest assembly, but keep reflection in the used assembly System.Data.SqlClient, as this one does not work with reflection disabled. I have tried to do this with combining the IlcDisableReflection option with an RdXmlFile. However, this still generates an error of type Unhandled Exception: EETypeRva:0x00E21B50: TypeInitialization_Type_NoTypeAvailable ---> EETypeRva:0x00E20D70: Reflection_Disabled. Is there a way to combine the 2 goals ?

**Comment by MichalStrehovsky** [comment]
If you put this class in the assembly, the metadata will be blocked within the assembly.

As with any other reflection blocking, it's 100% unsupported. It will have weird effects if e.g. a type from a blocked assembly is a base type of a type in unblocked assembly and the type is reflected on. We use this internally, but don't test it.

```csharp
namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.All)]
    internal class __BlockAllReflectionAttribute : Attribute { }
}
```

**Comment by LLT21** [comment]
Ok, I have added this to https://github.com/LLT21/aottest and it compiles well natively; it has the same exec size on mac with or without this class, but seems to execute just a little bit faster with the class added. If I understand it correctly, it has a similar effect as IlcDisableReflection = true, but specific to the assembly where it is added.

**Comment by Suchiman** [comment]
@LLT21 Not exactly, the same effect, `IlcDisableReflection` removes the entire reflection stack from the runtime, features such as reading / parsing metadata and the implementations for GetMethod().Invoke(), GetField, GetProperty, etc. That attribute just causes all metadata to be omitted for that assembly, which means that the implementations for GetMethod, GetField, etc. are still there but they have no data (for that assembly) to work on. If anything ever needs reflection the implementations need to be preserved and that is the major size saving, being able to remove the implementation, the metadata is comparatively only a minor saving.

**Comment by LLT21** [comment]
@Suchiman Ok, I guess this is logical as the other libraries that still require reflection to work (like SqlClient and Npgsql) still need the GetMethod, GetField, ... Thanks for the feedback and clarification. Would be nice in the future if there would be some simplified/reduced SqlClient and Npgsql functionality that is completely reflection free.
