### ISSUE TITLE
aspcore-corert-ado-pg TechEmpower Benchmark does not compile on mac

### ISSUE THREAD

**Issue by LLT21** [dotnet/runtimelab#1799]
Have some problem with compiling aspcore-corert-ado-pg on mac/intel: 
1) Executed: ./tfb --test aspcore-corert-ado-pg --type db
2) Result:
aspcore-corert-ado-pg:   Killed
aspcore-corert-ado-pg: /root/.nuget/packages/microsoft.dotnet.ilcompiler/7.0.0-alpha.1.21631.1/build/Microsoft.NETCore.Native.targets(292,5): error MSB3073: The command ""/root/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.0-alpha.1.21631.1/tools/ilc" @"obj/Release/net6.0/linux-x64/native/PlatformBenchmarks.ilc.rsp"" exited with code 137. [/app/PlatformBenchmarks.csproj]
aspcore-corert-ado-pg: Removing intermediate container d7c2fdc97d8e
aspcore-corert-ado-pg: Docker build failed; terminating

**Comment by MichalStrehovsky** [comment]
Exit code 137 is OOM killer. What PG driver do you use? If it's Npgsql, use version at least 6.0.0-rc.2. They had a generic recursion. The compiler can now cope with it, but it still uses a lot of memory to compile.

**Comment by LLT21** [comment]
@MichalStrehovsky Thanks for the info. I increased the docker memory on my Mac and now it works. I am using Npgsql version 6.0.2.
