### ISSUE TITLE
[NativeAOT-LLVM] what should be in __managed__Startup

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#1816]
When you call a native library the RhpReversePInvoke2 attempts to initialize the runtime calling `__managed__Startup`.  Should this be very similar to `__managed__Main` except it calls `Internal_CompilerGenerated__Module___NativeLibraryStartup` instead of `StartupCodeMain`?

**Comment by jkotas** [comment]
Yes, that sounds right.

**Comment by yowl** [comment]
Thanks, what is the relationship between this initialisation and `CoreRT_StaticInitialization` ?

**Comment by yowl** [comment]
Ok, never mind on that, I see its for some kind of callback.
