### ISSUE TITLE
[NativeAOT] GenericCompositionNode issue when Instantiation type name ends with _0, _1 or _2

### ISSUE THREAD

**Issue by tomcashman** [dotnet/runtimelab#1821]
I'm currently getting a `Duplicate node name emitted to file` on a project. After debugging, it comes from ObjectWriter for the following auto-generated types:

```
Com.Alchemiccutie.Scripting.Compiled.Npc.Martha.Martha_breed_jelly_tutorial_2
Com.Alchemiccutie.Scripting.Compiled.Npc.Martha.Martha_breed_jelly_tutorial
```

I've traced the issue to `GenericCompositionNode.AppendMangledName` where it suffixes a number based on the variance.

I've had trouble making a simple reproduction of this outside of our project. However, I've pinpointed the steps causing the issue:

- Martha_breed_jelly_tutorial_2 is added first to `_previouslyWrittenNodeNames` in ObjectWriter
- Martha_breed_jelly_tutorial is attempted to be added but due to how GenericCompositionNode generates the mangled name (result is Martha_breed_jelly_tutorial_2), it thinks there is a conflict.

**Comment by MichalStrehovsky** [comment]
Thanks for reporting this and root causing! Simplified repro:

```csharp
_ = typeof(IFoo<GenXXX>).ToString();
_ = typeof(Foo<GenXXX_2>).ToString();

class GenXXX { }
class GenXXX_2 { }

interface IFoo<in T> { }
class Foo<T> { }
```

**Comment by MichalStrehovsky** [comment]
It will take a couple days for package with the fix to come out. We're still publishing packages from this repo, but the fix is in the runtime repo. I'm waiting for fixes to https://github.com/dotnet/runtime/issues/63778 and https://github.com/dotnet/runtime/issues/63906 before integration because NativeAOT is currently a bit broken.

**Comment by tomcashman** [comment]
No problem thank you for quickly resolving the issue 🙂
