### ISSUE TITLE
[NativeAOT-LLVM] RhAllocateThunksMapping implementation

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#1830]
`RhAllocateThunksMapping` is currently not very good:

https://github.com/dotnet/runtimelab/blob/d30559af2b063dcaacdd973d3c9a2107b36c08bb/src/coreclr/nativeaot/Runtime/portable.cpp#L500-L503

This is a problem if you try to `GetFunctionPointerForDelegate` it all returns null and looks like an `OutOfMemoryException`

What should be in here, presumably we want to allocate some memory, but how much and where?

I think we'll also need at a minimum `RhpGetThunkBlockSize`, `RhpGetThunkDataBlockAddress`

**Comment by jkotas** [comment]
This has to return executable memory with method thunks that are agnostic to the signature. I do not think it is possible to that on wasm.

Where are you hitting the call to `GetFunctionPointerForDelegate`? It would be best to convert it to use C# function pointers.

**Comment by yowl** [comment]
Its : 

https://github.com/mono/SkiaSharp/blob/d4dbf39e4fd89e0df7379034a1d2f934a99b8377/binding/Binding/GRGlInterface.cs#L77-L85

where `gr_glinterface_assemble_webgl_interface` is declared as

```
[DllImport (SKIA, CallingConvention = CallingConvention.Cdecl)]
internal static extern gr_glinterface_t gr_glinterface_assemble_webgl_interface (void* ctx, GRGlGetProcProxyDelegate get);
```
It's trying to register the callback, where the stack looks like

```
___cxa_throw (wskia.js:2183)
$RhpThrowEx (wskia.wasm:0x11440a2)
CreateThunksHeap (RuntimeAugments.cs:904)
AllocateThunk (PInvokeMarshal.cs:172)
$S_P_CoreLib_System_Runtime_CompilerServices_ConditionalWeakTable_2_CreateValueCallback<System___Canon__System___Canon>__InvokeOpenStaticThunk (wskia.wasm:0x2a4113)
$S_P_CoreLib_System_Runtime_CompilerServices_ConditionalWeakTable_2_CreateValueCallback<System___Canon__System___Canon>__Invoke (wskia.wasm:0x68edc7)
GetValueLocked (ConditionalWeakTable.cs:201)
GetValue (ConditionalWeakTable.cs:190)
GetFunctionPointerForDelegate (PInvokeMarshal.cs:65)
invoke_ii (wskia.js:10230)
$SkiaSharp_SkiaSharp_SkiaApi__gr_glinterface_assemble_webgl_interface (wskia.wasm:0x347bf)
invoke_iii (wskia.js:10219)
$SkiaSharp_SkiaSharp_GRGlInterface__CreateWebGl (wskia.wasm:0x3229e)
Main (Program.cs:72)
$wskia__Module___MainMethodWrapper (wskia.wasm:0xfdd72e)
$StartupCodeMain (wskia.wasm:0x54e81)
$__managed__Main (wskia.wasm:0xfd6c40)
$main (wskia.wasm:0x11440ee)
(anonymous) (wskia.js:1550)
callMain (wskia.js:11199)
doRun (wskia.js:11256)
(anonymous) (wskia.js:11267)
setTimeout (async)
run (wskia.js:11263)
runCaller (wskia.js:11177)
removeRunDependency (wskia.js:1479)
receiveInstance (wskia.js:1639)
receiveInstantiationResult (wskia.js:1656)
Promise.then (async)
(anonymous) (wskia.js:1685)
Promise.then (async)
instantiateAsync (wskia.js:1682)
createWasm (wskia.js:1713)
(anonymous) (wskia.js:9871)
```

The callback has a `string` in it's args, although right now I don't care about that.  Callback is defined
```
        static IntPtr getGL(string name)
        {
            return glContext;
        }
```
Which I pass into 
```
            GRGlInterface grGlInterface = GRGlInterface.CreateWebGl(new GRGlGetProcedureAddressDelegate(getGL));
```
I'm not sure mono supports this either, I'm trying to establish if Uno are using WebGL and if so how they are doing it.

**Comment by yowl** [comment]
Will close, this because I don't think this callback is required anyway to get Skia working.
