### ISSUE TITLE
ran great, then after relaunch of Rider, "Unable to resolve ..."

### ISSUE THREAD

**Issue by daveyostcom** [dotnet/runtimelab#1833]
I was able to compile and run (vey fast!) a little hello world app.  That was two days ago.  I updated my macOS to 12.2, reopened Rider, and rebuilt.  Now I get this:
`Junk.csproj: [NU1100] Unable to resolve 'Microsoft.DotNet.ILCompiler (>= 7.0.0)' for 'net6.0'.`
The csproj file hasn’t changed:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.DotNet.ILCompiler" Version="7.0.0-*" />
  </ItemGroup>
</Project>
```

**Comment by jkotas** [comment]
Are you missing the dotnet-experimental nuget feed? https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/samples/HelloWorld/nuget.config#L7

**Comment by daveyostcom** [comment]
That also doesn’t work for me.

What I had was
<add key="dotnet-experimental" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-experimental/nuget/v3/index.json" />

which I got from
https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/docs/using-nativeaot/compiling.md

**Comment by kant2002** [comment]
@daveyostcom can you share your whole `nuget.config`?

Did you miss `<add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />` by a chance?
Also do you have other error messages except `NU1100` line?

**Comment by kant2002** [comment]
Today I see similar issue in Gitter, and it was caused by wrong package version. Command to add ILC which was used to produce error was `dotnet add package Microsoft.DotNet.ILCompiler -v "7.0.0.*"`, but it is required to be `dotnet add package Microsoft.DotNet.ILCompiler -v "7.0.0-*"`. Notice that proper version has `-` (dash) in the version name.

**Comment by kant2002** [comment]
@daveyostcom did you make it works?

**Comment by MichalStrehovsky** [comment]
Closing stale issues.
