### ISSUE TITLE
Missing main.js and index.html for WebAssembly in sample or instruction.

### ISSUE THREAD

**Issue by zwcloud** [dotnet/runtimelab#1835]
The [NativeAOT-LLVM doc on WebAssembly](https://github.com/dotnet/runtimelab/blob/ce43f371e1761fe6335f8c63d344e605b892ebe9/docs/using-nativeaot/compiling.md#webassembly) is missing some information to create required files like main.js and index.htm. @yowl 

main.js
> C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\6.0.2-mauipre.1.22054.8\Sdk\WasmApp.targets(270,5): error : $(WasmMainJSPath) property needs to be set [Z:\1_experiment\wasm\wasm.csproj]

index.html
> C:\Program Files\dotnet\sdk\6.0.200-preview.21617.4\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(248,5): error MSB3030: Could not copy the file "bin\Debug\net6.0\browser-wasm\native\wasm.html" because it was not found. [Z:\1_experiment\wasm\wasm.csproj]

Or do I need to install an experimental/un-released dotnet runtime? How?

**Comment by yowl** [comment]
The html and js file are produced by the `dotnet publish`.  It looks like it's getting confused with the mono targets.  What is the command line you are using and what is in your project file?

**Comment by zwcloud** [comment]
`dotnet publish -r browser-wasm -c Debug /p:TargetArchitecture=wasm --self-contained`

**Comment by zwcloud** [comment]
Here is the project:
[wasm.zip](https://github.com/dotnet/runtimelab/files/7966158/wasm.zip)

If `<WasmMainJSPath>main.js</WasmMainJSPath>` is removed from csproj, `error : $(WasmMainJSPath) property needs to be set` will occur.

**Comment by zwcloud** [comment]
The project was created via `dotnet new console`. Then I followed the docs to publish a webassembly app.

**Comment by yowl** [comment]
If you type `emcc -v` what do you get?

**Comment by zwcloud** [comment]
emcc is not in PATH
> emcc -v
emcc : The term 'emcc' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name

**Comment by yowl** [comment]
You need to install and activate emscripten.  Remove `WasmMainJSPath` - its not used.  Unfortunately there is a problem and there should be a message surfaced to do that, but it seems to be getting swallowed somewhere

**Comment by zwcloud** [comment]
I have already installed and activated emscripten 2.0.23 when trying [dotnet/runtime/mono/wasm](https://github.com/dotnet/runtime/tree/main/src/mono/wasm).
```
PS Z:\0_workspace\emsdk> $env:EMSDK_PATH
Z:\0_workspace\emsdk
```
Is it required to add emscripten(emsdk) to PATH?

**Comment by zwcloud** [comment]
Added `Z:\0_workspace\emsdk\upstream\emscripten` to PATH. But still got error `$(WasmMainJSPath) property needs to be set `:

```plain
PS Z:\1_experiment\wasm> emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 2.0.23 (b15ca40ca02f469de3bf9a4de67a2655aede8974)
clang version 13.0.0 (Cswircachegitchromium.googlesource.com-external-github.com-llvm-llvm--project 5852582532b3eb3ea8da51a1e272d8d017bd36c9)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: Z:/0_workspace/emsdk/upstream/bin
PS Z:\1_experiment\wasm> dotnet publish -r browser-wasm -c Debug /p:TargetArchitecture=wasm
Microsoft (R) Build Engine version 17.1.0-preview-21610-01+96a618ca5 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
C:\Program Files\dotnet\sdk\6.0.200-preview.21617.4\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(1110,5): warning NETSDK1179: One of '--self-contained' or '--no-self-contained' options are required when '--runtime' is used. [Z:\1_experiment\wasm\wasm.csproj]
  wasm -> Z:\1_experiment\wasm\bin\Debug\net6.0\browser-wasm\wasm.dll
C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\6.0.2-mauipre.1.22054.8\Sdk\WasmApp.targets(270,5): error : $(WasmMainJSPath) property needs to be set [Z:\1_experiment\wasm\wasm.csproj]
```

**Comment by zwcloud** [comment]
After build the updated project:
[wasm.zip](https://github.com/dotnet/runtimelab/files/7966274/wasm.zip)

**Comment by yowl** [comment]
> Is it required to add emscripten(emsdk) to PATH?

Yes, this is required.  At least for the session where you are running `dotnet publish`

**Comment by yowl** [comment]
The docs are missing the `--self-contained` option,   Add that to your `dotnet publish`

**Comment by zwcloud** [comment]
> You are using a preview version of .NET.

Maybe some feature introduced in the preview version interferes NativeAOT-LLVM WebAssembly? Should I will try to revert to a stable version of .NET?

**Comment by zwcloud** [comment]
> The docs are missing the `--self-contained` option, Add that to your `dotnet publish`

PS Z:\1_experiment\wasm> dotnet publish -r browser-wasm -c Debug /p:TargetArchitecture=wasm --self-contained
Microsoft (R) Build Engine version 17.1.0-preview-21610-01+96a618ca5 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  wasm -> Z:\1_experiment\wasm\bin\Debug\net6.0\browser-wasm\wasm.dll
C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\6.0.2-mauipre.1.22054.8\Sdk\WasmApp.targets(270,5): error : $(WasmMainJSPath) property needs to be set [Z:\1_experiment\wasm\wasm.csproj]

**Comment by yowl** [comment]
Your references should be:
```
    <PackageReference Include="runtime.win-x64.Microsoft.DotNet.ILCompiler.LLVM" Version="7.0.0-*"/>
    <PackageReference Include="Microsoft.DotNet.ILCompiler.LLVM" Version="7.0.0-*" />
```

With that you should be fine:

![image](https://user-images.githubusercontent.com/2720041/151707269-cf5424a7-65f5-4234-9f5f-d762bb9d7d66.png)

**Comment by zwcloud** [comment]
No, still got the same error. I'm trying to uninstall the preview-version of dotnet and try again.
current: 
```
PS D:\> dotnet --version
6.0.200-preview.21617.4
```

**Comment by yowl** [comment]
Dotnet 6 is not in preview anymore so you should probably uninstall any preview versions of v6 that you have.  This is what I have:
```
C:\Users\ScottWaye\Downloads\wasm>dotnet --version
6.0.101
```

**Comment by zwcloud** [comment]
OK, thanks! I will reply here if I fixed the issue or not. The preview version of dotnet is bound with VS2022 preview. So it seems that I need to uninstall VS2022 preview and install VS2022 stable, which requires a long period to complete.

**Comment by yowl** [comment]
Don't forget to remove ` runtime.browser-wasm.Microsoft.DotNet.ILCompiler.LLVM` from your csproj

**Comment by zwcloud** [comment]
No luck :/

> PS Z:\1_experiment\wasm> dotnet publish -r browser-wasm -c Debug /p:TargetArchitecture=wasm --self-contained
> Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
> Copyright (C) Microsoft Corporation. All rights reserved.   
> 
> ): error MSB4022: The result "" of evaluating the value "$(JsonToItemsTaskFactoryTasksAssemblyPath)" of the "AssemblyFile" attribute in element <UsingTask> is not valid. [Z:\1_experiment\wasm\wasm.csproj]
> PS Z:\1_experiment\wasm> ls
> 
> 
>     Directory: Z:\1_experiment\wasm
> 
> 
> Mode                 LastWriteTime         Length Name
> ----                 -------------         ------ ----
> -a----        2022-01-30     22:49            451 nuget.config
> -a----        2022-01-30     23:01            340 Program.cs
> -a----        2022-01-31     00:04            471 wasm.csproj
> 
> 
> PS Z:\1_experiment\wasm> dotnet publish -r browser-wasm -c Debug /p:TargetArchitecture=wasm --self-contained
> Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\6.0.1\Sdk\WasmApp.Native.targets(560,39): error MSB4022: The result "" of evaluating the value "$(JsonToItemsTaskFactoryTasksAssemblyPath)" of the "AssemblyFile" attribute in element <UsingTask> is not valid. [Z:\1_experiment\wasm\wasm.csproj]
> PS Z:\1_experiment\wasm> dotnet --version
> 6.0.101

[wasm.zip](https://github.com/dotnet/runtimelab/files/7966442/wasm.zip)

csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="runtime.win-x64.Microsoft.DotNet.ILCompiler.LLVM" Version="7.0.0-*"/>
    <PackageReference Include="Microsoft.DotNet.ILCompiler.LLVM" Version="7.0.0-*" />
  </ItemGroup>

</Project>
```

**Comment by yowl** [comment]
Hmm, something is pulling in `C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\6.0.1\Sdk\WasmApp.Native.targets` which we don't want.  Can you add /bl to the dotnet command and post the produced binlog?

**Comment by yowl** [comment]
Try adding `/p:PlatformTarget=AnyCPU /p:MSBuildEnableWorkloadResolver=false`

**Comment by zwcloud** [comment]
> PS Z:\1_experiment\wasm> dotnet publish -r browser-wasm -c Debug /p:TargetArchitecture=wasm --self-contained /p:PlatformTarget=AnyCPU /p:MSBuildEnableWorkloadResolver=false
> Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
>   Determining projects to restore...
>   Restored Z:\1_experiment\wasm\wasm.csproj (in 3.27 sec).
>   wasm -> Z:\1_experiment\wasm\bin\Debug\net6.0\browser-wasm\wasm.dll
>   Generating compatible native code. To optimize for size or speed, visit https://aka.ms/OptimizeCoreRT
>   RyuJIT compilation results, total methods 16894 RyuJit Methods 5739 33.9706%
> C:\Program Files\dotnet\sdk\6.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(248,5): error MSB3030: Could not copy the file "bin\Debug\net6.0\browser-wasm\native\wasm.html" because it was not found. [Z:\1_experiment\wasm\wasm.csproj]

**Comment by zwcloud** [comment]
With `/p:PlatformTarget=AnyCPU /p:MSBuildEnableWorkloadResolver=false`:
[msbuild.binlog.zip](https://github.com/dotnet/runtimelab/files/7966488/msbuild.binlog.zip)

**Comment by zwcloud** [comment]
Without `/p:PlatformTarget=AnyCPU /p:MSBuildEnableWorkloadResolver=false`
[msbuild.binlog.zip](https://github.com/dotnet/runtimelab/files/7966495/msbuild.binlog.zip)

**Comment by yowl** [comment]
Its' failing with `Emscripten not found, not linking WebAssembly. To enable WebAssembly linking, install Emscripten and ensure the EMSDK environment variable points to the directory containing upstream/emscripten/emcc.bat`

**Comment by yowl** [comment]
can you type 
```
echo %EMSDK%
```

**Comment by zwcloud** [comment]
oh, that envirment var is not set

**Comment by zwcloud** [comment]
Set `EMSDK` to `Z:\0_workspace\emsdk` and it succeeded! I'm trying to run it.

> PS Z:\1_experiment\wasm> $env:EMSDK
> Z:\0_workspace\emsdk
> PS Z:\1_experiment\wasm> dotnet publish -r browser-wasm -c Debug /p:TargetArchitecture=wasm --self-contained /p:PlatformTarget=AnyCPU /p:MSBuildEnableWorkloadResolver=false /bl
> Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> C:\Program Files\dotnet\sdk\6.0.101\MSBuild.dll -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\6.0.101\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\6.0.101\dotnet.dll -maxcpucount -property:TargetArchitecture=wasm -property:PlatformTarget=AnyCPU -property:MSBuildEnableWorkloadResolver=false -property:SelfContained=True -property:_CommandLineDefinedSelfContained=true -property:RuntimeIdentifier=browser-wasm -property:_CommandLineDefinedRuntimeIdentifier=true -property:Configuration=Debug -restore -target:Publish -verbosity:m /bl .\wasm.csproj 
>   Determining projects to restore...
>   All projects are up-to-date for restore.
>   wasm -> Z:\1_experiment\wasm\bin\Debug\net6.0\browser-wasm\wasm.dll
> EXEC : warning : undefined symbol: S_P_CoreLib_System_Runtime_InternalCalls__RhpNewArray (referenced by top-level compiled C/C++ code) [Z:\1_experiment\wasm\wasm.csproj]
> EXEC : warning : undefined symbol: S_P_CoreLib_System_Runtime_InternalCalls__RhpNewArrayAlign8 (referenced 
> by top-level compiled C/C++ code) [Z:\1_experiment\wasm\wasm.csproj]
> EXEC : warning : undefined symbol: S_P_CoreLib_System_Runtime_InternalCalls__RhpNewFast (referenced by top-level compiled C/C++ code) [Z:\1_experiment\wasm\wasm.csproj]
> EXEC : warning : undefined symbol: S_P_CoreLib_System_Runtime_InternalCalls__RhpNewFastAlign8 (referenced by top-level compiled C/C++ code) [Z:\1_experiment\wasm\wasm.csproj]
> EXEC : warning : undefined symbol: S_P_CoreLib_System_Runtime_InternalCalls__RhpNewFastMisalign (referenced by top-level compiled C/C++ code) [Z:\1_experiment\wasm\wasm.csproj]
> EXEC : warning : undefined symbol: S_P_CoreLib_System_Runtime_InternalCalls__RhpNewFinalizable (referenced 
> by top-level compiled C/C++ code) [Z:\1_experiment\wasm\wasm.csproj]
> EXEC : warning : undefined symbol: S_P_CoreLib_System_Runtime_InternalCalls__RhpNewFinalizableAlign8 (referenced by top-level compiled C/C++ code) [Z:\1_experiment\wasm\wasm.csproj]
> EXEC : warning : undefined symbol: dotnet_browser_entropy (referenced by top-level compiled C/C++ code) [Z:\1_experiment\wasm\wasm.csproj]
>   wasm -> Z:\1_experiment\wasm\bin\Debug\net6.0\browser-wasm\publish\

**Comment by yowl** [comment]
yes, that looks good so far.

**Comment by zwcloud** [comment]
Great! Got the expected result in Chrome by hosting an IIS website under folder `wasm\bin\Debug\net6.0\browser-wasm\native`.

![image](https://user-images.githubusercontent.com/6965758/151710750-4311b16f-5b1e-4ac7-bb22-1eebe4046a23.png)

**Comment by zwcloud** [comment]
Thank you very much! But I think the docs need to be updated as posted above.

**Comment by yowl** [comment]
Well done!  I'll add `/p:PlatformTarget=AnyCPU /p:MSBuildEnableWorkloadResolver=false` to the docs as mandatory.  You can also use Node to run it, which can be easier, just give the js file as the argument to node

**Comment by zwcloud** [comment]
Yes, node also works:

> Z:\1_experiment\wasm\bin\Debug\net6.0\browser-wasm\native>node wasm.js
> Calling stub instead of signal()
> Hello World from C# Main

![image](https://user-images.githubusercontent.com/6965758/151710882-182fd1a5-8bc9-4449-b12a-c4cb6f6c88fc.png)

**Comment by jkotas** [comment]
Docs updated in #1837
