### ISSUE TITLE
Is it possible to include the c source file in csproj instead of statically linking against a unmanaged library?

### ISSUE THREAD

**Issue by zwcloud** [dotnet/runtimelab#1841]
area: NativeAOT-LLVM WebAssembly

I'm trying to P/Invoke native functions in *.c. Is it possible to include the c source file in csproj like `<NativeFileReference Include="Test.c" />`, which has been [supported in dotnet/runtime/mono/wasm](https://github.com/dotnet/runtime/blob/9ddd58a58d14a7bec5ed6eb777c6703c48aca15d/src/mono/wasm/build/WasmApp.Native.targets#L247)?

I have read this but it said only static library *.lib/*.a are supported.
https://github.com/dotnet/runtimelab/blob/feature/NativeAOT-LLVM/docs/using-nativeaot/interop.md#linking

To be more specific, I'm trying to P/Invoke WebGL functions via [emscripten's EGL and OpenGLES implementations](https://emscripten.org/docs/porting/multimedia_and_graphics/OpenGL-support.html). The EGL/OpenGLES  functions will be invoked via P/Invoke in C#.

**Comment by jkotas** [comment]
We do recognize `NativeFileReference` in NativeAOT currently. It should not be hard to add the target for it. You can start by adding it locally in your project. I think all you need to do is to just pass these files on emcc command line.

cc @yowl

**Comment by yowl** [comment]
Yes, tt might be worth just trying to add `/p:EmccExtraArgs=Test.c` .  This will add `Test.c` to the linking step, but emcc might be smart enough to do the compilation first.

**Comment by zwcloud** [comment]
>  add /p:EmccExtraArgs=Test.c 

I hope, in the future, either of below will be supported in VS2022:
1. Test.c inside the project are automatically added to the command-line as `/p:EmccExtraArgs=Test.c`
2. C/C++ source code created/added to csproj in VS2022 are added as `NativeFileReference`, like `<NativeFileReference Include="Test.c" />`.
 
This is something related to VS2022 project/build toolchain.

I have tried manually add `<NativeFileReference Include="Test.c" />` to csproj, but it doesn't work. So it seems not passed to emcc in current implementation of *NativeAOT-LLVM WebAssembly*?

**Comment by yowl** [comment]
As you've discovered, the tooling for NativeAOT-LLVM is a little basic and you are right: `NativeFileReference`s are not added to the emcc command line.  I imagine that's not hard to do though...

**Comment by zwcloud** [comment]
> added to the command-line as /p:EmccExtraArgs=Test.c

It works:

> PS Z:\1_experiment\wasm> dotnet publish -r browser-wasm -c Debug /p:TargetArchitecture=wasm --self-contained /p:PlatformTarget=AnyCPU /p:MSBuildEnableWorkloadResolver=false /p:EmccExtraArgs=Test.c /bl
> Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> r,C:\Program Files\dotnet\sdk\6.0.101\dotnet.dll -maxcpucount -property:TargetArchitecture=wasm -property:PlatformTarget=AnyCPU -property:MSBuildEnableWorkloadResolver=false -property:EmccExtraArgs=Test.c -property:SelfContained=True -property:_CommandLineDefinedSelfContained=true -property:RuntimeIdentifier=browser-wasm -property:_CommandLineDefinedRuntimeIdentifier=true -property:Configuration=Debug -restore -target:Publish -verbosity:m /bl .\wasm.csproj
>   Determining projects to restore...
>   All projects are up-to-date for restore.
>   wasm -> Z:\1_experiment\wasm\bin\Debug\net6.0\browser-wasm\wasm.dll
>   Generating compatible native code. To optimize for size or speed, visit https://aka.ms/OptimizeCoreRT
>   RyuJIT compilation results, total methods 16944 RyuJit Methods 5744 33.8999%
> EXEC : warning : undefined symbol: S_P_CoreLib_System_Runtime_InternalCalls__RhpNewArray (referenced by top-level compiled C/C++ code) [Z:\1_experiment\wasm\wasm.csproj]
> EXEC : warning : undefined symbol: S_P_CoreLib_System_Runtime_InternalCalls__RhpNewArrayAlign8 (referenced by top-level compiled C/C++ code) [Z:\1_experiment\wasm\wasm.csproj]
> EXEC : warning : undefined symbol: S_P_CoreLib_System_Runtime_InternalCalls__RhpNewFast (referenced by top-level compiled C/C++ code) [Z:\1_experiment\wasm\wasm.csproj]
> EXEC : warning : undefined symbol: S_P_CoreLib_System_Runtime_InternalCalls__RhpNewFastAlign8 (referenced by top-level compiled C/C++ code) [Z:\1_experiment\wasm\wasm.csproj]
> EXEC : warning : undefined symbol: S_P_CoreLib_System_Runtime_InternalCalls__RhpNewFastMisalign (referenced by top-level compiled C/C++ code) [Z:\1_experiment\wasm\wasm.csproj]
> EXEC : warning : undefined symbol: S_P_CoreLib_System_Runtime_InternalCalls__RhpNewFinalizable (referenced by top-level compiled C/C++ code) [Z:\1_experiment\wasm\wasm.csproj]
> EXEC : warning : undefined symbol: S_P_CoreLib_System_Runtime_InternalCalls__RhpNewFinalizableAlign8 (referenced by top-level compiled C/C++ code) [Z:\1_experiment\wasm\wasm.csproj]
> EXEC : warning : undefined symbol: dotnet_browser_entropy (referenced by top-level compiled C/C++ code) [Z:\1_experiment\wasm\wasm.csproj]
>   wasm -> Z:\1_experiment\wasm\bin\Debug\net6.0\browser-wasm\publish\
> PS Z:\1_experiment\wasm> node .\bin\Debug\net6.0\browser-wasm\native\wasm.js
> Calling stub instead of signal()
> [Program.cs] Main
> [Test.c] NativeFunc
> [Program.cs] NativeFunc returns 123456

![Untitled](https://user-images.githubusercontent.com/6965758/152160351-2fce6967-2830-4a24-8ff7-2a1d010216d9.png)

**Comment by yowl** [comment]
Great, thanks for testing!

**Comment by ChristianWeyer** [comment]
Out of curiosity: what exactly are you building, with this stack? @zwcloud

**Comment by zwcloud** [comment]
> Out of curiosity: what exactly are you building, with this stack? @zwcloud

See https://github.com/zwcloud/CSharpWasmSamples

**Comment by zwcloud** [comment]
This should be outdated? I forgot the details.
