### ISSUE TITLE
Direct PInvoke Calls with static lib seems not working for  NativeAOT-LLVM WebAssembly?

### ISSUE THREAD

**Issue by zwcloud** [dotnet/runtimelab#1842]
To repoduce:
```bat
git clone https://github.com/zwcloud/CSharpWasmSamples.git
git checkout 14627df43c739e022a9de43765bcc897135775c0
cl .\Test.c
dotnet publish -r browser-wasm -c Debug /p:TargetArchitecture=wasm --self-contained /p:PlatformTarget=AnyCPU /p:MSBuildEnableWorkloadResolver=false /bl

node .\bin\Debug\net6.0\browser-wasm\native\wasm.js
```
`cl .\Test.c` is optional, I have added Test.lib to the repo.

---

Just tried Direct PInvoke Calls with static lib approach, but it seems not working for wasm:
```cs
using System;
using System.Runtime.InteropServices;

namespace HelloWorld
{
    class Program
    {
        [DllImport("Test")]
        static extern int _NativeFunc();

        static void Main(string[] args)
        {
            Console.WriteLine("[Program.cs] Main");
            int value = _NativeFunc();
            Console.WriteLine("[Program.cs] NativeFunc returns {0}", value);
        }
    }
}
```

Test.c:  
I think `__declspec( dllexport ) ` is not needed: I remember that a function of c is exported in static lib by default.
```c
#include "stdio.h"
__declspec( dllexport ) int NativeFunc()
{
	puts("[Test.c] NativeFunc");
    return 123456;
}
```

The Test.lib was compiled and linked from Test.c via `cl`:
```log
PS Z:\1_experiment\wasm> cl .\Test.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.30.30709 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

Test.c
Microsoft (R) Incremental Linker Version 14.30.30709.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:Test.exe
Test.obj
   Creating library Test.lib and object Test.exp
LINK : fatal error LNK1561: entry point must be defined
```

The exported functions does exists:
```cmd
PS Z:\1_experiment\wasm> DUMPBIN /EXPORTS .\Test.lib
Microsoft (R) COFF/PE Dumper Version 14.30.30709.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file .\Test.lib

File Type: LIBRARY

     Exports

       ordinal    name

                  _NativeFunc

  Summary

          BA .debug$S
          14 .idata$2
          14 .idata$3
           4 .idata$4
           4 .idata$5
           A .idata$6
```

execute result:
```log
PS Z:\1_experiment\wasm> node Z:\1_experiment\wasm\bin\Debug\net6.0\browser-wasm\native\wasm.js
Calling stub instead of signal()
[Program.cs] Main
missing function: _NativeFunc
-1
exception thrown: RuntimeError: abort(-1) at Error
    at jsStackTrace (Z:\1_experiment\wasm\bin\Debug\net6.0\browser-wasm\native\wasm.js:1707:19)
    at stackTrace (Z:\1_experiment\wasm\bin\Debug\net6.0\browser-wasm\native\wasm.js:1729:16)
    at abort (Z:\1_experiment\wasm\bin\Debug\net6.0\browser-wasm\native\wasm.js:1444:44)
    at __NativeFunc (Z:\1_experiment\wasm\bin\Debug\net6.0\browser-wasm\native\wasm.js:1779:41)
    at wasm_HelloWorld_Program___NativeFunc (wasm://wasm/046aee2a:wasm-function[124]:0xece3)
    at wasm_HelloWorld_Program__Main (wasm://wasm/046aee2a:wasm-function[13461]:0xa6f4d8)
    at wasm__Module___MainMethodWrapper (wasm://wasm/046aee2a:wasm-function[13557]:0xa74284)
    at StartupCodeMain (wasm://wasm/046aee2a:wasm-function[422]:0x38de0)
    at __managed__Main (wasm://wasm/046aee2a:wasm-function[13413]:0xa6dcd8)
    at main (wasm://wasm/046aee2a:wasm-function[19954]:0xb9fa51),RuntimeError: abort(-1) at Error
    at jsStackTrace (Z:\1_experiment\wasm\bin\Debug\net6.0\browser-wasm\native\wasm.js:1707:19)
    at stackTrace (Z:\1_experiment\wasm\bin\Debug\net6.0\browser-wasm\native\wasm.js:1729:16)
    at abort (Z:\1_experiment\wasm\bin\Debug\net6.0\browser-wasm\native\wasm.js:1444:44)
    at __NativeFunc (Z:\1_experiment\wasm\bin\Debug\net6.0\browser-wasm\native\wasm.js:1779:41)
    at wasm_HelloWorld_Program___NativeFunc (wasm://wasm/046aee2a:wasm-function[124]:0xece3)
    at wasm_HelloWorld_Program__Main (wasm://wasm/046aee2a:wasm-function[13461]:0xa6f4d8)
    at wasm__Module___MainMethodWrapper (wasm://wasm/046aee2a:wasm-function[13557]:0xa74284)
    at StartupCodeMain (wasm://wasm/046aee2a:wasm-function[422]:0x38de0)
    at __managed__Main (wasm://wasm/046aee2a:wasm-function[13413]:0xa6dcd8)
    at main (wasm://wasm/046aee2a:wasm-function[19954]:0xb9fa51)
    at abort (Z:\1_experiment\wasm\bin\Debug\net6.0\browser-wasm\native\wasm.js:1450:11)
    at __NativeFunc (Z:\1_experiment\wasm\bin\Debug\net6.0\browser-wasm\native\wasm.js:1779:41)
    at wasm_HelloWorld_Program___NativeFunc (wasm://wasm/046aee2a:wasm-function[124]:0xece3)
    at wasm_HelloWorld_Program__Main (wasm://wasm/046aee2a:wasm-function[13461]:0xa6f4d8)
    at wasm__Module___MainMethodWrapper (wasm://wasm/046aee2a:wasm-function[13557]:0xa74284)
    at StartupCodeMain (wasm://wasm/046aee2a:wasm-function[422]:0x38de0)
    at __managed__Main (wasm://wasm/046aee2a:wasm-function[13413]:0xa6dcd8)
    at main (wasm://wasm/046aee2a:wasm-function[19954]:0xb9fa51)
    at Z:\1_experiment\wasm\bin\Debug\net6.0\browser-wasm\native\wasm.js:1494:22
    at callMain (Z:\1_experiment\wasm\bin\Debug\net6.0\browser-wasm\native\wasm.js:6418:15)
```

[msbuild.binlog.zip](https://github.com/dotnet/runtimelab/files/7976553/msbuild.binlog.zip)

**Comment by zwcloud** [comment]
I found there has alreay been a build warning when `dotnet publish`:
```
EXEC : warning : undefined symbol: _NativeFunc (referenced by top-level compiled C/C++ code) [Z:\1_experiment\wasm\wasm.csproj]
```

For P/Invoke functions, this should be an error, I think.

**Comment by jkotas** [comment]
cc @yowl

**Comment by yowl** [comment]
I'm not sure what's going on here.  You  can't link a wasm module with a C object file, i.e. an x64 object file.  You'd have to build the C library with emcc (or supply the same options to clang).  Try to compile the C library with `emcc -c ` to create a wasm object file.

**Comment by yowl** [comment]
You certainly can PInvoke external libraries, that's how the Skia and Wasm4 demos work.

**Comment by zwcloud** [comment]
> You can't link a wasm module with a C object file, i.e. an x64 object file. 

Haha, I thought emscripten can somehow convert the object file to WebAssembly.

> Try to compile the C library with emcc -c to create a wasm object file.

OK. I'll try this later.

**Comment by kant2002** [comment]
Maybe that's should be documented somewhere? I think this would be common issue when WASM move forward in time.

**Comment by zwcloud** [comment]
> Try to compile the C library with emcc -c to create a wasm object file.

This works if `/p:EmccExtraArgs=Test.o` is added to `dotnet publish` command-line:

> PS Z:\1_experiment\wasm> emcc -c Test.c
> PS Z:\1_experiment\wasm> dotnet publish -r browser-wasm -c Debug /p:TargetArchitecture=wasm --self-contained /p:PlatformTarget=AnyCPU /p:MSBuildEnableWorkloadResolver=false /p:EmccExtraArgs=Test.o /bl
> Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
> Copyright (C) Microsoft Corporation. All rights reserved.
> C:\Program Files\dotnet\sdk\6.0.101\MSBuild.dll -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\6.0.101\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\6.0.101\dotnet.dll -maxcpucount -property:TargetArchitecture=wasm -property:PlatformTarget=AnyCPU -property:MSBuildEnableWorkloadResolver=false -property:EmccExtraArgs=Test.o -property:SelfContained=True -property:_CommandLineDefinedSelfContained=true -property:RuntimeIdentifier=browser-wasm -property:_CommandLineDefinedRuntimeIdentifier=true -property:Configuration=Debug -restore -target:Publish -verbosity:m /bl .\wasm.csproj
>   Determining projects to restore...
>   All projects are up-to-date for restore.
>   wasm -> Z:\1_experiment\wasm\bin\Debug\net6.0\browser-wasm\wasm.dll
> EXEC : warning : undefined symbol: S_P_CoreLib_System_Runtime_InternalCalls__RhpNewArray (referenced by top-level compiled C/C++ code) [Z:\1_experiment\wasm\wasm.csproj]
> EXEC : warning : undefined symbol: S_P_CoreLib_System_Runtime_InternalCalls__RhpNewArrayAlign8 (referenced by top-level compiled C/C++ code) [Z:\1_experiment\wasm\wasm.csproj]
> EXEC : warning : undefined symbol: S_P_CoreLib_System_Runtime_InternalCalls__RhpNewFast (referenced by top-level compiled C/C++ code) [Z:\1_experiment\wasm\wasm.csproj]
> EXEC : warning : undefined symbol: S_P_CoreLib_System_Runtime_InternalCalls__RhpNewFastAlign8 (referenced by top-level compiled C/C++ code) [Z:\1_experiment\wasm\wasm.csproj]
> EXEC : warning : undefined symbol: S_P_CoreLib_System_Runtime_InternalCalls__RhpNewFastMisalign (referenced by top-level compiled C/C++ code) [Z:\1_experiment\wasm\wasm.csproj]
> EXEC : warning : undefined symbol: S_P_CoreLib_System_Runtime_InternalCalls__RhpNewFinalizable (referenced by top-level compiled C/C++ code) [Z:\1_experiment\wasm\wasm.csproj]
> EXEC : warning : undefined symbol: S_P_CoreLib_System_Runtime_InternalCalls__RhpNewFinalizableAlign8 (referenced by top-level compiled C/C++ code) [Z:\1_experiment\wasm\wasm.csproj]
> EXEC : warning : undefined symbol: dotnet_browser_entropy (referenced by top-level compiled C/C++ code) [Z:\1_experiment\wasm\wasm.csproj]
>   wasm -> Z:\1_experiment\wasm\bin\Debug\net6.0\browser-wasm\publish\
> PS Z:\1_experiment\wasm> node .\bin\Debug\net6.0\browser-wasm\native\wasm.js
> Calling stub instead of signal()
> [Program.cs] Main
> [Test.c] NativeFunc
> [Program.cs] NativeFunc returns 123456

But, `DirectPInvoke` and `NativeLibrary` seems to be ignored when building wasm with `dotnet publish -r browser-wasm -c Debug /p:TargetArchitecture=wasm --self-contained /p:PlatformTarget=AnyCPU /p:MSBuildEnableWorkloadResolver=false`:
```xml
<ItemGroup>
  <DirectPInvoke Include="Test" />
  <NativeLibrary Include="Test.o"/>
</ItemGroup>
```
Without `/p:EmccExtraArgs=Test.o`, `dotnet publish` will fail with warning `EXEC : warning : undefined symbol: NativeFunc (referenced by top-level compiled C/C++ code)`, even if `DirectPInvoke` and `NativeLibrary` has been added to csproj.
