### ISSUE TITLE
[NativeAOT-LLVM]: Question fcntl F_DUPFD_CLOEXEC and WASI

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#1847]
`dup2` is generally used in Unix for pipes and things like `2>&1` which don't make any sense in WASI or Wasm far as I can see, there being only one process. 
`pal_io.c` has this for `dup`ing descriptors
```intptr_t SystemNative_Dup(intptr_t oldfd)
{
    int result;
#if HAVE_F_DUPFD_CLOEXEC
    while ((result = fcntl(ToFileDescriptor(oldfd), F_DUPFD_CLOEXEC, 0)) < 0 && errno == EINTR);
#else
    while ((result = fcntl(ToFileDescriptor(oldfd), F_DUPFD, 0)) < 0 && errno == EINTR);
    // do CLOEXEC here too
    fcntl(result, F_SETFD, FD_CLOEXEC);
#endif
    return result;
}
```
`fcntl` with a command of `F_DUPFD_CLOEXEC` would attempt to get a new file descriptor with a number >= `arg`.  However this is not available in WASI.  It has this to say: https://github.com/WebAssembly/WASI/blob/main/phases/snapshot/docs.md#-fd_renumberfd-fd-to-fd---result-errno

In emscripten, they implement this by returning `-ENOSYS`
```
long __syscall_fcntl64(long fd, long cmd, ...) {
  return -ENOSYS;
}
```
This makes opening the Console fail, as it dups the `fd` as part of `OpenStandardOutput` in `ConsolePal`:
```
        public static Stream OpenStandardOutput()
        {
            return new WasmConsoleStream(Interop.Sys.Dup(Interop.Sys.FileDescriptors.STDOUT_FILENO), FileAccess.Write);
        }
```
For Wasm, if that was just 
```
        public static Stream OpenStandardOutput()
        {
            return new WasmConsoleStream(Interop.Sys.FileDescriptors.STDOUT_FILENO, FileAccess.Write);
        }
```

The `Console`, `Out` is a static:
```
       public static TextWriter Out
```

So is that going to be a problem?  I'm going to try it anyway, but maybe there's consequences I'm not envisaging.

**Comment by jkotas** [comment]
I think it should work. I do not understand why we need to dup the stdin/out in the first place: https://github.com/dotnet/runtime/issues/25394

**Comment by yowl** [comment]
Ok, it seems fine. Thanks
