### ISSUE TITLE
[NativeAOT-LLVM] For WASI are we going to need another build of the C parts of the runtime?

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#1848]
In Emscripten, for opening files, `O_CREAT` is `0x40` .  In wasi-sdk it is `0x1000000`.  This makes opening files with the current emscripten build of the runtime (`libPortableRuntime.a` I think is the affected library, but not checked), difficult.  It would be nice to support wasi features like opening files.  Is there an alternative like switch `ConvertOpenFlags` based on something (https://github.com/dotnet/runtimelab/blob/714aef1181f175ab0f45930eb89f90dfd53d2064/src/libraries/Native/Unix/System.Native/pal_io.c#L233) ?

I suppose really we should build the whole library with wasi-sdk, but that's not simple either as it mean another dependency and I think their Windows build also needs MinGW.

**Comment by jkotas** [comment]
> Is there an alternative like switch ConvertOpenFlags based on something

I think you can implement a short-term workaround in these methods.

> I suppose really we should build the whole library with wasi-sdk,

It is likely unavoidable in the long run. I doubt that this is the only difference.

**Comment by yowl** [comment]
Ok, thanks.  I've got something working for now anyway.  You can opine on how bad the hack is when the PR is in :-)
