### ISSUE TITLE
[NativeAOT]  Delegate Method Data Error

### ISSUE THREAD

**Issue by wsxhm** [dotnet/runtimelab#1853]
![02KTZUYD 5`K$%}~O2{KTQC](https://user-images.githubusercontent.com/20971139/153410274-9137ac70-9ca9-4d2f-b80e-9a347e00fa77.png)

![DQUL3R5O@38KA)_1W%@{Q`L](https://user-images.githubusercontent.com/20971139/153407425-fc499168-5a84-4579-bb18-9ff56f1602c1.png)

![Y}VICYL_N(@ W}R5B4 _3K](https://user-images.githubusercontent.com/20971139/153406997-63ea6281-dc9b-439d-8d83-51535c9af8dd.png)

```
   var method = typeof(Polyline).GetMethod(nameof(Points_CollectionChanged), System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
   Console.WriteLine("--：" + method.Name);
   var del = method.CreateDelegate(typeof(EventHandler<CollectionChangedEventArgs<Point>>), this);
   Console.WriteLine("==：" + ":" + del.Method.Name);
   points.Events.AddHandler(nameof(points.CollectionChanged), del);
```

“Points_CollectionChanged” method becomes “OnHitTestOnPath” delegate，“Points_CollectionChanged”  private method in Polyline , “OnHitTestOnPath” private method in Shape。Polyline derived from Shape

net5, PackageReference Include="Microsoft.DotNet.ILCompiler" Version="7.0.0-alpha.1.22074.1" 

AOT release error，but AOT debug is OK

**Comment by kant2002** [comment]
From first glance, I think you should supply RD.xml where you add specific delegate type. Without specific sample it's hard to trace from information what we have.

As you see, from stack trace, that error comes from CPF itself, so likely that framework using some non-AOT-friendly code. It's hard to guess what it is.

Please correct me if I made a mistake. You are using CPF UI framework which is on Nuget
https://www.nuget.org/packages/Xhm.CPF/
and here official website http://cpf.cskin.net/

**Comment by wsxhm** [comment]
@kant2002   I'm the author of CPF. defined a weak reference event. using aot  the method of delegate has changed leading to crash.
 
test sample
[CPFTest.zip](https://github.com/dotnet/runtimelab/files/8047190/CPFTest.zip)

**Comment by kant2002** [comment]
@wsxhm can you remove `<IlcFoldIdenticalMethodBodies>true</IlcFoldIdenticalMethodBodies>` from your project file and check that issue would disappear?

Also can you trim application a bit, so troubleshooting would be easier.

**Comment by wsxhm** [comment]
@kant2002  Thank, If remove it, there will be no more errors.

**Comment by kant2002** [comment]
I assume that my suggestion works. If so, please close the issue.

Also all new issues should be posted to `dotnet/runtime`. More about change of repository here https://github.com/dotnet/runtimelab/issues/1241#issuecomment-1026571480
