### ISSUE TITLE
Multiple return types

### ISSUE THREAD

**Issue by dariolingotti** [dotnet/runtimelab#1856]
Allowing multiple return types in a interface would help adding new features to an existing interface without creating breaking changes.
For example we have the method:
```
ReturnType Method();
```
We want to have a method with the same signature that returns the IReturnType interface instead of its implementation ReturnType, for example:
```
IReturnType Method();
```
This is currently not allowed since they have the same signature.

If ReturnType does not have any public constructors we want use the IReturnType to mock the Method implementation. For example:

```
Mock<IReturnType> returnValue = new();
mock.Setup(x => x.Method()).Returns(returnValue.Object);
```
The proposal is to have a way to allow returning the correct type according to the calling method:

```
ReturnType one = Method();
IReturnType two = Method();
var three = Method();
```

In the third case we need to define a way to indicate the default return type.

Proposed notation is to include a "default" modifier:

```
default ReturnType Method();
```

Only one method can have the default modifier with the same signature.

Non default methods can be defined with a "non default" modifier:

```
non default IReturnType Method();
```

You can have many non default methods. 
The default modifier is not mandatory if the other methods with the same signature use the "non default" modifier.

Alternatively use a notation similar to Typescript union types where the first type should be the default type:
```
ReturnType|IReturnType Method();
```
Limitations: ReturnType should implement the IReturnType interface.

**Comment by huoyaoyuan** [comment]
The runtimelab repo is only for currently ongoing experiments inside the repository. For brand new features, please discuss at runtime or csharplang repo.

> This is currently not allowed since they have the same signature.

Note that the limitation is only for C# (and VB/F#) language. It's not limited by IL/CLR. The CLR counts name&parameter&return type as the signature of method. You may find such methods in output of obfuscators. See also https://github.com/dotnet/csharplang/discussions/4869

> Allowing multiple return types in a interface would help adding new features to an existing interface without creating breaking changes.

Adding or modifying member in interface is both breaking change. Adding member is breaking for implementations, though you can add one with default interface method implementation to avoid.
