### ISSUE TITLE
[NativeAOT-LLVM] [Question] CT_INDIRECT (revisited)

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#1860]
We still dont have support for `CT_INDIRECT` calls and one of the reasons why is that I don't know how to get the `CORINFO_SIG_INFO`.  The `gtCallMethHnd` is the call address node so `eeGetMethodSig` is out.  There are other methods like `eeGetSig` and `eeGetCallSiteSig` but they need a token.  We currently need the `CORINFO_SIG_INFO` in order to `lowerCallToShadowStack`  .  Are we going to have to try to rewrite `lowerCallToShadowStack` to not require a `CORINFO_SIG_INFO` or is there a way to get one from the `CT_INDIRECT` node?

Thanks

**Comment by jkotas** [comment]
`CORINFO_SIG_INFO` is available when `CT_INDIRECT` call is imported in `impImportIndirectCall`. Update `impImportIndirectCall` to store `CORINFO_SIG_INFO` so that it is available in lowering where you need it?

**Comment by yowl** [comment]
That might work, but `CORINFO_SIG_INFO ` is quite big, so I can't just add it as a struct to `GenTree` as it exceeds `TREE_NODE_SZ_LARGE` and I think there is a concern in making `GenTree` much larger.  If I just assign the pointer then it goes out of scope.

**Comment by jkotas** [comment]
Yes, it would probably need to be a separate struct and GenTree would have to have a pointer to it.

**Comment by yowl** [comment]
Righto, let me try that.  Thanks

**Comment by yowl** [comment]
Or maybe I should just `|| defined(TARGET_WASM)`  at

https://github.com/dotnet/runtimelab/blob/258c8cee8cec40849127995fee955c117ced3d42/src/coreclr/jit/gentree.h#L4214-L4217

As that seems to be doing just this:

https://github.com/dotnet/runtimelab/blob/258c8cee8cec40849127995fee955c117ced3d42/src/coreclr/jit/importer.cpp#L9230-L9235
