### ISSUE TITLE
Misaligned cctor context when Vectors are present

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtimelab#187]
This code is trying to make sure both the class constructor context and the non-GC static data that follows it is aligned.

https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/src/coreclr/src/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/NonGCStaticsNode.cs#L136-L151

But we then use incorrect offset when trying to access the cctor context given a pointer to the non-GC data.

Affected tests:
JIT/HardwareIntrinsics/X86/Avx/Avx_r
JIT/HardwareIntrinsics/X86/Avx/ConvertToVector_r
/JIT/HardwareIntrinsics/X86/Avx2/Avx2_r
JIT/HardwareIntrinsics/X86/Fma_Vector256/Fma_r

**Comment by MichalStrehovsky** [comment]
The only thing that should be needed to fix this is to make `NonGCStaticsNode.GetClassConstructorContextStorageSize` private and all the places that start failing to compile should call `GetClassConstructorContextSize` instead (we need to make that one public).

**Comment by ChiragRupani** [comment]
I have made changes according to above comments, Please have a look on above PR. Moreover, now type argument is redundant can we remove it - there are 23 references?

**Comment by MichalStrehovsky** [comment]
#287
