### ISSUE TITLE
[NativeAOT-LLVM] [Question] CORINFO_HELP_READYTORUN_DELEGATE_CTOR implementation

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#1870]
When compiling 
https://github.com/dotnet/runtimelab/blob/4fe7f4eddeded2978cec9bb4f802846e001400ec/src/coreclr/nativeaot/System.Private.TypeLoader/src/Internal/Reflection/Execution/AssemblyBinderImplementation.cs#L28-L32

`AddModuleRegistrationCallback` accepts a `Action<ModuleInfo>` and so will call the helper `CORINFO_HELP_READYTORUN_DELEGATE_CTOR `.

For the helper `CORINFO_HELP_READYTORUN_DELEGATE_CTOR `, if I ask for the symbol name from its `call->gtEntryPoint.handle` I'll get something like:

`__DelegateCtor_S_P_CoreLib_System_Delegate__InitializeClosedInstance__S_P_TypeLoader_Internal_Reflection_Execution_AssemblyBinderImplementation__RegisterModule`

I'd then have to write out an implementation for this ( which I believe we don't currently have), that would go on to call `S_P_CoreLib_System_Delegate__InitializeClosedInstance` I suppose.

My question is, should I do that?  I ask because the IL implementation for the ctor in `AssemblyBinderImplementation`  would directly call `S_P_CoreLib_System_Delegate__InitializeClosedInstance` without the need for a `__DelegateCtor_S_P_CoreLib_System_Delegate__InitializeClosedInstance__S_P_TypeLoader_Internal_Reflection_Execution_AssemblyBinderImplementation__RegisterModule` .

Thanks

**Comment by jkotas** [comment]
> I ask because the IL implementation for the ctor in AssemblyBinderImplementation would directly call S_P_CoreLib_System_Delegate__InitializeClosedInstance

I think you would need to inline it in the importer in `fgOptimizeDelegateConstructor` to make this work. Is it what you meant? It sounds good to me. It may improve the nativeaot non-wasm path as well.
