### ISSUE TITLE
[NativeAOT-LLVM]  error : The PrivateSdkAssemblies ItemGroup is required for _ComputeAssembliesToCompileToNative

### ISSUE THREAD

**Issue by insinfo** [dotnet/runtimelab#1876]
i tried to follow the little hello world tutorial in the NativeAOT-LLVM README but i try this error when running the command

```console
 dotnet publish -r win-x64 -c release
```

```
PS C:\MyCsharpProjects\fsbackup> dotnet publish -r win-x64 -c release
Microsoft(R) Build Engine versão 16.11.2+f32259642 para .NET
Copyright (C) Microsoft Corporation. Todos os direitos reservados.

  Determinando os projetos a serem restaurados...
  Todos os projetos estão atualizados para restauração.
  fsbackup -> C:\MyCsharpProjects\fsbackup\bin\release\net5.0\win-x64\fsbackup.dll
C:\Users\isaque\.nuget\packages\microsoft.dotnet.ilcompiler.llvm\7.0.0-alpha.1.22161.1\build\Microsoft.NETCore.Native.Publish.targets(75,5): error : The PrivateSdkAssemblies ItemGroup is required for _ComputeAssembliesToCompileToNative [C:\MyCsharpProjects\fsbackup\fsbackup.csproj]
PS C:\MyCsharpProjects\fsbackup>
```

https://github.com/dotnet/runtimelab/tree/feature/NativeAOT-LLVM

**Comment by yowl** [comment]
If you are targeting win-x64 you dont want the NativeAOT-LLVM branch, but the "main" branch which is now merged into runtime and no longer an experimental branch here.

**Comment by jkotas** [comment]
https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/compiling.md

**Comment by chuchu** [comment]
I get the same error with a basic ASP.NET Core project using net core version 6.0.301. Both on Windows using win-x64 or win10-x64 and on Linux with linux-x64.

```console
.nuget\packages\microsoft.dotnet.ilcompiler.llvm\7.0.0-alpha.1.22251.1\build\Microsoft.NETCore.Native.Publish.targets(75,5): error : The PrivateSdkAssemblies ItemGroup is required for _ComputeAssembliesToCompileToNative
```

I was able to compile a console application.

I use the nuget feed "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json" even I'm on net core 6. Is this a problem?

I do not really understand the above answer. What needs to be changed?

**Comment by jkotas** [comment]
You should use `microsoft.dotnet.ilcompiler` package, not `microsoft.dotnet.ilcompiler.llvm` package. `microsoft.dotnet.ilcompiler.llvm` package is for wasm-llvm experiment and it is not able to compile ASP.NET Core apps.

Also, you do not need the custom feed anymore. The preview versions are published on nuget.org now: https://www.nuget.org/packages/Microsoft.DotNet.ILCompiler/
