### ISSUE TITLE
HttpClient not working after AOT

### ISSUE THREAD

**Issue by sorainnosia** [dotnet/runtimelab#1883]
Compile to AOT using NativeAOT, method that uses system.net.http.httpclient pause when retrieving httpresponsemessage

Waited a long time and no output return

While compile using bflat it works. The URL is http not https

**Comment by jkotas** [comment]
Could you please share a short program that reproduces the problem, and version of the NativeAOT package that you are seeing this problem with?

**Comment by sorainnosia** [comment]
Hangs when calling below
`
            HttpClient cwc = new HttpClient();
`
`
            HttpResponseMessage msg = cwc.GetAsync(url2).Result;
`
`
            string page = msg.Content.ReadAsStringAsync().Result;
`

NativeAOT version : Microsoft.DotNet.ILCompiler 7.0.0-preview2.22152.2

**Comment by jkotas** [comment]
I have tried this against https://www.bing.com and it works fine. Can you share the url2 of the server if it is public, or at least share what kind of server is it?

> Microsoft.DotNet.ILCompiler 7.0.0-preview2.22152.2

You may want to try our nightly build feed that is preview4 currently: https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/compiling.md#add-ilcompiler-package-reference . The problem might have been fixed already.

**Comment by sorainnosia** [comment]
censored url

**Comment by jkotas** [comment]
Hmm, this url works fine for me. Are you on Windows, Linux or macOS?

**Comment by sorainnosia** [comment]
that's strange, let me tried again

**Comment by sorainnosia** [comment]
it works now, probably i used the wrong version

thanks

Edit :
Found out the reason, because I disable Reflection, after setting
```
<IlcDisableReflection>false</IlcDisableReflection>
```
It is working fine now
