### ISSUE TITLE
[NativeAOT] Not working COMPlus_legacyCorruptedStateExceptionsPolicy 1

### ISSUE THREAD

**Issue by RoccoZero** [dotnet/runtimelab#1887]
I can't catch AccessViolationException :(
C++ has __try __except
C# have COMPlus_legacyCorruptedStateExceptionsPolicy
but NativeAOT is nothing to catch AccessViolationException

sorry for my bad English

**Comment by jkotas** [comment]
Handling AccessViolationExceptions is a bad practice. We do not have plans to support `COMPlus_legacyCorruptedStateExceptionsPolicy` in NativeAOT.
