### ISSUE TITLE
[NativeAOT] Static class

### ISSUE THREAD

**Issue by RoccoZero** [dotnet/runtimelab#1896]
is it possible to remove these calls?
it's just that in my project, optimization should be at the highest level like c++

I myself immediately activate manually all static properties
I want to completely remove automatic activation of static classes
please give us this opportunity

<img width="540" alt="image" src="https://user-images.githubusercontent.com/33149580/173237270-013423fa-1196-4da5-b63e-f3dc9f1a086c.png">

**Comment by jkotas** [comment]
This is tracked by https://github.com/dotnet/runtime/issues/64242 -  Optimize static field access and Optimize class constructor checks

**Comment by jkotas** [comment]
Dup of https://github.com/dotnet/runtime/issues/64242
