### ISSUE TITLE
[Question] Calling C DLL Through DLLImport in Dependency

### ISSUE THREAD

**Issue by jamsoft** [dotnet/runtimelab#1924]
I'm working through compiling my application (.NET6.0/AvaloniaUI). It's slow going but I'm making progress and working on my `rd.xml` file as I go.

The issue I'm facing has me confused. I'm not even 100% sure my scenario is supported from reading the docs but I'm just not experienced enough to know for sure. It doesn't feel like an outlandish requirement so I'm hoping it's my inexperience that's the issue.

During application initialisation my application calls into a .NET managed library that wraps the functionality of a C library.

My rd.xml entry for the managed library is:

```
<Assembly Name="AssemblyName" Dynamic="Required All" MarshalDelegate="Required All" Serialize="Required All" />
```
This libraries calls to the C library are decorated with:
```
[DllImport("dllname", EntryPoint = "methodname")]
```

The first call it failed on is an instruction sent to this C library to load another C library that is a plugin to the main C library. So whilst it's obviously not using the unsupported `Assembly.Load` API I'm unsure whether to expect something like that to work given the published limitations on dynamic loading, but I'm also thinking that's limited to the "user code" of the application, not 3rd party dependencies also not using `Assembly.Load`.

So as A test, I removed all the plugin load code to simplify things.

It then started failing on the next call to the main C library. The error is:

```
0xC0000005: Access violation reading location 0x0000000000000000
```

All the C dependencies are in the same / expected location next to the main .exe file. The layout mirrors the non NativeAOT layout.

If I remove the dependencies and debug the application the error is that it cannot find the C library.

```
Unable to [find?] native library 'dllname' or one of its dependencies
```

If I put the dependencies back, I just get the access violation which seems to suggest it found the dll but cannot access it.

I've tried various settings out of desperation, such as `<DirectPInvoke Include="dllname" />` but I'm not doing the PInvoke from my code, the 3rd party is. The `NativeLibrary` seems the most appropriate but it needs a *.lib or *.a file.

I guess the first question is, can I even do what I need to do? If I can, is this documented anywhere or could I get a little nudge in the right direction?

TIA.

Setup: Rider, Release, Any CPU, .NET 6.0, win-x64, AvaloniaUI 0.10.15, ILCompiler 7.0.0-alpha.1.22074.1

**Comment by jkotas** [comment]
> this C library to load another C library that is a plugin to the main C library

This should work just fine. Native AOT compilation should not impact it in any way.

Are you able to get a stacktrace for the `Access violation reading location 0x0000000000000000` crash? You need to find out which code is trying to perform this read and how it got there.

> ILCompiler 7.0.0-alpha.1.22074.1

This is pretty old package. You may want to switch to the latest preview package published on nuget.org: https://www.nuget.org/packages/Microsoft.DotNet.ILCompiler/

**Comment by jamsoft** [comment]
Interesting. Just after I posted this, it started to work and progress further through the app initialisation. I'm just working through all the EFCore compilation bits now.

Also that's the most recent package on the feed I have. Will investigate that too. Thank you.

**Comment by jamsoft** [comment]
After upgrading to the latest preview, trying to compile bombs with

```
Microsoft.DotNet.ILCompiler.targets(45,5): error : The ResolvedILCompilerPack ItemGroup is required for target ImportRuntimeIlcPackageTarget
```

But I can't find much about this from Googling. Not sure how to fix.

**Comment by jkotas** [comment]
I think it means that you are setting `PublishAot` property, but you are using old .NET SDK that does not support it yet.

**Comment by jamsoft** [comment]
Gotcha. Didn't realise that wasn't in .NET 6. Removing:
```
<PublishAot>true</PublishAot>
```
Worked.

**Comment by jamsoft** [comment]
I'm not sure if I'm doing something fundamentally wrong but this is an excruciating process of compiling -> test -> tweaking the rd.xml loop. I guess this is a silly question but is there a repo of rd.xml snippets for libraries or common dependencies?

**Comment by jamsoft** [comment]
It's the forgetting I'm still debugging in one window and kicking off another compile that keeps getting me too ;)

**Comment by jkotas** [comment]
> is there a repo of rd.xml snippets for libraries or common dependencies?

There is not one. I am not sure it is even possible to have a reusable snippet in many cases. The problems often span multiple libraries.

Yes, tweaking rd.xml for app or libraries that use patterns that are incompatible with trimming or AOT is an excruciating process, and you cannot be ever sure whether you got it 100% right.

We believe that the only way to make the experience 100% reliable is static analysis of the whole application: https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/fixing-warnings . We are going to emphasize importance of getting to zero trim and AOT compat warnings for publishing native AOT apps with confidence; and campaign to have more libraries annotated. 

If there are libraries that give you hard time, please open issues in their repos to get them annotated properly: https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming The maintainers need to hear about this.

**Comment by jamsoft** [comment]
Will do. This is a feature I've been really looking forward to for years.

**Comment by jamsoft** [comment]
Sorry for coming in with another question but when I hit things as fundamental as this:
```
MissingMetadataException: 'System.IComparable<System.Nullable<System.Int64>>' is missing metadata
```
What's the best way of dealing with it?

**Comment by jamsoft** [comment]
Wow, I'm done. I have a running AOT compiled application!

4 12 hour days of tweak, compile, test ... ouch. 1100 lines in my rd.xml.

One interesting observation.

Even now it's working. When debugging the startup it will error on the calls to the external DLL with:

```
0xC0000005: Access violation reading location 0x0000000000000000
```

But it's definitely all working. Thanks for your help.

**Comment by jkotas** [comment]
Great to hear that you were able to make it work!
