### ISSUE TITLE
Where is WASM AOT support developed? dotnet/runtime vs. dotnet/runtimelab

### ISSUE THREAD

**Issue by hannesd** [dotnet/runtimelab#1932]
I've been looking for a way to build WASM from C# AOT, no JIT involved once code is run in the browser. The number of projects and people out there who try to solve this is very confusing to me. At this point I have narrowed it down to dotnet/runtimelab and dotnet/runtime (the uno platform seems to use dotnet/runtime). To me they look like they are the "official" projects.

First tests indicate that dotnet/runtime mono/wasm is stable and performs well while dotnet/runtimelab NativeAOT-LLVM is not as mature.

Hence my question: How are these projects related and which one should I use? It looks like dotnet/runtime has seen more development activity recently. Is this where the official AOT support for C# is built by the community?

**Comment by jkotas** [comment]
You should use dotnet/runtime if you are looking for something stable.

dotnet/runtimelab NativeAOT-LLVM is experimental project.
