### ISSUE TITLE
DllImportGenerator can't run

### ISSUE THREAD

**Issue by jerviscui** [dotnet/runtimelab#1941]
I clone the DllImportGenerator project and open sln by VS2022.
And then build the solution, there are 40 mistakes:

> Error CS8795 "NativeExportsNE.Sum(int, int)" must have an implementation part because it has an accessibility modifier. \runtimelab\DllImportGenerator\Demo\ program.cs 11 activity

**Comment by jkotas** [comment]
DllImportGenerator experiment in this repo was completed. The up-to-date version lives in dotnet/runtime repo at https://github.com/dotnet/runtime/tree/main/src/libraries/System.Runtime.InteropServices/gen/LibraryImportGenerator
