### ISSUE TITLE
NativeAOT not Stripping Symbols

### ISSUE THREAD

**Issue by jamsoft** [dotnet/runtimelab#1948]
Going on from the last couple of comments on [this thread](https://github.com/dotnet/runtimelab/issues/597). I have been trying to get my application to strip the debug symbols.

I've tried adding it to my csproj file in the main `PropertyGroup`:
```xml
    </PropertyGroup>
        ...
        <StripSymbols>true</StripSymbols>
    </PropertyGroup>
```

I've also tried specifying it on the command:

```
dotnet publish MyApp.csproj -c:Release --runtime linux-x64 -v:m --self-contained true -p:StripSymbols=true
```

But I'm still getting huge executables on Linux and OSX.

Is this version dependent? I'm targeting .NET 6 at the moment and it seems I've had issues with these entries previously as they are commented out (I can't remember why though, I think I ran into compiler issues - am investigating that now as I didn't add any comments).

```
<!--        <PublishAot>true</PublishAot> >NET 7+ --> 
<!--        <PublishTrimmed>true</PublishTrimmed>-->
```

I'm wondering if the `<StripSymbols>` not working for me is related?

**Comment by josephmoresena** [comment]
But when you run strip, at least in Linux, does the binary size get reduced?
I can't test StripSymbols for now, but in some of my experiments with NativeAOT in OSX x64 the strip command was unable to remove the binary oversize. 

Would be better if this Issue was opened in dotnet/runtime

**Comment by jkotas** [comment]
> Is this version dependent?

`StripSymbols` property was added just recently. If it does not work for you, you are likely using out-dated version of the native AOT package.

> I'm targeting .NET 6 at the moment and it seems I've had issues with these entries previously as they are commented out

These issues should be fixed in latest .NET 7 previews. 

> Would be better if this Issue was opened in dotnet/runtime

Yes, the project lives in dotnet/runtime now. Closing the issue here.
