### ISSUE TITLE
Question: NativeAOT-LLVM: strategy for PRs for RyuJIT with optimisations on

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#1964]
I'd like to make a bit of progress on removing 

https://github.com/dotnet/runtimelab/blob/feature/NativeAOT-LLVM/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.targets#L19-L20

I've not really got any idea how many issues there are going to be.  The first ones have already been discussed in https://github.com/dotnet/runtimelab/issues/1859.  Would it be ok to create PRs of individual issues even though on their own they wont be able to compile with optimisations and the flag will have to still be `false`.  It would keep the PRs small at the cost of potentially not being correct.  

Alternatively I can work through all the issues with a potentially large PR at the end that allows the tests to run.

Any preference?

@SingleAccretion @jkotas

**Comment by jkotas** [comment]
> Would it be ok to create PRs of individual issues even though on their own they wont be able to compile with optimisations

That sounds good. Smaller PRs are easier to review and merge.

**Comment by yowl** [comment]
Thanks
