### ISSUE TITLE
Question: NativeAOT-LLVM: leave targets

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#1990]
The IL backend has a bug that means the finally block is called twice if an exception occurs and is caught as in the following code:
```cs
private static void TryFinallyWithCatch()
{
    try
    {
        throw new Exception();
    }
    catch {}
    finally
    {
        finallyCalled++;
    }
}
```
The IL for this looks like:
```cs
.method void TryFinallyWithCatch() cil managed
{
  // Code size: 31
  .maxstack 2

  .try IL_0001 to IL_0008 catch object handler IL_0008 to IL_000D
  .try IL_0001 to IL_000F finally handler IL_000F to IL_001E
  IL_0000:  nop
  IL_0001:  nop
  IL_0002:  newobj      instance void [System.Private.CoreLib]System.Exception::.ctor()
  IL_0007:  throw
  IL_0008:  pop
  IL_0009:  nop
  IL_000A:  nop
  IL_000B:  leave.s     IL_000D
  IL_000D:  leave.s     IL_001E
  IL_000F:  nop
  IL_0010:  ldsfld      int32 Program::finallyCalled
  IL_0015:  ldc.i4.1
  IL_0016:  add
  IL_0017:  stsfld      int32 Program::finallyCalled
  IL_001C:  nop
  IL_001D:  endfinally
  IL_001E:  ret
}
```
The 2 leave targets 
```
  IL_000B:  leave.s     IL_000D
  IL_000D:  leave.s     IL_001E
```
Is one for the try and one for the catch?.  If so why are they both in the catch handler region, after all it is `IL_0008 to IL_000D`  ?

Thanks

**Comment by yowl** [comment]
The EH second pass handler for the exception should call the finally handler, shouldn't it?

**Comment by jkotas** [comment]
This is how the IL matches the C#. 
```
try
{
    try
    {
        // newobj      instance void [System.Private.CoreLib]System.Exception::.ctor()
        // throw
        throw new Exception();
    }
    catch
    {
        // leave.s     IL_000D
    }
    
    // IL_000D:
    // leave.s     IL_001E
}
finally
{
    // ldsfld      int32 Program::finallyCalled
    // ldc.i4.1
    // add
    // stsfld      int32 Program::finallyCalled
    finallyCalled++;
    
    // endfinally
}

// IL_001E
// ret
```

> The EH second pass handler for the exception should call the finally handler, 

Yes, that's correct.

**Comment by yowl** [comment]
Thanks, the catch leave destination is `IL_000D`, so why shouldn't the `leave` at `IL_000D` cause the finally to be executed?

**Comment by jkotas** [comment]
Yes, the leave at `IL_000D` should cause the finally to be executed.

**Comment by yowl** [comment]
I'm lost, so if the second pass handler calls it, and the leave at `IL_000D`  calls it, then that's twice?  That's the behavior I have currently and I'm not sure which call is wrong.

**Comment by jkotas** [comment]
Sorry for the confusion - I was not paying attention when I have confirmed that ~~The EH second pass handler for the exception should call the finally handler,~~

The exception handling second pass should stop in the catch block and it should not call the finally handler. The finally handler should be called via the non-exceptional regular program flow in this case.

If you see the finally handler getting called by the exception handling second pass, it is likely caused by exception handling clauses getting emitted in a wrong order.

**Comment by yowl** [comment]
Thanks, that could be,

I've added some debugging to `InvokeSecondPassWasm` so I can understand what is going on better.  The clauses are emitted/iterated in the order as they appear at the top of the IL for this example at least:
```cs
  .try IL_0001 to IL_0008 catch object handler IL_0008 to IL_000D
  .try IL_0001 to IL_000F finally handler IL_000F to IL_001E
```

I'm comparing the Wasm handler
https://github.com/dotnet/runtimelab/blob/f9cf5b0e52c4645c0a76ad3770d0c63c712c3a05/src/coreclr/nativeaot/Runtime.Base/src/System/Runtime/ExceptionHandling.wasm.cs#L109
to the main one
https://github.com/dotnet/runtimelab/blob/f9cf5b0e52c4645c0a76ad3770d0c63c712c3a05/src/coreclr/nativeaot/Runtime.Base/src/System/Runtime/ExceptionHandling.cs#L860
There are very similar, Wasm does the iterator a bit differently, and it has no PC.

For an EH to _not_ be called in the `for` loop that iterates over the EHs, I can see 3 options:

1. The iterator is not at the start of the list
2. `idxLimit` is small, less than the number or clauses
3. One of the conditions that cause a `continue` is true, e.g. by having `idxStart` to  a value < max(uint)

There's only 2 clauses in here, so I could try them the other way just for this test, but that's not going to make any difference with code as it is because the `for` loop will pass over them both.   My suspicion is either 1, 3 above.   In LLVM, the iterator is always reset to the start, and `idxStart` is always `max(uint)`

**Comment by yowl** [comment]
Hmm, I've missed something here, `InternalCalls.RhpSfiNext` can modify `idxStart`

**Comment by yowl** [comment]
Looking at 

https://github.com/dotnet/runtimelab/blob/f9cf5b0e52c4645c0a76ad3770d0c63c712c3a05/src/coreclr/nativeaot/Runtime/StackFrameIterator.cpp#L1376-L1384

Am I reading the comment right by inferring that for Wasm, where the iterator is never used for GC, that the Wasm iterator (as used in the EH), should always follow the behavior as though an `ExCollide`  flag was set?

**Comment by yowl** [comment]
Think I've made a fairly basic error.  The dispatch of the exception is calling the catch before the second pass...

**Comment by yowl** [comment]
@jkotas do you know where I can find the code that determines the order for the `EHClaue`s for non-wasm targets?

**Comment by jkotas** [comment]
It should be this: https://github.com/dotnet/runtime/blob/9cd1a32332daec34ca6a8b13d638b2904e797ae7/src/coreclr/jit/jiteh.cpp#L1800

**Comment by yowl** [comment]
This is fixed by the above PR.
