### ISSUE TITLE
NativeAOT-LLVM: RhUnbox2 changes to a ret void in release configuration

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#2008]
The `RhUnbox2` helper changes to a void method in release configuration:
```
CALL help void   HELPER.CORINFO_HELP_UNBOX
```
For linking between the clrjit module and the IL module this is a problem as in IL it is still a `ref` .  I don't really understand how unboxing can be a void, but it's obviously some optimisation.  Can I turn it off somehow, temporarily until the IL backend is gone?

**Comment by jkotas** [comment]
Looks like it is this line in importer.cpp: `op1 = gtNewHelperCallNode(helper, TYP_VOID, op2, op1);`. You can disable the optimization by replacing `if (canExpandInline && shouldExpandInline)` with `if (false)`. Changing the return type to `TYP_BYREF` may work too.

**Comment by yowl** [comment]
Thanks
