### ISSUE TITLE
[NativeAOT]How to fix  System.NotSupportedException: Metadata for type 'Newtonsoft.Json.Linq.JObject' was not provided by TypeInfoResolver of type '.aot.MyJsonContext'

### ISSUE THREAD

**Issue by lozn00** [dotnet/runtimelab#2046]
System.NotSupportedException: Metadata for type 'Newtonsoft.Json.Linq.JObject' was not provided by TypeInfoResolver of type '.aot.MyJsonContext'. If using source generation, ensure that all root types passed to the serializer have been indicated with 'JsonSerializableAttribute', along with any types that might be serialized polymorphically.
         at System.Text.Json.ThrowHelper.ThrowNotSupportedException_NoMetadataForType(Type type, IJsonTypeInfoResolver resolver)
         at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Bo

WEB API 
```
        [HttpPost("TEST")]
 
        public String TEST(String id, String userid,String username, JObject param, String? remark = "")

        {}

```

**Comment by jkotas** [comment]
This error is not native AOT specific. You should see the same error when you use System.Text.Json source generators without native AOT as well. Issues like that are best reported in https://github.com/dotnet/runtime under `area-System.Text.Json`.

Also, please make sure to provide complete repro steps for the problem.
