### ISSUE TITLE
Question: NativeAOT-LLVM: DateTime alignment for wasm32.  4 or 8 ?

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#2055]
There is a disconnect between the clrjit module and the IL module for the alignment of `DateTime`.  The IL module (as it uses the wrapped primitive for these types of single primitive structs) aligns the `ulong _dateData` at 8 by virtue of 

https://github.com/dotnet/runtimelab/blob/3b24124c8e6aab49a59b629b2d28de74b29c7f94/src/coreclr/tools/Common/TypeSystem/Common/TargetDetails.cs#L253-L256

`GetClassAlignmentRequirementStatic` when called for `DateTime` 

https://github.com/dotnet/runtimelab/blob/3b24124c8e6aab49a59b629b2d28de74b29c7f94/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs#L2045-L2071

returns 4 for wasm32 (pointer size ==4).  Should I not be calling `GetClassAlignmentRequirementStatic` for structs?  It doesn't seem to make sense that a struct that just contains an align 8 field should be allowed to be aligned at 4.

**Comment by jkotas** [comment]
`GetWellKnownTypeAlignment` returns alignment of field offsets for fields of given type.

`GetClassAlignmentRequirementStatic` returns required alignment of memory storage for given type.

**Comment by yowl** [comment]
Thanks, I see.
