### ISSUE TITLE
can  be Native AOT used as an analogue of obfuscation?

### ISSUE THREAD

**Issue by Divertisment** [dotnet/runtimelab#2062]
Most likely I misunderstood the general concept of your project. My dumb question is:
Can I use the generated native file HelloWorld.exe as an analogue of obfuscation and so that it runs without HelloWorld.dll which contains the original .Net code
![image](https://user-images.githubusercontent.com/5182065/198865803-c9f38b16-b144-45d6-8038-ef052de90e66.png)
![image](https://user-images.githubusercontent.com/5182065/198865820-de9bcd22-22f7-4e7e-a848-6e40a04f1bd6.png)

**Comment by jkotas** [comment]
Yes, native file HelloWorld.exe runs without HelloWorld.dll which contains the original .Net code.

Note that the NativeAOT project is not maintained in runtimelab repo anymore. It was moved to dotnet/runtime.

**Comment by Divertisment** [comment]
> Note that the NativeAOT project is not maintained in runtimelab repo anymore. It was moved to dotnet/runtime.

Ok sorry. I will ask questions there.
Thanks, I already figured it out and my test application started without the .net Dll. Great technology - well done
