### ISSUE TITLE
[NativeAOT-LLVM] Split RyuJit backend code into different files

### ISSUE THREAD

**Issue by SingleAccretion** [dotnet/runtimelab#2072]
As the NativeAOT-LLVM's RyuJit backend grows, it will eventually become untenable for all of the code to live in one `llvm.cpp` file. I propose to split the code in the somewhat near future, to avoid having to do that down the road, when there will be more of it.

The proposed changes (and file names) are modeled against similar files for non-WASM backends:
1) General-purpose utilities specific to LLVM-based compilation (e. g. "does this local need to exist on the shadow stack"): stay in `llvm.cpp`, in the `Llvm` class (as it exists today).
2) Things related to the type system (type descriptors, field descriptors, `XYZtoLLVMtype` methods): move to `llvmtypes.cpp`, (but stay part of the `Llvm` class, possibly as `static` methods)
3) Lowering: `lowerllvm.cpp`, in a new `LowerLlvm` class.
4) Codegen: `codegenllvm.cpp`, in a new `CodegenLlvm` class.

I think it is reasonable for the header file to remain singular (i. e. `llvm.h`) for now (it will be straightforward to split it in the future if needed).

Also, it could be better to name lower/codegen files `llvmlower.cpp`/`llvmcodegen.cpp`, so that everything shares a common prefix (I don't have a strong opinion on this).

@yowl thoughts? I will do this if you agree it is a good idea (which it may not necessarily be, considering the risk of conflicts etc).

**Comment by yowl** [comment]
I like this.  Prefix of `llvm` for the files would be my preference.

**Comment by SingleAccretion** [comment]
I will consider this done for now. Initially I wanted to split lowering and codegen into different classes, but will defer that for the time being. Doing it will not be as disruptive as moving code across files.
