### ISSUE TITLE
Is AOT compatible with WPF?

### ISSUE THREAD

**Issue by ComptonAlvaro** [dotnet/runtimelab#2076]
I a trying to compile a blank WPF project in .NET 7 enabling publish AOT in the project file but I get this error: error NETSDK1168: WPF is not supported or recommended with trimming enabled.

I don't enabled trim, but I guess it is enabled if I use AOT.

So I would like to know, if it is possible to use WPF with AOT. If not, could I get the benefits of AOT if I enable it in the libraries that are used by my WPF project?

Thanks.

**Comment by jkotas** [comment]
WPF is not supported with `PublishAot=true` in .NET 7.

WPF is only supported with `PublishReadyToRun=true`.

**Comment by jkotas** [comment]
The NativeAOT project was moved to dotnet/runtime repo that is the right place to ask questions like this.
