### ISSUE TITLE
Resetting history for feature/NativeAOT branch

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtimelab#2083]
When NativeAOT was getting integrated into runtime repo `main`, we were in a state for a while where runtime repo wasn't able to generate NativeAOT packages. During this time, I did integrations from `main` to `feature/NativeAOT`.

But the problem with that is that `main` reset all the history for the files, and after integrating things back here, we lost the history too (git UI shows the file originated in runtime repo `main`).

I'd like to reset feature/NativeAOT to just before #1779 (i.e. commit 4e5aed96a9494f96ca04e3e216766d0b319b4392) so that the branch can be used for code archeology. Code archeology for NativeAOT is already complicated enough without this extra hurdle because it spans dotnet/corert, dotnet/llilc, dotnet/runtimelab and now dotnet/runtime.

@yowl - the commits I would like to rebase away bridge the change from runtimelab to runtime. I think they would help bridge the feature/NativeAOT-LLVM branch to runtime repo main integration (i.e. you'd be better off integrating feature/NativeAOT before integrating main), in theory. If we're to reset the branch, it might be good to save it someplace else for the catchup integration.

Cc @dotnet/ilc-contrib for opinions about doing this

**Comment by jkotas** [comment]
I would avoid resetting history. Resetting history creates problems and confusion in forks.

To give a convenient name to commit https://github.com/dotnet/runtimelab/commit/4e5aed96a9494f96ca04e3e216766d0b319b4392, can we create a git tag or a new branch (like feature/NativeAOT-final) at this commit instead?

**Comment by MichalStrehovsky** [comment]
Makes sense!

Made a tag for this: https://github.com/dotnet/runtimelab/tags
