### ISSUE TITLE
[NativeAOT-LLVM] Remove the workaround for `CalendarData.EnumCalendarInfo`

### ISSUE THREAD

**Issue by SingleAccretion** [dotnet/runtimelab#2095]
The functions need real implementations. Opening an issue for tracking purposes.

Code references:

https://github.com/dotnet/runtimelab/blob/8284a6d8d46866f25f1ed605a9c4b6ac579a844c/src/coreclr/tools/Common/TypeSystem/IL/ILImporter.cs#L953-L969

https://github.com/dotnet/runtimelab/blob/8284a6d8d46866f25f1ed605a9c4b6ac579a844c/src/coreclr/jit/llvmcodegen.cpp#L23-L32

**Comment by SingleAccretion** [comment]
I am working on #2165 and the last warning to be dealt with is the missing symbol for `dotnet_browser_entropy`, which is referenced by System.Native now. I see two possible solutions:

1\) Properly plumb the JS through our build and use it.
2\) Add another workaround (either in compiler or System.Native) to silence the warning.

I like doing `1` now more because:
a\) It means we get properly working random data.
b\) The concern that we'll tie ourselves to JS-providing WASM hosts seems to no longer be as relevant, as [upstream is adding support for WASI builds directly into System.Native](https://github.com/dotnet/runtime/pull/79046), so, presumably, we'll be able to pick that up as well.

@yowl what do you think?

**Comment by yowl** [comment]
Yes, makes sense, i.e. point 1
