### ISSUE TITLE
Question: NativeAOT-LLVM: artifacts\bin\coreclr\windows.x64.Debug\IL and System.Private.CoreLib.dll

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#2097]
Hi,

I'm merging the last commits from NativeAOT and I have a question about this location and file.  At 

https://github.com/dotnet/runtimelab/blob/04b092003db5ba207d4fa3f3becb7f01828bf16c/src/libraries/externals.csproj#L92

I'm hitting this error because `artifacts\bin\coreclr\Browser.wasm.Debug\IL` is empty (no doubt its some merge/variable change issue that I've not found yet).  But what is the difference between the `System.Private.CoreLib.dll` that is put here and the one in `artifacts\bin\coreclr\Browser.wasm.Debug\aotsdk`  ?

**Comment by SingleAccretion** [comment]
In the ordinary CoreCLR build, CoreLib under `IL` is a purely managed assembly (no native code in it), while the CoreLib put under `artifacts\bin\coreclr\$OS.$Arch.Debug` contains R2R (native) code in it.

Conceptually, the steps are:
1) Build CoreLib with Roslyn, put it under `IL`.
2) CG-en it, put the result under `artifacts\bin\coreclr\$OS.$Arch.Debug`.

Not sure what do we do for platforms without CG-en, presumably we just put the IL version straight away.

Edit: and I think the CoreLib in `aotsdk` is the IL version, though it doesn't really matter. It's the CoreLib for the target platform.

**Comment by jkotas** [comment]
`aotsdk` has CoreLib used by native AOT. 
`coreclr\$OS.$Arch.$Configuration\IL` has CoreLib used by CoreCLR.
`coreclr\$OS.$Arch.$Configuration` has CoreLib used by CoreCLR, aot compiled using `R2R`.

**Comment by yowl** [comment]
Thanks!
