### ISSUE TITLE
NativeAot-LLVM: problem with NarrowFourUtf16CharsToAsciiAndWriteToBuffer

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#2114]
I don't know why this is coming up now, but in trying to compile this method in release config

https://github.com/dotnet/runtimelab/blob/6553dc0ffe33f4908fa1ab7ae5ac11683df7b2f0/src/libraries/System.Private.CoreLib/src/System/Text/ASCIIUtility.cs#L1129

The IR before LLVM starts:

```c#
*************** Finishing PHASE Rationalize IR
Trees after Rationalize IR

-----------------------------------------------------------------------------------------------------------------------------------------
BBnum BBid ref try hnd preds           weight    lp [IL range]     [jump]      [EH region]         [flags]
-----------------------------------------------------------------------------------------------------------------------------------------
BB01 [0000]  1                             1       [000..095)        (return)                     i LIR
-----------------------------------------------------------------------------------------------------------------------------------------

------------ BB01 [000..095) (return), preds={} succs={}
N001 (  1,  1) [000009] ------------         t9 =    LCL_VAR   byref  V00 arg0         u:1 $80
N003 (  1,  1) [000010] ------------        t10 =    LCL_VAR   long   V01 arg1         u:1 $c0
                                                  /--*  t9     byref
                                                  +--*  t10    long
               [000066] -A-XG-------              *  STOREIND  byte
```

Looking at the c# I guess the first `if`s are optimised away and this is
```c#
outputBuffer = (byte)value;
```
This is failing in `consumeValue`.   The node is `TYP_LONG` and the `targetLlvmType` is `i8`.  We can't handle this "cast" and we assert.  Any thoughts about what we should be doing about this?

Thanks,

cc @SingleAccretion

**Comment by SingleAccretion** [comment]
There should be a special case in `STOREIND` codegen to handle this invalid-ish IR. It will go away once we merge enough of upstream (the problematic transform has been rewritten a few months ago).
