### ISSUE TITLE
Question: NativeAOT-LLVM: how to do cross testing without CLRTest.NativeAot.targets

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#2142]
After 87777b624b0b8ea295b0fe9cd8505ce262ed75c0 where `CLRTest.NativeAot.targets` is removed, how do we set up tests for browser/wasm given that the build integration is from `CoreCLRBuildIntegrationDir`, set in `liveBuilds.targets` from 

```
<CoreCLRBuildIntegrationDir>$([MSBuild]::NormalizeDirectory('$(CoreCLRArtifactsPath)', 'build'))</CoreCLRBuildIntegrationDir>
```

Thanks

**Comment by jkotas** [comment]
@MichalStrehovsky ?

**Comment by MichalStrehovsky** [comment]
The commit changes the way the tests are built so that they build as part of the test tree build (previously, the build happened in the batch file as part of test execution).

The `BuildNativeAot` target in src/tests/Directory.Build.targets should be doing that. I would expect this to "just work" for WASM as well. What isn't working? Can you share the logs from `artifacts\log` (maybe delete that directory first before you run `src\tests\build.cmd` so that you only have the relevant binlogs there).

If the build works and the problem is with test execution, I expect we might need to tweak src/tests/Common/scripts/nativeaottest.cmd which controls how the test is executed. I assume we'll need to add whatever WASM interpreter is used for testing.

**Comment by yowl** [comment]
For 
```
src\tests\build nativeaot debug wasm skipnative tree nativeaot /p:LibrariesConfiguration=Debug
```
I get
```
E:\GitHub\runtimelab2\src\tests\Directory.Build.targets(478,3): error MSB4019:
 The imported project "E:\GitHub\runtimelab2\artifacts\bin\coreclr\Browser.wasm.Debug\build\Microsoft.NETCore.Native.targets" was not found. Confirm that the expression in the Import declaration 
"E:\GitHub\runtimelab2\artifacts\bin\coreclr\Browser.wasm.Debug\build\Microsoft.NETCore.Native.targets" is correct, and that the file exists on disk. [E:\GitHub\runtimelab2\src\tests\build.proj]
```
Line 478 is 
```
 <Import Project="$(CoreCLRBuildIntegrationDir)Microsoft.NETCore.Native.targets" Condition="'$(TestBuildMode)' == 'nativeaot'" />
```

Because there is no `build` artifact folder under the `coreclr\Browser.wasm.Debug` folder.  For wasm the subsets `nativeaot+libs` are built, and previously `Microsoft.NETCore.Native.targets` would be used, as you point out, at the "run" step and taken from `IlcPath` (in turn set from `CORE_ROOT` I think).

**Comment by yowl** [comment]
Logs:
[log.zip](https://github.com/dotnet/runtimelab/files/10305195/log.zip)

**Comment by yowl** [comment]
I've tried forcing 
```
   <CoreCLRArtifactsPath>$([MSBuild]::NormalizeDirectory('$(RepoRoot)', 'artifacts', 'bin', 'coreclr', 'windows.x64.Debug'))</CoreCLRArtifactsPath>
```
But of course that brings the coreclr aotsdk files (e.g. `E:\GitHub\runtimelab2\artifacts\bin\coreclr\windows.x64.Debug\aotsdk\System.Private.CoreLib.dll`) from `windows.x64.Debug` as well.

**Comment by MichalStrehovsky** [comment]
The `build` directory gets binplaced from `src\coreclr\nativeaot\BuildIntegration\BuildIntegration.proj`. We need to make sure that project is included when building for WASM.

**Comment by yowl** [comment]
I see, so I'll build `BuildIntegration.proj`, and that will require `ILCompiler.Build.Tasks.csproj`, `ILCompiler.csproj` and the wasm clrjit, but setting the RID to the host to avoid

```
E:\GitHub\runtimelab2\.dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(129,5): error NETSDK1084: There is no application host available for the specified RuntimeIdentifier 'browser-wasm'. [E:\GitHub\runtimelab2\Build.proj]
```

**Comment by yowl** [comment]
or maybe I don't understand what is meant by "binplaced", should these artifacts just be copied from windows.x64.Debug ?

**Comment by yowl** [comment]
Thinking and playing a bit more, I will try just to set `IlcSdkPath` and `IlcToolsPath` in `tests\build.proj`

**Comment by yowl** [comment]
Will close, suggestions to the merge can be followed up in the PR https://github.com/dotnet/runtimelab/pull/2143

Thanks
