### ISSUE TITLE
How to store binary resources when reflection is off?

### ISSUE THREAD

**Issue by edward-a** [dotnet/runtimelab#2152]
Considering that Assembly.GetManifestResourceNames() is unavailable when reflection is off, is there a way to store binary resources in an assembly or library compiled with NativeAOT? I am specifically interested in reflection-less builds since it reduces the size and makes reverse engineering more difficult.

**Comment by jkotas** [comment]
If you would like to avoid dependency on manifest resources, you can embed binary data as ReadOnlySpan<byte> using C#. Here is example from dotnet/runtime repo: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Globalization/CharUnicodeInfoData.cs

NativeAOT project has been moved to dotnet/runtime repo. It is best to ask questions like this in dotnet/runtime repo.

**Comment by edward-a** [comment]
I tried the suggested method of storing binary resource as byte arrays in C# files. Apparently, this method is only suitable for small data. With something bigger it makes Visual Studio grind to a halt. E.g. storing a 2MB mp3 file make VS consume about 12GB of RAM. So, this issue is not resolved and needs to be re-opened.

**Comment by jkotas** [comment]
The reflection-free mode has been an experiment to demonstrate how far can reflection stripping get us. We do not plan to build full end-to-end experience around it.

https://github.com/dotnet/runtime/issues/67193 is the best place to continue this discussion.
