### ISSUE TITLE
NativeAOT-LLVM: packages not publishing

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#2153]
Sorry @jkotas, the packages are failing to publish again:

![image](https://user-images.githubusercontent.com/2720041/211029723-ba216fa7-1e4b-41cd-916e-fdf761edc88d.png)

Would you mind having a look at the logs please?

**Comment by jkotas** [comment]
It fails with `/eng/common/templates/post-build/post-build.yml: (Line: 135, Col: 13, Idx: 4260) - (Line: 135, Col: 13, Idx: 4260): While scanning a simple key, could not find expected ':'.`

The problem was introduced by #2136

**Comment by yowl** [comment]
Thanks, I missed that conflict.  Will put it into the next merge #2143

**Comment by yowl** [comment]
Thanks @jkotas , this is publishing now.
