### ISSUE TITLE
NativeAOT-LLVM: Ilc is crashing on some input

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#2174]
Trying Ilc on larger input is resulting in 

![image](https://user-images.githubusercontent.com/2720041/213005655-10f4456c-4456-414b-a3a8-78e89e530eb8.png)

Don't have more to share at this point unfortunately. But on the surface it looks like a test with Regex matching might be prudent.

**Comment by SingleAccretion** [comment]
The error itself means we don't have the symbol defined when we are about to process its reference. I actually see this on a basically daily basis with a single-method compilation I am using for testing, it is always missing something related to dynamic invoke. Haven't invested the time to investigate it yet, though.

**Comment by yowl** [comment]
This might be related to the user compiling the c# with sdk 7.0.102 which might be producing some IL we can't handle.  I did try installing that SDK, but could no longer compile nativeaot-llvm.  Might be easier to just merge forward some more until the problem goes away or appears in our tests.

**Comment by yowl** [comment]
Going to close this as I don't have the means to replicate with the latest packages, and lots has changed.
