### ISSUE TITLE
[NativeAOT-LLVM] PI-related issues

### ISSUE THREAD

**Issue by SingleAccretion** [dotnet/runtimelab#2190]
We need to implement PI for WASM, there are two issues:

1) LLVM doesn't support lowering its aggregate types using C ABI rules, thus we need to lower them ourselves. The scheme would likely involve taking advantage of the frontend-provided handling for argument morphing.
2) We need to support wrong PI declarations, i. e. we need to be able to compile the following:
```cs
private static double Problem(int arg)
{
    [DllImport("*", EntryPoint = "__pinvoke")]
    static extern double __pinvoke1(double a, long b);
    [DllImport("*", EntryPoint = "__pinvoke")]
    static extern long __pinvoke2(long a, double b);

    switch (arg)
    {
        case 1:
            return __pinvoke1(1, 1);
        case 2:
            return __pinvoke2(2, 2);
        default:
            return 1;
    }
}
```
And have it work correctly at compile time and runtime when:
1) The ultimate definition of `__pinvoke` matches `__pinvoke1` and `arg` equals `1`.
2) The ultimate definition of `__pinvoke` matches `__pinvoke2` and `arg` equals `2`.
3) The ultimate definition of `__pinvoke` doesn't match either `__pinvoke1` or `__pinvoke2` but `arg` never equals `1` or `2`.

This implies we cannot emit direct calls to any PI methods as they could be using the wrong definition and that would fail at compile time (as invalid LLVM IR).

We cannot emit "naive" indirect calls like the IL backend does today either, because LLVM's WASM lowering contains a [pass](https://github.com/llvm/llvm-project/blob/main/llvm/lib/Target/WebAssembly/WebAssemblyFixFunctionBitcasts.cpp) which legalizes such calls by creating trapping stubs for all references save those matching the declaration. We cannot let LLVM create the stub for any single reference as we do not know which will be the correct one at runtime.

We therefore need to wrap the PI symbol reference into something that will force LLVM to emit a `call_indirect` in WASM, e. g. a volatile load from a global initialized with the function's address.

**Comment by jkotas** [comment]
> We need to support wrong PI declarations

Do these wrong PI declarations exist in something we care about? I am wondering whether it would be better to not support them, for now at last.

**Comment by SingleAccretion** [comment]
> Do these wrong PI declarations exist in something we care about?

Nothing that I would know, though that is a weak assertion as I haven't really looked.

> I am wondering whether it would be better to not support them, for now at last.

The way the requirement is, we need to do something about it to not emit invalid LLVM straight away. But then if we go with the "naive" approach:
1) The failure mode becomes dependent on compilation order, i. e. the first PI declaration the compiler sees "wins".
2) LLVM-generated stubs do things like add/drop arguments, so instead of a simple "function signature mismatch" runtime error, users will get undefined behavior. More importantly, combined with `1`, it means that they may get broken functionality even if their PI declaration was correct.

The last point really makes it a non-starter to not support this I think. I wouldn't expect significant implementation complexity here, though performance/size will suffer if we really will need to use volatile loads/stores.
