### ISSUE TITLE
NativeAOT-LLVM: Question var_type for shadowstack

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#2194]
With the removal of `PUTARG_TYP` we are losing this code that creates the shadowstack arg when lowering a call:

```
GenTreePutArgType* calleeShadowStackPutArg =
    _compiler->gtNewPutArgType(calleeShadowStack, CORINFO_TYPE_PTR, NO_CLASS_HANDLE);
```
This sets the type to `CORINFO_TYPE_PTR` which gets us a `*` arg in LLVM.  Without this we have normally the result of a `GT_ADD` for the shadowstack arg, which is `TYP_INT`/`TYP_I_IMPL` which gives us in LLVM an `i32` and hence we end up with problems matching signatures.  

I had initially a couple of thoughts

- Change the local for shadowstack (and probably the return slot) to `TYP_REF`
- or, add a `GT_BITCAST` after calculating shadowstack when lowering a call and add handling in the codegen for int->ptr to use LLVMs `inttoptr` instruction.

Neither seem great, any better ideas?

**Comment by SingleAccretion** [comment]
I would expect us to retain the ability to have pointers in signatures, by storing CorInfoType in the CallArg.
