### ISSUE TITLE
For Alpine and Void-Linux: If you use linux-musl-x64 for dotnet publish

### ISSUE THREAD

**Issue by DeafMan1983** [dotnet/runtimelab#2202]
Hello everyone, 

I made own embedded xcb libraries into static executable without dynamic libraries *.so :)

If you make sure directinvoke -> __Internal
example:
```
internal const string directinvoke = "__Internal";
[DllImport(directinvoke)]
private static extern nint* xcbsharp_connect(string display_name, int* screen_number);
```
I will write in xcbsharp.cpp:
```
/*
    standard std libraries
*/
#include <stdio.h>

/*
    XCB libraries
*/
#include <xcb/xcb.h>
...

/*
    statical methods as __Internal of DirectInvoke
    If you use musl-libc
    musl-gcc -static -c xcbsharp.cpp -lxcb -lXau -lXdmcp -fPIC -o libxcbsharp.o
    ar r libxcbsharp.a libxcbsharp.o
*/

extern "C"
{
    xcb_connection_t *xcbsharp_connect(const char *display_name, int* screen_number)
    {
        return xcb_connect(display_name, screen_number);
    }

    ....
}
```
Copy "libxcbsharp.a to root directory of Console-Project like XCBTest for example
Edit your-console-project.csproj
```
  <ItemGroup>
    <DirectPInvoke Include="__Internal" />
    <NativeLibrary Include="libxcbsharp.a" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.DotNet.ILCompiler; runtime.linux-musl-x64.Microsoft.DotNet.ILCompiler" Version="7.0.3" />
  </ItemGroup>
```
dotnet publish -c Release -r linux-musl-x64
Wait until error message after "Generating native code"
and copy whole ""clang" ..."
and replace "clang" with "musl-gcc -static" and remove "-pie" and add before removed "-pie" -lxcb -lXau -Xdmcp ( Just find "-lrt" and add there ) and prompt again and check with "ldd" then it happens:
`Not a valid dynamic program`

Oh beautifully! Run native executable, compiled by "musl-gcc -static ...." And I have tested move to Ubuntu 22.04 It works fine like charm :)
![image](https://user-images.githubusercontent.com/57066679/220766767-7512443e-4875-40c8-ba1f-7d24296ebe10.png)
That is proof because I have tried to run static single executable from dotnet native aot.

**Note:**
_I will upload for repository for next time._ 

For Alpine and Void-Linux should use musl-gcc and how do I add -l(libraries) If you want embed any static libraries without load any dynamical libraries (*.so)

I hope you find my great idea.

Enjoy your happy compiling & testing to other linux with higher or lower versions of glibc!

EDIT:
Bonus tips. If you want smaller than normal static dotnet native-aot executable then you can use upx with it.
`upx --best XCBTest-musl-small`
And run again like charm :)

**Comment by jkotas** [comment]
It is great to hear that you are finding native AOT form factor useful, and you are able to do cool things with it!

The native AOT project moved to dotnet/runtime repo. dotnet/runtime repo is a better place for discussions about native AOT in general.

**Comment by DeafMan1983** [comment]
Ok, thank you for moving to dotnet/runtime. I will respect your decision.
