### ISSUE TITLE
Question: NativeAOT-LLVM: no spill to shadowstack for GT_IND?

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#2207]
In the latest merge that I'm working through, its nearly passing, but I have one failure in release config with `HelloWasm` `StackEntriesLiveAcrossSafePointsGetScannedInner`:

```cs
[MethodImpl(MethodImplOptions.NoInlining)]
private static bool StackEntriesLiveAcrossSafePointsGetScannedInner<T>(ClassWithFields obj)
{
    return ObjRefsAreEqual(obj.Obj, TriggerObjRelocation(), obj.Obj);
}
```

This ensures that `obj.Obj` is not moved as part of `TriggerObjRelocation` and is failing.  The full dump is attached.
[EGitHubruntimelabartifactsbincoreclrwindows.x64.Debugilcnet7.0ilc.exe.txt](https://github.com/dotnet/runtimelab/files/10827869/EGitHubruntimelabartifactsbincoreclrwindows.x64.Debugilcnet7.0ilc.exe.txt)

In particular 
```cs
                                                             /--*  t11    byref
N004 (  6,  5) [000001] ---XG------                    t1 = *  IND       ref    <l:$1c3, c:$1c2>
```
This is loading the first `obj.Obj` and it is not spilled to the shadowstack .  There's no local for it so how is that meant to work? It's a while since I did any actual coding in the clrjit backend, so maybe I've just forgotten something obvious.

**Comment by SingleAccretion** [comment]
It's a GC hole we'll have to fix (by spilling temporaries live across safe points to the shadow stack).

I would recommend disabling this particular test to unblock the merging; we can fix it separately (the fix is not simple).

**Comment by yowl** [comment]
Thanks
