### ISSUE TITLE
NativeAOT-LLVM: Question: creating LLVM RhpNewArrayAlign8 signature from CORINFO_SIG_INFO

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#2239]
I'm having an issue with the latest merge from runtime.  The LLVM function for `RhpNewArrayAlign8 ` is being created while compiling `S_P_CoreLib_System_Runtime_RuntimeExports__RhGetRuntimeHelperForType` and this 
```
t36 =    CNS_INT(h) int    0x435FE8 ftn
```
So it goes through 
https://github.com/dotnet/runtimelab/blob/db747bf34cc2e45aaec8acb87fe41bab16d9a16b/src/coreclr/jit/llvmcodegen.cpp#L2815

Where it finds the method, the signature does not have any of `UnmanagedCallingConventionMask` set and ends up `CORINFO_CALLCONV_DEFAULT` .  It then goes on to add LLVM args for a shadow stack and return address and fails generating the call as that should be something like
```
%26 = call ptr @RhpNewArrayAlign8(ptr @"__MethodTable___Array<S_P_CoreLib_System_Globalization_UmAlQuraCalendar_DateMapping>", i32 %24)
```
i.e. just 2 args.

Where is this process going wrong?

N.B.  Previous to the merge `RhpNewArrayAlign8` is created via `consumeCallTarget` where it does not use the signature but the `GenTreeCall* call` to generate the LLVM function signature.

Thanks,

**Comment by jkotas** [comment]
cc @SingleAccretion

**Comment by SingleAccretion** [comment]
This should now be fixed - the problem was that `GetSignatureForMethodSymbol` didn't account for the fact runtime imports have an unmanaged calling convention.

**Comment by yowl** [comment]
Thanks, I see the change now.
