### ISSUE TITLE
[NativeAOT-LLVM] Implement finalization

### ISSUE THREAD

**Issue by SingleAccretion** [dotnet/runtimelab#2240]
Currently, finalization does not work on WASM as we cannot use the finalizer thread mechanism.

In principle, it should be possible to run the finalizers synchronously, on the same thread that started the GC. In practice, a naive implementation will result in a deadlock because `RhEnableFinalization` is called before the "more space lock" is released by the GC on some code paths (`gc_heap::allocate`). Presumably, this is the same reason GC stress is disabled on the finalizer thread.

Still looking for a place to thread things through...

**Comment by jkotas** [comment]
> it should be possible to run the finalizers synchronously, on the same thread that started the GC. 

Is it what Mono does currently?

**Comment by SingleAccretion** [comment]
> Is it what Mono does currently?

I looked and it is not. Mono schedules the finalizers to be run on a small queue with [setTimeout](https://developer.mozilla.org/en-US/docs/Web/API/setTimeout), with the delay parameter set to zero, along with a number of other "background" tasks.

**Comment by jkotas** [comment]
I think it is the only way to it reliably. It is risky to start running finalizers on a thread in arbitrary state. For example, the thread may be in the middle of updating a datastructure that the finalizer will try to access as well. It will result either into a deadlock or a data corruption.

**Comment by SingleAccretion** [comment]
> I think it is the only way to it reliably. It is risky to start running finalizers on a thread in arbitrary state. For example, the thread may be in the middle of updating a datastructure that the finalizer will try to access as well. It will result either into a deadlock or a data corruption.

Well, I am not sure how the event loop-driven scheme would ameliorate this issue. Canonically, control would yield to the event loop (and these "background" tasks would run) when code hits an `await` suspension point.

The problem with `setTimeout` is that it is not portable to synchronous code, where we don't yield to the event loop. This is the case for WASI and a certain subset of code one could write for NodeJS-like environments.

I am considering pulsing the finalizer queue on the exit of the slow path to allocation helpers right now.

**Comment by pavelsavara** [comment]
To make the runtime useful in browser, most of interop with JavaScript requires that you don't block the browser's event loop.
That is, in order to run any UI or make HTTP and WebSocket requests, you have to `yield` somehow from your `Task` queue.

I my opinion finalizer is "small fish" compared to those problems.
