### ISSUE TITLE
Hello World does not create a native .exe

### ISSUE THREAD

**Issue by BurgerBob** [dotnet/runtimelab#2241]
Hello,

It drives me a little bit crazy, I have used NativeAOT before, shipped a game with it, no problems.
And now, I can not manage to create an executable by following the steps of the Hello World wiki page.

It is like NativeAOT is not there.
Here is the project, with the bin folder generated included:
[https://1drv.ms/u/s!AlowO7RRIiAinhaRC5VBOapI13hO?e=dVE1fg](url) 

I hope someone can figure it out ...

![image](https://user-images.githubusercontent.com/4925468/228536847-c6922819-dbea-448c-86b2-971edc5c2284.png)

**Comment by jkotas** [comment]
The native AOT project moved to dotnet/runtime repo and it is shipping with standard .NET SDK. You example uses the old experimental bits that no longer work with new .NET SDK.

https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/ has the up-to-date instructions.

**Comment by BurgerBob** [comment]
That's great, thanks a lot :) :)
Maybe updating the pages that have outdated instructions with this link would help other people :)
