### ISSUE TITLE
NativeAOT-LLVM : merge broke the package publishing

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#2242]
Looks like the last merge broke the publishing.  I did try 
```
build nativeaot.packages -c release
build nativeaot.packages -a wasm -os Browser -c release
```

locally and they are ok.

@jkotas when you get a spare moment if you can see what the error is?

Thanks,

cc @dotnet/nativeaot-llvm 

![image](https://user-images.githubusercontent.com/2720041/229305290-30dc6795-a804-4631-bc7d-24fea87d61b2.png)

**Comment by yowl** [comment]
Maybe the pool change to `DncEngInternalBuildPool` ?

**Comment by jkotas** [comment]
These are the errors:

![image](https://user-images.githubusercontent.com/6668460/229418794-596d538e-e33b-4c3d-b686-5ecba19310d6.png)

It is failing very early (in less than 1 second) when importing the build definition. Does it ring any bells?

**Comment by yowl** [comment]
That looks like its running a job that should have `buildConfig` but doesnt because I assume the name is from
```
name: ${{ format('installer_{0}_{1}_{2}_{3}_{4}_', parameters.pgoType, parameters.runtimeFlavor, parameters.runtimeVariant, coalesce(parameters.name, parameters.platform), parameters.buildConfig) }}
```
So yes, I did have some problem with the `buildConfig` for the tests, it might be related - will investigate.

Thanks.

**Comment by jkotas** [comment]
Still failing with the exact same error

**Comment by yowl** [comment]
Looks more promising

![image](https://user-images.githubusercontent.com/2720041/230635902-aed6a738-bfe7-48f9-bb95-b308ce13af7e.png)

**Comment by yowl** [comment]
Thanks!
