### ISSUE TITLE
Question: NativeAOT-LLVM: IsRuntimeExport

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#2251]
`MethodDesc.IsRuntimeExport` has gone upstream, we have this code:

```cs
public static void EmitObject(string objectFilePath, IEnumerable<DependencyNode> nodes, LLVMCodegenCompilation compilation, IObjectDumper dumper)
{
    LLVMObjectWriter objectWriter = new LLVMObjectWriter(objectFilePath, compilation);
    NodeFactory factory = compilation.NodeFactory;

    bool succeeded = false;
    try
    {
        foreach (DependencyNode depNode in nodes)
        {
            if (depNode is LLVMMethodCodeNode { Method: { IsRuntimeExport: true } } runtimeExportNode)
            {
                objectWriter.EmitRuntimeExportThunk(runtimeExportNode);
                continue;
            }
```
in `LLVMObjectWriter` which used to use `IsRuntimeExport`.  What would be the new way to detect if we need to emit the export thunks?

cc @MichalStrehovsky  as I believe you might know?

Thanks

**Comment by jkotas** [comment]
You can call `method.HasCustomAttribute("System.Runtime", "RuntimeExportAttribute")` instead.

`IsRuntimeExport` property used to cache the result of the lookup, but the cache was unnecessary and that's why it was deleted.

**Comment by yowl** [comment]
Thanks!
