### ISSUE TITLE
NativeAOT-LLVM: reinstate PHASE_EXPAND_STATIC_INIT

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#2257]
Expanding static initializer is currently failing at runtime.  We should investigate and fix to get this benefit.

Some notes with the failing LLVM are in #2255

**Comment by SingleAccretion** [comment]
Note: https://github.com/dotnet/runtime/pull/86147.

**Comment by yowl** [comment]
This is resolved by #2271
