### ISSUE TITLE
NativeAOT-LLVM: export for NativeAOT_StaticInitialization automatically

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#2259]
We should probably do this automatically if the user specifies `/p:NativeLib=Static` as you cant do much without it.

I.e. to the linker command add 
```
-s EXPORTED_FUNCTIONS=_NativeAOT_StaticInitialization
```
Follows #2258

**Comment by SingleAccretion** [comment]
Probably just update this line to `$(NativeLib) != ''`:
https://github.com/dotnet/runtimelab/blob/cd6f3ffcabe63f7a9ce2cb9f47e7dead2ad538c8/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.targets#L437

**Comment by yowl** [comment]
Yes, that works, thanks

**Comment by RReverser** [comment]
Or maybe better to change `NativeLib` to `Shared` in that project?

**Comment by yowl** [comment]
The change will allow either.  I guess shared is the correct option as we are not linking the wasm library with anything at link time.

**Comment by RReverser** [comment]
> The change will allow either. I guess shared is the correct option as we are not linking the wasm library with anything at link time.

Yeah I remember that's what I was told in the original PR (or one of the related discussions, don't remember where exactly), so I explicitly enabled it only for `Shared`.

I think it could be nice to reserve `Static` for potentially actual static libraries built for Wasm.

**Comment by yowl** [comment]
WIll close this as we updated the documentation to reflect that `EXPORTED_FUNCTIONS=_NativeAOT_StaticInitialization` was not actually necessary.
