### ISSUE TITLE
Marshaling from (U)IntPtr to Sys(U)Int should be blittable

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/runtimelab#226]
It looks so. Is it intentionally not to do so?

**Comment by jkotas** [comment]
Could you please provide a code snippet demonstrating the problem?

**Comment by huoyaoyuan** [comment]
`System.Runtime.InteropServices.UnmanagedType` has members `SysInt` and `SysUInt` since .NET 1.0.

https://github.com/dotnet/runtimelab/blob/2d7dc69d0181a4333df005890f882f6dd50ec057/DllImportGenerator/DllImportGenerator/Marshalling/MarshallingGenerator.cs#L87-L98

Here specifies marshaling for using identical `UnmanagedType`. I think this should also be applied to `SysInt`/`SysUInt`.

**Comment by jkotas** [comment]
cc @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
@huoyaoyuan Thanks for filing this issue. We are still very early in this process and far from done so there are still gaps in the generator. The current focus for the work is supporting the needs of the `NetCoreApp` framework. If `NetCoreApp` doesn't need it the scenario may not be included or tested so holes may exist. Once `NetCoreApp` needs have been satisfied we will start exploring more of the matrix.

/cc @jkoritzinsky @elinor-fung

**Comment by jkoritzinsky** [comment]
Fixed by #1043
