### ISSUE TITLE
[AOT]LINK : fatal error LNK1123: 转换到 COFF 期间失败: 文件无效或损坏 [

### ISSUE THREAD

**Issue by lozn00** [dotnet/runtimelab#2281]
![image](https://github.com/dotnet/runtimelab/assets/14260426/f5911d84-0f54-4384-a793-a30cc2bc2caa)

I TRY uninstall 7.0.5 but 7.0.302 for visual studio cannot to uninstall or replase  7.0.202 for visual studio

C:\Program Files\dotnet\sdk\7.0.302\Sdks\Microsoft.DotNet.ILCompiler\build\Microsoft.NETCore.Native.targets(350,5): err
or MSB3073: 命令“"D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x64\link.
exe" @"obj\YTLSX_R\net7.0\win-x64\native\link.rsp"”已退出，代码为 1123。 [D:\dev\company_project\WEB_webapi\webapi_mes\webap
i_mes.csproj]

![image](https://github.com/dotnet/runtimelab/assets/14260426/42b14282-2619-48a6-9cc5-b571c1842b88)

**Comment by lozn00** [comment]
if from visual studio uninstall ,will uninstall all package

**Comment by yowl** [comment]
Hi, this repo is for the experimental branches of NativeAOT.  It looks like you are targeting win-x64 which is now supported by https://github.com/dotnet/runtime  .  You should post issues with .net 7 NativeAOT there, thanks.

**Comment by lozn00** [comment]
oh thank you ,i delete too file

**Comment by lozn00** [comment]
Because there was a problem with the code running after AOT was compiled, I deleted many 7.0 folders on the computer and uninstalled it, resulting in this problem that cannot be fixed regardless of whether it is reinstalled or not.
