### ISSUE TITLE
Support for 32 bit application in NativeAOT

### ISSUE THREAD

**Issue by NCLnclNCL** [dotnet/runtimelab#2285]
Is there any plans to support 32 bit ? 
32 bit compiled apps run using less ram and cpu, it seems to be fast too, and I think should have LARGEADDRESSAWARE enabled by default to be able to use 4gb ram on 64 bit devices

**Comment by MichalStrehovsky** [comment]
You opened the same issue in dotnet/runtime#86570. Please don't open duplicate issues.
