### ISSUE TITLE
NativeAOT: 404 for the pre-requisites link.

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#233]
Pre-requisites links is a 404.  I thought it was just a path error, but I can't see the section in any .md file, hence I've not created a PR.  Should it be in the `README.md` at the same level as https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/docs/workflow/building/coreclr/nativeaot.md and a copy from the old repo ?

![image](https://user-images.githubusercontent.com/2720041/96171829-1f4a5280-0eeb-11eb-8a3f-f84d14cd2dba.png)

**Comment by jkotas** [comment]
The prerequisites are the same as for building the dotnet/runtime. I have fixed the link. Thanks for reporting it!
