### ISSUE TITLE
NativeAOT-LLVM: publishing stopped

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#2336]
Sorry @jkotas looks like the publishing stopped on Tuesday

![image](https://github.com/dotnet/runtimelab/assets/2720041/bf5ed42d-a2dc-4b6d-80c7-f99cc11c5da4)

Any log info?

Thanks

**Comment by jkotas** [comment]
The build for the latest merged PR was published successfully.

A few builds before that failed with:
```
Installing NodeJS
Invoke-WebRequest : The remote server returned an error: (500) Internal Server Error.
```

**Comment by yowl** [comment]
Thanks
