### ISSUE TITLE
Question: NativeAOT-LLVM: Native lib - what sets tls_CurrentThread

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#2347]
If we are building a shared nativelib as per the documentation at https://github.com/dotnet/runtimelab/blob/feature/NativeAOT-LLVM/docs/using-nativeaot/compiling.md, when `new` is called we make a call to `RhpGcAlloc` which uses `tls_CurrentThread`  but what should initialize that?

**Comment by SingleAccretion** [comment]
The main initialization should happen as part of the RPI that initiated the call into managed call, see `ThreadStore::AttachCurrentThread`.

**Comment by yowl** [comment]
I wonder if something is not initializing property in wasi as I'm getting odd errors there
```
    Finished dev [unoptimized + debuginfo] target(s) in 20.33s
     Running `C:\github\cs-runtime-example-wasmtime\target\debug\cs-runtime-example.exe`
thread 'main' panicked at 'execution of foo:foo/floats#float32-param failed error while executing at wasm backtrace:
    0: 0xfa1454 - <unknown>!abort
    1: 0xfec3 - <unknown>!Assert(char const*, char const*, unsigned int, char const*)
    2: 0x25206 - <unknown>!SList<Thread, DefaultSListTraits<Thread, DoNothingFailFastPolicy>>::Iterator::_Validate(SList<Thread, DefaultSListTraits<Thread, DoNothingFailFastPolicy>>::Iterator::e_ValidateOperation) const
    3: 0x23c35 - <unknown>!SList<Thread, DefaultSListTraits<Thread, DoNothingFailFastPolicy>>::Iterator::Insert(Thread*)
    4: 0x23a9e - <unknown>!SList<Thread, DefaultSListTraits<Thread, DoNothingFailFastPolicy>>::PushHead(Thread*)
    5: 0x2393c - <unknown>!ThreadStore::AttachCurrentThread(bool)
    6: 0x23d05 - <unknown>!ThreadStore::AttachCurrentThread()
    7: 0x1e67c - <unknown>!Thread::ReversePInvokeAttachOrTrapThread(ReversePInvokeFrame*)
    8: 0x1ead8 - <unknown>!RhpReversePInvokeAttachOrTrapThread2
    9: 0x1ed40 - <unknown>!RhpReversePInvoke
   10: 0xcf014b - <unknown>!cswasi_wit_the_world_ExportsInterop__wasmExportFloat32Param
   ```
I will investigate some more.

**Comment by SingleAccretion** [comment]
Perhaps the runtime initialization callback (`g_RuntimeInitializationCallback`) is missing and `EnsureRuntimeInitialized` is not doing what it is supposed to do (usually you would expect it to be present due to the `RhSetRuntimeInitializationCallback` that runs in a global C++ constructor context).

**Comment by yowl** [comment]
Yes, there's a bit of history with wasm components : 

https://github.com/bytecodealliance/preview2-prototyping/issues/99

**Comment by yowl** [comment]
Closing as I have a bit better understanding now.
