### ISSUE TITLE
NativeAOT-LLVM: Question: Interest in wit-bindgen for c#

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#2377]
Hi, Some time back in the ByteAlliance zulip chat there was mention of some interest from Microsoft in helping with the c# bindings for wit-bindgen https://bytecodealliance.zulipchat.com/#narrow/stream/327223-wit-bindgen/topic/C.23.20bindings.3F  from https://github.com/squillace principally @squillace.  Is there anything that Microsoft can share publically about whether they are still interested in getting involved?  In theory it need not be restricted to NativeAOT I suppose, but also work with Mono/interpreter.

Thanks

**Comment by jkotas** [comment]
@SteveSandersonMS @lewing Do you have any updates about C# support in wit-bindgen? 

(There was email thread about it in May that both of you are on, but it died for some reason.)

**Comment by jkotas** [comment]
cc @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
@yowl This is something I started to explore late last year but was pulled in another direction and subsequently fell off my radar. What can we do to help? Happy to dedicate time in this area if some experts are willing to help educate me :-)

**Comment by yowl** [comment]
@silesmo has a fork of https://github.com/bytecodealliance/wit-bindgen where the bindgen code is being created for C#.  This fork was focused initially on Mono, but is now being developed firstly on NativeAOT (really NativeAOT-LLVM as this is WebAssembly).  We (silesmo and I) have it (https://github.com/Nor2-io/wit-bindgen-yowl/tree/scott-wasmtime) to the point where the codegen for c# produces valid bindings for the simple numbers test (which is passing ints/longs/floats/doubles around), but there is work to do on more complex types., there are a lot of `todo!`s in https://github.com/Nor2-io/wit-bindgen-yowl/blob/scott-wasmtime/crates/csharp/src/lib.rs, the wit-bindgen is in Rust.

While we are developing for the NativeAOT runtime, I don't think we've done anything specific to that runtime, so this ought to work with Mono also, but I'm not an expert on that.

 Currently we are using a source code generator to invoke the wit-bindgen for csharp (https://github.com/Nor2-io/wit-bindgen-yowl/tree/scott-wasmtime/testing-csharp/WitSourceGen) to make the user experience as easy as Rust.

So, we wondered if you (Microsoft) would want to get involved in helping fill out the remaining functionality to make C# as viable a source language for Wasm Components as Rust.  @silesmo knows more about what we have currently in terms of codegen, I know more about NativeAOT-LLVM and can contribute changes there if required.  (I am also helping with the codegen, but I'm a bit slow there as I'm new to Rust).

**Comment by AaronRobinsonMSFT** [comment]
@yowl This looks like a great start. Yes I would be interested in helping. Feel free to tag me and point to places that might need some help.

> Currently we are using a source code generator to invoke the wit-bindgen for csharp

We should discuss this part. Appreciate what this is being used for, but it does sort of violate some Roslyn source generator principles. I can help engage with the experts to provide guidance.

**Comment by jaredpar** [comment]
> Currently we are using a source code generator to invoke the wit-bindgen for csharp

This falls outside of the actions that are allowed in source generators. If the runtime team provided an API by which we could prevent process related calls we would do so. This not only breaks the contracts of source generators, it breaks the contract of build correctness. MSBuild has no knowledge of this tool and will not account for it in it's up to date checks, dependencies, etc ... 

In short, this is not a supported scenario.

**Comment by jkotas** [comment]
> the codegen for c# produces valid bindings for the simple numbers test

This is great progress! Have you thought about the best strategy to upstream the work eventually? Do wit-bindgen maintainers prefer smaller PRs for intermediate milestones or one very large PR with the complete work?

**Comment by pavelsavara** [comment]
> @yowl This looks like a great start. 

Definitely!

I would be also interested to observe your progress and look at it from Mono/WASM perspective.

**Comment by yowl** [comment]
> In short, this is not a supported scenario.

Thanks, that is good to know!   The source code generator has to be completely contained in the net standard 2.0 code, is basically what we would have to do to use a source code generator.  Any kind of "cheating" like `NativeLibrary.Load` is out?

So, short of porting wit-bindgen to dotnet, we are looking at a different approach.  Perhaps a `Target`/`BeforeTargets="Compile"` ?

N.B.  Rust does this via a macro in the source code, e.g. 

```
wit_bindgen::generate!({
    path: "../../tests/runtime/numbers",
    exports: {
        world: Component,
        "test:numbers/test": Component
    }
});
```

**Comment by AaronRobinsonMSFT** [comment]
> Perhaps a Target/BeforeTargets="Compile" ?

Right. That is going to be the recommended path for this.

Push the .wit files as `<AdditionalFiles>`. Add a `BeforeTargets` to `CoreCompile`, run the tool there, then put the output of the tool into the inputs to `CoreCompile`. That will fit more appropriately into the build model.

**Comment by yowl** [comment]
Thanks,

I was thinking we might be able to use the new `static abstract` interface methods to provide the client implementer for exported interfaces guidance on what was required.  Maybe that can be looked at later, right now it will be convention based, so for example code gen will generate
```cs
    [UnmanagedCallersOnly(EntryPoint = "test:numbers/test#roundtrip-u8")]
    internal static int wasmExportRoundtripU8(int p0) {
        return (int)TestImpl.RoundtripU8((byte)p0);       
    }
```

Where `TestImpl` will be a class that the implementer of the exports will have to provide.

**Comment by yowl** [comment]
Will close this as wit-bindgen for c# is progressing nicely over in https://github.com/bytecodealliance/wit-bindgen
