### ISSUE TITLE
[NativeAOT LLVM] Produce reactor when compiling OutputType Library on wasi-wasm

### ISSUE THREAD

**Issue by RReverser** [dotnet/runtimelab#2384]
As per discussion in https://github.com/dotnet/runtimelab/issues/2235#issuecomment-1688374322, there are currently two issues making it hard to produce Wasm libraries with custom imports/exports:

1. `<OutputType>Library</OutputType>` should pass `-mexec-model=reactor` to the linker so that it produces a reactor / library instead of WASI executable.
2. The generated Wasm should allow to invoke `_initialize` multiple times - right now it doesn't expect it to be called before any exports.

**Comment by SingleAccretion** [comment]
This is now fixed.
