### ISSUE TITLE
[NativeAOT LLVM] Generate exports list for the linker on wasi-wasm

### ISSUE THREAD

**Issue by RReverser** [dotnet/runtimelab#2385]
As per https://github.com/dotnet/runtimelab/issues/2235#issuecomment-1688298619, right now you need to pass explicit

```xml
<CustomLinkerArg Include="-Wl,--export,test:numbers/test!roundtrip-s8" />
```

to get symbols exported from Wasm on wasi-wasm target.

It needs a solution similar to https://github.com/dotnet/runtimelab/pull/2232 to automatically generate export list and pass it to the linker.

**Comment by SingleAccretion** [comment]
This is now fixed.

**Comment by RReverser** [comment]
Nice!
