### ISSUE TITLE
[NativeAOT] Missing Marshal.PtrToStructure on some types

### ISSUE THREAD

**Issue by mrhelmut** [dotnet/runtimelab#240]
Hello there,

While implementing an SDK from a third party vendor (which is a C# wrapper to a native C dll), we stumbled upon some issues with ```Marshal.PtrToStructure()``` and ```StructureToPtr()``` which are throwing exceptions.

The exceptions go as "marshalling from this type is currently not supported".

The type goes like this:

```
	[StructLayout(LayoutKind.Sequential, Pack = 8)]
	internal sealed class SomeClass
	{
		public object SomeField { get; private set; }

		public SomeClass(object someField )
		{
			SomeField = someField ;
		}
	}
```

The context is in regard to marshalling this type to ```IntPtr``` back and forth.

Given the nature of the exception, I am assuming that it is known and scheduled to be implemented at some point. If so, please do feel free to consider this as a non-issue.

On our end we've been able to workaround this with the vendor by reworking the wrapper to work differently on marshalling these data.

Cheers!

**Comment by MichalStrehovsky** [comment]
I think the `object` field implies COM marshalling - that's a tough one and one of dotnet/runtime#69919.

There were many discussions about COM support in the CoreRT repo.

**Comment by MichalStrehovsky** [comment]
Lets track this as part of general COM support in dotnet/runtime#69919.
