### ISSUE TITLE
NativeAOT-LLVM Question How do TypeDefintions get written to the metadata

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#242]
I'm investigating why `Type.GetType(fullTypeName)` does not work for Wasm/LLVM.  At runtime the only `TypeDefinition` that is found in `NativeFormatRuntimeAssembly`  https://github.com/dotnet/corert/blob/0d45438de099e08f140ff4a487d1daeced683873/src/System.Private.Reflection.Core/src/System/Reflection/Runtime/Assemblies/NativeFormat/NativeFormatRuntimeAssembly.GetTypeCore.CaseSensitive.cs#L45-L50 is for a type called `<Module>`.  I think this is `CompilerGeneratedAssembly` https://github.com/dotnet/corert/blob/0d45438de099e08f140ff4a487d1daeced683873/src/Common/src/TypeSystem/IL/TypeSystemContext.GeneratedAssembly.cs#L40 (not sure).  This `CompilerGeneratedAssembly` looks like it can never have any types, so I don't understand how the type lookup from assemblies works at runtime.  What's missing in my understanding here?

Thanks

**Comment by jkotas** [comment]
This likely means that a wrong `NativeFormatRuntimeAssembly` was looked up earlier. What is the assembly name in the `fullTypeName`?

`s_assemblyRefNameToAssemblyDispenser` in https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/src/coreclr/src/nativeaot/System.Private.Reflection.Core/src/System/Reflection/Runtime/General/Dispensers.cs#L105 is the place to look at. 

The compiler writes this out in https://github.com/dotnet/runtimelab/tree/feature/NativeAOT/src/coreclr/src/tools/aot/ILCompiler.MetadataTransform if you would like to double check it on the compiler side.

**Comment by yowl** [comment]
Thanks.  I can see that at compile time in the MetadataTransform, the assembly, ReflectionTest (as this is the simple Reflections tests that I'm trying to get at least partially running) is there and the types are not blocked.  So that bit looks ok.  At runtime the Dispenser delegate is only ever called with the `RuntimeAssemblyName`  `System.Private.CoreLib` which reasonable enough returns the assembly with full name `System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e`  ,  So I should expect a call to the dispenser for `Reflection` I presume, that being the name
of the assembly `Reflection, Version=0.0.0.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb` .  I will look around why there is no call for that.

**Comment by MichalStrehovsky** [comment]
Is it this test?

https://github.com/dotnet/runtimelab/blob/b4c0f03d7693a890db0d1f67d85b607834f6d24c/src/tests/nativeaot/SmokeTests/Reflection/Reflection.cs#L1145-L1183

This test is testing the annoying behavior of `Type.GetType` where Type.GetType is supposed to search the assembly that contains the code that is calling the API. CoreCLR implements this using a stackwalk at runtime to figure out who's the caller. We expand these APIs intrinsically. The way it works is that the codegen backend calls into this code in Compilation:

https://github.com/dotnet/runtimelab/blob/b4c0f03d7693a890db0d1f67d85b607834f6d24c/src/tests/nativeaot/SmokeTests/Reflection/Reflection.cs#L1145-L1183

And this method will return a new MethodDesc. Codegen backend will just pretend that this is the MethodDesc that was there in the IL to begin with (look under what conditions the RyuJIT backend calls into this).
