### ISSUE TITLE
[NativeAOT LLVM] Missing main export when using `IlcExportUnmanagedEntrypoint=true`

### ISSUE THREAD

**Issue by maraf** [dotnet/runtimelab#2433]
If I set `IlcExportUnmanagedEntrypoint=true`, main is not exported. 
It can be fixed by adding `<CustomLinkerArg Include="-Wl,--export,__main_argc_argv" />`

https://github.com/dotnet/runtimelab/blob/feature/NativeAOT-LLVM/src/coreclr/tools/aot/ILCompiler/Program.cs#L590

Is it correct to add such export explicitly when `IlcExportUnmanagedEntrypoint == true && NativeLib == ''`?

**Comment by ivanpovazan** [comment]
Is the question related to the managed main? 

If I am not mistaken, managed main is exposed via `__managed__Main` symbol

**Comment by maraf** [comment]
Good question. I didn't realized yesterday that I need to call the actual C# main, the one that user, possibly async, so that we can yield to JavaScript loop

**Comment by SingleAccretion** [comment]
We now export native `main` explicitly in this configuration: https://github.com/dotnet/runtimelab/blob/1b1dbae4bf879130e59f78ff7d9eb438dd089f9e/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/ExportsFileWriter.cs#L49C22-L52C22, so this can be considered fixed.
