### ISSUE TITLE
[NativeAOT LLVM] [Question] this project will be added to main repo?

### ISSUE THREAD

**Issue by sajjadarashhh** [dotnet/runtimelab#2435]
in blazor projects we have many problems with application start time that we solved them with some tricks like hybrid application
But afterall we cant use blazor as a complete framework for ui
For example if you see mudblazor you dont wana to open pages in new tab for that slow runtime you dont wana to wait for application starting
And this bad ux
I think NativeAOT can solved application size and make better start time

**Comment by jkotas** [comment]
We do not have any committed plans on this front currently.
