### ISSUE TITLE
[Misc] Info about projects currently in this repo

### ISSUE THREAD

**Issue by En3Tho** [dotnet/runtimelab#244]
Hey! I was wondering if there could be a dedicated page for each feature in this repo describing it in more detail and shedding more light about it's progress / design decisions / evolution e.t.c?
Now links at main page navigate to branches and this isn't very useful if I want to read more about a certain feature/features.
Would be cool if I could just use the link and read about how for example Utf8Strings are going to be represented in the runtime, at least some draft or sketch that can be updated from time to time.

**Comment by jkotas** [comment]
I am adding a note about this to the master README.md. 

It is up to owners of each of the experiments to do this. If you would like to see more details written down about e.g. Utf8String, file a specific issue against area-Utf8String.

**Comment by En3Tho** [comment]
Thanks. Now things are more clear :) But before I try to file "update readme" issues against feature branches I would like to ask if you think it would be beneficial to community and not a huge blunder to a maintainer. @jkotas

**Comment by jkotas** [comment]
Yes, I think it is beneficial for creating clarity.
