### ISSUE TITLE
[NativeAOT-LLVM][Question] import wasm modules

### ISSUE THREAD

**Issue by sajjadarashhh** [dotnet/runtimelab#2457]
We can import wasm modules?
If we cant thats good to implement that in this repo?

**Comment by SingleAccretion** [comment]
WASM modules themselves cannot be imported, but if you mean WASM methods, they can be imported with `WasmImportLinkage` (see #2454, #2444, [#dotnet/runtime/93824](https://github.com/dotnet/runtime/issues/93824)).

**Comment by sajjadarashhh** [comment]
@SingleAccretion i told above about a component model in wasm

**Comment by SingleAccretion** [comment]
I see, so it's about producing _components_ as opposed to core WASM modules? The approach so far has been to produce core WASM modules and then use external tools to turn them into components, I believe. It may make sense to support producing components directly, but I am not sure. What does the current tooling story here look like?

**Comment by yowl** [comment]
We are doing  the production of wasm components over in https://github.com/bytecodealliance/wit-bindgen  where we are doing the codegen (c#) for NativeAOT-LLVM and Mono interpreter.

**Comment by yowl** [comment]
> use external tools to turn them into components

This is correct, we use `wasm-tools` for the actual conversion of core wasm modules to components.

**Comment by sajjadarashhh** [comment]
Its about using components written in another language like rust or js and compiled as wasm component

**Comment by yowl** [comment]
That scenario would be covered by the wit-bindgen work.  You combine the the c# and other language component with `wasm-tools compose <c# wasm> <other language wasm> ...`

**Comment by sajjadarashhh** [comment]
That would be nice.
Thank you for response
