### ISSUE TITLE
[NativeAOT-LLVM] Implement alternative for reachable block detection

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#2478]
We are currently reseting the `bbIDom` to detect reachable blocks

https://github.com/dotnet/runtimelab/blob/75e4231c4983020f2c1a75b80bb5bb0b111a0f4c/src/coreclr/jit/compiler.cpp#L5167

We could instead use `m_dfsTree->Contains` and then remove this code.

cc @SingleAccretion  @jakobbotsch

**Comment by SingleAccretion** [comment]
Fixed in #2480.
