### ISSUE TITLE
Application size

### ISSUE THREAD

**Issue by sajjadarashhh** [dotnet/runtimelab#2484]
In this repository we will working on reducing application size?

**Comment by jkotas** [comment]
General work on reducing application size is done in https://github.com/dotnet/runtime repo. For example, check issues in this query: https://github.com/dotnet/runtime/issues?q=is%3Aissue+label%3Alinkable-framework+is%3Aopen

Some of the experimental projects in this repo may be doing work on application size, but that work should be specific to the experimental project.
