### ISSUE TITLE
[Question] [NativeAOT-LLVM] What defines if jobs has a `Initialize containers` step?

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#2618]
Looking at this
![image](https://github.com/dotnet/runtimelab/assets/2720041/ff319d56-c5c8-4624-9bd6-b3c0ee2f9afa)

`linux-x64 release` has an "Initialize containers" step, whereas `wasi-wasm linux release` does not, yet they are both from 
```
    ${{ if eq(parameters.jobParameters.pool, '') }}:
      pool:
        # Public Linux Build Pool
        ${{ if and(or(in(parameters.osGroup, 'linux', 'freebsd', 'android', 'tizen'), eq(parameters.jobParameters.hostedOs, 'linux')), eq(variables['System.TeamProject'], 'public')) }}:
          name:  $(DncEngPublicBuildPool)
          demands: ImageOverride -equals Build.Ubuntu.2204.Amd64.Open
```

What is is that makes them different?

**Comment by yowl** [comment]
Or how can I get an "Initialize containers" step in my new job ?  (As I am missing some packages and I'm guessing its because of the lack of this step).

**Comment by jkotas** [comment]
Can you try this: https://github.com/dotnet/runtimelab/blob/89058f06a4e667d4b8ff8561355d768050c2630d/eng/pipelines/common/platform-matrix.yml#L243-L248 ?

**Comment by jkotas** [comment]
> I am missing some packages and I'm guessing its because of the lack of this step).

Right. `mcr.microsoft.com/dotnet-buildtools/prereqs:azurelinux-3.0-cross-amd64-net9.0` should be the container to use.

**Comment by yowl** [comment]
Thanks!
