### ISSUE TITLE
[NativeAOT-LLVM] Publishing is broken

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#2640]
@jkotas Please can you get the logs for the publishing, the last merge seems to have broken it.

![image](https://github.com/user-attachments/assets/485be344-32ce-4fbd-95a1-39a329414dc2)

Thanks!

**Comment by jkotas** [comment]
This should be fixed now. There was a permission issue.

**Comment by yowl** [comment]
Thank you!  Looks good:
![image](https://github.com/user-attachments/assets/9df94812-5969-4f4d-99a3-6b1a195df0b8)
