### ISSUE TITLE
What is next?

### ISSUE THREAD

**Issue by rollsch** [dotnet/runtimelab#2642]
I see that the code has not been updated in 2 years. What is next ?

I'd love to be able to compile C# to a native exe (performance, obfuscation, many reasons).

I'd also love for WPF to work.

**Comment by jkotas** [comment]
I assume that you are talking about native AOT. The project was moved to https://github.com/dotnet/runtime/ repo and ships with the rest of the .NET runtime.

WPF is not compatible with native AOT currently. It is tracked by https://github.com/dotnet/wpf/issues/3811
