### ISSUE TITLE
[NativeAOT-LLVM] [Question] RhpGcPoll implementation.

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#2644]
`RhpGcPoll` is currently a NOP

https://github.com/dotnet/runtimelab/blob/3e66fa1a37df00e2c974dc913bec7649dcb22a06/src/coreclr/nativeaot/Runtime/portable.cpp#L434-L438

Would it be appropriate to base the implementation on 

https://github.com/dotnet/runtimelab/blob/3e66fa1a37df00e2c974dc913bec7649dcb22a06/src/coreclr/nativeaot/Runtime/amd64/GcProbe.S#L146-L160

I'm likely not the best person to attempt this, but happy to have a go if people don't mind me asking questions.

**Comment by jkotas** [comment]
I think the empty implementation is fine for single-threaded wasm.

**Comment by yowl** [comment]
Sorry, I meant to bring up multi threaded wasm.

**Comment by jkotas** [comment]
Ah ok. The GC poll is basically a cooperative->preemptive->cooperative mode switch, with an early out optimization if there is no GC pending.

I think it can follow the same pattern as the wasm allocation helpers in https://github.com/dotnet/runtimelab/blob/feature/NativeAOT-LLVM/src/coreclr/nativeaot/Runtime/wasm/AllocFast.cpp .

Something like:

```
FCIMPL0(void, RhpGcPoll)
{
    if (RhpTrapThreads == 0)
        return;

    PInvokeTransitionFrame frame;
    RhpPInvoke(pShadowStack, &frame);
    RhpPInvokeReturn(&frame);
}
FCIMPLEND
```

If it helps performance, the `PInvokeTransitionFrame` part can be in a separate non-inlined method.

**Comment by yowl** [comment]
Thanks, thought it would be more complicated :-)
