### ISSUE TITLE
TypeDiscovery failure when aliasing attribute

### ISSUE THREAD

**Issue by kevinwkt** [dotnet/runtimelab#27]
- JsonCodeGen branch (Source Generation project)

**Minimal Repro**
Any aliasing on JsonSerializableAttribute such as the following examples:

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzhgHwAEAmARgFgAoIgBgAIBBAOwgwAsYoA5bAWxi4ADtjAx6AXnpEyAbmp16AZQgCOAS2YBzAKIAbXDB3MM62HoCek6WQB0Sruux71AL2zA9MRhgxR1wACuGDDyVNQA2g7+zm4eXgC6CgDM0iRM9ADeAL7UkTL2jrHunt6+/kEhSTSppPQAQlm54VQRLGycPPyCImKFMS4liSlp9ADCTXmtKmrsmroGRiZmMJbVRLXpACJNQA===

**Expected Behavior**
Semantic model comparison for attributes instead of name comparison using syntax tokens. 

**Actual Behavior**
Currently for JsonCodeGen branch, type discovery relies on string comparison on attribute syntax name as shown below

```c#
// src/libraries/System.Text.Json/System.Text.Json.SourceGeneration/JsonSerializableSyntaxReceiver.cs
serializableAttributes = attributeList.Attributes.Where(node => (node is AttributeSyntax attr && attr.Name.ToString() == "JsonSerializable")).Cast<AttributeSyntax>();
```

**Comment by jkotas** [comment]
> JsonCodeGen branch (Source Generation project)

@kevinwkt I have created issue labels to use for different projects. You can just mark the issue next time instead of mentioning this in the description.
