### ISSUE TITLE
[NativeAOT-LLVM] Application DispatcherUnhandledException is not observed

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#2708]
While we don't support WPF, https://learn.microsoft.com/en-us/dotnet/api/system.windows.application.dispatcherunhandledexception?view=windowsdesktop-8.0 is not observed and would be nice to help bring up Avalonia XPF as the exception details are lost when transitioning to Javascript land.

**Comment by yowl** [comment]
I suppose what could happen, under a flag, is that UCO methods would have to know there is nothing managed above them in the stack frame (does our virtual unwind info help here?) and then check for the `DispatcherUnhandledException` and call it .

**Comment by SingleAccretion** [comment]
> the exception details are lost when transitioning to Javascript land.

It seems this is primary problem that needs solving. It is expected that unhandled exceptions from `JSExport`s bubble up as unhandled JS exceptions.

**Comment by yowl** [comment]
> It seems this is primary problem

I agree this is more important and would help/solve things.  It would also be nice to have `DispatcherUnhandledException` work as documented though.

**Comment by yowl** [comment]
I was wrong this event is called, sorry.
