### ISSUE TITLE
[NativeAOT-LLVM] Implement RhGetCommonStubAddress  ?

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#2735]
Do we want to/can we implement `RhGetCommonStubAddress` ?  `IDynamicInterfaceCastable` is implemented with thunk pools and requires this helper.

**Comment by SingleAccretion** [comment]
See #2693. It's not possible to implement `RhGetCommonStub` as-is (it is signature-agnostic). What we should do in the meantime is ifdef out the path to the thunk pool with PNSEs so that the code doesn't get kept.
