### ISSUE TITLE
[Swift Bindings] Hiking app requirements

### ISSUE THREAD

**Issue by jkurdek** [dotnet/runtimelab#2749]
Addition of Hiking app into Swift Projection tooling changed the requirements to build the project. (I have in mind running `dotnet build` in the project root).

I found that at minimum it requires maccatalyst workload and some iOS Simulator (in my case I received an error that iOS 18.1 is not installed). 

I think we should document those requirements. 
Also, I wonder whether Hiking App should be build when running `dotnet build` in the project root at all. As it imposes additional dependencies maybe it would be beneficial to have a separate build script?

**Comment by matouskozak** [comment]
Ah I see, we debugged the experience around using the `build.sh` script and not `dotnet build`.  I think we will have to remove the Hiking App entry from the main solution file to make it work as expected with `dotnet build`. This will cause that debugging of Hiking App (running `F5`) won't work from the main project and will require opening the HikingApp.MacCatalyst in a separate instance of VSCode. cc: @kotlarmilos

**Comment by kotlarmilos** [comment]
I agree. I've created another vscode instance locally for prototyping.
