### ISSUE TITLE
[ Microsoft.DotNet.ILCompiler ] "COM Interop is not supported on this platform" exception after updating to new version of package

### ISSUE THREAD

**Issue by FoggyFinder** [dotnet/runtimelab#279]
Didn't change anything except

```xml
<PackageReference Include="Microsoft.DotNet.ILCompiler" Version="1.0.0-alpha-*" />
```
->
```xml
<PackageReference Include="Microsoft.DotNet.ILCompiler" Version="6.0.0-*" />
```

App uses `Avalonia 0.9.11`

part of StackTrace

```
Unhandled Exception: System.PlatformNotSupportedException: COM Interop is not supported on this platform.
   at Internal.Runtime.CompilerHelpers.InteropHelpers.ConvertManagedComInterfaceToNative(Object) + 0x42
   at Avalonia.Win32.Interop.UnmanagedMethods.RegisterDragDrop(IntPtr, IDropTarget) + 0x46
   at Avalonia.Win32.OleContext.RegisterDragDrop(IPlatformHandle, IDropTarget) + 0x68
   at Avalonia.Win32.WindowImpl.CreateDropTarget() + 0x43
   at Avalonia.Controls.TopLevel..ctor(ITopLevelImpl, IAvaloniaDependencyResolver) + 0x1ac
   at Avalonia.Controls.WindowBase..ctor(IWindowBaseImpl, IAvaloniaDependencyResolver) + 0x24
   at Avalonia.Controls.Window..ctor(IWindowImpl) + 0x62
```

**Comment by jkotas** [comment]
The COM interop has not been supported by CoreRT. It is not clear to me how this could ever work.

**Comment by FoggyFinder** [comment]
Yeah, that's odd.

I tried to reproduce on [AvaloniaCoreRTDemo](https://github.com/teobugslayer/AvaloniaCoreRTDemo). It works just fine for `1.0.0-*` (with small adjustment) but I even wasn't able to build the project with 6.0.0.-*

I'm getting 

```
Compiling [S.P.TypeLoader]System.Collections.Generic.LowLevelDictionary`2<Internal.Runtime.TypeLoader.TypeLoaderEnvironment+RuntimeFieldHandleKey,System.RuntimeFieldHandle>.ExpandBuckets()...
EXEC : LLVM error : IO failure on output stream. [...\AvaloniaCoreRTDemo.csproj]
```

**Comment by josephmoresena** [comment]
> Yeah, that's odd.
> 
> I tried to reproduce on [AvaloniaCoreRTDemo](https://github.com/teobugslayer/AvaloniaCoreRTDemo). It works just fine for `1.0.0-*` (with small adjustment) but I even wasn't able to build the project with 6.0.0.-*
> 
> I'm getting
> 
> ```
> Compiling [S.P.TypeLoader]System.Collections.Generic.LowLevelDictionary`2<Internal.Runtime.TypeLoader.TypeLoaderEnvironment+RuntimeFieldHandleKey,System.RuntimeFieldHandle>.ExpandBuckets()...
> EXEC : LLVM error : IO failure on output stream. [...\AvaloniaCoreRTDemo.csproj]
> ```

Try to use 
`   <TargetFramework>netcoreapp3.1</TargetFramework>
    <Platforms>x64</Platforms>` 
instead of 
`    <TargetFramework>net5.0</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>`
Seems new Avalonia version doesn't work with CoreRT nor NativeAOT.

**Comment by FoggyFinder** [comment]
> Try to use `<TargetFramework>netcoreapp3.1</TargetFramework> <Platforms>x64</Platforms>`

I had removed this line at all. 
I tried to specify `<Platforms>x64</Platforms>` and result is even worse. I get an exception and after than system gets crazy. Many launched applications are stopped to respond. And those that didn't are getted blurry. I had to restart system completely.

I was able to make a screenshot though:

![_exceptionCoreRt](https://user-images.githubusercontent.com/16510738/97912305-4f03b200-1d55-11eb-83fd-24c6f8ec4fca.jpg)

> Seems new Avalonia version doesn't work with CoreRT nor NativeAOT.

yeah. Seems like I will stick to good old CoreRt and Avalonia 0.9.11.

**Comment by josephmoresena** [comment]
> > Try to use `<TargetFramework>netcoreapp3.1</TargetFramework> <Platforms>x64</Platforms>`
> 
> I had removed this line at all.
> I tried to specify `<Platforms>x64</Platforms>` and result is even worse. I get an exception and after than system gets crazy. Many launched applications are stopped to respond. And those that didn't are getted blurry. I had to restart system completely.
> 
> I was able to make a screenshot though:
> 
> ![_exceptionCoreRt](https://user-images.githubusercontent.com/16510738/97912305-4f03b200-1d55-11eb-83fd-24c6f8ec4fca.jpg)
> 
> > Seems new Avalonia version doesn't work with CoreRT nor NativeAOT.
> 
> yeah. Seems like I will stick to good old CoreRt and Avalonia 0.9.11.

Weird, what windows version are you using? I'm running W10 LTSC 2020.
![image](https://user-images.githubusercontent.com/44370115/97916884-9ff9b300-1d21-11eb-907d-013a1fcf0140.png)

![image](https://user-images.githubusercontent.com/44370115/97916926-aee06580-1d21-11eb-94f3-f9ceb9653333.png)

Framework version is 6.0 according to Native AOT, when use latest old CoreRT Framework version says
![image](https://user-images.githubusercontent.com/44370115/97917349-59588880-1d22-11eb-8d71-71d9926eb815.png)

**Comment by FoggyFinder** [comment]
> Weird, what windows version are you using?

10.0.17763

**Comment by jkotas** [comment]
I have submitted PR to update AvaloniaCoreRTDemo to the new nuget feed: https://github.com/teobugslayer/AvaloniaCoreRTDemo/pull/4 . It works fine for me.

**Comment by josephmoresena** [comment]
> > Weird, what windows version are you using?
> 
> 10.0.17763

I have the same version. I attached a detailed log by executing `dotnet publish -r win-x64 -c release -v d >> log.txt may it help.
[log.txt](https://github.com/dotnet/runtimelab/files/5478055/log.txt)

**Comment by jkotas** [comment]
We have fixed a crash in FinishObjWriter a few weeks ago. Maybe you are not using the latest package?

**Comment by FoggyFinder** [comment]
> We have fixed a crash in FinishObjWriter a few weeks ago. Maybe you are not using the latest package?

How can I make sure I'm on latest? 

I have 3 packages:

`6.0.0-alpha.1.20531.1` (probably the one where I got  `FinishObjWriter` crash
`6.0.0-alpha.1.20527.1` (probably the one where I saw `System.PlatformNotSupportedException` exception described in started post)

old one: CoreRt (works great)

`1.0.0-alpha-29408-02`

**Comment by FoggyFinder** [comment]
> I attached a detailed log by executing `dotnet publish -r win-x64 -c release -v d >> log.txt may it help.

dunno. I use these settings in a fsproj/csproj

```xml
  <ItemGroup>
    <IlcArg Include="--verbose" />
    <IlcArg Include="--singlethreaded" />
  </ItemGroup>
```

to get more informative logs.

**Comment by jkotas** [comment]
Both these are very recent (20527.1 is October 27, 20531.1 is October 31). I am running out of ideas why it may be crashing for you.

**Comment by FoggyFinder** [comment]
I had an idea. 
`CoreRtDemo` project was on system disk (`C`) while my application was on a different one.

So I moved `CoreRtDemo` to another one and now there is no crash and it started just fine (after I copied images near .exe).

**Comment by FoggyFinder** [comment]
since it works OK on demo project I'll try to create MCVE. I can only hope it won't be too complicated

**Comment by FoggyFinder** [comment]
@jkotas why the issuw was closed? Cause there is no way to reproduce?

**Comment by jkotas** [comment]
If you are still not able to figure why things that used to work with the CoreRT package do not work anymore, I will be happy to reactive this issue.

I have created a dedicated issues for the COM interop support since it is a popular topic: https://github.com/dotnet/runtimelab/issues/306

**Comment by FoggyFinder** [comment]
> If you are still not able to figure why things that used to work with the CoreRT package do not work anymore, I will be happy to reactive this issue.

Yep, no idea. I tried to create MCVE but for some reason my attempt is crashed horribly with "hard error" exception during the first "Generating native code" task even with old version of CoreRt. 

Initally I thought it is coincidnce and might be unrelated to CoreRt but when I repeat test (this time I turned off almost all applications) and got the same crash I decide to stop.

I'll try find another machine to confirm crash on test project.

But for the main issue I will have to minimize my project step by step so it will take longer. I'll try to do it on weekend.

New version of CoreRt produces bigger executable (+8Mb for my project). Maybe it keeps some methods that were stripped away previously despite they're unused?

**Comment by jkotas** [comment]
> Maybe it keeps some methods that were stripped away previously despite they're unused?

The compiler logic that controls what is stripped have not changed. If you see this, it must be caused by some secondary effect like implementation change in one of the libraries.
