### ISSUE TITLE
[SwiftBindings] Extra enum-specific entries in ValueWitnessTable

### ISSUE THREAD

**Issue by stephen-hawley** [dotnet/runtimelab#2881]
ValueWitnessFlags needs to be based on uint32 explicitly to ensure that it lines up with the Swift.

We need to add (in order):

/// Given a valid object of this enum type, extracts the tag value indicating
/// which case of the enum is inhabited. Returned values are in the range
/// [0..NumElements-1].
uint getEnumTag(void *enumData, TypeMetadata md);

/// Given a valid object of this enum type, destructively extracts the
/// associated payload.
void destructiveProjectEnumData(void *enumData, TypeMetadata md);

/// Given an enum case tag and a valid object of case's payload type,
/// destructively inserts the tag into the payload. The given tag value
/// must be in the range [-ElementsWithPayload..ElementsWithNoPayload-1].
void destructiveInjectEnumTag(void *enumData, uint tag, TypeMetadata md)

How to use these -
getEnumTag returns the tag for enum.
destructiveProject clears the tag from the enum payload, so if you want to extract a payload without worrying about the tag, you can do this:
```csharp
public SomeEnumProjection {
    SomeType Case0Value {
        get {
            unsafe {
                var metadata = GetTypeMetadata();
                var witnessTable = metadata.ValueWitnessTable;
                if (witnessTable->GetEnumTag() != 0) throw new Exception();
                var copy = stackalloc byte[_payload.Length];
                Array.Copy(_payload, 0, copy, 0, _payload.Length);
                fixed (void *copyPtr = copy) {
                    witnessTable->destructiveProjectEnumData(copyPtr, metadata);
                    return SwiftRuntime.SwiftMarshal.FromSwift<SomeType>((IntPtr)copy);
                }
        }
    }
}
```
Destructive project enum data removes the tag information, letting us pull the data directly from the payload, but because it's destructive, we need to work with a copy. In theory we would reinject the tag, but that creates a potential thread safety issue if there are any mutating methods on the type.

Similarly, this lets us implement factory methods like this:
```csharp
public SomeEnumProjection {
    static SomeEnumProjection CreateCase0(SomeType payload) {
        var someEnum = default(SomeEnumProjection);
        var metadata = GetTypeMetadata();
        var witnessTable = metadata.ValueWitnessTable;
        unsafe {
             fixed (void *payloadPtr = &_payload) {
                 SwiftRuntime.SwiftMarshal.ToSwift(payload, (IntPtr)payloadPtr);
                  witnessTable->destructiveInjectEnumTag(payloadPtr, 0, metadata);
             }
         }
    }
}
```

And of course since this is boiler plate code that really won't vary, we can make methods to extract and set payloads parameterized by the metadata, the payload array (or a pointer to it), and in the case of setting, the desired tag and the desired payload.

**Comment by matouskozak** [comment]
```
/// Given an enum case tag and a valid object of case's payload type,
/// destructively inserts the tag into the payload. The given tag value
/// must be in the range [-ElementsWithPayload..ElementsWithNoPayload-1].
void destructiveInjectEnumTag(void *enumData, uint tag, TypeMetadata md)
```
I don't follow the tag value range specification, what does `ElementsWithPayload` and `ElementsWithNoPayload` represent?

**Comment by matouskozak** [comment]
We will also likely need the special calls for single payload enums (I believe these are enums which contain one case with payload and one or more non-payload cases):

```
// Given an instance of valid single payload enum with a payload of this
// witness table's type (e.g Optional<ThisType>) , get the tag of the enum.
uint getEnumTagSinglePayload (void *enumData, uint numEmptyCases, TypeMetadata md);
```

and

```
// Given uninitialized memory for an instance of a single payload enum with a
// payload of this witness table's type (e.g Optional<ThisType>), store the
// tag.
void storeEnumTagSinglePayload(void *enumData, uint tag, uint numEmptyCases, TypeMetadata md);

**Comment by kotlarmilos** [comment]
Good job Steve, this is nice.

> I don't follow the tag value range specification, what does `ElementsWithPayload` and `ElementsWithNoPayload` represent?

`-ElementsWithPayload to -1` - I assume these represent payload cases
`0 to ElementsWithNoPayload - 1` -  - I assume these represent cases without payload

**Comment by matouskozak** [comment]
Completed in https://github.com/dotnet/runtimelab/pull/2893
