### ISSUE TITLE
Move Utf8String experiment to dotnet/runtimelab

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtimelab#3]
- [x] Create Utf8String branch that is clone of dotnet/runtime
- [ ] (optional) Trim the the build in this branch so that it builds just ref pack, runtimepack and the Utf8String package, CoreCLR-only, no mono.
- [ ] Add lightweight pre-checkin CI that just builds say Windows and Linux, and runs tests on it
- [ ] Add post-commit CI that publishes ref pack, runtimepack and the Utf8String package into a new feed that we will setup for runtimelab packages.
- [x] Add readme and notes for how to setup a new experiment (in dotnet/runtimelab:master)
- [x] Delete the experimental code in dotnet/runtime

**Comment by jeffhandley** [comment]
This was completed and the branch is available here: https://github.com/dotnet/runtimelab/tree/feature/Utf8String, as linked to in the README.
