### ISSUE TITLE
GT_RET_EXPR in fat transform

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtimelab#321]
NO_WAY("Cloning of GT_RET_EXPR node not supported");

Hitting an issue in fat transform when running with optimizations on unoptimized IL of this method:

https://github.com/dotnet/runtimelab/blob/cd82da18bdfa0390378682c0811251fca5d75752/src/coreclr/src/nativeaot/Runtime.Base/src/System/Runtime/DispatchResolve.cs#L20-L23

(`DynamicTypeSlotDispatchResolve` is a function pointer, hence this is a `calli`)

We end up with a following tree for the calli:

```
STMT00040 (IL   ???...  ???)
               [000151] -ACXG-------              *  ASG       long
               [000150] D------N----              +--*  LCL_VAR   long   V20 tmp5
               [000149] --CXG-------              \--*  CALL ind  long
               [000145] ------------ arg0            +--*  LCL_VAR   long   V19 tmp4
               [000146] --C--------- arg1            +--*  RET_EXPR  long  (inl return from call [000142])
               [000147] ------------ arg2            +--*  LCL_VAR   ushort V02 arg2
               [000148] ------------ calli tgt       \--*  LCL_VAR   long   V06 loc3
```

The inl return is a call to the IntPtr casting operator - note the C# source has two casts like this, but one of them is spilled into a temporary, so the tree has a load from the temporary instead of the RET_EXPR.

`FatPointerCallTransformer::CreateThen` (also `CreateElse`, I assume), is trying to clone this tree and hitting the `NO_WAY("Cloning of GT_RET_EXPR node not supported");`. I assume we need to spill arguments into temps first?

This problem is new after #191 - before that, the calli was in a separate method and the casts happened elsewhere.

Thanks for C# 9.0 introducing direct support for function pointers, this can be hit in customer code too.

**Comment by MichalStrehovsky** [comment]
`GuardedDevirtualizationTransformer` uses `gtCloneCandidateCall` instead of `gtCloneExpr` which apparently is the thing that prevents issues with GT_RET_EXPR. Not sure what the "appropriate other fixup" will be tho, so maybe let's leave this to the JIT team after the holidays...

```
            // We can't safely clone calls that have GT_RET_EXPRs via gtCloneExpr.
            // You must use gtCloneCandidateCall for these calls (and then do appropriate other fixup)
```

**Comment by MichalStrehovsky** [comment]
@sandreenko is this something you could have a look at?

**Comment by sandreenko** [comment]
Sure @MichalStrehovsky , will take a look later this week.

**Comment by MichalStrehovsky** [comment]
Thank you! This is currently getting hit in the NativeAOT implementation of Marshal.PtrToStructure/StructureToPtr/DestroyStructure so something that pulls those methods into the NativeAOT compilation would be a good repro.

E.g. add a call to `Marshal.StructureToPtr<GCHandle>(default, default, default);` into the [repro project](https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/docs/workflow/building/coreclr/nativeaot.md#convenience-visual-studio-repro-project).

**Comment by MichalStrehovsky** [comment]
@sandreenko did you have a chance to look at this?

**Comment by sandreenko** [comment]
@MichalStrehovsky sorry got distracted and did not finish the PR, I will allocate time for it tomorrow.

**Comment by sandreenko** [comment]
> `GuardedDevirtualizationTransformer` uses `gtCloneCandidateCall` instead of `gtCloneExpr` which apparently is the thing that prevents issues with GT_RET_EXPR. Not sure what the "appropriate other fixup" will be tho, so maybe let's leave this to the JIT team after the holidays...

`gtCloneCandidateCall` is needed when the call that we want to copy is an inline candidate, in the case of this issue the call is not an inline candidate but it has an argument that is `GT_RET_EXPR`.
I thought that case was supported but apparently, the place for the transformation was chosen a little wrong. The good news is that the all logic that we need is already written and we just need to move the `addFatPointerCandidate` call.
