### ISSUE TITLE
Code generation for POCOs with Collections

### ISSUE THREAD

**Issue by kevinwkt** [dotnet/runtimelab#38]
Using previous structure for simple POCOs with value types we should support collections and create tests to make sure they work.

This feature should also be aligned with current json serializer behavior handling collections.

considered api branch:
https://github.com/dotnet/runtimelab/compare/master...steveharter:ApiAdds

**Comment by layomia** [comment]
Closing as initial work for `Dictionary<,>` and `List<T>` was done in https://github.com/dotnet/runtimelab/pull/62. Support for other types is tracked in https://github.com/dotnet/runtimelab/projects/1#card-48357417.
