### ISSUE TITLE
runtimelab/samples/NativeLibrary no function pointer sample?

### ISSUE THREAD

**Issue by darkguy2008** [dotnet/runtimelab#398]
Hello!

I'm embarking on a quest to call C#-exported methods (using CoreRT/NativeAOT/.NET 5's Native Exports) from another C# app through P/Invoke (to overcome `Reflection.Emit`'s limitation for EF, and other reasons). So far I've got some stuff working, but my marshalling / C++ knowledge isn't great.

Reading through the source code, I expected to see a sample [here](https://github.com/dotnet/corert/blob/master/samples/NativeLibrary/Class1.cs) where it'd explain how to pass/read/invoke a function (could be an `Action<>`, `Func<>`, or even/maybe a `delegate`?) but I haven't found any. Not even in [Seiri](https://github.com/chyyran/seiri/tree/998b3b8ce968db377103054c4d90be2a5f63c653/katatsuki/libkatatsuki-sys/libkatatsuki/src) which claims to use CoreRT for some functions (although the code has been a bit useful, too).

So, I'm wondering if there is a sample somewhere which shows how to export a function that will accept a `delegate` "from the other side"? I could find the P/Invoke part, but I don't know how to export it from CoreRT/NativeAOT to use it with P/Invoke.

I'm opening this as an issue as some documentation on this subject would be appreciated. The code currently shows how to pass ints and other native types, and Seiri shows how to read & send structs, but I haven't found anything regarding delegates. I've tried some stuff by sending `GCHandle` `IntPtr`s pointing to different variables but the app crashes saying it cannot read/write protected memory (which makes sense since it's not a pinned GCHandle - but then, I can't pin a non-native type!).

Ideally, I'd love if it could be done without using `unsafe`. Any pointers would be appreciated :)

**Comment by jkotas** [comment]
The CoreRT and regular .NET runtime in your setup are two independent runtimes. It is no different from e.g. .NET runtime and JVM in the same process.

The only way to do interop between two independent runtimes is via unmanaged interop, like DllImport/PInvoke.

**Comment by darkguy2008** [comment]
@jkotas thanks for your answer!

Yeah I have that clear already. I have it set up in a way thay I'm exporting the .NET method as native like this:
```
      [UnmanagedCallersOnlyAttribute]
        public static void Call(IntPtr window, IntPtr strMethodName)
        {
            var w = _windows[window];
            var handle = GCHandle.FromIntPtr(strMethodName);
            string methodName = handle.Target as string;
            var method = w.GetType().GetMethod(methodName);
            method.Invoke(w, null);
        }
```
This works in debugging mode, but it doesn't outside VSCode due to the protected memory issue. Disregard that, what's important here is that I'm receiving an `IntPtr` to a string I can read (I'll work around it using pinning).

My question is, how do I receive a function to call instead? Similar to what `EnumWindows` does where you give it a callback and the C++ part of the library calls it. How do I do that on my C# function which as been exported with `UnmanagedCallersOnlyAttribute` ?

**Comment by jkotas** [comment]
Use C# 9 function pointers. For example:

```
        [UnmanagedCallersOnlyAttribute]
        public static void OnAction(IntPtr strEvent, delegate* unmanaged<void> fnToCall)
```

**Comment by darkguy2008** [comment]
@jkotas awesome, that worked, thanks! I was unaware that C# 9.0 function pointers could work in this case. Although I don't really like to use `unsafe`, it works for me for the time being. Thanks a lot!!
