### ISSUE TITLE
Question: NativeAOT-llvm yml

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#403]
https://github.com/dotnet/runtimelab/blob/feature/NativeAOT-LLVM/eng/pipelines/runtimelab.yml is a bit behind the `NativeAOT` branch, but I don't think in a way that stops it running the `Build` stage.  Is there something that needs to be setup in Azure DevOps for the branch?  I'm thinking that `NativeAOT-LLVM` should run all the tests that `NativeAOT` does, maybe with `isOfficialBuild==false`, plus whatever new ones for the LLVM backend.  Alternatively it could just run LLVM tests, but that seems a bit risky.

**Comment by jkotas** [comment]
You may need to change the branch name here: https://github.com/dotnet/runtimelab/blob/feature/NativeAOT-LLVM/eng/pipelines/runtimelab.yml#L9

**Comment by jkotas** [comment]
And also here: https://github.com/dotnet/runtimelab/blob/feature/NativeAOT-LLVM/eng/pipelines/runtimelab.yml#L29

**Comment by jkotas** [comment]
Actually, we can just change the trigger to `feature/*` to match dotnet/runtime: https://github.com/dotnet/runtimelab/pull/404 . It will make these changes unnecessary.

**Comment by jkotas** [comment]
The fix is merged. The CI is triggering now. Could you please take a look at why it is failing and whether it is doing what you would like it to do?

**Comment by yowl** [comment]
Thanks, I'll drop all configs except Windows Debug and then try to remove all tests except Generics (which was one of the ones working in CoreRT) and try and get that to run via node as it did, hopefully then getting a green tick.

**Comment by yowl** [comment]
When `src\tests\build nativeaot Debug  /p:SmokeTestsOnly=true` is run it looks like it builds dlls and hosts them in a wrapper, there is no exes built for each test, is that right?

**Comment by jkotas** [comment]
The exes are built as part of running the tests.

**Comment by yowl** [comment]
Thanks.  Have a related question about the `host_os` property for example at https://github.com/dotnet/runtimelab/blob/e8649501abd77fe47112782b601ef46c92139584/src/coreclr/scripts/coreclr_arguments.py#L248  When compiling for Wasm on Windows, would you expect that to be windows, or Browser.  Seems like the expectation is for it to be Browser, but I wonder if a target_os property is also required?  I'm going down the latter, as it starts looking for .sh files to run otherwise.

**Comment by jkotas** [comment]
This script does not seem to have support for os cross targeting as you have pointed out.

**Comment by yowl** [comment]
Closing as #411 seems to be working.
