### ISSUE TITLE
System.Half cannot be loaded in NativeAOT

### ISSUE THREAD

**Issue by HurricanKai** [dotnet/runtimelab#415]
I've just tried to run a BND test using the CoreRT toolchain (`Core RT 1.0.0-alpha-*` according to BND)
And got this exception:
```
System.TypeLoadException: Could not load type 'System.Half' from assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Internal.Runtime.CompilerHelpers.ThrowHelpers.ThrowTypeLoadException(ExceptionStringID, String, String) + 0x11
   at Silk.NET.Maths.Scalar.Log[T](T) + 0x19
   at ...
```
does NativeAOT/CoreRT not support `Half`? not yet? am I using something outdated here?

**Comment by jkotas** [comment]
`Core RT 1.0.0-alpha-*` is old outdated package.

Please to switch to this feed https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/samples/HelloWorld/nuget.config#L6 and 6.0 package references https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/samples/HelloWorld/HelloWorld.csproj#L9
