### ISSUE TITLE
Linker warning when generating native dynamic .NET 5 library on MacOS

### ISSUE THREAD

**Issue by BasTossings** [dotnet/runtimelab#430]
When I compile my .net 5 class library into a native MacOS library I get the following linker warnings:

```
Generating native code
ld : warning : could not create compact unwind for _S_P_CoreLib_System_Number__Dragon4: stack subq instruction is too different from dwarf stack size [/Users/X/Documents/Source/AzureDevOps/Isotope/Frameworks/Aelian.Applications.MosNet.VST3Bootstrap/Aelian.Applications.MosNet.VST3Bootstrap.csproj]
ld : warning : can't parse dwarf compilation unit info in obj/Release/net5.0/osx-x64/native/Aelian.Applications.MosNet.VST3Bootstrap.o [/Users/X/Documents/Source/AzureDevOps/Isotope/Frameworks/Aelian.Applications.MosNet.VST3Bootstrap/Aelian.Applications.MosNet.VST3Bootstrap.csproj]
```

Is this going to give me trouble down the line?

I used `dotnet publish /p:NativeLib=Shared -r osx-x64 -c Release` to build the project

Also, on MacOS it produces a 14 MB dylib whereas the native windows x64 dll is only 5 MB. I used the following trimming options in the csproj:

```xml
<PropertyGroup>
    <IlcInvariantGlobalization>true</IlcInvariantGlobalization>
    <RootAllApplicationAssemblies>false</RootAllApplicationAssemblies>
    <IlcGenerateCompleteTypeMetadata>false</IlcGenerateCompleteTypeMetadata>
    <IlcGenerateStackTraceData>false</IlcGenerateStackTraceData>
</PropertyGroup>
```

Is there a reason the dylib is that much larger? And is there any way I can slim it down?

**Comment by jkotas** [comment]
> Is this going to give me trouble down the line?

We have not seen these warnings to result in real problems.

> MacOS it produces a 14 MB dylib whereas the native windows x64 dll is only 5 MB

Is it after you have stripped the symbols? https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/docs/using-nativeaot/optimizing.md#special-considerations-for-linuxmacos

**Comment by MichalStrehovsky** [comment]
Closing in favor of #956.
