### ISSUE TITLE
Does Native AOT warn me about code it doesn't support?

### ISSUE THREAD

**Issue by Shadowblitz16** [dotnet/runtimelab#434]
Does Native AOT give me warnings me about code it doesn't support?

**Comment by jkotas** [comment]
You will get warnings in some case. There is a lot of failure modes that you will only see at runtime. We are actively working on making this better and detecting more of the issue at build time. cc @MichalStrehovsky 

Are there specific areas that you would like to see warnings for?

**Comment by Shadowblitz16** [comment]
no I was just wondering if it had warnings so that it was easy to know what wasn't compatible.

**Comment by MichalStrehovsky** [comment]
You need to opt into the warnings though - they're disabled by default because you'll see many for code in the base class libraries that is hard to reason about.

To opt in, add `<SuppressTrimAnalysisWarnings>false</SuppressTrimAnalysisWarnings>` to a PropertyGroup in your csproj file.

**Comment by Shadowblitz16** [comment]
ok ty
