### ISSUE TITLE
[Native AOT]cannot run app if using <IlcDisableReflection>true</IlcDisableReflection>

### ISSUE THREAD

**Issue by unominhtuan** [dotnet/runtimelab#455]
I'm having trouble trying to use the cannot run app if using <IlcDisableReflection> true </IlcDisableReflection> to reduce the size of the app (with avaloniaui). the application after building cannot be started, no exceptions are thrown.
any solution for me? thanks
my options.

`<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net5.0</TargetFramework>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>

	<PropertyGroup>
		<IlcDisableReflection>true</IlcDisableReflection>
		<RootAllApplicationAssemblies>false</RootAllApplicationAssemblies>
		<IlcGenerateCompleteTypeMetadata>false</IlcGenerateCompleteTypeMetadata>
		<IlcGenerateStackTraceData>false</IlcGenerateStackTraceData>
		<IlcDisableUnhandledExceptionExperience>true</IlcDisableUnhandledExceptionExperience>
	</PropertyGroup>

	<ItemGroup Condition="$(RuntimeIdentifier.StartsWith('win'))">
		<NativeLibrary Include="WindowsApp.lib" />
	</ItemGroup>`

**Comment by jkotas** [comment]
You may be hitting #449

**Comment by FoggyFinder** [comment]
@unominhtuan make sure you run an app from the `publish` folder and not from the `native` one.

Previously both of them worked and I used one from the `native` folder (since there was less noise) maybe you're doing the same.

**Comment by unominhtuan** [comment]
@jkotas I added this code to the csproj file, but everything is still silent, the app still cannot launch
`<Target Name="CopyClrCompressionDll" AfterTargets="Publish" Condition="'$(RuntimeIdentifier)'=='win-x64'">
    <Copy SourceFiles="$(IlcPath)\framework\System.IO.Compression.Native.dll" DestinationFolder="$(PublishDir)" />
  </Target>`

only when I remove <IlcDisableReflection> true </IlcDisableReflection> will the application run

@FoggyFinder I run an app from the publish folder

**Comment by jkotas** [comment]
Avalonia is not compatible with the IlcDisableReflection mode. It depends on reflection here:
```
AvaloniaCoreRTDemo!S_P_DisabledReflection_Internal_Reflection_RuntimeTypeInfo__GetAttributeFlagsImpl+0x2b
AvaloniaCoreRTDemo!Avalonia_Visuals_Avalonia_AvaloniaPropertyExtensions__CanValueAffectRender+0x15 [D:\a\1\s\src\Avalonia.Visuals\AvaloniaPropertyExtensions.cs @ 18] 
AvaloniaCoreRTDemo!Avalonia_Visuals_Avalonia_Visual__AffectsRender_0<System___Canon>+0x3b [D:\a\1\s\src\Avalonia.Visuals\Visual.cs @ 365] 
AvaloniaCoreRTDemo!Avalonia_Visuals_Avalonia_Visual___cctor+0x79b [D:\a\1\s\src\Avalonia.Visuals\Visual.cs @ 109] 
```
There are likely many more places where average Avalonia app depends on reflection.
