### ISSUE TITLE
Need to copy project’s SxS manifest

### ISSUE THREAD

**Issue by wjk** [dotnet/runtimelab#476]
The ILCompiler package copies the version info resource from the input DLL to the output EXE automatically. This is a good thing. However, it only includes a static, predefined SxS manifest that specifies UAC `asInvoker` only. If I add an `app.manifest` file in my own project, it is dutifully ignored by ILC and the stock one written. As we work towards being able to AOT WinForms apps, we will need to fix this issue, as it is a major use-case there.

However, it is also a “low-hanging fruit” that someone (albeit not I) could fix today, and will have immediate impact (say, if the developer wants to make his program `requireAdministrator`). I don’t have enough experience with NativeAOT to implement this change myself yet (the codebase changed a lot since the corert days). Still, a PR may nevertheless be forthcoming to fix this problem. Thanks!

**Comment by MichalStrehovsky** [comment]
Hm, do you have repro steps for this? The compiler should copy all unmanaged resources to the output and we ask linker not to create a manifest - adding a `<ApplicationManifest>app.manifest</ApplicationManifest>` line to the main project file and publishing the project results in the specified manifest being present in the native executable for me.

**Comment by wjk** [comment]
Strangely, my repro project doesn’t repro anymore. A clean rebuild might have fixed things. Thanks nevertheless!
