### ISSUE TITLE
reflection free AOT?

### ISSUE THREAD

**Issue by gamedevcb** [dotnet/runtimelab#482]
According to the nativeAOT/CoreRT documentation:
https://github.com/dotnet/runtimelab/blob/feature/NativeAOT-LLVM/docs/using-nativeaot/reflection-free-mode.md

- compiling to binary with the reflection free mode enabled, should generate code with the same level of complexity as C++, as far as reverse engineering goes. 

My question is, can someone show me how to verify this? I tried opening the compiled .exe-s with dotnetpeek, and it didn't work, but it also didn't work when I did not enable reflection free compilation. Can someone point me to a software that would ordinarily decompile nativeAOT, but with this option enabled it would not?

Thanks!

**Comment by mahoshojoHCG** [comment]
Try IDA, it is a paid software but also have a free veision.

**Comment by MichalStrehovsky** [comment]
> Can someone point me to a software that would ordinarily decompile nativeAOT, but with this option enabled it would not

There is no specialized decompiler for Native AOT. If someone were to write one, they could use the reflection information to get some amount of detail about the app (names of methods, parameters, names of types, fields, etc.). But nobody has publicly done that, so currently there's really no difference between the two modes. Both are equally hard.

Note that with either reflection enabled or disabled, the available code is still just the machine code - we don't keep the source IL - so NativeAOT will never be as easy to decompile as regular .NET.

You could also try [Ghidra](https://ghidra-sre.org/) as a free alternative to IDA.
