### ISSUE TITLE
 NativeAOT-LLVM web assembly?

### ISSUE THREAD

**Issue by gamedevcb** [dotnet/runtimelab#483]
The NativeAOT-LLVM repo is supposed to generate web assembly output. However, when I followed the tutorials and generated the 'Hello World' example, it only produced an .exe file? How can I use NativeAOT-LLVM to produce a wasm file that can be executed in the browser?

**Comment by yowl** [comment]
I guess you are trying to follow the Convenience Visual Studio "repro" project  instructions.  Unfortunately they've not been updated for Wasm, apologies.  If you want to run the compiler in the debugger for working on it, or just for fun, then you'll need to update the `rsp` file, I can help you with that if that is what you are after.  If you just want to build something and run it in the browser, or node.js, then you can just create your own .net 5 project and follow this part of the instructions:
```
Run build nativeaot+libs+nativeaot.packages -rc [Debug|Release] -lc [Debug|Release] -a wasm -os Browser -runtimeFlavor CoreCLR
Add the package directory to your nuget.config as above.
Run dotnet publish -r browser-wasm -c [Debug|Release] /p:Platform=wasm to publish.
```

**Comment by gamedevcb** [comment]
> uild nativeaot+libs+nat

Thanks, I tried this but it didn't work! It gave me the following error:

`"build.cmd : The term 'build.cmd' is not recognized as the name of a cmdlet, function, script file, or operable program. "`

I had a look at the pre-requisities, and I installed the component 'C++/CLI support for v142 build tools'. (I am on VS 16.9.0 preview 2.0 and I already had the 'Workload/Desktop development with C++' workload). But this did not make a difference. What am I missing?

**Comment by yowl** [comment]
That looks like a message from Powershell which is a bit odd.  Can you build the non-llvm tools:

`build.cmd nativeaot+libs+nativeaot.packages -rc Debug -lc Release`

?

**Comment by gamedevcb** [comment]
@yowl,  same error,: 
`build.cmd : The term 'build.cmd' is not recognized as the name of a cmdlet, function, script file, or operable program.  `
I think I am missing something, what does build.cmd normally come with?

**Comment by yowl** [comment]
Are you starting the build from within a powershell? You don't need to do that, from the windows menu, type x64 and you should get an option that is a visual studio 2019 command shell, click that and CD into the root of the repo and run the build command.  If that doesn't work, or it's what you are already doing,  then attach a screenshot.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gamedevcb** [comment]
@yowl
![buildcmd](https://user-images.githubusercontent.com/76231490/102698559-3d5b6880-4236-11eb-93b1-116f17fb69bf.png)

- I think I am missing either a component, or something from the PATH... ?

**Comment by yowl** [comment]
What else is in this folder?.  Have you cloned the repo from here?  Build.cmd should be in the root of the repo, ie exactly where you are : https://github.com/dotnet/runtimelab/blob/feature/NativeAOT-LLVM/build.cmd

**Comment by yowl** [comment]
https://www.techjunkie.com/is-not-recognized-as-an-internal-or-external-command/ might also be useful, although I've not encountered this problem myself
