### ISSUE TITLE
[NativeAOT] How to reduce size of published shared library?

### ISSUE THREAD

**Issue by Symbai** [dotnet/runtimelab#524]
I was trying out nativeAOT following this [guide](https://github.com/dotnet/runtimelab/tree/feature/NativeAOT/samples/NativeLibrary#building-native-libraries-with-corert) but I'm using a new **empty** .NET 5 dll project. The output size were **4.5mb** for literally NO code at all.

Then I was trying to add some lines:
```JS
<PropertyGroup>
	<IlcDisableReflection>true</IlcDisableReflection>
	<RootAllApplicationAssemblies>false</RootAllApplicationAssemblies>
	<IlcGenerateCompleteTypeMetadata>false</IlcGenerateCompleteTypeMetadata>
	<IlcGenerateStackTraceData>false</IlcGenerateStackTraceData>
	<IlcDisableUnhandledExceptionExperience>true</IlcDisableUnhandledExceptionExperience>
	<IlcOptimizationPreference>Size</IlcOptimizationPreference>
</PropertyGroup>
```

This reduced the size from 4.5mb to 1mb. But imagine that its an empty project, it's still waaaaay too big. With C++ or Pascal I'm within 100kb area.

Is there more I can do to reduce the size or is it expected to be 10 times larger than other AOT compilers?

**Comment by jkotas** [comment]
Yes, this is what you can get in the ballpark. We do not plan to work on reducing .dlls down to 100kB as part of this experimental project.
