### ISSUE TITLE
NativeAot-LLVM: Question: PortableThreadPool.WorkerThread.cs

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#544]
I'm trying to merge in the latest and hitting a few thread related compilation problems with `System.Private.CoreLib`.  E.g.

```
E:\GitHub\runtimelab\src\libraries\System.Private.CoreLib\src\System\Threading\PortableThreadPool.WorkerThread.cs(298,34): 
error CS1061: 'Thread' does not contain a definition for 'UnsafeStart' and no accessible extension method 'UnsafeStart' accepting 
a first argument of type 'Thread' could be found (are you missing a using directive or an assembly reference?)
 [E:\GitHub\runtimelab\src\coreclr\nativeaot\System.Private.CoreLib\src\System.Private.CoreLib.csproj]
```

Maybe related to https://github.com/dotnet/runtime/commit/2a234f91fc654381d5bd2d001c59c48b3634b4ab 

For the LLVM backend, where just Wasm is supported, should `PortableThreadPool.WorkerThread.cs` be included in the build of `System.Private.CoreLib` ?

**Comment by jkotas** [comment]
For wasm, this should use something similar to the Mono browser-specific implementations https://github.com/dotnet/runtime/blob/master/src/mono/netcore/System.Private.CoreLib/src/System/Threading/ThreadPool.Browser.Mono.cs, https://github.com/dotnet/runtime/blob/master/src/mono/netcore/System.Private.CoreLib/src/System/Threading/Thread.Browser.Mono.cs, etc.

I would start by adding implementations that just throw PNSE for browser to get things to compile.

**Comment by yowl** [comment]
Thanks!
