### ISSUE TITLE
DateTime.Now Error

### ISSUE THREAD

**Issue by kkptm** [dotnet/runtimelab#561]
There is always an error when using DateTime.Now

**Comment by kkptm** [comment]
Setting ilcDisableReleConnection to false solves this problem, but creates a new one: the program may not run on older versions of Windows(WIndows7)

**Comment by jkotas** [comment]
>  Setting ilcDisableReleConnection to false solves this problem, but creates a new one: the program may not run on older versions of Windows(WIndows7)

Why would it not run on Windows 7?

**Comment by kkptm** [comment]
I think it might be necessary to make this kind of library stable with reflection disabled,this is ultimately what needs to be done.

**Comment by jkotas** [comment]
The no-reflection mode is very experimental. It is expected that many APIs won't work well in this mode. 

However, I agree that it is a general goodness to avoid pulling in reflection for `DateTime.UtcNow`: https://github.com/dotnet/runtime/pull/47013

**Comment by jkotas** [comment]
This will be fixed by #562
