### ISSUE TITLE
NativeAOT Avalonia UI compilation problems

### ISSUE THREAD

**Issue by josephmoresena** [dotnet/runtimelab#597]
From Microsoft.DotNet.ILCompiler version 6.0.0-alpha.1.21072.1 compilation of AvaloniaUI apps takes a long time and reaches high ram consumes, additionally it generates warnings on System.Reactive following methods:
[System.Reactive]System.Reactive.Concurrency.CatchScheduler1+CatchSchedulerPeriodic+PeriodicallyScheduledWorkItem1<System.__Canon,System.ValueTuple2<System.__Canon,System.__Canon>>.Tick(ValueTuple2<__Canon,__Canon>)
[System.Reactive]System.Reactive.Concurrency.CatchScheduler1+CatchSchedulerPeriodic+PeriodicallyScheduledWorkItem1<System.__Canon,System.__Canon>.Tick(__Canon)

The warning says: "Method will always throw because: Invalid IL or CLR metadata".
The Attached build log was generated compiling [https://github.com/teobugslayer/AvaloniaCoreRTDemo](url) on 
Windows.

[output.zip](https://github.com/dotnet/runtimelab/files/5877189/output.zip)

**Comment by jkotas** [comment]
cc @MichalStrehovsky Fallout from unifying the defaults for 3rd party code with IL linker?

**Comment by MichalStrehovsky** [comment]
Yes. @josephmoresena replacing this line:

https://github.com/teobugslayer/AvaloniaCoreRTDemo/blob/4a2207a19f47913bcfcfa02a7b5911f195b7c9f8/src/AvaloniaCoreRTDemo.csproj#L11

with

```
<TrimMode>link</TrimMode>
```

Should fix that.

**Comment by josephmoresena** [comment]
> Yes. @josephmoresena replacing this line:
> 
> https://github.com/teobugslayer/AvaloniaCoreRTDemo/blob/4a2207a19f47913bcfcfa02a7b5911f195b7c9f8/src/AvaloniaCoreRTDemo.csproj#L11
> 
> with
> 
> ```
> <TrimMode>link</TrimMode>
> ```
> 
> Should fix that.

Thanks Michal, although the warnings has gone and has reduced to half the RAM consumption it still is too high (almos 4.3GB).

**Comment by josephmoresena** [comment]
> Yes. @josephmoresena replacing this line:
> 
> https://github.com/teobugslayer/AvaloniaCoreRTDemo/blob/4a2207a19f47913bcfcfa02a7b5911f195b7c9f8/src/AvaloniaCoreRTDemo.csproj#L11
> 
> with
> 
> ```
> <TrimMode>link</TrimMode>
> ```
> 
> Should fix that.

Thanks Michal, although the warnings has gone and has reduced to half the RAM consumption it still is too high (arround 4.3GB).

**Comment by MichalStrehovsky** [comment]
Last time I was looking at Avalonia, it was producing executables more than 100 MB in size. There's just too much code and data structures required. How big is the executable you're looking at?

The RAM used at compile time is usually proportional to the size of the executable. If the executable is huge, the RAM usage will be high too.

**Comment by josephmoresena** [comment]
> Last time I was looking at Avalonia, it was producing executables more than 100 MB in size. There's just too much code and data structures required. How big is the executable you're looking at?
> 
> The RAM used at compile time is usually proportional to the size of the executable. If the executable is huge, the RAM usage will be high too.

Today 50.9 MB for win-x64 and 93.7 MB for linux-x64 WSL (53.8 MB after strip).

**Comment by FoggyFinder** [comment]
> Today 50.9 MB for win-x64 and 93.7 MB for linux-x64 WSL (53.8 MB after strip).

Wow. Sounds promising. Last time my app was 104Mb (on latest 0.10.0-rc1 version of Avalonia). To compare: 0.9.11 produces 89Mb.

**Comment by josephmoresena** [comment]
> > Today 50.9 MB for win-x64 and 93.7 MB for linux-x64 WSL (53.8 MB after strip).
> 
> Wow. Sounds promising. Last time my app was 104Mb (on latest 0.10.0-rc1 version of Avalonia). To compare: 0.9.11 produces 89Mb.

I'm using 0.10.0 release now, if I ain't wrong me with 0.9.11 release this app was approximately 69 Mb for win-x64.

**Comment by jkotas** [comment]
This will be fixed by https://github.com/teobugslayer/AvaloniaCoreRTDemo/pull/7 . @josephmoresena Thank you for submitting the PR to fix it!

**Comment by jamsoft** [comment]
Hmm, my windows .exe is 269mb and my OSX app is 1.3gb ...

**Comment by jkotas** [comment]
> Hmm, my windows .exe is 269mb and my OSX app is 1.3gb ...

https://docs.microsoft.com/en-us/dotnet/core/deploying/native-aot#native-debug-information

**Comment by jamsoft** [comment]
I was reading some of the threads earlier today and decided to look at this very setting tonight and see how things pan out size wise.

Thanks for the headsup.
