### ISSUE TITLE
[ NativeAOT ] ILCompiler.CodeGenerationFailedException: Code generation failed with System.NotImplementedException: getFunctionEntryPoint

### ISSUE THREAD

**Issue by FoggyFinder** [dotnet/runtimelab#603]
Upgraded to .net 5, now getting an odd `ILCompiler.CodeGenerationFailedException` exception.

StackTrace:

```
  Unhandled exception. ILCompiler.CodeGenerationFailedException: Code generation failed for method '[MCVENativeAOT]Program+doSmth@12.Invoke(SomeType)'
   ---> System.NotImplementedException: getFunctionEntryPoint
     at Internal.JitInterface.CorInfoImpl.getFunctionEntryPoint(CORINFO_METHOD_STRUCT_* ftn, CORINFO_CONST_LOOKUP& pResult, CORINFO_ACCESS_FLAGS accessFlags)
     at Internal.JitInterface.CorInfoImpl._getFunctionEntryPoint(IntPtr thisHandle, IntPtr* ppException, CORINFO_METHOD_STRUCT_* ftn, CORINFO_CONST_LOOKUP* pResult, CORINFO_ACCESS_FLAGS accessFlags)
     --- End of inner exception stack trace ---
     at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(IMethodNode methodCodeNodeNeedingCode, MethodIL methodIL)
     at Internal.JitInterface.CorInfoImpl.CompileMethod(MethodCodeNode methodCodeNodeNeedingCode, MethodIL methodIL)
     at ILCompiler.RyuJitCompilation.CompileSingleMethod(CorInfoImpl corInfo, MethodCodeNode methodCodeNodeNeedingCode)
     at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
Here is MCVE:

```fs
open System

type SomeType = {
    Id : int
    Value : string
} 
with override i.ToString() = i.Value

let doSmth (xs:SomeType list) = 
    xs
    |> List.map(fun st -> string st.Id)

let r = Random()
let testData = 
    [0..5..30]
    |> List.map(fun i -> { Id = i; Value = string <| r.Next()})

let output =
    testData
    |> doSmth

output
|> Seq.iter(Console.WriteLine)
```

I can attach an archive with sample or create a repo if it make it easier to investigate.

**Package version:** 6.0.0-preview.2.21078.1

**Comment by MichalStrehovsky** [comment]
Did you use `<RootAllApplicationAssemblies>false</RootAllApplicationAssemblies>` in your csproj? If so, this option was removed. `<LinkMode>trim</LinkMode>` will give you the equivalent behavior. We're aligning with how these settings are named in the .NET 5 SDK (that finally added these options into the official product).

**Comment by FoggyFinder** [comment]
> Did you use <RootAllApplicationAssemblies>false</RootAllApplicationAssemblies> in your csproj? If so, this option was removed.

Nope, I didn't specify any options, .fsproj looks like

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.DotNet.ILCompiler" Version="6.0.0-*" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

</Project>
```
In my real app I have

```xml
<TrimMode>link</TrimMode>
```

though. Anyway it doesn't change anything and seems unrelated.

**Comment by MichalStrehovsky** [comment]
Oh, okay. Then it's probably different IL generated by the F# compiler that comes with .NET 5. I was hoping we wouldn't need to fully implement getFunctionEntrypoint, but I guess we have to.

**Comment by FoggyFinder** [comment]
Workaround. Replace

```fs
|> List.map(fun st -> string st.Id)
``` with

```fs
|> List.map(fun st -> st.Id.ToString())
```

unsure why it's matter and why it was working before

**Comment by MichalStrehovsky** [comment]
The former is producing some particularly bad IL that RyuJIT is desperately trying to optimize (this should have been generated as a constrained call; instead RyuJIT needs to fight the boxing, virtual call, and we then fail for getFunctionEntryPoint on System.Int32. C# doesn't generate code like this and that's why we haven't needed this before.

```
  IL_0000:  ldarg.1
  IL_0001:  ldfld      int32 Program/SomeType::Id@
  IL_0006:  stloc.0
  IL_0007:  ldloc.0
  IL_0008:  box        [System.Runtime]System.Int32
  IL_000d:  unbox.any  [System.Runtime]System.IFormattable
  IL_0012:  ldnull
  IL_0013:  call       class [netstandard]System.Globalization.CultureInfo [netstandard]System.Globalization.CultureInfo::get_InvariantCulture()
  IL_0018:  tail.
  IL_001a:  callvirt   instance string [netstandard]System.IFormattable::ToString(string,
                                                                                  class [netstandard]System.IFormatProvider)
```

**Comment by MichalStrehovsky** [comment]
I'll try to look into it sometime next week. `getFunctionEntryPoint` on CoreCLR is doing some particularly weird things that I don't understand and I need to understand the subtleties of that to actually implement this. Fixing this particular case would be a one-liner (just don't throw), but the throw is there because there might be dragons.

Unfortunately crossgen2 seems to be fine with just having all of this be jitted, so I can't steal the implementation from there:

https://github.com/dotnet/runtimelab/blob/0a644c722ebdbd96974614fe171c683fcbc56dc1/src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs#L822-L825

**Comment by MichalStrehovsky** [comment]
Nuget with the fix should be out within 24 hours or so. Thanks for reporting this!

**Comment by FoggyFinder** [comment]
Wow. I didn't expect fix will be provided & merged so fast. Honestly I thought it would be more complicated :-)

**Comment by MichalStrehovsky** [comment]
Well i just carefully avoided the problem because the full fix is not needed here. I think I could also do the full fix for this, but I don't understand it's purpose and I haven't seen a test for that behavior yet, so I keep pushing it away.
