### ISSUE TITLE
[NativeAOT] Package preview.2.21077.1 broke pipelines

### ISSUE THREAD

**Issue by mrhelmut** [dotnet/runtimelab#604]
Hello there,

Since package version ```6.0.0-preview.2.21077.1``` our builds are failing to execute.

When building, we are getting several warning about structures that are missing marshalling information while they do have those information (we were not getting those before). Upon running, when run into exceptions indicating the same thing and that we should add the marshalling information to the ```rd.xml``` file.
Did we miss a breaking change? This is about structs.

Sorry for the lack of context, I'm a bit in a hurry right now.

Cheers!

**Comment by MichalStrehovsky** [comment]
There was a change in how the detection of `Marshal.SizeOf(Type)` is done. It should work for the simple cases because we do have test coverage for it:

https://github.com/dotnet/runtimelab/blob/e28a3923884274e2c541f1ac8ee8d70ac58bfbaa/src/tests/nativeaot/SmokeTests/PInvoke/PInvoke.cs#L998-L999

Is there anything special in how this API is called in your codebase?

One thing that I know would have regressed is if this API is used through a generic wrapper (e.g. `int SizeOfWrapped<T> => Marshal.SizeOf(typeof(T))`). This was not 100% reliable before either but now it won't work at all (and will warn).

`Marshal.SizeOf<T>()` should be used instead of the override that takes a `System.Type` as much as possible.

**Comment by mrhelmut** [comment]
Here's one of the regression:

**Comment by mrhelmut** [comment]
Here's one of the type that regressed:

https://github.com/rlabrecque/Steamworks.NET-Example/blob/master/Assets/Plugins/Steamworks.NET/autogen/SteamCallbacks.cs#L2290

We have a few other but unfortunately they are closed source.

**Comment by MichalStrehovsky** [comment]
How is the Marshal.SizeOf called for it (at the spot where this is failing at runtime)?

I assume it's not just `Marshal.SizeOf(typeof(UserAchievementStored_t))` because that should work.

**Comment by mrhelmut** [comment]
This particular type indeed is used as part of a call to ```Marshal.SizeOf(typeof(T))```. Here, for instance: 
https://github.com/rlabrecque/Steamworks.NET-Example/blob/master/Assets/Plugins/Steamworks.NET/CallbackDispatcher.cs#L77

Contrary to my initial statement, we don't (always?) get compiler warnings about these types. Some do, some don't. This one doesn't.

It's kind of complex to get through this. In our case, there are a lot of types which have regressed and most of them are in closed assemblies. So it's basically a game of hit & repeat until we managed to get a full coverage, and possibly involving disassembling stuff. Not unmanageable, but very tedious.

**Comment by MichalStrehovsky** [comment]
> This particular type indeed is used as part of a call to Marshal.SizeOf(typeof(T)). Here, for instance:
https://github.com/rlabrecque/Steamworks.NET-Example/blob/master/Assets/Plugins/Steamworks.NET/CallbackDispatcher.cs#L77

Ah, yes, that's specifically where I knew we would be losing the heuristic. I was hoping people don't do that when a generic method is available on Marshal but I realize the generic version was only added in .NET 4.5 and a lot of code was written before that.

For background, we picked up the dataflow analysis engine that IL Linker uses and while the dataflow engine is a lot more powerful, it only operates on uninstantiated method bodies. The previous engine (which really was just a 300 line quick hack) operated on _some_ instantiated bodies and it would generally work as long as the T was a struct.

The RD.XML the error message is referring to is only supported in .NET Native for UWP apps - it shouldn't be hard to add it to NativeAOT/CoreRT too - let me know if you're blocked on that and I can add it. It would basically work like the [MarshalStructure](https://docs.microsoft.com/en-us/dotnet/framework/net-native/runtime-directives-rd-xml-configuration-file-reference) directive in .NET Native - you list every type that didn't have marshalling information pregenerated in the XML file and the compiler will make sure it's generated.

> And, how do these cases can be handled?

Those cases were even previously operating on luck so hopefully they will still have the same luck :). The compiler pregenerates the data needed to compute marshalling sizes if the type is used in a p/invoke method signature so maybe all of those types were used in p/invokes. Or maybe they are all blittable.

**Comment by mrhelmut** [comment]
Having the directive implemented in RD.XML might be handy for cases where assemblies are source closed. Though not a blocker so far. I've been able to locally fix all the assemblies that we use (which mostly were Steamworks.NET, to which I can propose changes; Epic Games SDK, with whom I can discuss with the engineering team which seem keen to support AOT scenarios; and MonoGame, which we'll get fixed easily).

**Comment by MichalStrehovsky** [comment]
#646 will add support for the directive. Hopefully it unblocks everything. Sorry for the breakage!
