### ISSUE TITLE
RequiresDynamicCodeAttribute warnings in HelloWorld 

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtimelab#615]
Repro: Build samples\HelloWorld using the latest package

Result:
```
/_/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/TraceLogging/PropertyValue.cs(200): AOT analysis warning IL9700: System.Diagnostics.Tracing.PropertyValue.GetReferenceTypePropertyGetter(PropertyInfo): Calling 'System.Type.MakeGenericType(Type[])' which has `RequiresDynamicCodeAttribute` can break functionality when compiled fully ahead of time. [C:\runtimelab\samples\HelloWorld\HelloWorld.csproj]
/_/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/TraceLogging/PropertyValue.cs(210): AOT analysis warning IL9700: System.Diagnostics.Tracing.PropertyValue.TypeHelper.GetGetMethod(PropertyInfo,Type): Calling 'System.Type.MakeGenericType(Type[])' which has `RequiresDynamicCodeAttribute` can break functionality when compiled fully ahead of time. [C:\runtimelab\samples\HelloWorld\HelloWorld.csproj]
```

**Comment by jkotas** [comment]
@MichalStrehovsky `MakeGenericType` is only used for reference types here. Should this be marked as AOT-safe?

**Comment by MichalStrehovsky** [comment]
The one on line 200 is safe, but the one on line 210 doesn't look like it. It's getting called with a finite number of valuetypes, but there are valuetype instantiations for it.

There is a cast to the type we're constructing, so maybe that's the thing that made this work in .NET Native. I'm not sure how that worked. https://github.com/dotnet/corert/issues/7505 was a similar pattern.

I really don't want to promote types used in casts to full EETypes to make patterns like this to work.

**Comment by jkotas** [comment]
> It's getting called with a finite number of valuetypes, but there are valuetype instantiations for it.

Should we add generic overload of GetGetMethod and use it for this finite number of valuetypes?

**Comment by MichalStrehovsky** [comment]
If I understand your proposal correctly, that wouldn't help because we only scan the generic definitions of the method bodies, not their instantiated version - so whether the known System.Type comes as a parameter or a generic parameter doesn't matter - we don't see it.

Seems like we used RD.XML to root these types in .NET Native.

**Comment by jkotas** [comment]
I meant:
```csharp
            private static Func<TContainer, TProperty> GetGetMethod<TProperty>(PropertyInfo property) =>
                property.GetMethod!.CreateDelegate<Func<TContainer, TProperty>>(property.DeclaringType!);
...
                    if (type == typeof(bool)) { var f = GetGetMethod<bool>(property); return container => new PropertyValue(f((TContainer)container.ReferenceValue!)); }
...
```
If this does not work for some reason, I think we should fix that in `MethodInfo.CreateDelegate<T>`

**Comment by MichalStrehovsky** [comment]
Ah, that should work. I missed the fact that we're already generic over `TContainer`. Thansk!
