### ISSUE TITLE
Cannot publish custom runtime

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtimelab#632]
@jkotas I'm playing with custom runtime for UEFI.
Prior to NativeAOT I add following lines to project file
```
<SelfContained>false</SelfContained>
<UseAppHost>false</UseAppHost>
```

As was mentioned in the #589 this results in the error from ILLink `NETSDK1102: Optimizing assemblies for size is not supported for the selected publish configuration. Please ensure that you are publishing a self-contained app.`

I understand why this cannot be easily done. I take a look at MSBuild files and options which I see is too hacky.
I'm not scary of them, but want to consult about direction.
- I somehow create custom AppHost to which bootstrap UEFI runtime for me.
- Somehow disable AppHost generation altogether.

While I write this I decide give one more round of debugging and at least disable AppHost generation (?) by specifying 
`<ComputeNETCoreBuildOutputFiles>false</ComputeNETCoreBuildOutputFiles>`. I think this is not full fix, since I cannot make UEFI application run, but neverless I want to preserve my findings for somebody else. Also I would like to know is this even right direction to dig?

**Comment by MichalStrehovsky** [comment]
If you can somehow kick PrepareForILLink out of IlcCompileDependsOn, that would probably help. Why do you need to set SelfContained to false though?

https://github.com/dotnet/runtimelab/blob/c1f54d8e34bf22af412177c7dc0c58485fec2c37/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.targets#L88

**Comment by kant2002** [comment]
I'm not sure that this is strictly needed right now, because I implement that as workaround for something.
1. I have 2 projects. EfiRuntime + HelloWorld project. Both of them have `<NoStdLib>true</NoStdLib>`
2. HelloWorld depends on EfiRuntime which very stripped version of `System.Private.CoreLib`, or if you like slightly enhanced yours MiniRuntime
3. I have  `<DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>` lead me to `<UseAppHost>false</UseAppHost>`
4. `<UseAppHost>false</UseAppHost>` lead me to `<SelfContained>false</SelfContained>`

I'm not really sure why I have to remove implicit framework references, but at least this removes `microsoft.netcore.app.runtime.win-x64` DLL from ILC compilation. Which I do not think I should be part of my compilation process given that I explicitly want use only custom framework.
Your question allow me re-evaluate my life choices, at least everything compiled once I remove `<DisableImplicitFrameworkReferences>` and others mentioned earlier switches, but application still does not work, but that's likely unrelated.

**Comment by kant2002** [comment]
I was not able override linker subsystem, and have to patch MSBuild files #633
