### ISSUE TITLE
[NativeAOT] Segmentation fault calling SHA256.HashData on linux

### ISSUE THREAD

**Issue by mazdak-dev** [dotnet/runtimelab#648]
Calling SHA1/SHA256 hash methods (HashData, ComputeHash) lead to segmentation fault on Debian 10.

Code:
`var buffer = SHA256.HashData(new byte[] {0});
Console.WriteLine(buffer.Length);`

gdb output:
`Reading symbols from Showcase...done.
(gdb) run
Starting program: /mnt/d/Development/Workshop/Showcase/bin/Release/net5.0/linux-x64/native/Showcase
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffd7548700 (LWP 5524)]

Thread 1 "Showcase" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()`

**Comment by jkotas** [comment]
Thank you for reporting this!

Regression triggered by https://github.com/dotnet/runtime/pull/46640 . We do not correctly handle precise static constructors for inlineable PInvokes.

**Comment by MichalStrehovsky** [comment]
Fixed in #651. NuGet package with the fix should be out within 24 hours.
