### ISSUE TITLE
Unhandled exception at 0x00007FFDF663BD5C (KernelBase.dll) in ConsoleApp.exe: 0x00001001

### ISSUE THREAD

**Issue by netcorefan1** [dotnet/runtimelab#673]
Hello,
when I call an exported function from a C# console application, as soon as I try to step into the exported function I get the exception in the title after a couple of seconds. Before the exception occurs sometimes I can also see the variables value. If I step over and remove the breakpoint (as showed in the video below) I don't get any exception and the program execution flow continue without any problem.
It doesn't matter if I directly pinvoke the function or use a delegate.
`Unhandled exception at 0x00007FFDF663BD5C (KernelBase.dll) in ConsoleApp.exe: 0x00001001.
The Common Language Runtime cannot stop at this exception. Common causes include: incorrect COM interop marshalling and memory corruption. To investigate further use native-only debugging.`

https://user-images.githubusercontent.com/63934725/107553464-15083e80-6bd5-11eb-9c14-98b2c10e69ab.mp4

1.  I suppose that this exception is voluntarily raised from your staff because basically I am trying to debug a library that now is completely native. If I execute the function without stepping through code, can I assume that it will be safe as seems to be from the video or I can expect bad things?
2. How it is possible to debug the C# code? The doc gives some tips and I can debug the provided "LoadLibrary.c", but this is unmanaged and will be very hard if I can't step into C#. Is there a workaround or at least a way to debug portions of C# code?
3. Should I have used `<DirectPInvoke Include="NativeLibrary!add" />` ??
Thanks

Edit: Strangely, from a c++ console app, the same code debug fine or at least the debug output does not shows anything wrong:

https://user-images.githubusercontent.com/63934725/107573332-b26f6c80-6bed-11eb-8334-eb425544aa01.mp4

At this point I am wondering what is the right way to go and if the exceptions I'm getting from a C# console app are due to something wrong from my side.

**Comment by jkotas** [comment]
This looks same as #359. I am able to reproduce it - looks like some bad iteration between debugger and EH.

**Comment by netcorefan1** [comment]
That means that what I am doing is supported and I should not go into this problem.
When I activated symbol server I also got `Runtime-generated FailFast: (1): Runtime internal error`
The exception seems to be generated inside `{NativeLibrary.dll!RhpReversePInvoke2(ReversePInvokeFrame *)}`
So, if I have understood well, this should have to do with VS debugger being too aggressive and/or the lack of cooperation between the two sides.
I have attached here a sample project if that can help you.
Depending from how to you step or where you put the breakpoint you may have different exceptions. However, one things is sure: indifferently from the method you use to call the function (pinvoke, loadlibrary etc), once you are inside the function, you will not exit anymore!

[NativeAOT2.zip](https://github.com/dotnet/runtimelab/files/5968036/NativeAOT2.zip)
(the command I used to compile: `dotnet publish -c Debug -r win-x64 /p:NativeLib=Shared /p:SelfContained=true`)

**Comment by jkotas** [comment]
#685 has the fix

**Comment by MichalStrehovsky** [comment]
The package with the fix should be out within 24 hours or so.
