### ISSUE TITLE
NativeAOT libobjwriter not found on Linux

### ISSUE THREAD

**Issue by wjk** [dotnet/runtimelab#699]
I'm running Debian 10 (buster), and attempting to compile the HelloWorld example as from this repo. It all goes well until ILC attempts to load `libobjwriter.so` and fails, complaining the library isn’t in any of the search paths. This file is next to the ilc binary on disk, so adding `$ORIGIN` to the LD_LIBRARY_PATH environment variable should solve the problem (`$ORIGIN` expands to the directory containing the current file, in this case the ilc binary, which is where libobjwriter is located). However, I tried that, and nothing happens; it still fails. I cannot cross-compile when using NativeAOT (I tried on macOS, and it chokes on the Linux-native binary), so I cannot build on macOS or on Windows where the build system is more tested. Would anyone mind giving me some pointers on how to fix this problem? I am using ILC version 6.0.0-preview.2.21116.4. Thanks!

**Comment by jkotas** [comment]
This is usually caused by missing dependencies.

Could you please run `ldd` on [libobjwriter.so](https://github.com/dotnet/corert/issues/7096#issuecomment-488239030) to see what's missing?

**Comment by wjk** [comment]
Indeed, `libtinfo.so.5` was missing. Installing the `libtinfo5` Debian package fixed ILC. I also needed to install the `zlib1g-dev` and `libkrb5-dev` packages before Clang would link properly. Works great now. Thanks!
