### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by sekkit** [dotnet/runtimelab#700]
Will there be iOS support in the future?

**Comment by huoyaoyuan** [comment]
runtime repo has already iOS support in preview.

**Comment by sekkit** [comment]
> runtime repo has already iOS support in preview.

that preview seems to be xamarin.iOS which means no .NET AOT but Mono AOT

**Comment by ryancheung** [comment]
It seems dotnet 6 would still use Mono AOT for iOS. The Native AOT and Mono AOT probably coexists for some time.

**Comment by jkotas** [comment]
We are open to contributions to make this possible, but it is not something the core team working on this project plans to spend time on in foreseeable future.

The first step would be to add support for macOS Arm64 (Apple Silicon) that should be very close. We have Windows and Linux arm64 building as of a few days ago (#738).

**Comment by filipnavara** [comment]
This shipped in .NET 8 as experiment. Let's close this.
