### ISSUE TITLE
Cannot build Debug version of ObjWriter

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtimelab#708]
The Debug build of ObjWriter fails with llvm-tblgen.exe complaining that it doesn't understand the `-gen-attrs` parameter.

I spent 3 minutes debugging it, but command line argument parsing is done using some C++ bs instead of `if` checks that I didn't have the nerves to untangle.

Restoring the `  -DLLVM_OPTIMIZED_TABLEGEN=1 ^` line in build.cmd fixed the problem for me.

Cc @AntonLapounov in case you saw this.

**Comment by AntonLapounov** [comment]
Yes, I have seen that. Apparently something is wrong with the debug build of `llvm-tblgen.exe` and you have to build it optimized. Is `RelWithDebInfo` not good enough for debugging?

**Comment by MichalStrehovsky** [comment]
Debug build of ObjectWriter are currently asserting left and right so probably it would be a good idea to build it Debug from time to time (apparently, we [shut LLVM down](https://github.com/dotnet/runtimelab/blob/1883ced99453c8f4ab38eb941a57925ce32df893/src/coreclr/tools/aot/ObjWriter/objwriter.cpp#L82) when the `Init` method finishes for reasons I don't understand and there are some reads beyond the bounds of `std::vector` too). I'm currently digging through those.

I'm surprised it lasted us for so long (nobody really touched it in years).

**Comment by AntonLapounov** [comment]
@MichalStrehovsky I have mentioned that the debug build of `objwriter` seem broken on Windows. In `llvm_shutdown` they go through the `StaticList` and `destroy` everything. The problem is that that list is actually a loop, so it would try to `destroy` already `destroy`ed objects. I guessed that the order of initialization might be different on Windows. Good luck with debugging it. :)

**Comment by AntonLapounov** [comment]
LLVM bug for this issue: https://bugs.llvm.org/show_bug.cgi?id=41367.

**Comment by MichalStrehovsky** [comment]
Heh, I was debugging this too but didn't bother looking for LLVM bugs.

I assume this is also the reason why llvm-tblgen doesn't work in Debug builds (it actually _uses_ the command line BS that is broken here, instead of being merely left with it because we don't end up eliminating the useless code that just breaks thing badly from the object writer library).

**Comment by jkotas** [comment]
> LLVM bug for this issue: https://bugs.llvm.org/show_bug.cgi?id=41367.

The fix is one-liner. Can we include it in our local patch?

**Comment by MichalStrehovsky** [comment]
I tried the code that is in ManagedStatic in the mainline LLVM and it didn't fix the issue for me. It's possible I did something wrong. I'll look at it again next week.

For reference, this is the underlying issue for both the debug build break, and the assert at runtime when we initialize objwriter.

**Comment by MichalStrehovsky** [comment]
>I tried the code that is in ManagedStatic in the mainline LLVM and it didn't fix the issue for me

I fell into the trap of build.cmd wiping my local changes to LLVM. Need to export them into the patch file first.
