### ISSUE TITLE
NativeAOT-LLVM: Align 8 Finalizable types

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#712]
How is 

https://github.com/dotnet/runtimelab/blob/1883ced99453c8f4ab38eb941a57925ce32df893/src/coreclr/nativeaot/Runtime.Base/src/System/Runtime/RuntimeExports.cs#L44-L45

reconciled with 

https://github.com/dotnet/runtimelab/blob/1883ced99453c8f4ab38eb941a57925ce32df893/src/coreclr/nativeaot/Runtime/portable.cpp#L184-L187

I'm hitting this for Wasm32 with ` public static readonly TplEventSource Log = new TplEventSource();`

I.e. should it be possible to ask for a finalizable type at 8 alignment, or has wasm incorrectly marked the type as `RequiresAlign8` ?

**Comment by jkotas** [comment]
I think it should be possible for a finalizable type to be aligned at 8 bytes. I do not see anything that would prevent it. Looks like this `ASSERT_UNCONDITIONALLY("UNREACHABLE")` is a mistake.
