### ISSUE TITLE
PreserveSig not supported

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtimelab#727]
Right now `PreserveSig == false` does not supported for PInvoke calls.
This blocks WinForms applications from using NativeAOT (in addition to COM for sure).

I have [test application](https://github.com/kant2002/CoreRTWinFormsTestBed) which create minimal ComWrappers for WinForms, and when I run against ILC from #653 it chockes on the methods from System.Drawing and others, and not even requires COM support yet.

Are there any technical reasons why this is not implemented in one form or another in ILC right now?

**Comment by kant2002** [comment]
Specifically I was blocked by this method

https://github.com/dotnet/winforms/blob/2178e7a66ed27332202659c3ea86649dc4578c3d/src/System.Windows.Forms.Primitives/src/Interop/UiaCore/Interop.UiaRaiseNotificationEvent.cs#L13-L19

which only used 

https://github.com/dotnet/winforms/blob/2178e7a66ed27332202659c3ea86649dc4578c3d/src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs#L1924-L1930

And from the usage alone it seems that `PreserveSig` somehow become `true`, or this is declaration bug in the WinForms itself.

**Comment by Suchiman** [comment]
Well that Code in the first link doesn't set `PreserveSig` explicitly which means the [default value of true](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.dllimportattribute.preservesig?view=net-5.0#remarks) is being used.

**Comment by kant2002** [comment]
Fun. If you look there sentence
> This field is similar to the PreserveSigAttribute; however, in contrast to the PreserveSig field, the default value for the attribute is false.
So I understand that other way around. Looks like somewhere documentation bug.

**Comment by jkotas** [comment]
> Are there any technical reasons why this is not implemented in one form or another in ILC right now?

No technical reasons. 

> Looks like somewhere documentation bug.

I do not see any obvious bug. You can always submit PR to improve the docs.

**Comment by kant2002** [comment]
If you interested, Looks like some discrepancy in the documentation. https://github.com/dotnet/dotnet-api-docs/pull/5359

**Comment by kant2002** [comment]
Crap, I apologize for noise. I read both sentences with default values couple times, and still understand all of it incorrectly. Even if I look into the flaws in my reasoning. 😢 

Now after some beating I'm ready to work.
I notice https://github.com/dotnet/runtime/blob/master/docs/design/features/source-generator-pinvokes.md and https://github.com/dotnet/runtimelab/tree/feature/DllImportGenerator/DllImportGenerator

Should I look how `PreserveSig == false` was done in DllImportGenerator and mimic in the ILC? Or this is should work in different manner? 

My undertanding that I should account for following settings
- DirectInvokation
- SetLastError
- Also return type should be handled slightly differently

Where tests for this functionality has to be sitting?

**Comment by kant2002** [comment]
I was misdiagnose the issue. It was related that `object` should be converted to `IUnknown` or to `IDispatch` so that's more related to my COM work.
