### ISSUE TITLE
Is it possible to make work Enum.GetValues in reflection free mode ?

### ISSUE THREAD

**Issue by spamoogleo** [dotnet/runtimelab#728]
In the my application i want to use pgp from the BouncyCastle lib with reflection free mode.
But reading parts of the pgp message with that lib requires reflection usage without any workarounds.
I got the following stacktrace, any chances to make this work ? 
`Unhandled Exception: EETypeRva:0x005DFAF8: TypeInitialization_Type_NoTypeAvailable
 ---> EETypeRva:0x005DFAF8: TypeInitialization_Type_NoTypeAvailable
 ---> EETypeRva:0x005DF2E8: Arg_NotSupportedException
StackTrace_AtWordSystem.Type.MakeArrayType() + 0x36
StackTrace_AtWordInternal.Reflection.RuntimeTypeInfo.MakeArrayType() + 0x493
StackTrace_AtWordSystem.Array.GetArrayTypeFromElementType(Type, Boolean, Int32) + 0x9e
StackTrace_AtWordSystem.Array.CreateSzArray(Type, Int32) + 0x68
StackTrace_AtWordSystem.Array.CreateInstance(Type, Int32) + 0x57
StackTrace_AtWordSystem.Enum.GetValues(Type) + 0x1ca
StackTrace_AtWordOrg.BouncyCastle.Utilities.Enums.GetEnumValues(Type) + 0x67
StackTrace_AtWordOrg.BouncyCastle.Utilities.Enums.GetArbitraryValue(Type) + 0x2f
StackTrace_AtWordOrg.BouncyCastle.Security.DigestUtilities..cctor() + 0x9a
StackTrace_AtWordSystem.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0x17c
   Exception_EndOfInnerExceptionStack
StackTrace_AtWordSystem.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0x27d
StackTrace_AtWordSystem.Runtime.CompilerServices.ClassConstructorRunner.CheckStaticClassConstructionReturnNonGCStaticBase(StaticClassConstructionContext*, IntPtr) + 0x1b
StackTrace_AtWordOrg.BouncyCastle.Security.DigestUtilities.GetDigest(String) + 0x4b
StackTrace_AtWordOrg.BouncyCastle.Security.SecureRandom.CreatePrng(String, Boolean) + 0x37
StackTrace_AtWordOrg.BouncyCastle.Security.SecureRandom..ctor() + 0x31
StackTrace_AtWordOrg.BouncyCastle.Math.BigInteger..cctor() + 0x1591
StackTrace_AtWordSystem.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0x17c
   Exception_EndOfInnerExceptionStack
StackTrace_AtWordSystem.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0x27d
StackTrace_AtWordSystem.Runtime.CompilerServices.ClassConstructorRunner.CheckStaticClassConstructionReturnNonGCStaticBase(StaticClassConstructionContext*, IntPtr) + 0x1b
StackTrace_AtWordOrg.BouncyCastle.Math.BigInteger..ctor(Int32, Byte[]) + 0x1a
StackTrace_AtWordOrg.BouncyCastle.Bcpg.MPInteger..ctor(BcpgInputStream) + 0x107
StackTrace_AtWordOrg.BouncyCastle.Bcpg.RsaPublicBcpgKey..ctor(BcpgInputStream) + 0x42
StackTrace_AtWordOrg.BouncyCastle.Bcpg.PublicKeyPacket..ctor(BcpgInputStream) + 0x23b
StackTrace_AtWordOrg.BouncyCastle.Bcpg.SecretKeyPacket..ctor(BcpgInputStream) + 0xbb
StackTrace_AtWordOrg.BouncyCastle.Bcpg.BcpgInputStream.ReadPacket() + 0x633
StackTrace_AtWordOrg.BouncyCastle.Bcpg.OpenPgp.PgpSecretKeyRing..ctor(Stream) + 0x169
StackTrace_AtWordOrg.BouncyCastle.Bcpg.OpenPgp.PgpObjectFactory.NextPgpObject() + 0x27a
StackTrace_AtWordOrg.BouncyCastle.Bcpg.OpenPgp.PgpObjectFactory.AllPgpObjects() + 0x57
StackTrace_AtWordOrg.BouncyCastle.Bcpg.OpenPgp.PgpSecretKeyRingBundle..ctor(Stream) + 0x4f`
According it the problem is in Enum.GetValues or Array.CreateInstance not sure

**Comment by MichalStrehovsky** [comment]
Try adding `<AppContextSwitchOverrides Include="Switch.System.Enum.RelaxedGetValues" />` into a `ItemGroup` in your project.

**Comment by spamoogleo** [comment]
> Try adding `<AppContextSwitchOverrides Include="Switch.System.Enum.RelaxedGetValues" />` into a `ItemGroup` in your project.

yep, seems like this one fixed previous error but now i have new one related to enum as well 
any solutions for this ?
`Unhandled Exception: EETypeRva:0x005E2CC8: TypeInitialization_Type_NoTypeAvailable
 ---> EETypeRva:0x005E2CC8: TypeInitialization_Type_NoTypeAvailable
 ---> EETypeRva:0x005E1978: Arg_DivideByZero
StackTrace_AtWordOrg.BouncyCastle.Utilities.Enums.GetArbitraryValue(Type) + 0x62
StackTrace_AtWordOrg.BouncyCastle.Security.DigestUtilities..cctor() + 0x9a
StackTrace_AtWordSystem.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0x17c
   Exception_EndOfInnerExceptionStack
StackTrace_AtWordSystem.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0x27d
StackTrace_AtWordSystem.Runtime.CompilerServices.ClassConstructorRunner.CheckStaticClassConstructionReturnNonGCStaticBase(StaticClassConstructionContext*, IntPtr) + 0x1b
StackTrace_AtWordOrg.BouncyCastle.Security.DigestUtilities.GetDigest(String) + 0x4b
StackTrace_AtWordOrg.BouncyCastle.Security.SecureRandom.CreatePrng(String, Boolean) + 0x37
StackTrace_AtWordOrg.BouncyCastle.Security.SecureRandom..ctor() + 0x31
StackTrace_AtWordOrg.BouncyCastle.Math.BigInteger..cctor() + 0x1591
StackTrace_AtWordSystem.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0x17c
   Exception_EndOfInnerExceptionStack
StackTrace_AtWordSystem.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0x27d
StackTrace_AtWordSystem.Runtime.CompilerServices.ClassConstructorRunner.CheckStaticClassConstructionReturnNonGCStaticBase(StaticClassConstructionContext*, IntPtr) + 0x1b
StackTrace_AtWordOrg.BouncyCastle.Math.BigInteger..ctor(Int32, Byte[]) + 0x1a
StackTrace_AtWordOrg.BouncyCastle.Bcpg.MPInteger..ctor(BcpgInputStream) + 0x107
StackTrace_AtWordOrg.BouncyCastle.Bcpg.RsaPublicBcpgKey..ctor(BcpgInputStream) + 0x42
StackTrace_AtWordOrg.BouncyCastle.Bcpg.PublicKeyPacket..ctor(BcpgInputStream) + 0x23b
StackTrace_AtWordOrg.BouncyCastle.Bcpg.SecretKeyPacket..ctor(BcpgInputStream) + 0xbb
StackTrace_AtWordOrg.BouncyCastle.Bcpg.BcpgInputStream.ReadPacket() + 0x633
StackTrace_AtWordOrg.BouncyCastle.Bcpg.OpenPgp.PgpSecretKeyRing..ctor(Stream) + 0x169
StackTrace_AtWordOrg.BouncyCastle.Bcpg.OpenPgp.PgpObjectFactory.NextPgpObject() + 0x27a
StackTrace_AtWordOrg.BouncyCastle.Bcpg.OpenPgp.PgpObjectFactory.AllPgpObjects() + 0x57
StackTrace_AtWordOrg.BouncyCastle.Bcpg.OpenPgp.PgpSecretKeyRingBundle..ctor(Stream) + 0x4f`

**Comment by MichalStrehovsky** [comment]
Oh, right.

https://github.com/bcgit/bc-csharp/blob/93b32a75656955faf7996d0f3e0ed391968d2ac6/crypto/src/util/Enums.cs#L64-L65

In reflection disabled mode, asking for a list of enum values returns an empty array because getting anything else would be reflection. This results in a division by zero.

I doubt bouncy castle would work.

The subsequent code is not going to work either because it converts string names to numerical values:

https://github.com/bcgit/bc-csharp/blob/93b32a75656955faf7996d0f3e0ed391968d2ac6/crypto/src/openssl/PEMUtilities.cs#L32-L36

At some point I would like to introduce a "reflection free mode v2" that would allow a couple things that currently don't work. Reflecting on enums would be one because it's too common.
