### ISSUE TITLE
[NativeAOT] Would it be possible to make the recent debug header export optional?

### ISSUE THREAD

**Issue by JoshuaWierenga** [dotnet/runtimelab#739]
I am currently working on a program with /SUBSYSTEM:EFI_APPLICATION and the recent debug header commit adds a new /EXPORT argument to the linker but that is not supported on this subsystem. I did not just pull request a fix since perhaps there is an existing solution since the export is already conditional. is there a different OS variable for cases like this? In that case, does that change the build process since changing OS already requires DisableUnsupportedError to avoid the cross-compilation error which feels overkill and might just lead to more issues?

**Comment by MichalStrehovsky** [comment]
Would it help if we lump it together with the rest of debugging support and make it also conditional on NativeDebugSymbols? Then you could opt out by disabling debugging support.

https://github.com/dotnet/runtimelab/blob/168e3047c487140d4e04795d618b1c0defc33c19/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.targets#L26

**Comment by JoshuaWierenga** [comment]
That would probably work. There is no debugging support currently anyway
and while I believe uefi does support it, it would use it's own system that
most likely does not use any of the dotnet debug symbols.

**Comment by MichalStrehovsky** [comment]
Fixed in #743

**Comment by JoshuaWierenga** [comment]
Thanks
