### ISSUE TITLE
net6 plan to support aot?

### ISSUE THREAD

**Issue by mingyangzhu** [dotnet/runtimelab#748]
hi，net6 plan to support aot?

**Comment by jkotas** [comment]
We’re not ready to productize NativeAOT for .NET 6.

You can follow the rest of the AOT work via https://themesof.net and via https://devblogs.microsoft.com/dotnet/. 

[Replacing crossgen with crossgen2](https://github.com/dotnet/runtime/issues/43653), [PGO](https://github.com/dotnet/core/issues/5491) and [optimizing AOT for specific scenarios](https://github.com/dotnet/core/issues/5438) are the major themes for .NET 6.
