### ISSUE TITLE
Reenable vxsort in GC

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtimelab#77]
This was disabled due to missing symbols.

The VXSort feature enables intrinsic-optimized sorting within the garbage collector.

**Comment by MichalStrehovsky** [comment]
To fix, find the `#ifdef` guarding `#define USE_VXSORT` in https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/src/coreclr/src/gc/gc.cpp. Remove the part referencing `FEATURE_REDHAWK`. `FEATURE_REDHAWK` means "native AOT".

**Comment by nietras** [comment]
Oh, I definitely want to do this! Assign me please 😁

**Comment by MichalStrehovsky** [comment]
@nietras seems like @MartinZikmund beat you to it by 11 minutes in #281.

**Comment by nietras** [comment]
@MichalStrehovsky damn! 😅👍

**Comment by MartinZikmund** [comment]
@nietras I'm sorry 😶

**Comment by nietras** [comment]
@MartinZikmund ha, no problem at all! 👍

**Comment by MichalStrehovsky** [comment]
Closed in #281. Github unfortunately doesn't auto-close until the commit reaches the master branch.
