### ISSUE TITLE
When will WPF be supported?

### ISSUE THREAD

**Issue by yiszza** [dotnet/runtimelab#770]

**Comment by jkotas** [comment]
The pre-requisite for considering NativeAOT for WPF are:
- WPF compatibility with [trimming](https://github.com/dotnet/wpf/issues/3811)
- WPF compatibility with [single-file](https://github.com/dotnet/wpf/search?q=single+file&type=issues) (the proper single-file - not the one that unzips files to disk during application startup)
Until these pre-requisites are met, there is no point in considering NativeAOT support for WPF.
