### ISSUE TITLE
Detect infinite generic expansion

### ISSUE THREAD

**Issue by hez2010** [dotnet/runtimelab#776]
*Previous discussion: https://github.com/dotnet/corert/issues/363*

We need to detect infinite generic expansion and terminate type loading.

Affected test:
```
JIT\Methodical\inlining\bug505642\test\
```

.NET Native for UWP apps uses [Tarjan's algorithm](https://en.wikipedia.org/wiki/Tarjan%27s_strongly_connected_components_algorithm) to find strongly connected components in the graph of constructed types.

The task is to:

- Figure out how to run the algorithm in parallel with code generation (in .NET Native for UWP apps, this is a global pre-pass, but we don't have global pre-passes here)
- Convert static generic lookups to lazy lookups to break the connected component. Lazy lookups are not wired up yet, so maybe that should be the first thing to do.

Here's a couple test cases: [recursion.zip](https://github.com/dotnet/runtimelab/files/6091566/recursion.zip). We would be able to solve the ones where the recursion happens over reference types. If the recursion happens over value types, this is not solvable without universal shared code.

**Comment by MichalStrehovsky** [comment]
This is mostly done but I would like to avoid the spurious `NullReferenceException`s when cutoff happens, and I would like the compiler to print some sort of useful feedback when the cutoff happens so that people can ideally remove the generic cycle from the source.

**Comment by MichalStrehovsky** [comment]
Fixed in #1681, #1699, #1709, #1710.
