### ISSUE TITLE
NativeAOT ilcompiler publish integration with CLI tools?

### ISSUE THREAD

**Issue by gamedevcb** [dotnet/runtimelab#780]
I would like to run a command line .exe on the .dll files before those are passed onto the ilcompiler. To illustrate the use-case let me explain:

Normal chain compilation events:
**1.** dotnet generates .dlls 
**2.** ilcompiler takes said .dlls and compiles them to native

This is what I would like instead:
**1.** dotnet generates .dlls 
**2. .dlls are modified by a CLI tool ([ConfuserEx](https://github.com/mkaring/ConfuserEx/))**
**3.** ilcompiler takes said .dlls and compiles them to native

So to do this, I would need to know when/where the intermediate .dll files the dotnet publish chain generates are placed just before the ilcompiler takes them to turn them into .obj files, and at that point, I would somehow need to insert **step (2)**. How can I achieve this?

PS: I am using the nuget _microsoft.dotnet.ilcompiler\6.0.0-preview.3.21153.3_ on Win10 and publishing via calling _'dotnet publish -r win-x64 -c release'_ on the X64 VS 2019 command prompt.

**Comment by jkotas** [comment]
You can hook into the publish pipeline by adding your msbuild target. `BeforeTargets` and `DependsOnTargets` attributes allows you to control where your target is going to run. 

Here is example of how NativeAOT toolchain hooks into the publish pipeline: https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Publish.targets#L22-L24

Note that these internal msbuild targets are not considered to be a stable documented surface, so hooking into them tends to break once in a while as the SDK evolves.

**Comment by gamedevcb** [comment]
Thanks @jkotas, I was able to make it work with your help! For future reference, here are some additional tips that others may find useful:

**1. the NativeAOT chain starts after the regular 'PostBuildEvent',** so you should apply changes to your .dlls after that as
` <Target Name="YourCustomTarget" AfterTargets="PostBuildEvent">`


**2. As it was pointed out the NativeAOT chain is still subject to changes, so to make my pipeline more robust,** I overwritten all dlls in my solution with the changed ones. This is because the ILC does NOT take everything from the $(TargetDir), but rather it seems to be taking the input .dlls from all over the place. Eg, the .dlls for shared projects seem to be taken from their **bin\** folders (eg: <SharedProj>\bin\x64\release\netstandard2.0\SharedProj.dll ), but the main project from the **obj\** folders (<MainProj>obj\x64\release\net5.0\win-x64\MainProj.dll). So by overwriting all of them, I made sure that the ILC will always work with the correct ones.
