### ISSUE TITLE
[NativeAOT] LINK fail

### ISSUE THREAD

**Issue by SupinePandora43** [dotnet/runtimelab#781]
```
λ dotnet publish -c Release -r win-x64 -p:PublishReadyToRun=true
Microsoft (R) Build Engine версии 16.9.0-preview-21103-02+198f3f262 для .NET
(C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

  Определение проектов для восстановления...
  Все проекты обновлены для восстановления.
  Вы используете предварительную версию .NET. Дополнительные сведения см. на странице https://aka.ms/dotnet-core-preview.
  Вы используете предварительную версию .NET. Дополнительные сведения см. на странице https://aka.ms/dotnet-core-preview.
  UltralightSharp -> C:\Users\Дом\source\repos\SupinePandora43\UltralightSharp\UltralightSharp\bin\Release\net5\win-x64\UltralightSharp.dll
  VeldridSandbox -> C:\Users\Дом\source\repos\SupinePandora43\UltralightSharp\VeldridSandbox\bin\Release\net5\win-x64\VeldridSandbox.dll
LINK : fatal error LNK1181: не удается открыть входной файл "C:\Users\Р"Р?Р?\.nuget\packages\runtime.win-x64.microsoft.dotnet.ilcompiler\6.0.0-preview.3.21153.3\sdk\bootstrapper.lib" [C:\Users\Дом\source\repos\SupinePandora43\UltralightSharp\VeldridSandbox\VeldridSandbox.csproj]
C:\Users\Дом\.nuget\packages\microsoft.dotnet.ilcompiler\6.0.0-preview.3.21153.3\build\Microsoft.NETCore.Native.targets(310,5): error MSB3073: выход из команды ""C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29910\bin\Hostx64\x64\link.exe"  @"obj\Release\net5\win-x64\native\link.rsp"" с кодом 1181. [C:\Users\Дом\source\repos\SupinePandora43\UltralightSharp\VeldridSandbox\VeldridSandbox.csproj]
```
it is because of non-ascii characters in path?

project: https://github.com/SupinePandora43/UltralightSharp/blob/24a5c1183bdf034efae1ba22c097ef3f1ff0b226/VeldridSandbox/Program.cs#L21

**Comment by jkotas** [comment]
Thank you for reporting this! #782 has the fix.

**Comment by SupinePandora43** [comment]
> Thank you for reporting this! #782 has the fix.

Thank you for such a quick response.
I'll instantly test when PR get merged. (~~And nuget updated~~)

**Comment by AntonLapounov** [comment]
@SupinePandora43 You are welcome! Please note that the `PublishReadyToRun` property has no effect on NativeAOT publishing, so you may omit it.

**Comment by SupinePandora43** [comment]
@AntonLapounov now i only need to wait until new version of `Microsoft.DotNet.ILCompiler` releases?

**Comment by AntonLapounov** [comment]
@SupinePandora43 The updated package should be released in a day or two.  If you do not want to wait, you may locate `Microsoft.NETCore.Native.Windows.props` file in NuGet `packages` directory on your computer and replace it with the [fixed file](https://raw.githubusercontent.com/jkotas/runtimelab/73ada5e747a82d09df793c9a58d8396b7ca84518/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.targets). That file normally has the following path:
```
%USERPROFILE%\.nuget\packages\microsoft.dotnet.ilcompiler\6.0.0-preview.3.21153.3\build\Microsoft.NETCore.Native.Windows.props
```
where the version number changes on each release.
