### ISSUE TITLE
Question: NativeAOT-LLVM: LIR block preds and succs

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#874]
In this LIR:
```
Trees after Rationalize IR

-----------------------------------------------------------------------------------------------------------------------------------------
BBnum BBid ref try hnd preds           weight    lp [IL range]     [jump]      [EH region]         [flags]
-----------------------------------------------------------------------------------------------------------------------------------------
BB01 [0001]  1                             1       [???..???)                                     i internal label target hascall LIR
BB02 [0000]  1       BB01                  1       [000..002)        (return)                     i LIR
-----------------------------------------------------------------------------------------------------------------------------------------

------------ BB01 [???..???), preds={} succs={BB02}
N001 ( 14,  2) [000002] --CXG-------         t2 =    CALL help byref  HELPER.CORINFO_HELP_READYTORUN_STATIC_BASE

------------ BB02 [000..002) (return), preds={BB01} succs={}
               [000003] ------------                 IL_OFFSET void   IL offset: 0x0
N001 (  1,  1) [000000] ------------                 NO_OP     void
N001 (  0,  0) [000001] ------------                 RETURN    void

```
Is the information `succs={BB02}` and `preds={BB01}` available in the `BasicBlock` class?  

And is the information that there is only one  `succs={BB02}` and the last statement in the block is not some kind of branch enough to say that this is a fall through from `BB01` to `BB02`.  

Or  to put this another way, it would seem that because `BB01` only has one successor, `BB02`, and `BB02` only has one predecessor, `BB01`, could these 2 blocks be collapsed?  In LLVM I could create 2 blocks and a branch from the first to the second, but it would seem superfluous.

**Comment by jkotas** [comment]
> Is the information succs={BB02} and preds={BB01} available in the BasicBlock class?

Yes, look for `bbPreds` and `NumSucc` + `GetSucc`.

> this is a fall through from BB01 to BB02.

`BBJ_NONE` says the block is a fallthrough to the next block.

If you have not seen it, https://github.com/dotnet/runtime/blob/main/docs/design/coreclr/jit/ryujit-overview.md covers some of this at high level
