### ISSUE TITLE
Options how library can speify their own RD.xml

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtimelab#882]
My understanding that rd.xml right now is application level directive. Is is possible/valuable to be able provide alternative to rd.xml via attributes which can be picked up by ILC ? Somewhat related to https://github.com/dotnet/corert/issues/5001.
I personally start thinking about that when hit [issue with BenchmarkDotNet](https://github.com/dotnet/BenchmarkDotNet/issues/1680) and playing with Dappers.PerformanceTests

**Comment by jkotas** [comment]
cc @MichalStrehovsky

**Comment by MichalStrehovsky** [comment]
The RD.XML file format is not great, but we don't have anything better. The "way forward" is the ILLink descriptors format, which is not great either, but already in use in the mainstream runtimes, which means we're stuck with it for the time being. We don't parse the rooting part yet in ILC. It also cannot express instantiated generics, why is why I haven't even bothered with it. I'm reluctant to allow RD.XML in more places.

Can you work around with code. E.g.

```csharp
if (string.Empty.Length > 0)
{
    Type t = Type.GetType("Foo, FooAssembly");
    t.GetMethods();
}
```

This will keep all public methods on Foo in FooAssembly. It's a misuse of the reflection dataflow analysis that the compiler does, but it works pretty well.

We don't model MakeGenericType/MakeGenericMethod. I would want to add that at some point.

**Comment by MichalStrehovsky** [comment]
https://github.com/mono/linker/blob/main/docs/data-formats.md#descriptor-format

This can be embedded in the assembly as a managed resource. ILC currently doesn't parse this though. Also, there's no way to express generic instantiations. One would think that Unity (who is using this as well and has similar problems for full AOT in their IL2CPP) would have already contributed such extension, but they use this format + an additional text file for generics to specify what needs to be kept/generated, which is just lovely.

**Comment by kant2002** [comment]
Do you want to support ILLink format in ILC in theory?

**Comment by MichalStrehovsky** [comment]
> Do you want to support ILLink format in ILC in theory?

It's already used (in the embedded form) in e.g. ASP.NET, so supporting it eventually is pretty much mandatory.

**Comment by MichalStrehovsky** [comment]
No plans for RD.XML experiences.
