### ISSUE TITLE
ILC memory hungry

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtimelab#883]
Do ILC should eat that much memory when compile Benchmarks ?

![image](https://user-images.githubusercontent.com/4257079/112950590-4379b300-915c-11eb-9336-b7fabe795024.png)

**Comment by jkotas** [comment]
It is not unusual to see ilc to consume GBs of memory for large apps. What is the size of the .exe produced by the compilation?

You can profile it to see whether you can find any botleneck.

**Comment by kant2002** [comment]
69Mb in produced EXE. Not big I would say with current state of affairs. Is this expected? 30 Mb at least from Microsoft.Data.SqlClient. I will try take a look.

**Comment by Fabi** [comment]
> 69Mb is relatively big native compiled binary.

In native aot scenarios like we have atm 69MB is really small to be honest. A bit more complex even go to > 200mb here and they like never use that much memory for ilc.exe

**Comment by kant2002** [comment]
Let me start collecting some observation. It's not full fledged analysis of the memory usage, but at least maybe this give somebody idea what's going on.
I compile `ComWrappers` smoke test.

# Snapshot 1
I take Snapshot no. 1 when ILC process was at 401Mb.
Top-most classes which eat's up memory was. 
| Object type | Count | Size (bytes) | Inclusive size (bytes) |
|--------------|--------| -------------| ---------------------|
| ILCompiler.DependencyAnalysis.MethodCodeNode	| 20,844	| 15,157,960	| 220,406,744 |
| ILCompiler.DependencyAnalysis.ObjectNode+ObjectData	| 17,408	| 7,498,632	| 162,413,016| 
| ILCompiler.DependencyAnalysis.TentativeInstanceMethodNode	| 8,735	| 349,400	| 62,131,672 |
| ILCompiler.DependencyAnalysisFramework.DependencyNodeCore+DependencyList<ILCompiler.DependencyAnalysis.NodeFactory>	| 6,770	| 804,672	| 41,594,872 |
| List<ILCompiler.DependencyAnalysis.MethodCodeNode>	| 1	| 2,104	| 24,671,632 |
| Dictionary<Object, IntPtr>	| 16	| 7,364,000	| 8,739,320 |
| ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer<ILCompiler.DependencyAnalysisFramework.NoLogStrategy<ILCompiler.DependencyAnalysis.NodeFactory>, ILCompiler.DependencyAnalysis.NodeFactory>	| 1	| 4,562,672	| 5,752,848 |
| Internal.IL.EcmaMethodIL	| 14,384	 | 3,345,400	 | 3,345,400 |

# Snapshot 2
4 seconds later, I take second snapshot. ILC process memory was 566 Mb

| Object type | Count | Size (bytes) | Inclusive size (bytes) |
|--------------|--------| -------------| ---------------------|
| ILCompiler.DependencyAnalysis.MethodCodeNode	 | 21,211	| 15,618,776	 | 68,857,512 |
| ILCompiler.DependencyAnalysis.ObjectNode+ObjectData	 | 17,952	| 7,750,120	| 50,388,472 |
| ILCompiler.DependencyAnalysis.TentativeInstanceMethodNode	 | 8,929	| 357,160	| 20,868,680 |
| Dictionary<String, ILCompiler.DependencyAnalysis.ISymbolNode>	| 1	| 5,090,064	| 20,495,656 |
| ILCompiler.DependencyAnalysis.RyuJitNodeFactory	| 1	| 3,148,208	| 19,492,320 |
| Dictionary<Object, IntPtr>	| 16	| 7,495,056	| 9,489,408 |
| Dictionary<Internal.TypeSystem.MethodDesc, Internal.Text.Utf8String>	| 2	| 5,208,024	| 5,208,024 |
| Dictionary<String, ILCompiler.DependencyAnalysis.ISymbolNode>	| 1	| 5,090,064	| 20,495,656 |

Then compare difference in the heap structure using VS perf tools. This is sorted by biggest inclusive size change.

| Object type | Count | Size (bytes) | Inclusive size (bytes) | Count | Size (bytes) | Inclusive size (bytes) |
|--------------|--------| -------------| ---------------------|--------| -------------| ---------------------|
| Dictionary<String, ILCompiler.DependencyAnalysis.ISymbolNode>|	+1	|+5,090,064	| +20,495,656	| 1	| 5,090,064	| 20,495,656|
| List<ILCompiler.DependencyAnalysis.ExternalReferencesTableNode+SymbolAndDelta>	| 0	| +278,600|	+12,099,104	|3	|278,696	|12,099,200|
| ILCompiler.DependencyAnalysis.ExternalReferencesTableNode	| 0	| -160	| +12,098,328	| 3	| 216	| 12,099,416 |
| ILCompiler.CoreRTNameMangler	| 0	| 0	| +5,411,472	| 1	| 88	| 7,402,088 |
| Dictionary<Internal.TypeSystem.MethodDesc, Internal.Text.Utf8String>	| 0	| +4,911,984	| +4,911,984	| 2	| 5,208,024	| 5,208,024|
| ILCompiler.DependencyAnalysis.MethodCodeNode	| +367	| +460,816	| -151,549,232	| 21,211	| 15,618,776	| 68,857,512 |
| ILCompiler.DependencyAnalysis.ObjectNode+ObjectData	| +544	| +251,488	| -112,024,544	| 17,952	| 7,750,120	| 50,388,472| 
| ILCompiler.DependencyAnalysis.TentativeInstanceMethodNode	| +194	| +7,760	| -41,262,992	| 8,929	| 357,160	| 20,868,680|
| ILCompiler.DependencyAnalysisFramework.DependencyNodeCore+DependencyList<ILCompiler.DependencyAnalysis.NodeFactory>	| +145	| +16,384	| -39,874,536	| 6,915	| 821,056	| 1,720,336 |
| List<ILCompiler.DependencyAnalysis.MethodCodeNode>	| -1	| -2,104	| -24,671,632	| 0	| 0	| 0

Since biggest offended in change was 1 instance was  `Dictionary<String, ILCompiler.DependencyAnalysis.ISymbolNode>` I take a look what's there. `Count = 17572`.

# Snapshot 3
After that I place breakpoint at exit of the application and take snapshot again. Total memory was 797Mb.

| Object type | Count | Size (bytes) | Inclusive size (bytes) |
|--------------|--------| -------------| ---------------------|
Dictionary<String, ILCompiler.DependencyAnalysis.ISymbolNode>	1	13,090,424	68,858,680
ILCompiler.DependencyAnalysis.MethodCodeNode	21,211	15,618,776	26,270,728
ILCompiler.DependencyAnalysis.ObjectAndOffsetSymbolNode	39	4,352	24,579,312
ILCompiler.DependencyAnalysis.InterfaceDispatchCellSectionNode	1	88	24,460,896
ILCompiler.DependencyAnalysis.InterfaceDispatchCellSectionNode+DispatchCellComparer	1	32	24,434,056

Since biggest offended in change was again 1 instance was  `Dictionary<String, ILCompiler.DependencyAnalysis.ISymbolNode>` I take a look what's there. `Count = 47077`.

Change from second snapshot

| Object type | Count | Size (bytes) | Inclusive size (bytes) | Count | Size (bytes) | Inclusive size (bytes) |
|--------------|--------| -------------| ---------------------|--------| -------------| ---------------------|
| Dictionary<String, ILCompiler.DependencyAnalysis.ISymbolNode>	| 0	| +8,000,360	| +48,363,024	| 1	| 13,090,424	| 68,858,680 |
| ILCompiler.DependencyAnalysis.ObjectAndOffsetSymbolNode	|0	|0	|+24,434,000	|39	|4,352	|24,579,312|
| ILCompiler.DependencyAnalysis.InterfaceDispatchCellSectionNode	|0	|0	|+24,434,000	|1	|88	|24,460,896|
| ILCompiler.DependencyAnalysis.InterfaceDispatchCellSectionNode+DispatchCellComparer	|0	|0	|+24,434,000	|1	|32	|24,434,056|
| ILCompiler.RyuJitCompilation	|0	|0	|+5,423,568	|1	|160	|5,723,056|
| ILCompiler.DependencyAnalysis.MethodCodeNode	|0	|0	|-42,586,784	|21,211	|15,618,776	|26,270,728|
| ILCompiler.DependencyAnalysis.ObjectNode+ObjectData	|-1	|-800	|-42,408,856	|17,951	|7,749,320	|7,979,616|
| ILCompiler.DependencyAnalysis.TentativeInstanceMethodNode	|0	|0	|-20,242,840	|8,929	|357,160	|625,840|
| ILCompiler.UsageBasedMetadataManager	|0	|0	|-13,085,360	|1	|1,000,256	|3,320,240|
| HashSet<ILCompiler.DependencyAnalysis.IMethodBodyNode>	|0	|0	|-12,979,568	|1	|350,504	|350,504|

Growth of `Dictionary<String, ILCompiler.DependencyAnalysis.ISymbolNode>` displayed as coming mostly (at least half) from `ILCompiler.DependencyAnalysis.MethodCodeNode`, but it is visible that total memory from `ILCompiler.DependencyAnalysis.MethodCodeNode` reduced, so probably it is a lot of churn going on here.


Other big offender is strings everywhere.
`ILCompiler.DependencyAnalysis.InterfaceDispatchCellNode` has 699 _nestedNodes each of them has string like this: `__GenericDict_S_P_Reflection_Core_System_Collections_Generic_EnumerableExtensions__AsNothingButIEnumerable_d__0_1<S_P_CoreLib_System_Type>`, sometimes it's better though.

Semi-related observation:  `ILCompiler.CoreRTNameMangler` uses `Dictionary<MethodDesc, Utf8String>`, but `ILCompiler.DependencyAnalysis.InterfaceDispatchCellNode` use `string _callSiteIdentifier`. 

In the diagnostics tools displayed heap size as 100Mb, but I see 900 in the panel above. Is this indication that GC pre-allocate some memory and actual usage is 100Mb, but GC need more to account for churn?
![image](https://user-images.githubusercontent.com/4257079/115990505-6ffede80-a5e5-11eb-8f97-019c85092e60.png)

**Comment by jkotas** [comment]
> `Dictionary<String, ILCompiler.DependencyAnalysis.ISymbolNode>`

Are you doing this analysis on a debug build? This dictionary should not exist in the release build of the compiler.

**Comment by jkotas** [comment]
> In the diagnostics tools displayed heap size as 100Mb, but I see 900 in the panel above. Is this indication that GC pre-allocate some memory and actual usage is 100Mb,

It likely means that a lot of the memory is garbage (ie all structures used to produce the output) when the application is exiting, but the GC did not have a chance to collect it yet. It would be more interestring to look at the snapshot when the output is finished writing, but the structures used to produce it are still rooted.

**Comment by kant2002** [comment]
You are right, my biggest gross mistake is that I test in Debug, then I really have to do is Release. Also I will try to find proper place where to put my breakpoint more properly. Cannot promise that this is my priority, just want keep ball rolling.
