### ISSUE TITLE
DllImportGenerator marshal bool as byte

### ISSUE THREAD

**Issue by SupinePandora43** [dotnet/runtimelab#891]
currently DllImportGenerator marshals `bool` as `int`
it causes problems eg:
`ULBitmap.IsEmpty` returns `true`, but should be `false`

# DllImportGenerator behaviour
```cs
		[GeneratedDllImport("Ultralight")]
		public static partial bool ulBitmapIsEmpty(IntPtr bitmap);
		public bool IsEmpty => ulBitmapIsEmpty(Ptr);
```

## Expected
`IsEmpty` returns `false`
## Actual
`IsEmpty ` returns `true`
# DllImport
(using `byte` **not bool**)
```cs
		[DllImport("Ultralight")]
		public static extern byte ulBitmapIsEmpty(IntPtr bitmap);
		public bool IsEmpty => ulBitmapIsEmpty(Ptr) != 0;
```
everything is ok

**Comment by MichalPetryka** [comment]
Afaik, by default `bool`s are marshalled as UnmanagedType.Bool by default, which means it's 4B, you have to use `UnmanagedType.I1` as per the documentation: `A 1-byte signed integer. You can use this member to transform a Boolean value into a 1-byte, C-style bool (true = 1, false = 0).`

**Comment by NN---** [comment]
```cs
[return: MarshalAs(UnmanagedType.U1)]
```

https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1414

**Comment by jkotas** [comment]
cc @AaronRobinsonMSFT

**Comment by SupinePandora43** [comment]
> `[return: MarshalAs(UnmanagedType.U1)]`

solved
