### ISSUE TITLE
marshaling of classes?

### ISSUE THREAD

**Issue by jtorjo** [dotnet/runtimelab#897]
While compiling my project with .net native, I run into an error:

Lit_happy_120.mp3:EETypeRva:0x00067310(System.Runtime.InteropServices.MissingInteropDataException): NAudio.Wave.Mp3WaveFormat is missing structure marshalling data. To enable structure marshalling data, add a MarshalStructure directive to the application rd.xml file. For more information, please visit http://go.microsoft.com/fwlink/?LinkID=393965

I've added marshaling info here:
 
    <Directives xmlns="http://schemas.microsoft.com/netfx/2013/01/metadata">
    <Library Name="naudio.uwp">
        <Namespace Name="NAudio.Wave">
	        <Type Name="WaveFormat" MarshalStructure="Required All"/>
        </Namespace>

    </Library>
  </Directives>

However, the same error gets thrown.

I've read here: https://github.com/dotnet/corert/issues/5374#issuecomment-455706335 that CoreRT only supports `struct`s for now. 

Has this been fixed? 

Will this be fixed?

**Comment by MichalStrehovsky** [comment]
Class marshalling is now supported.

> NAudio.Wave.Mp3WaveFormat is missing structure marshalling data
> <Type Name="WaveFormat" MarshalStructure="Required All"/>

The exception is about one type, but the RD.XML is about another type. Is that your issue?

**Comment by jtorjo** [comment]
That is my issue, thanks. But I don't understand what I'm doing wrong :) Please help :)

**Comment by MichalStrehovsky** [comment]
> That is my issue, thanks. But I don't understand what I'm doing wrong :) Please help :)

I meant the exception is about Mp3WaveFormat, but your RD.XML has WaveFormat.

**Comment by jtorjo** [comment]
Oh  my! Thanks, I must be blind! Let me try it now!
