### ISSUE TITLE
Hard to diagnose error in ILC

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtimelab#899]
When specify type ``<Type Name="System.Func`2[[System.Int32,System.Private.CoreLib],[System.Nullable`1[System.Int32,System.Private.CoreLib],System.Private.CoreLib]]" Dynamic="Required All" />`` ILC gives misleading error message `Internal.TypeSystem.TypeSystemException+TypeLoadException: Failed to load type 'System.Private.CoreLib' from assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'`

I think it would be helpful to either enforce incorrect format, or at least print line where this error happens.

**Comment by MichalStrehovsky** [comment]
The RD.XML parser is here: https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/src/coreclr/tools/aot/ILCompiler/RdXmlRootProvider.cs

I think we just need to wrap the places that call into `GetTypeByCustomAttributeTypeName` in a `try {} catch (TypeSystemException) { }` and have it include detail on where in XML parsing we are.

**Comment by MichalStrehovsky** [comment]
No plans for RD.XML experiences.
