### ISSUE TITLE
MySql.Data PackageReference generates error

### ISSUE THREAD

**Issue by LLT21** [dotnet/runtimelab#916]
Michal, I am new to the AOT native compilation but going forward. In my .NET 5 project I have a reference to the MySql.Data Nuget package. With this included, I receive an error: "EXEC : error : Value cannot be null. (Parameter 'key')". I guess this has more to do with the MySql.Data package as such than the AOT compilation. I am using this version 6.0.0-preview.4.21203.1 with compilation RID osx.11.0-x6. When excluding the package, the error is gone.

**Comment by MichalStrehovsky** [comment]
I think this is same as #926, but that one has a stack trace pointing to the problem. Closing in favor of that
