### ISSUE TITLE
Support generating code even if error occurs to enable hand editing for non-supported scenarios

### ISSUE THREAD

**Issue by SupinePandora43** [dotnet/runtimelab#925]
https://github.com/dotnet/runtimelab/blob/0c64a2aa529dff4ef3ad15b17663b5314f55145b/DllImportGenerator/DllImportGenerator/DllImportGenerator.cs#L175-L190

is there's any plans for net framework and or netstandard support?

**Comment by AaronRobinsonMSFT** [comment]
@SupinePandora43 Unfortunately no. This was attempted at first but given some of our needs (for example, C# function pointers and some new APIs) we needed to drop support for anything prior to .NET 5 and it might come to a point where we need .NET 6 for some APIs.

We are keeping a compatibility list [here](https://github.com/dotnet/runtimelab/blob/feature/DllImportGenerator/DllImportGenerator/designs/Compatibility.md).

**Comment by SupinePandora43** [comment]
> @SupinePandora43 Unfortunately no. This was attempted at first but given some of our needs (for example, C# function pointers and some new APIs) we needed to drop support for anything prior to .NET 5 and it might come to a point where we need .NET 6 for some APIs.
> 
> We are keeping a compatibility list [here](https://github.com/dotnet/runtimelab/blob/feature/DllImportGenerator/DllImportGenerator/designs/Compatibility.md).

Then, could generator continue generate code even if it will error?

**Comment by AaronRobinsonMSFT** [comment]
@SupinePandora43 As in generate all the code anyways so one can use it as a starting point for manually updating? I assume in this case you would be fine if we still errored out, but the large swathe of generated code is a helpful starting point. Please confirm and if that is the case, we should reopen this and update the title so it is about permitting the generated source to be used as a boot strap - which I think is a reasonable request.

**Comment by SupinePandora43** [comment]
> @SupinePandora43 As in generate all the code anyways so one can use it as a starting point for manually updating? I assume in this case you would be fine if we still errored out, but the large swathe of generated code is a helpful starting point. Please confirm and if that is the case, we should reopen this and update the title so it is about permitting the generated source to be used as a boot strap - which I think is a reasonable request.

@AaronRobinsonMSFT 

reopen with what title? ~~i have a little language barrier.~~
eg. `Continue generating code, even if it will error`? am i understood it right? if yes - yes.

**Comment by AaronRobinsonMSFT** [comment]
@jkoritzinsky and @elinor-fung I think this is a reasonable request if we are only going to support recent platforms. Users may find it at least a helpful starting point. Perhaps have a "ignore errors" flag? I thought we already had some sort of scenario like that, but perhaps not with this early support check.

**Comment by jkotas** [comment]
Would this workflow be better covered by compiling the project against supported platform and using the source generated for that as a starting point for manually updating?

**Comment by jkoritzinsky** [comment]
Using the `<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>` MSBuild property, you can persist the source-generated output to disk. Since we always generate even in failure cases, this property should enable hand-editing by copying from the generated file back to source.
