### ISSUE TITLE
Regression 4.21206.3

### ISSUE THREAD

**Issue by Bxaa** [dotnet/runtimelab#933]
Error while compiling (regression was introduced with last build 4.21206.3)
> Cant find .ilc.rsp
\tools\ilc" @"obj\x64\Release\net5.0-windows\win-x64\native\project.ilc.rsp"" with code 3

Wrong path?

(no issues with 6.0.0-preview.4.21203.1)

**Comment by MichalStrehovsky** [comment]
@AntonLapounov could this be some fallout from #919?

**Comment by AntonLapounov** [comment]
@Bxaa Could you please tell me how to reproduce the issue?  I just tried `dotnet publish -r win-x64` with a hello-world app and it compiled fine with 6.0.0-preview.4.21206.3.

**Comment by AntonLapounov** [comment]
Oh, that happens if one uses the x86 version of `dotnet`.

**Comment by Bxaa** [comment]
**@Антон**, странная фигня. Нужно было обновить один из проектов и я его перекомпилировать пытался и тут такая хрень. Я весь код перерыл и потом попробовал другие проекты скомпилировать и тоже самое. Пару часов тупил и всё перерыл...а потом только заметил, что версия обновилась :)

_- Could you please tell me how to reproduce the issue?_

Ну а как это воспроизвести - это тупо пробовать скомпилить любой проект (включая hello world). Получается ошибка.
Не знаю...может это у меня тут частный случай какой... Но, стоит откатиться на предыдущую версию - и всё нормально.
Вероятно это связано с cross-architecture publishing.

I just tried to recompile one of my project (work fine with 4.21203.1)
And got same error for all of projects after update to 4.21206.3
No any changes to system or...may be last vs2019 update changed something?

(I returned to version 4.21203.1 and it solved all issues)

**Comment by AntonLapounov** [comment]
Sorry for the trouble and thank you for reporting this issue.  The fix will be merged soon.  Until then, you may either continue using the previous version of the package, or use the x64 version of `dotnet.exe` (make sure it is the first one on the `PATH`), or set `<IlcHostArch>x64</IlcHostArch>` in your project file(s), or pass `/p:IlcHostArch=x64` to `msbuild.exe`.

**Comment by Bxaa** [comment]
Thx for you work!

**Comment by MichalStrehovsky** [comment]
Fixed in #934.
