### ISSUE TITLE
NativeAOT-LLVM: Question: How to get arg types from CORINFO_SIG_INFO

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#942]
Can I get the argument types from a `CORINFO_METHOD_HANDLE` using this struct?

https://github.com/dotnet/runtimelab/blob/bd215e1ff87ed33bc5645d2d572088e2a16c3965/src/coreclr/inc/corinfo.h#L1102

`CORINFO_ARG_LIST_HANDLE args;` is the obvious, but its opaque.

Preferably as `CorInfoType`s like the return type:

https://github.com/dotnet/runtimelab/blob/bd215e1ff87ed33bc5645d2d572088e2a16c3965/src/coreclr/inc/corinfo.h#L1107

**Comment by yowl** [comment]
I can get the struct with 
```
    CORINFO_SIG_INFO sigInfo;
    _compiler->eeGetMethodSig(methodHandle, &sigInfo);
```

**Comment by jkoritzinsky** [comment]
You can get from a `CORINFO_SIG_INFO` to a `CORINFO_CLASS_HANDLE` + `CorInfoTypeWithMod` for each argument.

Given a compiler object `_compiler` and a `CORINFO_SIG_INFO` object `sigInfo`:

```cpp
CORINFO_ARG_LIST_HANDLE sigArgs = sigInfo->args;
for (int i = 0; i < sigInfo->numArgs; i++, sigArgs = _compiler->info.compCompHnd->getArgNext(sigArgs))
{
      CORINFO_CLASS_HANDLE clsHnd;
      CorInfoTypeWithMod corTypeWithMod = _compiler->info.compCompHnd->getArgType(sigInfo, sigArgs, &clsHnd);
      // Use clsHnd and corTypeWithMod here.
}

```

**Comment by yowl** [comment]
@jkoritzinsky Thanks!
