### ISSUE TITLE
Top level exception filter

### ISSUE THREAD

**Issue by distee-ubi** [dotnet/runtimelab#961]
Hello,
I have an application in two variants. The _NET_ variant consumes a C# assembly via an C++/CLI bridge, while the _AOT_ variant links the assembly after building it into a static native AOT lib.

The C# assembly targets `netcore5.0` and runtime `win-x64`.
The application uses a SEH top level exception filter installed via `SetUnhandledExceptionFilter `to report crashes to developers.

Unhandled exceptions in the _NET_ application actually get reported via the installed top level filter.
Unhandled exceptions in the _AOT_ application never make it to the top level filter and the application is killed silently.
Even with some hacking that ensures that our top level filter cannot be replaced after being installed unhandled exceptions in the _AOT_ application never make it there.

**1)** Is the top level SEH filter mechanism used at all when dealing with unhandled exceptions?
**2)** How does process termination due to unhandled exception work?

I appreciate any answers, help, pointers!

Best,
dirk

**Comment by jkotas** [comment]
NativeAOT does not have interop with SEH on Windows. Unhandled exceptions in NativeAOT compiled code call `RaiseFailFastException`.

**Comment by MichalStrehovsky** [comment]
It's possible that your use-case would be solvable by hooking into the [`AppDomain.UnhandledException`](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.unhandledexception?view=net-5.0) event but I just looked into it and it doesn't look like we call it before the failfast. But we probably should; it's likely an omission.

**Comment by agocke** [comment]
@distee-ubi Out of curiosity, do you anticipate being in the situation where you use Core/Native AOT side-by-side for a while? Is there a particular characteristic that makes you want one over the other?

**Comment by distee-ubi** [comment]
@agocke Yes we will be using it side-by-side for a while. The top reason for trying to switch NativeAOT is performance, but we have some concerns that made us keep Core as a fallback. For example, we already have a Core build copy-protected by a third party, but do not know if this is going to work out for NativeAOT.

So far, we (and in particular I) do not have much experience with NativeAOT. Right now I can not give reason why I would prefer one over the other or keep them side-by-side. Some will pop up down the road, I guess.

**Comment by distee-ubi** [comment]
@jkotas, @MichalStrehovsky Thanks for your insight!

Our _NET_ app uses `AppDomain.UnhandledException` to deal with unhandled exceptions originating in the managed world. If the delegate would be called with _AOT_  exceptions from the managed world would be handled straight away.

I am trying to become a bit more familiar with the NativeAOT dev workflow in order understand things better and form an opinion, but I am not there yet. So here are just two observations I made. Maybe you could comment with your expectations on how exception handling should work here.

**1)** When I cause an access violation directly within the native subsystem by tripping `TryAcquireSRWLockShared()` the exception makes it to the top level filter we installed via `SetUnhandledExceptionFilter` and our reporting kicks in.

**2)** On the other hand, an access violation within the original, native app code (i.e., no managed code AOTed to native involved) triggers an assertion within the vectored exception handler provided in `EhHelpers.cpp` then proceeds to fast-fail. The top of the callstack looks something like this:

`App.exe!Assert(const char* expr, ...)`
`App.exe!RhpVectoredExceptionHandler(_EXCEPTION_POINTERS*)`     _[ehhelpers.cpp]_
`ntdll.dll!RtlpCallVectoredHandlers()`
`ntdll.dll!RtlDispatchException()`
`ntdll.dll!KiUserExceptionDispatch()`
`App.exe!SomeType::SomeTrigger()`

The assertion failure and fast-kill in `EhHelpers.cpp` happens here:
```
if (((uint8_t*)faultingIP >= s_pbRuntimeModuleLower) && ((uint8_t*)faultingIP < s_pbRuntimeModuleUpper))
{
    // Generally any form of hardware exception within the runtime itself is considered a fatal error.
    // Note this includes the managed code within the runtime.
    ASSERT_UNCONDITIONALLY("Hardware exception raised inside the runtime.");
    PalRaiseFailFastException(pExPtrs->ExceptionRecord, pExPtrs->ContextRecord, 0);
}
```

**Comment by jkotas** [comment]
> fast-kill in EhHelpers.cpp happens here:

As the comment says, this fast-kill is there to immediately terminate the process for fatal crashes in the runtime (e.g. in GC). CoreCLR has the same logic, e.g. fatal crash in CoreCLR GC or VM will fail fast, the unhandled exception filter won't get called. Our experience on CoreCLR was that when the fatal crash in GC or VM is handled as an exception, it typically produces other crashes along the way and makes the root cause harder to diagnose.

The difference for NativeAOT is that the unmanaged app code statically linked with the runtime is covered by this check as well. There is no way to tell whether the crash happened in the runtime code or unmanaged app code when everything is statically linked together.

I guess we can add an option to replace this fail fast with your custom handler.

**Comment by distee-ubi** [comment]
Thanks for the info @jkotas. 

For me, replacing the fail fast handler sounds just like it: I can still kill the application fast but I get the chance to replace WER and do the error info collecting/sending myself.

**Comment by jkotas** [comment]
Would you be interested in contributing a change that lets you override the fail fast handler with your custom callback? E.g. it can be a function pointer that gets called when set.

**Comment by distee-ubi** [comment]
Sure, with pleasure. Going is (and will be slow) in the next days though.

**Comment by distee-ubi** [comment]
(@jkotas) Forked and build NativeAOT today and looked at the code a bit. Code and tool chain are unfamiliar and are triggering newb questions. Is there some channel I should/could ask those?

**Comment by jkotas** [comment]
You can ask here or on the CoreRT gitter channel https://gitter.im/dotnet/corert

**Comment by distee-ubi** [comment]
Hello @jkotas, sorry for the long delay. Alex lost patience with me and did #1134 in order to speed things up. I just opened another pull request for a small amendment that allows windows clients to search for handlers on unhandled exception from the runtime: #1149
