### ISSUE TITLE
Error trying to compile NativeLibrary sample

### ISSUE THREAD

**Issue by josephmoresena** [dotnet/runtimelab#964]
When trying to compile the NativeLibrary project, I get the following error:
`/usr/share/dotnet/sdk/5.0.202/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ILLink.targets(143,5): error NETSDK1102: Optimizing assemblies for size is not supported for the selected publish configuration. Please ensure that you are publishing a self-contained app.`
At the moment, I must manually modify line 143 of Microsoft.NET.ILLink.targets, modifying the invalid condition to be able to get size optimization. 
I do it in the following way but I don't know if it is the right way to do it:
`<NETSdkError Condition="'$(SelfContained)' != 'true'" ResourceName="ILLinkNotSupportedError" />` 
to
`<NETSdkError Condition="'$(SelfContained)' != 'true' AND '$(NativeLib)' == ''" ResourceName="ILLinkNotSupportedError" />`

**Comment by jkotas** [comment]
Do you pass `/p:SelfContained=true` on the command line?

https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/samples/NativeLibrary/README.md#building-static-libraries

**Comment by josephmoresena** [comment]
You're right I missing that, I remember pass it once directly on .csproj but now seems is working well. Thanks.
