### ISSUE TITLE
Struct requires marshalling that is not yet supported by this compiler.

### ISSUE THREAD

**Issue by josephmoresena** [dotnet/runtimelab#969]
Im working on a .NET solution that involves the development of a native library compiled with NativeAOT.
Everything has been worked fine, but today I decided to add an additional feature to a structure and got the following message.

`Unhandled Exception: EETypeRva:0x00618CF0: Struct 'SvgPathNative' requires marshalling that is not yet supported by this compiler.`

It seems very strange to me because the only thing I changed in that struct was to add a Decimal field to it.  This exception occurs in the native library when trying to generate a delegate from a native pointer to a callback function that receives that struct as parameter.

Delegate:
`public delegate void CreateLayerPathDelegate(Guid processId, Guid layerId, SvgPathNative svgPathNative);`

Struct:

    public struct SvgPathNative : ISvgPath
    {
        public Int32 Index { get; set; }
        public Guid Id { get; set; }
        public IntPtr PointsGuidId { get; set; }
        public Int32 Length { get; set; }
        public Guid CenterId { get; set; }
        public Decimal Area { get; set; }
    }

Exception line:
`CreateLayerPathDelegate createLayerPathDelegate = createLayerPath.GetDelegate<CreateLayerPathDelegate>();`

Extension method:
`public static T GetDelegate<T>(this IntPtr ptr) where T : Delegate =>
            Marshal.GetDelegateForFunctionPointer<T>(ptr);`

Update:
Trying to pass Decimal field as parameter modifiying delegate definition and keeping struct definition got:
`Unhandled Exception: EETypeRva:0x006193D8: Method '[S.P.CompilerGenerated]Internal.CompilerGenerated.PInvokeDelegateWrapper__CreateLayerPathDelegate.ForwardNativeFunctionWrapper__CreateLayerPathDelegate(Guid,Guid,SvgPathNative,Decimal)' requires marshalling that is not yet supported by this compiler.`

**Comment by jkotas** [comment]
The decimal type is not blittable and requires a special marshaler that is not implemented for NativeAOT yet.

**Comment by jkotas** [comment]
- Add handling of `MarshallerKind.Decimal` to `GetNativeTypeFromMarshallerKind` and `CreateMarshaller(MarshallerKind kind)`
- Copy definition of NativeDecimal from  https://github.com/dotnet/runtime/blob/main/src/coreclr/System.Private.CoreLib/src/System/StubHelpers.cs
- Add `class DecimalMarshaller : ArrayMarshaller` to `Marshaler.Aot.cs`. 
- Add a basic test to src\tests\nativeaot\SmokeTests\PInvoke to verify that it works.

**Comment by hez2010** [comment]
Why it's `class DecimalMarshaller : ArrayMarshaller` but not `class DecimalMarshaller : Marshaller`?

**Comment by jkotas** [comment]
Sorry, that was a typo. It should be `class DecimalMarshaller : Marshaller` as you have pointed out.

**Comment by kant2002** [comment]
@josephmoresena changes should be already in latest version. I think this issue can be closed right now.
