### ISSUE TITLE
Library linker files for applications using NativeAOT compiled static libraries

### ISSUE THREAD

**Issue by elominp** [dotnet/runtimelab#974]
Hello,

Do you have a list on Windows of libraries linker files (`.lib`) and their location to add to the linker input for a static library compiled with NativeAOT?

I tried to use a C# library compiled with NativeAOT, I was able to build it as a dynamic library (`.dll`) and as a static library (`.lib`) as well as to call one of the exported function using `LoadLibrary` and `GetProcAddress`.

However as I try to statically link a simple C++ console application to it I get the following list of unresolved symbols:

```
RhpInitialDynamicInterfaceDispatch
RhpNewFast
RhpNewArray
RhpAssignRef
RhpCheckedAssignRef
RhpByRefAssignRef
RhpPInvoke
RhpPInvokeReturn
RhpTrapThreads
RhpGcPoll
RhpThrowEx
RhpNewFinalizable
RhpCheckedLockCmpXchg
RhpRethrow
RhNewString
RhpStackProbe
RhpFallbackFailFast
RhpReversePInvoke2
RhpReversePInvokeReturn2
RhHandleSet
CallingConventionConverter_GetStubs
RhGetUniversalTransitionThunk
RhGetCodeTarget
RhHandleFree
RhGetGCDescSize
RhFindBlob
RhGetModuleFromEEType
RhCurrentNativeThreadId
RhGetTargetOfUnboxingAndInstantiatingStub
RhGetRuntimeHelperForType
CompressionNative_DeflateInit2_
CompressionNative_Deflate
CompressionNative_DeflateEnd
CompressionNative_InflateInit2_
CompressionNative_Inflate
CompressionNative_InflateEnd
BCryptGenRandom
RhBulkMoveWithWriteBarrier
RhGetProcessCpuCount
RhGetGeneration
RhSuppressFinalize
RhReRegisterForFinalize
RhGetMemoryInfo
RhGetOSModuleFromEEType
RhpEtwExceptionThrown
g_cpuFeatures
RhSpinWait
RhpLockCmpXchg32
RhpLockCmpXchg64
RhpCheckedXchg
RhpMemoryBarrier
RhSetThreadExitCallback
RhYield
RhInitializeFinalizerThread
RhCompatibleReentrantWaitAny
RhFindMethodStartAddress
RhpHandleAlloc
RhpHandleAllocDependent
RhpGetDispatchCellInfo
RhpUpdateDispatchCellCache
RhpSearchDispatchCellCache
RhpWaitForFinalizerRequest
RhpSignalFinalizationComplete
RhpCollect
RhpGetNextFinalizableObject
RhpGetRequestedExceptionEvents
RhpSendExceptionEventToDebugger
RhpGetClasslibFunctionFromCodeAddress
RhpGetClasslibFunctionFromEEType
RhpCopyContextFromExInfo
RhpGetThreadAbortException
RhpSfiInit
RhpSfiNext
RhpSetThreadDoNotTriggerGC
RhpCallCatchFunclet
RhpEHEnumInitFromStackFrameIterator
RhpEHEnumNext
RhpCallFilterFunclet
RhpCallFinallyFunclet
RhpGetGcTotalMemory
RhpEndNoGCRegion
RhpReleaseCastCacheLock
RhpStartNoGCRegion
RhpInitMultibyte
RhpCopyObjectContents
RhpGetCurrentThreadStackTrace
RhpGetThunkSize
RhpGetNumThunksPerBlock
RhpGetNumThunkBlocksPerMapping
RhpAcquireThunkPoolLock
RhpReleaseThunkPoolLock
RhpGetThunkDataBlockAddress
RhpGetThunkStubsBlockAddress
RhAllocateThunksMapping
RhpGetThunkBlockSize
RhGetCommonStubAddress
RhGetCurrentThunkContext
RhCompareObjectContentsAndPadding
RhGetCurrentThreadStackBounds
RhGetOSModuleFromPointer
RhGetThreadStaticStorageForModule
RhSetThreadStaticStorageForModule
RhpGetModuleSection
RhNewInterfaceDispatchCell
RhGetModuleFileName
RhCallDescrWorker
RhpRegisterOsModule
RhpCreateTypeManager
RhpRegisterFrozenSegment
RhAllocateNewObject
RhpDbl2ULng
CryptProtectMemory
CryptUnprotectMemory
RhpAcquireCastCacheLock
PalGetTickCount64
closesocket
ioctlsocket
recv
setsockopt
shutdown
WSAIoctl
WSASocketW
WSAStartup
WSACleanup
BCryptOpenAlgorithmProvider
BCryptCloseAlgorithmProvider
BCryptCreateHash
BCryptDestroyHash
BCryptHashData
BCryptFinishHash
BCryptGetProperty
GetNetworkParams
GetAdaptersAddresses
GetIfEntry2
GetPerAdapterInfo
WSAEventSelect
RhHandleGetDependent
RhAllocateNewArray
```

For now I tried adding the following list of libraries as input of the linker but it enables only to resolve 20 of these 138 symbols:

```
bcrypt.lib
crypt32.lib
mswsock.lib
ncrypt.lib
secur32.lib
version.lib
ws2_32.lib
```

It seems to me that these symbols are part of the .NET DLLs as they seem to be part of the symbols contained in the DLLs copied for example in the output directory of the `HelloWorld` console application, comparing their name and list of symbols I found here: https://dev.getsol.us/D10618

As far as I know, I still can't feed the linker with these raw `.dll` files like I could with `.so` shared libraries on Linux and need to use the `.lib` files instead, so does anyone knows where I could find them or do I need to compile a .NET SDK from scratch in order to have a chance to get them (hoping it would produce them but for now I get errors when using the build script)?

**Comment by jkotas** [comment]
Here is the list:
- https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Windows.props#L32-L33
  - bootstrapperdll.lib for libraries
  - Runtime.lib or Runtime.ServerGC.lib
- https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Windows.props#L47-L61

**Comment by elominp** [comment]
Thanks, I was able to successfully link my test application with these libraries but I also had to add `System.IO.Compression.Native.lib` or `System.IO.Compression.Native-Static.lib` from the `framework` folder to link against 6 symbols contained in this library.
