### ISSUE TITLE
Question: NativeAOT-LLVM: LIR - Are LCL_VAR argx in sync with the Vyy ?

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#975]
In this LIR:

```
------------ BB01 [000..019) -> BB05 (cond), preds={} succs={BB02,BB05}
               [000121] ------------                 IL_OFFSET void   IL offset: 0x0
N001 (  1,  1) [000000] ------------                 NO_OP     void
N002 (  3,  2) [000001] ------------         t1 =    LCL_VAR   long   V00 arg0
                                                  /--*  t1     long   arg0 in rcx
N003 ( 17,  5) [000002] --CXG-------         t2 = *  CALL      int    Internal.Runtime.CompilerHelpers.MathHelpers.Hi32Bits
                                                  /--*  t2     int
N005 ( 21,  8) [000004] DA-XG-------              *  STORE_LCL_VAR int    V03 loc1
N002 (  3,  2) [000005] ------------         t5 =    LCL_VAR   long   V01 arg1
```

It can be seen that `V00` is from `arg0` and `V01` is from `arg1`.  But is that relationship of 0->0, 1->1, etc.  guaranteed?

I don't see anything in `GenTreeLclVar` that would identify the arg number

![image](https://user-images.githubusercontent.com/2720041/115163820-e7c28b80-a070-11eb-96ce-61627aa65fbd.png)

**Comment by jkotas** [comment]
@AndyAyersMS Could you please help?

**Comment by AndyAyersMS** [comment]
> But is that relationship of 0->0, 1->1, etc. guaranteed?

Not necessarily; if the method is passed a generic context, returns a large struct value, or is varags, there are extra arguments that throw off this mapping.

> I don't see anything in GenTreeLclVar that would identify the arg number

The correspondence is given by `Compiler::compMap2ILvarNum`:  the first N IL vars are the args, the remaining M are the locals.

**Comment by yowl** [comment]
Thanks!
