### ISSUE TITLE
[NativeAot] C++ class pinvokes

### ISSUE THREAD

**Issue by SupinePandora43** [dotnet/runtimelab#977]
It is even possible?

**Comment by MichalStrehovsky** [comment]
That sounds a lot like what COM interop does. NativeAOT doesn't support COM yet.

**Comment by jkotas** [comment]
Interop with C++ is not a NativeAOT specific issue. It is an issue for .NET in general. There are number of issues discussing it in dotnet/runtime and elsewhere, e.g. E.g. https://github.com/dotnet/runtime/issues/4107 . 

The portable C++ interop solutions that work for regular .NET will work with NativeAOT as well.
