### ISSUE TITLE
[NativeAOT] Missing symbols when linking static AOT lib

### ISSUE THREAD

**Issue by distee-ubi** [dotnet/runtimelab#979]
When building an application that links an AOTed assembly (`netcore5.0`, `win-x64`) as static library I and up with two unresolved external symbols:
`RhpDebugFuncEvalHelper`
`RhAllocateNewObject`

Do I need to link anything in addition to the libs listed below?
_advapi32.lib
bcrypt.lib
crypt32.lib
iphlpapi.lib
kernel32.lib
mswsock.lib
ncrypt.lib
normaliz.lib
ntdll.lib
ole32.lib
oleaut32.lib
secur32.lib
user32.lib
version.lib
ws2_32.lib_
_bootstrapperdll.lib
Runtime.lib
System.IO.Compression.Native.lib_

**Comment by jkotas** [comment]
`RhpDebugFuncEvalHelper` was deleted in https://github.com/dotnet/runtimelab/pull/893/files#diff-d37e6794a359079a49ec3041dd90cc1daf8e9ed808fc0e8796519c5299113b12L14.

`RhAllocateNewObject` was added in #870.

Looks like you are using mismatched builds of the runtime and libraries.

**Comment by distee-ubi** [comment]
Dang! Should have spotted that. Sorry for the noise.
